"""
Generate src/in_game/common/building_types/towards_victory_buildings.txt from data/academy_buildings.yaml.

Pattern: 5 academy tier buildings; employment/price/construction/production follow
tv_academy_{n}_<type> naming convention and are derived from n.
"""

import sys
import argparse
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "academy_buildings.yaml"
ESTABLISHMENT_FILE = REPO_ROOT / "data" / "io_establishment.yaml"
OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "building_types" / "towards_victory_buildings.txt"

HEADER = (
    "# @Generated by scripts/in_game/common/building_types/gen_towards_victory_buildings.py\n"
    "#   Data:    data/academy_buildings.yaml + data/io_establishment.yaml\n"
    "#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/building_types/gen_towards_victory_buildings.py\n"
    "# Do not edit directly — modify the data file and re-run the generator.\n"
    "# Verification — Step 3, Reference: capital_buildings.txt:17-56, Quote: \"location_potential = { is_capital = yes }\"\n"
    "# Verification — Step 3, Reference: capital_buildings.txt:15, Quote: \"build_time = large_capital_build_time\"\n"
    "# Verification — Step 3, Reference: culture_buildings.txt:1-48, Quote: \"category = cultural_category\"\n"
    "# Verification — Step 3, Reference: unique_buildings.txt:516-524, Quote: \"location.owner = { ... }\" (on_built owner access)\n"
    "# Verification — Step 3, Reference: estate_buildings.txt, Quote: \"scope:actor = { ... }\" in allow block\n"
)

T = "\t"  # single tab shorthand


def _indent_block(text: str, depth: int) -> str:
    prefix = T * depth
    return "\n".join(prefix + line if line.strip() else "" for line in text.rstrip().splitlines())


def gen_building(tier: dict) -> str:
    n = tier["n"]
    score = tier["score_threshold"]
    modifier_lines = tier["modifier_lines"].rstrip()
    capital_lines = (tier.get("capital_modifier_lines") or "").rstrip()
    event_id = (tier.get("trigger_event_id") or "").strip()

    lines = []
    lines.append(f"tv_academy_of_sciences_{n} = {{")
    lines.append(T + "is_foreign = no")
    lines.append(T + "pop_type = clergy")
    lines.append(T + "max_levels = 1")
    lines.append(T + f"employment_size = tv_academy_{n}_employment")
    lines.append("")
    lines.append(T + "category = cultural_category")
    lines.append(T + f"price = tv_academy_{n}_price")
    lines.append("")
    lines.append(T + "town = yes")
    lines.append(T + "city = yes")
    lines.append(T + "megalopolis = yes")
    lines.append(T + "rural_settlement = no")
    lines.append("")
    lines.append(T + "important_for_AI = yes")
    lines.append(T + "automation_build_allowed = yes")
    lines.append("")
    lines.append(T + "location_potential = {")
    lines.append(T*2 + "is_capital = yes")
    lines.append(T + "}")
    lines.append("")
    lines.append(T + "allow = {")
    if n > 1:
        lines.append(T*2 + "custom_tooltip = {")
        lines.append(T*3 + f"text = TV_ACADEMY_HAS_PREV_{n}_TT")
        lines.append(T*3 + "scope:actor = { has_variable = tv_academy_of_sciences_level }")
        lines.append(T*3 + f"scope:actor = {{ var:tv_academy_of_sciences_level >= {n - 1} }}")
        lines.append(T*2 + "}")
    lines.append(T*2 + "custom_tooltip = {")
    lines.append(T*3 + f"text = TV_ACADEMY_SCORE_{n}_TT")
    lines.append(T*3 + "scope:actor = { has_variable = tv_science_score }")
    lines.append(T*3 + f"scope:actor = {{ var:tv_science_score >= {score} }}")
    lines.append(T*2 + "}")
    lines.append(T + "}")
    lines.append("")
    lines.append(T + "build_time = large_capital_build_time")
    lines.append(T + f"construction_demand = tv_academy_{n}_construction")
    lines.append("")
    lines.append(T + "modifier = {")
    lines.append(_indent_block(modifier_lines, 2))
    lines.append(T + "}")
    lines.append("")
    if capital_lines:
        lines.append(T + "capital_country_modifier = {")
        lines.append(_indent_block(capital_lines, 2))
        lines.append(T + "}")
        lines.append("")
    lines.append(T + "possible_production_methods = {")
    lines.append(T*2 + f"tv_academy_{n}_maintenance")
    lines.append(T + "}")
    lines.append("")
    lines.append(T + "on_built = {")
    lines.append(T*2 + "hidden_effect = {")
    lines.append(T*3 + "location.owner = {")
    lines.append(T*4 + f"set_variable = {{ name = tv_academy_of_sciences_level value = {n} }}")
    lines.append(T*4 + "tv_check_science_milestones_effect = yes")
    if event_id:
        lines.append(T*4 + f"trigger_event_non_silently = {{ id = {event_id} }}")
    lines.append(T*3 + "}")
    lines.append(T*2 + "}")
    lines.append(T + "}")
    lines.append("}")
    return "\n".join(lines)


def gen_headquarters_building(est: dict) -> str:
    pid = est["id"]
    hq = est["headquarters"]
    building = hq["building"]
    maintenance = f"{building}_maintenance"
    lines = []
    lines.append(f"{building} = {{")
    lines.append(T + "is_foreign = no")
    lines.append(T + f"pop_type = {hq['pop_type']}")
    lines.append(T + "max_levels = 1")
    lines.append(T + f"employment_size = {hq['employment_size']}")
    lines.append("")
    lines.append(T + f"category = {hq['category']}")
    lines.append(T + "price = tv_io_headquarters_price")
    lines.append("")
    lines.append(T + "town = yes")
    lines.append(T + "city = yes")
    lines.append(T + "megalopolis = yes")
    lines.append(T + "rural_settlement = no")
    lines.append("")
    lines.append(T + "important_for_AI = yes")
    lines.append(T + "automation_build_allowed = yes")
    lines.append("")
    lines.append(T + "location_potential = {")
    lines.append(T*2 + "is_capital = yes")
    lines.append(T + "}")
    lines.append("")
    lines.append(T + "allow = {")
    lines.append(T*2 + "scope:actor = {")
    lines.append(T*3 + "OR = {")
    lines.append(T*4 + f"has_variable = tv_{pid}_establishment_basic_done")
    lines.append(T*4 + f"has_variable = tv_{pid}_victory_enabled")
    lines.append(T*3 + "}")
    lines.append(T*2 + "}")
    lines.append(T + "}")
    lines.append("")
    lines.append(T + "build_time = large_capital_build_time")
    lines.append(T + f"construction_demand = {hq['construction_demand']}")
    lines.append("")
    lines.append(T + "modifier = {")
    for key, value in hq["modifier"].items():
        lines.append(T*2 + f"{key} = {value:g}")
    lines.append(T + "}")
    lines.append("")
    lines.append(T + "possible_production_methods = {")
    lines.append(T*2 + maintenance)
    lines.append(T + "}")
    lines.append("")
    lines.append(T + "remove_if = {")
    lines.append(T*2 + "is_no_longer_capital = yes")
    lines.append(T + "}")
    lines.append("")
    lines.append(T + "on_built = {")
    lines.append(T*2 + "hidden_effect = {")
    lines.append(T*3 + "location.owner = {")
    lines.append(T*4 + f"set_variable = {{ name = tv_{pid}_establishment_headquarters_done value = 1 }}")
    lines.append(T*3 + "}")
    lines.append(T*2 + "}")
    lines.append(T + "}")
    lines.append("}")
    return "\n".join(lines)


def generate(data: dict, establishment: dict | None = None) -> str:
    parts = [HEADER]
    for tier in data["tiers"]:
        parts.append(gen_building(tier))
        parts.append("")
    if establishment and establishment.get("paths"):
        for est in sorted(establishment["paths"], key=lambda path: int(path.get("order", 0))):
            parts.append(gen_headquarters_building(est))
            parts.append("")
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with open(DATA_FILE, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    with open(ESTABLISHMENT_FILE, encoding="utf-8") as f:
        establishment = yaml.safe_load(f)

    content = generate(data, establishment)

    if args.dry:
        print(content)
    else:
        OUT_FILE.write_text(content, encoding="utf-8-sig")
        print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
