"""
Generate src/in_game/common/laws/tv_trade_league_laws.txt from
data/trade_league_laws.yaml.

Pattern: Trade League IO laws. Policies may define country_modifier,
leader_modifier, and non_leader_modifier blocks and keep IO policy votes
enabled.
"""

import argparse
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "trade_league_laws.yaml"
OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "laws" / "tv_trade_league_laws.txt"

T = "\t"
MODIFIER_BLOCKS = ("country_modifier", "leader_modifier", "non_leader_modifier")

FILE_HEADER = (
    "# @Generated by scripts/in_game/common/laws/gen_tv_trade_league_laws.py\n"
    "#   Data:    data/trade_league_laws.yaml\n"
    "#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/laws/gen_tv_trade_league_laws.py\n"
    "# Do not edit directly - modify the data file and re-run the generator.\n"
    "#\n"
    "# TOWARDS VICTORY - TRADE LEAGUE LAWS\n"
    "# Two simple Trade League law groups with vote-gated policies.\n"
    "# requires_vote = yes: Trade League law changes use IO policy votes.\n"
)

LAW_DIVIDER = "# ------------------------------------------------------------------------------"


def _indent_block(text: str, depth: int) -> str:
    prefix = T * depth
    return "\n".join(prefix + line if line.strip() else "" for line in text.rstrip().splitlines())


def gen_policy(policy: dict) -> str:
    pid = policy["id"]
    comment = policy.get("display_comment", "")

    lines = []
    if comment:
        lines.append(T + f"# {comment}")
    lines.append(T + f"{pid} = {{")
    lines.append(T * 2 + "allow = {")
    lines.append(T * 3 + "always = yes")
    lines.append(T * 2 + "}")
    for block_name in MODIFIER_BLOCKS:
        modifier_lines = (policy.get(block_name) or "").rstrip()
        if modifier_lines:
            lines.append(T * 2 + f"{block_name} = {{")
            lines.append(_indent_block(modifier_lines, 3))
            lines.append(T * 2 + "}")
    lines.append(T + "}")
    return "\n".join(lines)


def gen_law(law: dict, default_law_category: str, io_type: str) -> str:
    lid = law["id"]
    law_category = law.get("law_category", default_law_category)
    display_comment = law.get("display_comment", "")
    policies = law["policies"]

    lines = [LAW_DIVIDER]
    if display_comment:
        lines.append(f"# {display_comment}")
    lines.append(LAW_DIVIDER)
    lines.append(f"{lid} = {{")
    lines.append(T + "type = international_organization")
    lines.append(T + f"law_category = {law_category}")
    lines.append(T + "potential = {")
    lines.append(T * 2 + f"international_organization_type = international_organization_type:{io_type}")
    lines.append(T + "}")
    lines.append(T + "allow = {")
    lines.append(T * 2 + "always = yes")
    lines.append(T + "}")
    lines.append(T + "locked = {")
    lines.append(T + "}")
    lines.append(T + "requires_vote = yes")
    lines.append(T + "custom_tags = { forbids_no_policy }")
    lines.append("")

    for index, policy in enumerate(policies):
        lines.append(gen_policy(policy))
        if index < len(policies) - 1:
            lines.append("")

    lines.append("}")
    return "\n".join(lines)


def generate(data: dict) -> str:
    law_category = data["law_category"]
    io_type = data["io_type"]

    parts = [FILE_HEADER]
    for law in data["laws"]:
        parts.append(gen_law(law, law_category, io_type))
        parts.append("")
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with open(DATA_FILE, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    content = generate(data)

    if args.dry:
        print(content)
    else:
        OUT_FILE.write_text(content, encoding="utf-8-sig")
        print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
