"""
Generate src/in_game/common/laws/tv_govhouse_laws.txt from data/govhouse_laws.yaml.

Pattern: Governor's House IO laws. Policies define additive country_modifier
blocks for the leader country and keep IO policy votes enabled, matching the
Academy of Sciences law flow while keeping the visible policy effects available
outside vote-recipient tooltip contexts.
"""

import argparse
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "govhouse_laws.yaml"
OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "laws" / "tv_govhouse_laws.txt"

T = "\t"
ALLOWED_AI_BASE_BIASES = {-60, -40, -20, 0, 20, 40, 60}

FILE_HEADER = (
    "# @Generated by scripts/in_game/common/laws/gen_tv_govhouse_laws.py\n"
    "#   Data:    data/govhouse_laws.yaml\n"
    "#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/laws/gen_tv_govhouse_laws.py\n"
    "# Do not edit directly - modify the data file and re-run the generator.\n"
    "#\n"
    "# TOWARDS VICTORY - GOVERNOR'S HOUSE LAWS\n"
    "# Governor's House law groups and Local Governor Function policies.\n"
    "# requires_vote = yes: Governor's House law changes use IO policy votes.\n"
)

LAW_DIVIDER = "# ------------------------------------------------------------------------------"


def _indent_block(text: str, depth: int) -> str:
    prefix = T * depth
    return "\n".join(prefix + line if line.strip() else "" for line in text.rstrip().splitlines())


def gen_ai_vote_bias(policy: dict) -> list[str]:
    bias = policy.get("ai_base_bias")
    if bias not in ALLOWED_AI_BASE_BIASES:
        pid = policy["id"]
        allowed = ", ".join(str(value) for value in sorted(ALLOWED_AI_BASE_BIASES))
        raise ValueError(f"{pid}: ai_base_bias must be one of {allowed}")

    lines = []
    lines.append(T * 2 + "wants_this_policy_bias = {")
    lines.append(T * 3 + "add = {")
    lines.append(T * 4 + 'desc = "TV_GOVHOUSE_POLICY_BASE_BIAS"')
    lines.append(T * 4 + f"value = {bias}")
    lines.append(T * 3 + "}")
    lines.append(T * 3 + "if = {")
    lines.append(T * 4 + "limit = {")
    lines.append(T * 5 + "exists = scope:recipient")
    lines.append(T * 5 + "scope:recipient = {")
    lines.append(T * 6 + "international_organization_has_leader = yes")
    lines.append(T * 6 + "has_variable = ai_io_law_target")
    lines.append(T * 6 + "var:ai_io_law_target = scope:policy")
    lines.append(T * 5 + "}")
    lines.append(T * 4 + "}")
    lines.append(T * 4 + "add = {")
    lines.append(T * 5 + 'desc = "POLICY_BIAS_OPINION_OF_IO_LEADER"')
    lines.append(T * 5 + "value = {")
    lines.append(T * 6 + 'value = "opinion(scope:recipient.leader_country)"')
    lines.append(T * 6 + "multiply = 0.5")
    lines.append(T * 6 + "min = -100")
    lines.append(T * 6 + "max = 100")
    lines.append(T * 5 + "}")
    lines.append(T * 4 + "}")
    lines.append(T * 4 + "add = {")
    lines.append(T * 5 + 'desc = "IO_LEADER_DIP_REP"')
    lines.append(T * 5 + "value = scope:recipient.leader_country.modifier:diplomatic_reputation")
    lines.append(T * 5 + "multiply = 5")
    lines.append(T * 4 + "}")
    lines.append(T * 3 + "}")
    lines.append(T * 2 + "}")
    return lines


def gen_policy(policy: dict) -> str:
    pid = policy["id"]
    comment = policy.get("display_comment", "")
    modifier_lines = (policy.get("country_modifier") or "").rstrip()
    on_activate_lines = (policy.get("on_activate") or "").rstrip()

    lines = []
    if comment:
        lines.append(T + f"# {comment}")
    lines.append(T + f"{pid} = {{")
    lines.append(T * 2 + "allow = {")
    lines.append(T * 3 + "always = yes")
    lines.append(T * 2 + "}")
    lines.extend(gen_ai_vote_bias(policy))
    if on_activate_lines:
        lines.append(T * 2 + "on_activate = {")
        lines.append(_indent_block(on_activate_lines, 3))
        lines.append(T * 2 + "}")
    if modifier_lines:
        lines.append(T * 2 + "country_modifier = {")
        lines.append(T * 3 + "potential_trigger = {")
        lines.append(T * 4 + "OR = {")
        lines.append(T * 5 + "NOT = { exists = scope:recipient }")
        lines.append(T * 5 + "is_leader_of_international_organization = scope:recipient")
        lines.append(T * 4 + "}")
        lines.append(T * 3 + "}")
        lines.append(_indent_block(modifier_lines, 3))
        lines.append(T * 2 + "}")
    lines.append(T + "}")
    return "\n".join(lines)


def gen_law(law: dict, default_law_category: str, io_type: str) -> str:
    lid = law["id"]
    law_category = law.get("law_category", default_law_category)
    display_comment = law.get("display_comment", "")
    policies = law["policies"]

    lines = [LAW_DIVIDER]
    if display_comment:
        lines.append(f"# {display_comment}")
    lines.append(LAW_DIVIDER)
    lines.append(f"{lid} = {{")
    lines.append(T + "type = international_organization")
    lines.append(T + f"law_category = {law_category}")
    lines.append(T + "potential = {")
    lines.append(T * 2 + f"international_organization_type = international_organization_type:{io_type}")
    lines.append(T + "}")
    lines.append(T + "allow = {")
    lines.append(T * 2 + "always = yes")
    lines.append(T + "}")
    lines.append(T + "locked = {")
    lines.append(T + "}")
    lines.append(T + "requires_vote = yes")
    lines.append(T + "custom_tags = { forbids_no_policy }")
    lines.append("")

    for index, policy in enumerate(policies):
        lines.append(gen_policy(policy))
        if index < len(policies) - 1:
            lines.append("")

    lines.append("}")
    return "\n".join(lines)


def generate(data: dict) -> str:
    law_category = data["law_category"]
    io_type = data["io_type"]

    parts = [FILE_HEADER]
    for law in data["laws"]:
        parts.append(gen_law(law, law_category, io_type))
        parts.append("")
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with open(DATA_FILE, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    content = generate(data)

    if args.dry:
        print(content)
    else:
        OUT_FILE.write_text(content, encoding="utf-8-sig")
        print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
