"""
Generate a bridge file that registers Towards Victory custom on_action names
under vanilla singleton pulses and other shared/hardcoded on_actions.

The generated file is a small additive bridge. It declares only parent hook keys
plus TV-owned `on_actions = { ... }`, letting vanilla or feature files provide
the events/random_events/effect bodies. This avoids copying vanilla pulse
content into the mod, avoids vanilla filename collisions, and avoids scattering
singleton bridge blocks across feature files.

Usage:
    conda run --no-capture-output -n eu5 python scripts/in_game/common/on_action/gen_tv_pulse_registry.py
"""

import sys
import yaml
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[4]

REGISTRY = REPO_ROOT / "data" / "pulse_registry.yaml"

HARDCODED_ON_ACTIONS = REPO_ROOT / "reference_game_files" / "game" / "in_game" / "common" / "on_action" / "_hardcoded.txt"

SOURCE_FILES: dict[str, Path | None] = {
    "monthly_country_pulse": REPO_ROOT / "reference_game_files" / "game" / "in_game" / "common" / "on_action" / "country_monthly.txt",
    "yearly_country_pulse":  REPO_ROOT / "reference_game_files" / "game" / "in_game" / "common" / "on_action" / "country_yearly.txt",
    "on_character_death":    REPO_ROOT / "reference_game_files" / "game" / "in_game" / "common" / "on_action" / "character_death_pulses.txt",
    "on_ruler_death":        HARDCODED_ON_ACTIONS,
    "on_game_start":         HARDCODED_ON_ACTIONS,
    # on_game_load is fired by the CMF scripted GUI layer, not vanilla _hardcoded.txt.
    "on_game_load":          None,
    "on_work_of_art_created": HARDCODED_ON_ACTIONS,
    "on_character_moved_country": HARDCODED_ON_ACTIONS,
    "on_new_ruler":          HARDCODED_ON_ACTIONS,
    "on_character_marriage": HARDCODED_ON_ACTIONS,
    "on_royal_marriage":     HARDCODED_ON_ACTIONS,
    "on_dependency_gained":  HARDCODED_ON_ACTIONS,
    "on_becoming_free":      HARDCODED_ON_ACTIONS,
    "on_subject_created":    HARDCODED_ON_ACTIONS,
    "on_transfer_subject":   HARDCODED_ON_ACTIONS,
    "on_war_declared":       HARDCODED_ON_ACTIONS,
    "on_join_war":           HARDCODED_ON_ACTIONS,
    "on_ending_war":         HARDCODED_ON_ACTIONS,
    "on_pre_winning_war":    HARDCODED_ON_ACTIONS,
    "on_location_changed_owner": HARDCODED_ON_ACTIONS,
    "on_institution_embraced": HARDCODED_ON_ACTIONS,
    "on_capital_moved":      HARDCODED_ON_ACTIONS,
    # CMF scripted GUIs fire this custom callback hook.
    "cmf_on_callback":       None,
}

OUTPUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "on_action" / "tv_pulse_bridges.txt"

SCRIPT_REL = "scripts/in_game/common/on_action/gen_tv_pulse_registry.py"
DATA_REL    = "data/pulse_registry.yaml"

HEADER_TEMPLATE = """\
# @Generated by {script}
#   Data:    {data}
#   Regen:   conda run --no-capture-output -n eu5 python {script}
# Do not edit directly — modify the data file and re-run the generator.

"""

def extract_on_action_block(lines: list[str], hook_name: str) -> list[str]:
    """Return only the named on_action block from a multi-action source file."""
    start_idx: int | None = None
    depth = 0

    for i, raw in enumerate(lines):
        stripped = raw.strip()
        if start_idx is None:
            if stripped.startswith(hook_name) and "=" in stripped and "{" in stripped:
                start_idx = i
                depth = stripped.count("{") - stripped.count("}")
                if depth <= 0:
                    return [raw]
            continue

        depth += stripped.count("{") - stripped.count("}")
        if depth <= 0:
            return lines[start_idx:i + 1]

    raise ValueError(f"on_action block not found or unterminated: '{hook_name}'")


def build_bridge_block(hook_name: str, additions: list[str]) -> list[str]:
    """Build a small bridge that registers TV-owned on_actions."""
    lines = [
        f"{hook_name} = {{\n",
        "\ton_actions = {\n",
        "\t\t# Towards Victory additions\n",
    ]
    for name in additions:
        lines.append(f"\t\t{name}\n")
    lines.extend([
        "\t}\n",
        "}\n",
    ])
    return lines


def generate_block(hook_name: str, additions: list[str]) -> list[str]:
    src_path = SOURCE_FILES[hook_name]

    if src_path is None:
        print(f"Skipping source verification for custom hook: {hook_name}")
    else:
        print(f"Reading source: {src_path.relative_to(REPO_ROOT)}")
        # Use utf-8-sig to strip UTF-8 BOM if present (some vanilla files start with BOM)
        text = src_path.read_text(encoding="utf-8-sig")
        lines = text.splitlines(keepends=True)
        extract_on_action_block(lines, hook_name)
    return build_bridge_block(hook_name, additions)


def main() -> None:
    registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    groups = [
        ("singleton pulse/death bridges", registry.get("pulses", {})),
        ("general/hardcoded hook bridges", registry.get("bridges", {})),
    ]

    blocks: list[str] = []
    for label, hooks in groups:
        group_blocks: list[str] = []
        for hook_name, additions in hooks.items():
            if hook_name not in SOURCE_FILES:
                print(f"WARNING: no source mapping for '{hook_name}', skipping")
                continue
            group_blocks.append("".join(generate_block(hook_name, additions)).rstrip())
        if group_blocks:
            blocks.append(f"# {label}")
            blocks.extend(group_blocks)

    header = HEADER_TEMPLATE.format(script=SCRIPT_REL, data=DATA_REL)
    output = header + "\n\n".join(blocks) + "\n"
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output, encoding="utf-8-sig")
    print(f"Wrote: {OUTPUT_FILE.relative_to(REPO_ROOT)}")

    print("Done.")


if __name__ == "__main__":
    main()
