"""
Generate src/in_game/common/on_action/tv_cmf_suppressions.txt.

The generated on_action holds CMF warning suppressions in one unreachable
effect block, as recommended by CMF:

if = {
    limit = { always = no }
    cmf_suppress = { v = some_variable }
}
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "cmf_warning_suppressions.yaml"
TRADE_GOODS_FILE = REPO_ROOT / "data" / "trade_league_goods.yaml"
LOCKED_ADVANCES_FILE = REPO_ROOT / "data" / "locked_advances.yaml"
VICTORY_PATHS_FILE = REPO_ROOT / "data" / "victory_paths.yaml"
OUT_FILE = (
    REPO_ROOT
    / "src"
    / "in_game"
    / "common"
    / "on_action"
    / "tv_cmf_suppressions.txt"
)

HEADER = """\
# @Generated by scripts/in_game/common/on_action/gen_tv_cmf_suppressions.py
#   Data:    data/cmf_warning_suppressions.yaml + data/trade_league_goods.yaml + data/locked_advances.yaml + data/victory_paths.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/on_action/gen_tv_cmf_suppressions.py
# Do not edit directly - modify the data file and re-run the generator.

"""

TRADE_GOOD_VARIABLE_PREFIXES = (
    "tv_trade_available_monopoly_level_pct",
    "tv_trade_consumer_control_pct",
    "tv_trade_embargo_active",
    "tv_trade_embargo_country",
    "tv_trade_embargo_location",
    "tv_trade_embargo_used_pct",
    "tv_trade_global",
    "tv_trade_io",
    "tv_trade_monopoly",
    "tv_trade_monopoly_level",
    "tv_trade_monopoly_level_pct",
    "tv_trade_monopoly_stage",
    "tv_trade_monopoly_type",
    "tv_trade_node_control_pct",
    "tv_trade_origin_control_pct",
    "tv_trade_used_monopoly_level",
    "tv_trade_used_monopoly_level_pct",
    "tv_trade_virtual_demand_active",
    "tv_trade_virtual_demand_amount",
    "tv_trade_virtual_demand_location",
    "tv_trade_virtual_demand_used_pct",
    "tv_trade_virtual_supply_active",
    "tv_trade_virtual_supply_amount",
    "tv_trade_virtual_supply_applied",
    "tv_trade_virtual_supply_location",
    "tv_trade_virtual_supply_used_pct",
)

MONOPOLY_SLOT_COUNT = 2

MONOPOLY_SLOT_FIELDS = (
    "consumer_pct",
    "good",
    "good_index",
    "monopoly",
    "monopoly_level_pct",
    "monopoly_stage",
    "monopoly_type",
    "node_pct",
    "origin_pct",
    "unlocked",
)

INTELLIGENCE_ROW_FIELDS = (
    "active",
    "io_power",
    "strength_pct",
)

SELECTED_BASE_VARIABLES = (
    "tv_trade_selected_available_monopoly_level_pct",
    "tv_trade_selected_consumer_pct",
    "tv_trade_selected_embargo_active",
    "tv_trade_selected_embargo_used_pct",
    "tv_trade_selected_good_index",
    "tv_trade_selected_intelligence_active",
    "tv_trade_selected_intelligence_io_power",
    "tv_trade_selected_intelligence_strength_pct",
    "tv_trade_selected_intelligence_top_power_1",
    "tv_trade_selected_intelligence_top_power_2",
    "tv_trade_selected_intelligence_top_power_3",
    "tv_trade_selected_monopoly",
    "tv_trade_selected_monopoly_level_pct",
    "tv_trade_selected_monopoly_stage",
    "tv_trade_selected_monopoly_type",
    "tv_trade_selected_node_pct",
    "tv_trade_selected_origin_pct",
    "tv_trade_selected_used_monopoly_level_pct",
    "tv_trade_selected_virtual_demand_active",
    "tv_trade_selected_virtual_demand_amount",
    "tv_trade_selected_virtual_demand_used_pct",
    "tv_trade_selected_virtual_supply_active",
    "tv_trade_selected_virtual_supply_amount",
    "tv_trade_selected_virtual_supply_used_pct",
)

SELECTED_MARKET_PREFIXES = (
    "origin",
    "node",
    "consumer",
)

SELECTED_MARKET_FIELDS = (
    "control_pct",
    "io_export",
    "io_import",
    "local_demand",
    "local_production",
    "total_export",
    "total_import",
)

TRADE_EXTRA_VARIABLES = (
    "tv_trade_full_consumer_weight",
    "tv_trade_full_consumer_weighted_sum",
    "tv_trade_full_export_pct",
    "tv_trade_full_import_pct",
    "tv_trade_full_local_demand",
    "tv_trade_full_local_production",
    "tv_trade_full_node_count",
    "tv_trade_full_node_pct_sum",
    "tv_trade_full_origin_weight",
    "tv_trade_full_origin_weighted_sum",
    "tv_trade_full_weighted_piece",
    "tv_trade_good_global_consumption_calc",
    "tv_trade_good_global_production_calc",
    "tv_trade_intelligence_candidate_country",
    "tv_trade_league_member_count",
    "tv_trade_market_candidate_local_demand",
    "tv_trade_market_candidate_local_production",
    "tv_trade_market_candidate_total_export",
    "tv_trade_market_candidate_total_import",
    "tv_trade_monopoly_candidate_consumer_pct",
    "tv_trade_monopoly_candidate_good",
    "tv_trade_monopoly_candidate_good_index",
    "tv_trade_monopoly_candidate_level_pct",
    "tv_trade_monopoly_candidate_monopoly",
    "tv_trade_monopoly_candidate_node_pct",
    "tv_trade_monopoly_candidate_origin_pct",
    "tv_trade_monopoly_candidate_stage",
    "tv_trade_monopoly_candidate_type",
    "tv_trade_monopoly_slot_count",
)


def load_yaml(path: Path) -> dict:
    with path.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)
    return data or {}


def add_trade_league_suppressions(targets: set[str]) -> None:
    goods = load_yaml(TRADE_GOODS_FILE).get("goods", [])
    for good in goods:
        for prefix in TRADE_GOOD_VARIABLE_PREFIXES:
            targets.add(f"{prefix}_{good}")

    for slot in range(1, MONOPOLY_SLOT_COUNT + 1):
        for field in MONOPOLY_SLOT_FIELDS:
            targets.add(f"tv_trade_monopoly_slot_{slot}_{field}")

    for row in range(1, 11):
        for field in INTELLIGENCE_ROW_FIELDS:
            targets.add(f"tv_trade_intelligence_row_{row}_{field}")

    targets.update(SELECTED_BASE_VARIABLES)
    for prefix in SELECTED_MARKET_PREFIXES:
        for rank in range(1, 4):
            for field in SELECTED_MARKET_FIELDS:
                targets.add(f"tv_trade_selected_{prefix}_{field}_{rank}")

    targets.update(TRADE_EXTRA_VARIABLES)


def add_locked_advance_suppressions(targets: set[str]) -> None:
    advances = load_yaml(LOCKED_ADVANCES_FILE).get("locked_advances", [])
    for advance in advances:
        unlock_var = advance.get("research_unlock_var")
        if unlock_var:
            targets.add(unlock_var)


def add_victory_path_suppressions(targets: set[str]) -> None:
    paths = load_yaml(VICTORY_PATHS_FILE).get("paths", [])
    targets.add("tv_victory_selected_path")
    for path in paths:
        pid = path["id"]
        for rank in range(1, 6):
            targets.add(f"tv_{pid}_rank_{rank}_country")
        for milestone in path.get("milestones", []):
            n = int(milestone["n"])
            targets.add(f"tv_{pid}_m{n}_reward_choice")


def build_targets(config: dict) -> list[str]:
    targets: set[str] = set()

    if config.get("include_trade_league_generated_variables", False):
        add_trade_league_suppressions(targets)

    if config.get("include_locked_advance_unlock_variables", False):
        add_locked_advance_suppressions(targets)

    if config.get("include_victory_path_generated_variables", False):
        add_victory_path_suppressions(targets)

    targets.update(config.get("extra_suppressions", []))
    return sorted(targets)


def generate(targets: list[str]) -> str:
    lines = [
        HEADER.rstrip(),
        "",
        "tv_cmf_warning_suppressions_monthly_pulse = {",
        "\teffect = {",
        "\t\tif = {",
        "\t\t\tlimit = { always = no }",
    ]
    for target in targets:
        lines.append(f"\t\t\tcmf_suppress = {{ v = {target} }}")
    lines.extend(
        [
            "\t\t}",
            "\t}",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    config = load_yaml(DATA_FILE)
    targets = build_targets(config)
    if not targets:
        raise SystemExit("No CMF suppressions generated")

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(generate(targets), encoding="utf-8-sig")
    print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)} ({len(targets)} suppressions)")


if __name__ == "__main__":
    main()
