l_simp_chinese:
 cmf_settings_title: "社区模组框架"
 cmf_settings_page_action_bar: "动作栏"
 cmf_settings_action_bar_group_layout: "布局"
 cmf_settings_action_bar_position_activate: "激活此位置"
 cmf_settings_action_bar_position: "操作栏位置"
 cmf_settings_action_bar_position_top: "顶部"
 cmf_settings_action_bar_position_bottom_left: "左下"
 cmf_settings_action_bar_position_bottom_right: "右下"
 cmf_settings_action_bar_group_active_buttons: "活跃按钮"
 cmf_settings_action_bar_group_active_button_activate: "激活按钮"
 cmf_settings_action_bar_group_active_button_deactivate: "停用按钮"
