"""Shared data/build logic for the Unique Wonder Ceremony framework.

Reads the `ceremony` block that gen-time-validates on every non-bespoke unique
wonder in data/unique_wonders.yaml (see scripts/wonder_mechanics/_core.py's
`_validate_ceremony`) and builds the shared, wonder-id-generic scripted_effects,
the 8 shared events (per-wonder flavor via triggered_desc), and localization
tables consumed by the per-file generators under scripts/in_game/... and
scripts/main_menu/localization/....
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts_engineering_department"))

from wonder_mechanics.io import load_all_wonder_mechanics  # noqa: E402
from wonder_mechanics.rituals import (  # noqa: E402
    STYLE_3_REWARD_EFFECTS,
    ceremony_cost_country_modifier_name,
    ceremony_cost_local_modifier_name,
    ceremony_cost_stage_multiplier,
)

T = "\t"
NAMESPACE = "tv_engineering_department"
EVENT_ID_START = 9300
STAGE_COUNT = 8
COMPLETION_EVENT_ID = EVENT_ID_START + STAGE_COUNT
CEREMONY_IMAGE = "gfx/interface/icons/towards_victory/wonders/tv_wonder_construction_cropped.dds"

def script_rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT)).replace("\\", "/")


def render_header(script: str, data: str, target: str) -> list[str]:
    return [
        f"# @Generated by {script}",
        f"#   Data:    {data}",
        f"#   Regen:   conda run --no-capture-output -n eu5 python {script}",
        "# Do not edit directly - modify the data file and re-run the generator.",
        f"# Target: {target}",
        "",
    ]


def ceremony_wonders_and_mechanics() -> tuple[list[dict], dict]:
    """Ceremony-enabled unique wonders and the generic reward data they reuse."""
    wonders, mechanics = load_all_wonder_mechanics()
    ceremony_wonders = sorted(
        (wonder for wonder in wonders if wonder.get("is_unique") and wonder.get("ceremony") is not None),
        key=lambda w: int(w["id"]),
    )
    return ceremony_wonders, mechanics


def ceremony_wonders() -> list[dict]:
    """Every unique wonder that carries a `ceremony` block (excludes Pharos/Hagia)."""
    return ceremony_wonders_and_mechanics()[0]


def stage_2_reward_for_wonder(wonder: dict, mechanics: dict) -> list[dict]:
    """Reuse the matching generic style-3 reward at ceremony stage two."""
    return mechanics["generic_rituals"][wonder["mechanic_key"]]["style_3"]["reward"]


def stage_event_id(stage: int) -> int:
    """1-indexed stage (1..8) -> event id (10000..10007)."""
    return EVENT_ID_START + stage - 1


def title_key(stage: int, wonder_id: int) -> str:
    return f"TV_WONDER_CEREMONY_S{stage}_TITLE_{wonder_id}"


def desc_key(stage: int, wonder_id: int) -> str:
    return f"TV_WONDER_CEREMONY_S{stage}_DESC_{wonder_id}"


def card_icon_key(stage: int, wonder_id: int) -> str:
    return f"TV_WONDER_CEREMONY_CARD_ICON_S{stage}_{wonder_id}"


def pay_option_key(stage: int) -> str:
    return f"{NAMESPACE}.{stage_event_id(stage)}.a"


def decline_option_key(stage: int) -> str:
    return f"{NAMESPACE}.{stage_event_id(stage)}.b"


def option_pay_text_key(stage: int, wonder_id: int) -> str:
    return f"TV_WONDER_CEREMONY_S{stage}_OPTION_PAY_{wonder_id}"


def option_decline_text_key(stage: int, wonder_id: int) -> str:
    return f"TV_WONDER_CEREMONY_S{stage}_OPTION_DECLINE_{wonder_id}"


def option_pay_fallback_key(stage: int) -> str:
    return f"TV_WONDER_CEREMONY_S{stage}_OPTION_PAY_FALLBACK"


def option_decline_fallback_key(stage: int) -> str:
    return f"TV_WONDER_CEREMONY_S{stage}_OPTION_DECLINE_FALLBACK"


def used_ceremony_cost_tiers(wonders: list[dict], catalog: str) -> list[tuple[str, int]]:
    """Every distinct (id, tier) pair actually referenced by an authored ceremony stage cost
    for the given catalog ("country_modifier" or "local_modifier") — shared by the static
    modifier generators and the loc generators' STATIC_MODIFIER_NAME_ entries, so both stay
    in sync with exactly what's used (not the full catalog x tier cross product)."""
    used: set[tuple[str, int]] = set()
    for wonder in wonders:
        for stage_index, stage in enumerate(wonder["ceremony"]["stages"], start=1):
            tier = ceremony_cost_stage_multiplier(stage_index)
            for item in stage["cost"]:
                if item["catalog"] == catalog:
                    used.add((item["type"], tier))
    return sorted(used)


def option_pay_cl_block(stage: int) -> str:
    """Customizable Localization block name for a stage's 'pay' option text."""
    return f"tv_wonder_ceremony_stage_{stage}_pay"


def option_decline_cl_block(stage: int) -> str:
    """Customizable Localization block name for a stage's 'decline' option text."""
    return f"tv_wonder_ceremony_stage_{stage}_decline"


def append_option_customizable_localization_block(
    lines: list[str], stage: int, wonders: list[dict], *, pay: bool
) -> None:
    """One Customizable Localization block (type = country) per stage/option, dispatching
    on var:tv_wonder_locked to the per-wonder option text key. The event's option.name stays
    a single flat key (tv_engineering_department.<event_id>.a/.b, unchanged); only that key's
    localization VALUE calls Custom(<block name>) to resolve per-wonder — see
    docs/technical/EU5_Modding_Knowledge_Base.md "Customizable Localization Syntax and Usage"
    and this mod's own tv_academy_debate_groups.txt precedent."""
    block_name = option_pay_cl_block(stage) if pay else option_decline_cl_block(stage)
    key_fn = option_pay_text_key if pay else option_decline_text_key
    fallback_fn = option_pay_fallback_key if pay else option_decline_fallback_key
    lines.append(f"{block_name} = {{")
    lines.append(f"{T}type = country")
    lines.append("")
    for wonder in wonders:
        lines.append(f"{T}text = {{")
        lines.append(f"{T}{T}trigger = {{ var:tv_wonder_locked ?= {wonder['id']} }}")
        lines.append(f"{T}{T}localization_key = {key_fn(stage, wonder['id'])}")
        lines.append(f"{T}}}")
    lines.append(f"{T}text = {{")
    lines.append(f"{T}{T}trigger = {{ always = no }}")
    lines.append(f"{T}{T}fallback = yes")
    lines.append(f"{T}{T}localization_key = {fallback_fn(stage)}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def reward_effect_lines(reward: list[dict], indent: int, allow_artwork: bool = False) -> list[str]:
    """Mirrors gen_tv_engineering_department_wonder_mechanics_effects.py's
    reward_effect_lines() for the same STYLE_3_REWARD_EFFECTS vocabulary. Stage-two
    rewards retain site-scoped entries, while ceremony costs are restricted by the
    data validator. An "artwork" entry has no scalar effect, so it only renders when
    allow_artwork=True, which the per-stage ceremony cost dispatch opts into."""
    prefix = T * indent
    lines: list[str] = []
    for entry in reward:
        if entry["type"] == "artwork":
            if not allow_artwork:
                raise ValueError("'artwork' is not a valid reward type")
            lines.append(f"{prefix}random_work_of_art_in_country = {{ save_scope_as = tv_wonder_ceremony_sacrificed_artwork }}")
            lines.append(f"{prefix}destroy_art = scope:tv_wonder_ceremony_sacrificed_artwork")
            continue
        spec = STYLE_3_REWARD_EFFECTS[entry["type"]]
        effect = spec["effect"]
        scope = spec["scope"]
        value = entry["value"]
        if scope in {"country_scalar", "country_raw"}:
            lines.append(f"{prefix}{effect} = {value}")
        elif scope == "country_value_block":
            lines.append(f"{prefix}{effect} = {{ value = {value} }}")
        elif scope == "country_scale_block":
            lines.append(f"{prefix}{effect} = {{ scale = {value} }}")
        elif scope == "ruler_scalar":
            lines.append(f"{prefix}ruler ?= {{ {effect} = {value} }}")
        elif scope == "culture_scalar":
            lines.append(f"{prefix}culture = {{ {effect} = {value} }}")
        elif scope == "location_scalar":
            lines.append(f"{prefix}var:tv_wonder_site ?= {{ {effect} = {value} }}")
        else:
            raise ValueError(f"Unsupported ceremony reward scope: {scope}")
    return lines


CEREMONY_COST_TEMPORARY_MODIFIER_YEARS = 5

# country_reward ids that reuse an existing STYLE_3_REWARD_EFFECTS scalar effect verbatim
# (same effect name, new magnitude sourced from data/cost_reward_units.yaml).
CEREMONY_COST_COUNTRY_REWARD_EFFECTS = {
    "government_power": "add_government_power",
    "stability": "add_stability",
    "prestige": "add_prestige",
    "research_progress": "add_research_progress",
    "army_tradition": "add_army_tradition",
    "navy_tradition": "add_navy_tradition",
    "manpower": "add_manpower",
    "sailors": "add_sailors",
}
CEREMONY_COST_ESTATE_SATISFACTION_TYPES = {
    "nobles_satisfaction": "estate_type:nobles_estate",
    "clergy_satisfaction": "estate_type:clergy_estate",
    "burghers_satisfaction": "estate_type:burghers_estate",
    "peasants_satisfaction": "estate_type:peasants_estate",
}
CEREMONY_COST_LOCAL_REWARD_EFFECTS = {
    "development": "change_development",
    "prosperity": "change_prosperity",
}
CEREMONY_COST_CHARACTER_RULER_EFFECTS = {
    "adm": "add_adm",
    "dip": "add_dip",
    "mil": "add_mil",
}


def ceremony_cost_effect_lines(cost: list[dict], indent: int, stage_index: int) -> list[str]:
    """Renders a Unique Wonder Ceremony stage's cost — data/cost_reward_units.yaml-backed,
    {catalog, type, value} shape — into EU5 effect lines. New, separate from
    reward_effect_lines() above, which remains the STYLE_3_REWARD_EFFECTS renderer for the
    unrelated stage-2/4/8 reward channels (see docs/knowledge/risk_cards/wonders.md rule 20)."""
    prefix = T * indent
    lines: list[str] = []
    for entry in cost:
        catalog = entry["catalog"]
        entry_id = entry["type"]
        value = entry["value"]
        if catalog == "country_reward":
            if entry_id == "scaled_gold":
                lines.append(f"{prefix}change_gold_effect = {{ scale = {value} }}")
            elif entry_id in CEREMONY_COST_COUNTRY_REWARD_EFFECTS:
                lines.append(f"{prefix}{CEREMONY_COST_COUNTRY_REWARD_EFFECTS[entry_id]} = {value}")
            elif entry_id == "inflation":
                lines.append(f"{prefix}add_inflation = {value}")
            elif entry_id in CEREMONY_COST_ESTATE_SATISFACTION_TYPES:
                estate = CEREMONY_COST_ESTATE_SATISFACTION_TYPES[entry_id]
                lines.append(f"{prefix}add_estate_satisfaction = {{ type = {estate} value = {value} }}")
            else:
                raise ValueError(f"Unsupported country_reward cost id: {entry_id}")
        elif catalog == "local_reward":
            if entry_id not in CEREMONY_COST_LOCAL_REWARD_EFFECTS:
                raise ValueError(f"Unsupported local_reward cost id: {entry_id}")
            effect = CEREMONY_COST_LOCAL_REWARD_EFFECTS[entry_id]
            lines.append(f"{prefix}var:tv_wonder_site ?= {{ {effect} = {value} }}")
        elif catalog == "character_reward":
            if entry_id in CEREMONY_COST_CHARACTER_RULER_EFFECTS:
                effect = CEREMONY_COST_CHARACTER_RULER_EFFECTS[entry_id]
                lines.append(f"{prefix}ruler ?= {{ {effect} = {value} }}")
            elif entry_id == "artist_skill":
                lines.append(
                    f"{prefix}random_artist = {{ limit = {{ is_alive = yes }} "
                    f"save_scope_as = tv_wonder_ceremony_cost_artist }}"
                )
                lines.append(f"{prefix}if = {{")
                lines.append(f"{prefix}{T}limit = {{ exists = scope:tv_wonder_ceremony_cost_artist }}")
                lines.append(f"{prefix}{T}scope:tv_wonder_ceremony_cost_artist = {{ add_artist_skill = {value} }}")
                lines.append(f"{prefix}}}")
            else:
                raise ValueError(f"Unsupported character_reward cost id: {entry_id}")
        elif catalog == "country_modifier":
            tier = ceremony_cost_stage_multiplier(stage_index)
            modifier_name = ceremony_cost_country_modifier_name(entry_id, tier)
            lines.append(
                f"{prefix}add_country_modifier = {{ modifier = {modifier_name} "
                f"years = {CEREMONY_COST_TEMPORARY_MODIFIER_YEARS} mode = add_and_extend }}"
            )
        elif catalog == "local_modifier":
            tier = ceremony_cost_stage_multiplier(stage_index)
            modifier_name = ceremony_cost_local_modifier_name(entry_id, tier)
            lines.append(f"{prefix}var:tv_wonder_site ?= {{")
            lines.append(
                f"{prefix}{T}add_location_modifier = {{ modifier = {modifier_name} "
                f"years = {CEREMONY_COST_TEMPORARY_MODIFIER_YEARS} mode = add_and_extend }}"
            )
            lines.append(f"{prefix}}}")
        else:
            raise ValueError(f"Unsupported ceremony cost catalog: {catalog}")
    return lines
