"""Shared data builders for generated Wonder Construction random events."""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = REPO_ROOT / "data" / "wonder_construction_events.yaml"
T = "\t"


NONENG_MAGNITUDE_DECIMALS = {
    "gold": 0,
    "legitimacy": 0,
    "stability": 0,
    "prestige": 0,
    "nobles_satisfaction": 2,
    "clergy_satisfaction": 2,
    "burghers_satisfaction": 2,
    "peasants_satisfaction": 2,
    "site_development": 2,
    "capital_development": 2,
    "site_prosperity": 1,
    "capital_prosperity": 1,
    "site_laborers": 0,
}


def format_noneng_magnitude(token_id: str, magnitude: float) -> str:
    decimals = NONENG_MAGNITUDE_DECIMALS[token_id]
    if decimals == 0:
        return str(int(round(magnitude)))
    return f"{magnitude:.{decimals}f}"


EVENT_KIND_WEIGHTS = {
    "gain_engineering_2": 1,
    "gain_engineering_1": 5,
    "trade_noneng_for_eng": 5,
    "swing_engineering_1": 5,
    "choose_eng_or_noneng_loss": 5,
    "lose_noneng_1": 5,
    "lose_noneng_2": 1,
    "engineer_gain_engineering_2": 5,
    "engineer_gain_engineering_1": 5,
    "engineer_swing_engineering_1": 5,
    "engineer_lose_noneng_1": 5,
    "engineer_lose_noneng_2": 5,
}

KIND_OUTCOMES = {
    "gain_engineering_2": "positive",
    "gain_engineering_1": "positive",
    "trade_noneng_for_eng": "neutral",
    "swing_engineering_1": "neutral",
    "choose_eng_or_noneng_loss": "negative",
    "lose_noneng_1": "negative",
    "lose_noneng_2": "negative",
    "engineer_gain_engineering_2": "positive",
    "engineer_gain_engineering_1": "positive",
    "engineer_swing_engineering_1": "neutral",
    "engineer_lose_noneng_1": "negative",
    "engineer_lose_noneng_2": "negative",
}

# Fixed token iteration order used by build_events() below - also doubles as the
# deterministic index basis for picking a variant out of a combinatorial-kind pool.
ENG_TOKEN_ORDER = [
    "domestic_support", "scale_competence", "organization_competence",
    "logistics_competence", "construction_progress",
]
NONENG_TOKEN_ORDER = [
    "gold", "legitimacy", "stability", "prestige",
    "nobles_satisfaction", "clergy_satisfaction", "burghers_satisfaction", "peasants_satisfaction",
    "site_development", "site_prosperity", "capital_development", "capital_prosperity",
    "site_laborers",
]

# The 2 kinds whose desc/option text is drawn from a rotating pool (keyed on the
# specific eng/noneng token pairing) rather than a fixed per-event lookup.
COMBINATORIAL_KINDS = {"trade_noneng_for_eng", "choose_eng_or_noneng_loss"}

ENGINEERING_CONCEPT_REF_EN = {
    "domestic_support": "[tv_wonder_domestic_support|E]",
    "scale_competence": "[tv_wonder_scale_competence|E]",
    "organization_competence": "[tv_wonder_organization_competence|E]",
    "logistics_competence": "[tv_wonder_logistics_competence|E]",
    "materials_stockpile": "[tv_wonder_materials|E]",
    "construction_progress": "[tv_wonder_construction|E] progress",
}

NON_ENGINEERING_CONCEPT_REF_EN = {
    "gold": "[gold|E]",
    "legitimacy": "[legitimacy|E]",
    "stability": "[stability|E]",
    "prestige": "[prestige|E]",
    "nobles_satisfaction": "[estate_satisfaction|E] among the nobles",
    "clergy_satisfaction": "[estate_satisfaction|E] among the clergy",
    "burghers_satisfaction": "[estate_satisfaction|E] among the burghers",
    "peasants_satisfaction": "[estate_satisfaction|E] among the peasants",
    "site_development": "[development|E] at the site",
    "site_prosperity": "[prosperity|E] at the site",
    "capital_development": "[development|E] in the capital",
    "capital_prosperity": "[prosperity|E] in the capital",
    "site_laborers": "the laboring [population|E] at the site",
}

ENGINEERING_CONCEPT_REF_ZH = {
    "domestic_support": "[tv_wonder_domestic_support|E]",
    "scale_competence": "[tv_wonder_scale_competence|E]",
    "organization_competence": "[tv_wonder_organization_competence|E]",
    "logistics_competence": "[tv_wonder_logistics_competence|E]",
    "materials_stockpile": "[tv_wonder_materials|E]",
    "construction_progress": "[tv_wonder_construction|E]\u8fdb\u5ea6",
}

NON_ENGINEERING_CONCEPT_REF_ZH = {
    "gold": "[gold|E]",
    "legitimacy": "[legitimacy|E]",
    "stability": "[stability|E]",
    "prestige": "[prestige|E]",
    "nobles_satisfaction": "\u8d35\u65cf[estate_satisfaction|E]",
    "clergy_satisfaction": "\u6559\u58eb[estate_satisfaction|E]",
    "burghers_satisfaction": "\u5e02\u6c11[estate_satisfaction|E]",
    "peasants_satisfaction": "\u5e73\u6c11[estate_satisfaction|E]",
    "site_development": "\u5de5\u5740[development|E]",
    "site_prosperity": "\u5de5\u5740[prosperity|E]",
    "capital_development": "\u9996\u90fd[development|E]",
    "capital_prosperity": "\u9996\u90fd[prosperity|E]",
    "site_laborers": "\u5de5\u5740\u52b3\u5de5[population|E]",
}

# ---- Begin generated data tables (see scripts/_scratch_build_lib_tables.py) ----

TITLE_EN = {
    7000: '[tv_wonder_construction|E]：The Streets Applaud the Site',
    7001: '[tv_wonder_construction|E]：A Wider Line on the Earth',
    7002: '[tv_wonder_construction|E]：Names and Orders Fall Into Place',
    7003: '[tv_wonder_construction|E]：Roads and Carts Find Their Rhythm',
    7004: '[tv_wonder_construction|E]：Stone Rises Past the Mark',
    7005: '[tv_wonder_construction|E]：Street Talk Turns',
    7006: '[tv_wonder_construction|E]：The Measure Is Corrected',
    7007: '[tv_wonder_construction|E]：The Yard Learns Its Rhythm',
    7008: '[tv_wonder_construction|E]：Ruts Find a Better Road',
    7009: '[tv_wonder_construction|E]：Hammers Draw Completion Near',
    7010: '[tv_wonder_construction|E]：Treasury Doors Open for Public Backing',
    7011: '[tv_wonder_construction|E]：Royal Authority Is Pledged for Public Backing',
    7012: '[tv_wonder_construction|E]：Villages Give Way for Public Backing',
    7013: '[tv_wonder_construction|E]：Reputation Is Spent for Public Backing',
    7014: '[tv_wonder_construction|E]：Noble Patience Is Borrowed for Public Backing',
    7015: '[tv_wonder_construction|E]：The Altars Are Asked to Yield for Public Backing',
    7016: '[tv_wonder_construction|E]：The Market Lends Its Streets for Public Backing',
    7017: '[tv_wonder_construction|E]：Village Shoulders Are Borrowed for Public Backing',
    7018: '[tv_wonder_construction|E]：The Site Gives Stone and Space for Public Backing',
    7019: '[tv_wonder_construction|E]：Local Trade Is Bent Toward the Works for Public Backing',
    7020: '[tv_wonder_construction|E]：Capital Works Are Reassigned for Public Backing',
    7021: '[tv_wonder_construction|E]：The Capital\'s Markets Are Turned for Public Backing',
    7022: '[tv_wonder_construction|E]：Labor Is Driven Harder for Public Backing',
    7023: '[tv_wonder_construction|E]：Treasury Doors Open for A Broader Design',
    7024: '[tv_wonder_construction|E]：Royal Authority Is Pledged for A Broader Design',
    7025: '[tv_wonder_construction|E]：Villages Give Way for A Broader Design',
    7026: '[tv_wonder_construction|E]：Reputation Is Spent for A Broader Design',
    7027: '[tv_wonder_construction|E]：Noble Patience Is Borrowed for A Broader Design',
    7028: '[tv_wonder_construction|E]：The Altars Are Asked to Yield for A Broader Design',
    7029: '[tv_wonder_construction|E]：The Market Lends Its Streets for A Broader Design',
    7030: '[tv_wonder_construction|E]：Village Shoulders Are Borrowed for A Broader Design',
    7031: '[tv_wonder_construction|E]：The Site Gives Stone and Space for A Broader Design',
    7032: '[tv_wonder_construction|E]：Local Trade Is Bent Toward the Works for A Broader Design',
    7033: '[tv_wonder_construction|E]：Capital Works Are Reassigned for A Broader Design',
    7034: '[tv_wonder_construction|E]：The Capital\'s Markets Are Turned for A Broader Design',
    7035: '[tv_wonder_construction|E]：Labor Is Driven Harder for A Broader Design',
    7036: '[tv_wonder_construction|E]：Treasury Doors Open for Sharper Orders',
    7037: '[tv_wonder_construction|E]：Royal Authority Is Pledged for Sharper Orders',
    7038: '[tv_wonder_construction|E]：Villages Give Way for Sharper Orders',
    7039: '[tv_wonder_construction|E]：Reputation Is Spent for Sharper Orders',
    7040: '[tv_wonder_construction|E]：Noble Patience Is Borrowed for Sharper Orders',
    7041: '[tv_wonder_construction|E]：The Altars Are Asked to Yield for Sharper Orders',
    7042: '[tv_wonder_construction|E]：The Market Lends Its Streets for Sharper Orders',
    7043: '[tv_wonder_construction|E]：Village Shoulders Are Borrowed for Sharper Orders',
    7044: '[tv_wonder_construction|E]：The Site Gives Stone and Space for Sharper Orders',
    7045: '[tv_wonder_construction|E]：Local Trade Is Bent Toward the Works for Sharper Orders',
    7046: '[tv_wonder_construction|E]：Capital Works Are Reassigned for Sharper Orders',
    7047: '[tv_wonder_construction|E]：The Capital\'s Markets Are Turned for Sharper Orders',
    7048: '[tv_wonder_construction|E]：Labor Is Driven Harder for Sharper Orders',
    7049: '[tv_wonder_construction|E]：Treasury Doors Open for A Clearer Road',
    7050: '[tv_wonder_construction|E]：Royal Authority Is Pledged for A Clearer Road',
    7051: '[tv_wonder_construction|E]：Villages Give Way for A Clearer Road',
    7052: '[tv_wonder_construction|E]：Reputation Is Spent for A Clearer Road',
    7053: '[tv_wonder_construction|E]：Noble Patience Is Borrowed for A Clearer Road',
    7054: '[tv_wonder_construction|E]：The Altars Are Asked to Yield for A Clearer Road',
    7055: '[tv_wonder_construction|E]：The Market Lends Its Streets for A Clearer Road',
    7056: '[tv_wonder_construction|E]：Village Shoulders Are Borrowed for A Clearer Road',
    7057: '[tv_wonder_construction|E]：The Site Gives Stone and Space for A Clearer Road',
    7058: '[tv_wonder_construction|E]：Local Trade Is Bent Toward the Works for A Clearer Road',
    7059: '[tv_wonder_construction|E]：Capital Works Are Reassigned for A Clearer Road',
    7060: '[tv_wonder_construction|E]：The Capital\'s Markets Are Turned for A Clearer Road',
    7061: '[tv_wonder_construction|E]：Labor Is Driven Harder for A Clearer Road',
    7062: '[tv_wonder_construction|E]：Treasury Doors Open for A Sudden Advance',
    7063: '[tv_wonder_construction|E]：Royal Authority Is Pledged for A Sudden Advance',
    7064: '[tv_wonder_construction|E]：Villages Give Way for A Sudden Advance',
    7065: '[tv_wonder_construction|E]：Reputation Is Spent for A Sudden Advance',
    7066: '[tv_wonder_construction|E]：Noble Patience Is Borrowed for A Sudden Advance',
    7067: '[tv_wonder_construction|E]：The Altars Are Asked to Yield for A Sudden Advance',
    7068: '[tv_wonder_construction|E]：The Market Lends Its Streets for A Sudden Advance',
    7069: '[tv_wonder_construction|E]：Village Shoulders Are Borrowed for A Sudden Advance',
    7070: '[tv_wonder_construction|E]：The Site Gives Stone and Space for A Sudden Advance',
    7071: '[tv_wonder_construction|E]：Local Trade Is Bent Toward the Works for A Sudden Advance',
    7072: '[tv_wonder_construction|E]：Capital Works Are Reassigned for A Sudden Advance',
    7073: '[tv_wonder_construction|E]：The Capital\'s Markets Are Turned for A Sudden Advance',
    7074: '[tv_wonder_construction|E]：Labor Is Driven Harder for A Sudden Advance',
    7075: '[tv_wonder_construction|E]：Opinion at the Scaffold Wavers',
    7076: '[tv_wonder_construction|E]：The Plan Outgrows the Page',
    7077: '[tv_wonder_construction|E]：Orders Change Under the Awning',
    7078: '[tv_wonder_construction|E]：The Route Turns Through Mud',
    7079: '[tv_wonder_construction|E]：A New Method Hangs in the Air',
    7080: '[tv_wonder_construction|E]：Public Doubt or Silver Runs Thin',
    7081: '[tv_wonder_construction|E]：Public Doubt or Mandate Wears Thin',
    7082: '[tv_wonder_construction|E]：Public Doubt or Order Loosens',
    7083: '[tv_wonder_construction|E]：Public Doubt or Prestige Gathers Dust',
    7084: '[tv_wonder_construction|E]：Public Doubt or Noble Murmurs',
    7085: '[tv_wonder_construction|E]：Public Doubt or Clerical Unease',
    7086: '[tv_wonder_construction|E]：Public Doubt or Merchant Complaints',
    7087: '[tv_wonder_construction|E]：Public Doubt or Tired Villages',
    7088: '[tv_wonder_construction|E]：Public Doubt or The Site Is Hollowed',
    7089: '[tv_wonder_construction|E]：Public Doubt or The Site Cools',
    7090: '[tv_wonder_construction|E]：Public Doubt or The Capital Gives Up Its Frame',
    7091: '[tv_wonder_construction|E]：Public Doubt or The Capital Cools',
    7092: '[tv_wonder_construction|E]：Public Doubt or Laborers Fall',
    7093: '[tv_wonder_construction|E]：A Narrower Monument or Silver Runs Thin',
    7094: '[tv_wonder_construction|E]：A Narrower Monument or Mandate Wears Thin',
    7095: '[tv_wonder_construction|E]：A Narrower Monument or Order Loosens',
    7096: '[tv_wonder_construction|E]：A Narrower Monument or Prestige Gathers Dust',
    7097: '[tv_wonder_construction|E]：A Narrower Monument or Noble Murmurs',
    7098: '[tv_wonder_construction|E]：A Narrower Monument or Clerical Unease',
    7099: '[tv_wonder_construction|E]：A Narrower Monument or Merchant Complaints',
    7100: '[tv_wonder_construction|E]：A Narrower Monument or Tired Villages',
    7101: '[tv_wonder_construction|E]：A Narrower Monument or The Site Is Hollowed',
    7102: '[tv_wonder_construction|E]：A Narrower Monument or The Site Cools',
    7103: '[tv_wonder_construction|E]：A Narrower Monument or The Capital Gives Up Its Frame',
    7104: '[tv_wonder_construction|E]：A Narrower Monument or The Capital Cools',
    7105: '[tv_wonder_construction|E]：A Narrower Monument or Laborers Fall',
    7106: '[tv_wonder_construction|E]：Muddled Rosters or Silver Runs Thin',
    7107: '[tv_wonder_construction|E]：Muddled Rosters or Mandate Wears Thin',
    7108: '[tv_wonder_construction|E]：Muddled Rosters or Order Loosens',
    7109: '[tv_wonder_construction|E]：Muddled Rosters or Prestige Gathers Dust',
    7110: '[tv_wonder_construction|E]：Muddled Rosters or Noble Murmurs',
    7111: '[tv_wonder_construction|E]：Muddled Rosters or Clerical Unease',
    7112: '[tv_wonder_construction|E]：Muddled Rosters or Merchant Complaints',
    7113: '[tv_wonder_construction|E]：Muddled Rosters or Tired Villages',
    7114: '[tv_wonder_construction|E]：Muddled Rosters or The Site Is Hollowed',
    7115: '[tv_wonder_construction|E]：Muddled Rosters or The Site Cools',
    7116: '[tv_wonder_construction|E]：Muddled Rosters or The Capital Gives Up Its Frame',
    7117: '[tv_wonder_construction|E]：Muddled Rosters or The Capital Cools',
    7118: '[tv_wonder_construction|E]：Muddled Rosters or Laborers Fall',
    7119: '[tv_wonder_construction|E]：Delayed Convoys or Silver Runs Thin',
    7120: '[tv_wonder_construction|E]：Delayed Convoys or Mandate Wears Thin',
    7121: '[tv_wonder_construction|E]：Delayed Convoys or Order Loosens',
    7122: '[tv_wonder_construction|E]：Delayed Convoys or Prestige Gathers Dust',
    7123: '[tv_wonder_construction|E]：Delayed Convoys or Noble Murmurs',
    7124: '[tv_wonder_construction|E]：Delayed Convoys or Clerical Unease',
    7125: '[tv_wonder_construction|E]：Delayed Convoys or Merchant Complaints',
    7126: '[tv_wonder_construction|E]：Delayed Convoys or Tired Villages',
    7127: '[tv_wonder_construction|E]：Delayed Convoys or The Site Is Hollowed',
    7128: '[tv_wonder_construction|E]：Delayed Convoys or The Site Cools',
    7129: '[tv_wonder_construction|E]：Delayed Convoys or The Capital Gives Up Its Frame',
    7130: '[tv_wonder_construction|E]：Delayed Convoys or The Capital Cools',
    7131: '[tv_wonder_construction|E]：Delayed Convoys or Laborers Fall',
    7132: '[tv_wonder_construction|E]：Lost Progress or Silver Runs Thin',
    7133: '[tv_wonder_construction|E]：Lost Progress or Mandate Wears Thin',
    7134: '[tv_wonder_construction|E]：Lost Progress or Order Loosens',
    7135: '[tv_wonder_construction|E]：Lost Progress or Prestige Gathers Dust',
    7136: '[tv_wonder_construction|E]：Lost Progress or Noble Murmurs',
    7137: '[tv_wonder_construction|E]：Lost Progress or Clerical Unease',
    7138: '[tv_wonder_construction|E]：Lost Progress or Merchant Complaints',
    7139: '[tv_wonder_construction|E]：Lost Progress or Tired Villages',
    7140: '[tv_wonder_construction|E]：Lost Progress or The Site Is Hollowed',
    7141: '[tv_wonder_construction|E]：Lost Progress or The Site Cools',
    7142: '[tv_wonder_construction|E]：Lost Progress or The Capital Gives Up Its Frame',
    7143: '[tv_wonder_construction|E]：Lost Progress or The Capital Cools',
    7144: '[tv_wonder_construction|E]：Lost Progress or Laborers Fall',
    7145: '[tv_wonder_construction|E]：A New Gap in the Treasury',
    7146: '[tv_wonder_construction|E]：Dust on the Royal Seal',
    7147: '[tv_wonder_construction|E]：Quiet Towns Are Disturbed',
    7148: '[tv_wonder_construction|E]：The Court Loses Color',
    7149: '[tv_wonder_construction|E]：Cold Words at Noble Tables',
    7150: '[tv_wonder_construction|E]：Frowns Before the Altar',
    7151: '[tv_wonder_construction|E]：Thinner Ledgers in the Market',
    7152: '[tv_wonder_construction|E]：Heavier Backs in the Villages',
    7153: '[tv_wonder_construction|E]：The Site Gives Up Its Streets',
    7154: '[tv_wonder_construction|E]：The Site Grows Quieter',
    7155: '[tv_wonder_construction|E]：Capital Projects Make Way',
    7156: '[tv_wonder_construction|E]：Quieter Streets in the Capital',
    7157: '[tv_wonder_construction|E]：Names Added to the Injury Roll',
    7158: '[tv_wonder_construction|E]：Silence at the Treasury Door',
    7159: '[tv_wonder_construction|E]：Mandate Cracks Before the Site',
    7160: '[tv_wonder_construction|E]：Order Splinters in the Levy',
    7161: '[tv_wonder_construction|E]：Honor Falters in Public',
    7162: '[tv_wonder_construction|E]：Noble Patience Is Chiseled Through',
    7163: '[tv_wonder_construction|E]：Patience Runs Out in the Vestry',
    7164: '[tv_wonder_construction|E]：Anger Reaches the Streets',
    7165: '[tv_wonder_construction|E]：Rural Anger Will Not Stay Quiet',
    7166: '[tv_wonder_construction|E]：The Site Falls Back',
    7167: '[tv_wonder_construction|E]：The Site\'s Prosperity Is Smothered',
    7168: '[tv_wonder_construction|E]：The Capital Pays in Stone',
    7169: '[tv_wonder_construction|E]：The Royal City\'s Trade Is Pressed Low',
    7170: '[tv_wonder_construction|E]：Sweat Crosses Into Blood',
    7171: '[tv_wonder_construction|E]：[tv_great_engineer|E] Wins the Street',
    7172: '[tv_wonder_construction|E]：[tv_great_engineer|E] Redraws the Grand Line',
    7173: '[tv_wonder_construction|E]：[tv_great_engineer|E] Rebuilds the Schedule',
    7174: '[tv_wonder_construction|E]：[tv_great_engineer|E] Opens the Road',
    7175: '[tv_wonder_construction|E]：[tv_great_engineer|E] Drives the Main Works',
    7176: '[tv_wonder_construction|E]：[tv_great_engineer|E] Calms the Rumor',
    7177: '[tv_wonder_construction|E]：[tv_great_engineer|E] Sets the Measure',
    7178: '[tv_wonder_construction|E]：[tv_great_engineer|E] Straightens the Rolls',
    7179: '[tv_wonder_construction|E]：[tv_great_engineer|E] Clears the Convoy',
    7180: '[tv_wonder_construction|E]：[tv_great_engineer|E] Fits the Critical Joint',
    7181: '[tv_wonder_construction|E]：[tv_great_engineer|E] Courts the Crowd',
    7182: '[tv_wonder_construction|E]：[tv_great_engineer|E] Enlarges the Plan',
    7183: '[tv_wonder_construction|E]：[tv_great_engineer|E] Rewrites the Shift',
    7184: '[tv_wonder_construction|E]：[tv_great_engineer|E] Takes the Risky Road',
    7185: '[tv_wonder_construction|E]：[tv_great_engineer|E] Tests a Faster Method',
    7186: '[tv_wonder_construction|E]：[tv_great_engineer|E] Miscounts the Coin',
    7187: '[tv_wonder_construction|E]：[tv_great_engineer|E] Forgets the Court',
    7188: '[tv_wonder_construction|E]：[tv_great_engineer|E] Misreads the Villages',
    7189: '[tv_wonder_construction|E]：[tv_great_engineer|E] Speaks Too Soon',
    7190: '[tv_wonder_construction|E]：[tv_great_engineer|E] Slights the Nobles',
    7191: '[tv_wonder_construction|E]：[tv_great_engineer|E] Disturbs the Calendar',
    7192: '[tv_wonder_construction|E]：[tv_great_engineer|E] Blocks the Market',
    7193: '[tv_wonder_construction|E]：[tv_great_engineer|E] Underestimates the Villages',
    7194: '[tv_wonder_construction|E]：[tv_great_engineer|E] Cuts the Wrong Streets',
    7195: '[tv_wonder_construction|E]：[tv_great_engineer|E] Crowds the Site\'s Livelihoods',
    7196: '[tv_wonder_construction|E]：[tv_great_engineer|E] Misuses the Capital',
    7197: '[tv_wonder_construction|E]：[tv_great_engineer|E] Disturbs the Royal City',
    7198: '[tv_wonder_construction|E]：[tv_great_engineer|E] Misjudges the Labor Limit',
    7199: '[tv_wonder_construction|E]：[tv_great_engineer|E] Breaks the Ledger',
    7200: '[tv_wonder_construction|E]：[tv_great_engineer|E] Wounds the Crown',
    7201: '[tv_wonder_construction|E]：[tv_great_engineer|E] Unsettles the Country',
    7202: '[tv_wonder_construction|E]：[tv_great_engineer|E] Makes a Spectacle',
    7203: '[tv_wonder_construction|E]：[tv_great_engineer|E] Angers the Houses',
    7204: '[tv_wonder_construction|E]：[tv_great_engineer|E] Offends the Clergy',
    7205: '[tv_wonder_construction|E]：[tv_great_engineer|E] Provokes the Burghers',
    7206: '[tv_wonder_construction|E]：[tv_great_engineer|E] Breaks the Villages',
    7207: '[tv_wonder_construction|E]：[tv_great_engineer|E] Injures the Site',
    7208: '[tv_wonder_construction|E]：[tv_great_engineer|E] Snuffs Out the Site\'s Markets',
    7209: '[tv_wonder_construction|E]：[tv_great_engineer|E] Hollows the Capital\'s Plans',
    7210: '[tv_wonder_construction|E]：[tv_great_engineer|E] Dims the Capital\'s Prosperity',
    7211: '[tv_wonder_construction|E]：[tv_great_engineer|E] Causes Casualties',
}

TITLE_ZH = {
    7000: '[tv_wonder_construction|E]：围栏外开始叫好',
    7001: '[tv_wonder_construction|E]：测线证明还能扩建',
    7002: '[tv_wonder_construction|E]：名册与工序终于对上',
    7003: '[tv_wonder_construction|E]：补给线终于跑顺了',
    7004: '[tv_wonder_construction|E]：主工段提前越过标线',
    7005: '[tv_wonder_construction|E]：工地外的议论缓下来了',
    7006: '[tv_wonder_construction|E]：图纸上的误差被纠正',
    7007: '[tv_wonder_construction|E]：工棚里的交接终于理顺',
    7008: '[tv_wonder_construction|E]：补给线的坏转角被改掉',
    7009: '[tv_wonder_construction|E]：关键接口终于合上',
    7010: '[tv_wonder_construction|E]：国库拨款稳住民心',
    7011: '[tv_wonder_construction|E]：王命压下反对声',
    7012: '[tv_wonder_construction|E]：地方让路，民议转缓',
    7013: '[tv_wonder_construction|E]：宫廷声望为工地背书',
    7014: '[tv_wonder_construction|E]：贵族默许工程继续',
    7015: '[tv_wonder_construction|E]：教士暂时收起异议',
    7016: '[tv_wonder_construction|E]：商人把便利让给工地',
    7017: '[tv_wonder_construction|E]：村社再挤出一口余力',
    7018: '[tv_wonder_construction|E]：拆开街区安抚了议论',
    7019: '[tv_wonder_construction|E]：工地吸走了本地买卖',
    7020: '[tv_wonder_construction|E]：首都工程为奇观让路',
    7021: '[tv_wonder_construction|E]：王城商路转向工地',
    7022: '[tv_wonder_construction|E]：劳工多熬了一个月',
    7023: '[tv_wonder_construction|E]：追加拨款扩出基址',
    7024: '[tv_wonder_construction|E]：王命压出了更大的蓝图',
    7025: '[tv_wonder_construction|E]：地方退让，工地得以扩展',
    7026: '[tv_wonder_construction|E]：宫廷声望托住了扩建',
    7027: '[tv_wonder_construction|E]：贵族默许更大的规模',
    7028: '[tv_wonder_construction|E]：教士为扩建让出余地',
    7029: '[tv_wonder_construction|E]：商路让出更多空间',
    7030: '[tv_wonder_construction|E]：村社再出力，工地得以扩展',
    7031: '[tv_wonder_construction|E]：拆开的街区腾出尺度',
    7032: '[tv_wonder_construction|E]：本地买卖供出了扩建空间',
    7033: '[tv_wonder_construction|E]：首都修缮让位给扩建',
    7034: '[tv_wonder_construction|E]：王城商气托起更大规模',
    7035: '[tv_wonder_construction|E]：劳工把尺度硬撑了出来',
    7036: '[tv_wonder_construction|E]：追加拨款整顿工序',
    7037: '[tv_wonder_construction|E]：王命压住了工地杂音',
    7038: '[tv_wonder_construction|E]：地方让路，排班得以重整',
    7039: '[tv_wonder_construction|E]：宫廷声望替工地立规矩',
    7040: '[tv_wonder_construction|E]：贵族默许新的调度',
    7041: '[tv_wonder_construction|E]：教士让步，工地重排工序',
    7042: '[tv_wonder_construction|E]：商人让出调度空间',
    7043: '[tv_wonder_construction|E]：村社出力，工地重新归整',
    7044: '[tv_wonder_construction|E]：拆开街区重排工队',
    7045: '[tv_wonder_construction|E]：本地生计为工序让位',
    7046: '[tv_wonder_construction|E]：首都为工地腾出调度余地',
    7047: '[tv_wonder_construction|E]：王城商路服从新安排',
    7048: '[tv_wonder_construction|E]：劳工硬撑住新排班',
    7049: '[tv_wonder_construction|E]：追加拨款打通运路',
    7050: '[tv_wonder_construction|E]：王命催开补给线',
    7051: '[tv_wonder_construction|E]：地方让路，车队得以前行',
    7052: '[tv_wonder_construction|E]：宫廷声望替车队清障',
    7053: '[tv_wonder_construction|E]：贵族车马投入工地',
    7054: '[tv_wonder_construction|E]：教士为运输再让一步',
    7055: '[tv_wonder_construction|E]：商路改向工地',
    7056: '[tv_wonder_construction|E]：村社车驾被拉上前线',
    7057: '[tv_wonder_construction|E]：拆开工址腾出车道',
    7058: '[tv_wonder_construction|E]：本地买卖先给车队让路',
    7059: '[tv_wonder_construction|E]：首都让出运力',
    7060: '[tv_wonder_construction|E]：王城仓储转向工地',
    7061: '[tv_wonder_construction|E]：劳工硬抢出一条运路',
    7062: '[tv_wonder_construction|E]：追加拨款推动赶工',
    7063: '[tv_wonder_construction|E]：王命压出一轮赶工',
    7064: '[tv_wonder_construction|E]：地方退让，主工段加速',
    7065: '[tv_wonder_construction|E]：宫廷声望压成一轮赶工',
    7066: '[tv_wonder_construction|E]：贵族人力补上主工段',
    7067: '[tv_wonder_construction|E]：教士让出一个工期',
    7068: '[tv_wonder_construction|E]：商街把余力送上工地',
    7069: '[tv_wonder_construction|E]：村社把最后一把力交给工地',
    7070: '[tv_wonder_construction|E]：拆开工址抢回进度',
    7071: '[tv_wonder_construction|E]：本地买卖替工地挪出工时',
    7072: '[tv_wonder_construction|E]：首都余裕压进主工段',
    7073: '[tv_wonder_construction|E]：王城商气化成石料与工时',
    7074: '[tv_wonder_construction|E]：劳工把进度硬推过线',
    7075: '[tv_wonder_construction|E]：工地外的议论又起了',
    7076: '[tv_wonder_construction|E]：场地开始装不下图纸',
    7077: '[tv_wonder_construction|E]：排班命令一改再改',
    7078: '[tv_wonder_construction|E]：补给线被迫改道',
    7079: '[tv_wonder_construction|E]：新工法还站不住脚',
    7080: '[tv_wonder_construction|E]：民心要稳，国库就得出血',
    7081: '[tv_wonder_construction|E]：民心要稳，王命就得受折',
    7082: '[tv_wonder_construction|E]：民心要稳，地方就得受扰',
    7083: '[tv_wonder_construction|E]：民心要稳，声望就得拿去消耗',
    7084: '[tv_wonder_construction|E]：民心要稳，贵族就得忍着',
    7085: '[tv_wonder_construction|E]：民心要稳，教士就得让步',
    7086: '[tv_wonder_construction|E]：民心要稳，商街就得吃亏',
    7087: '[tv_wonder_construction|E]：民心要稳，村社就得多扛',
    7088: '[tv_wonder_construction|E]：民心要稳，工址就得拆出余地',
    7089: '[tv_wonder_construction|E]：民心要稳，工址买卖就得让路',
    7090: '[tv_wonder_construction|E]：民心要稳，首都工程就得退后',
    7091: '[tv_wonder_construction|E]：民心要稳，王城买卖就得降温',
    7092: '[tv_wonder_construction|E]：民心要稳，劳工就得硬撑',
    7093: '[tv_wonder_construction|E]：要保住规模，就得继续掏钱',
    7094: '[tv_wonder_construction|E]：要保住规模，就得再压一次王命',
    7095: '[tv_wonder_construction|E]：要保住规模，就得惊动地方',
    7096: '[tv_wonder_construction|E]：要保住规模，就得烧掉声望',
    7097: '[tv_wonder_construction|E]：要保住规模，就得再借贵族的人情',
    7098: '[tv_wonder_construction|E]：要保住规模，就得再向教士求让步',
    7099: '[tv_wonder_construction|E]：要保住规模，就得先让商路受损',
    7100: '[tv_wonder_construction|E]：要保住规模，就得再压村社一程',
    7101: '[tv_wonder_construction|E]：要保住规模，就得继续拆工址',
    7102: '[tv_wonder_construction|E]：要保住规模，就得拿工址繁荣去垫',
    7103: '[tv_wonder_construction|E]：要保住规模，就得抽走首都工程',
    7104: '[tv_wonder_construction|E]：要保住规模，就得拿王城买卖去换',
    7105: '[tv_wonder_construction|E]：要保住规模，就得逼劳工多撑一步',
    7106: '[tv_wonder_construction|E]：要稳住排班，就得再填一笔钱',
    7107: '[tv_wonder_construction|E]：要稳住排班，就得再压一次王命',
    7108: '[tv_wonder_construction|E]：要稳住排班，就得多动地方秩序',
    7109: '[tv_wonder_construction|E]：要稳住排班，就得继续耗声望',
    7110: '[tv_wonder_construction|E]：要稳住排班，就得让贵族继续忍着',
    7111: '[tv_wonder_construction|E]：要稳住排班，就得再向祭坛借时间',
    7112: '[tv_wonder_construction|E]：要稳住排班，就得让商街再吃一次亏',
    7113: '[tv_wonder_construction|E]：要稳住排班，就得再压村社人力',
    7114: '[tv_wonder_construction|E]：要稳住排班，就得继续拆工址',
    7115: '[tv_wonder_construction|E]：要稳住排班，就得拿工址买卖去垫',
    7116: '[tv_wonder_construction|E]：要稳住排班，就得抽走首都工力',
    7117: '[tv_wonder_construction|E]：要稳住排班，就得让王城生意降温',
    7118: '[tv_wonder_construction|E]：要稳住排班，就得逼劳工再撑一轮',
    7119: '[tv_wonder_construction|E]：要救车队，就得再花一笔钱',
    7120: '[tv_wonder_construction|E]：要救车队，就得再借一次王命',
    7121: '[tv_wonder_construction|E]：要救车队，就得惊动更多地方',
    7122: '[tv_wonder_construction|E]：要救车队，就得继续透支体面',
    7123: '[tv_wonder_construction|E]：要救车队，就得再借贵族车马',
    7124: '[tv_wonder_construction|E]：要救车队，就得让祭坛再忍一次',
    7125: '[tv_wonder_construction|E]：要救车队，就得先堵住商路',
    7126: '[tv_wonder_construction|E]：要救车队，就得再抽村社的车驾',
    7127: '[tv_wonder_construction|E]：要救车队，就得继续拆开工址',
    7128: '[tv_wonder_construction|E]：要救车队，就得拿工址繁荣去换',
    7129: '[tv_wonder_construction|E]：要救车队，就得抽走首都运力',
    7130: '[tv_wonder_construction|E]：要救车队，就得让王城市场让路',
    7131: '[tv_wonder_construction|E]：要救车队，就得逼人力再撑一次',
    7132: '[tv_wonder_construction|E]：要抢回进度，就得继续掏钱',
    7133: '[tv_wonder_construction|E]：要抢回进度，就得再压一次王命',
    7134: '[tv_wonder_construction|E]：要抢回进度，就得惊动地方',
    7135: '[tv_wonder_construction|E]：要抢回进度，就得拿声望去垫',
    7136: '[tv_wonder_construction|E]：要抢回进度，就得再向贵族借力',
    7137: '[tv_wonder_construction|E]：要抢回进度，就得让祭坛再让一步',
    7138: '[tv_wonder_construction|E]：要抢回进度，就得先挤占商路',
    7139: '[tv_wonder_construction|E]：要抢回进度，就得再抽村社一把',
    7140: '[tv_wonder_construction|E]：要抢回进度，就得继续拆工址',
    7141: '[tv_wonder_construction|E]：要抢回进度，就得拿工址生计去填',
    7142: '[tv_wonder_construction|E]：要抢回进度，就得让首都工程后退',
    7143: '[tv_wonder_construction|E]：要抢回进度，就得让王城生意让路',
    7144: '[tv_wonder_construction|E]：要抢回进度，就得逼劳工再咬牙',
    7145: '[tv_wonder_construction|E]：奇观又在国库上挖了个口子',
    7146: '[tv_wonder_construction|E]：王命被工地磨薄了',
    7147: '[tv_wonder_construction|E]：施工惊动了地方安宁',
    7148: '[tv_wonder_construction|E]：宫廷的体面又薄了一层',
    7149: '[tv_wonder_construction|E]：贵族席间开始说冷话',
    7150: '[tv_wonder_construction|E]：祭坛前有人皱起了眉头',
    7151: '[tv_wonder_construction|E]：商街的账本又薄了一页',
    7152: '[tv_wonder_construction|E]：村社肩上又压了一担',
    7153: '[tv_wonder_construction|E]：工址街区又被拆开一块',
    7154: '[tv_wonder_construction|E]：工址周围的买卖冷了下去',
    7155: '[tv_wonder_construction|E]：首都修缮又给奇观让了路',
    7156: '[tv_wonder_construction|E]：王城街市也被拖冷了',
    7157: '[tv_wonder_construction|E]：伤员名册上又添了人',
    7158: '[tv_wonder_construction|E]：国库先替奇观吞下了代价',
    7159: '[tv_wonder_construction|E]：王权的体面被工地扯开了',
    7160: '[tv_wonder_construction|E]：征发把地方搅得更乱了',
    7161: '[tv_wonder_construction|E]：工地让宫廷声望当众受损',
    7162: '[tv_wonder_construction|E]：贵族的耐心被工地磨没了',
    7163: '[tv_wonder_construction|E]：教士的耐心也快用尽了',
    7164: '[tv_wonder_construction|E]：市民的怒气已经摆上街面',
    7165: '[tv_wonder_construction|E]：乡间的怨气已经压不住了',
    7166: '[tv_wonder_construction|E]：工址先为奇观倒退了一步',
    7167: '[tv_wonder_construction|E]：工址的繁荣先被压暗了',
    7168: '[tv_wonder_construction|E]：首都先替奇观付了账',
    7169: '[tv_wonder_construction|E]：王城买卖也被奇观拖慢了',
    7170: '[tv_wonder_construction|E]：工地把劳工逼出了伤亡',
    7171: '[tv_wonder_construction|E]：[tv_great_engineer|E]当众说服了围观者',
    7172: '[tv_wonder_construction|E]：[tv_great_engineer|E]重画了主轴线',
    7173: '[tv_wonder_construction|E]：[tv_great_engineer|E]把工序全都重排了',
    7174: '[tv_wonder_construction|E]：[tv_great_engineer|E]重新打通了运路',
    7175: '[tv_wonder_construction|E]：[tv_great_engineer|E]亲手推过了主工段',
    7176: '[tv_wonder_construction|E]：[tv_great_engineer|E]把议论压了下去',
    7177: '[tv_wonder_construction|E]：[tv_great_engineer|E]校准了场地尺度',
    7178: '[tv_wonder_construction|E]：[tv_great_engineer|E]理顺了工棚名册',
    7179: '[tv_wonder_construction|E]：[tv_great_engineer|E]疏通了补给车队',
    7180: '[tv_wonder_construction|E]：[tv_great_engineer|E]补上了关键部件',
    7181: '[tv_wonder_construction|E]：[tv_great_engineer|E]决定拿工地去赌人心',
    7182: '[tv_wonder_construction|E]：[tv_great_engineer|E]执意放大了蓝图',
    7183: '[tv_wonder_construction|E]：[tv_great_engineer|E]当场改了排班',
    7184: '[tv_wonder_construction|E]：[tv_great_engineer|E]让车队改走险路',
    7185: '[tv_wonder_construction|E]：[tv_great_engineer|E]强行试了新工法',
    7186: '[tv_wonder_construction|E]：[tv_great_engineer|E]把修补费用算漏了',
    7187: '[tv_wonder_construction|E]：[tv_great_engineer|E]把王命用得太随手了',
    7188: '[tv_wonder_construction|E]：[tv_great_engineer|E]低估了施工扰动',
    7189: '[tv_wonder_construction|E]：[tv_great_engineer|E]把话说得太满了',
    7190: '[tv_wonder_construction|E]：[tv_great_engineer|E]把贵族耐性当成了存货',
    7191: '[tv_wonder_construction|E]：[tv_great_engineer|E]把祭坛也卷进了工期',
    7192: '[tv_wonder_construction|E]：[tv_great_engineer|E]拿商路给工地让了道',
    7193: '[tv_wonder_construction|E]：[tv_great_engineer|E]把村社余力看多了',
    7194: '[tv_wonder_construction|E]：[tv_great_engineer|E]把工址拆过了头',
    7195: '[tv_wonder_construction|E]：[tv_great_engineer|E]挤掉了工址生计',
    7196: '[tv_wonder_construction|E]：[tv_great_engineer|E]误动了首都余裕',
    7197: '[tv_wonder_construction|E]：[tv_great_engineer|E]拖慢了王城买卖',
    7198: '[tv_wonder_construction|E]：[tv_great_engineer|E]看错了劳工的极限',
    7199: '[tv_wonder_construction|E]：[tv_great_engineer|E]把账册彻底拖垮了',
    7200: '[tv_wonder_construction|E]：[tv_great_engineer|E]把王命也拖下了水',
    7201: '[tv_wonder_construction|E]：[tv_great_engineer|E]把地方搅成了一团',
    7202: '[tv_wonder_construction|E]：[tv_great_engineer|E]把宫廷体面也赔进去了',
    7203: '[tv_wonder_construction|E]：[tv_great_engineer|E]把贵族彻底惹恼了',
    7204: '[tv_wonder_construction|E]：[tv_great_engineer|E]把教士也得罪透了',
    7205: '[tv_wonder_construction|E]：[tv_great_engineer|E]把市民逼出了火气',
    7206: '[tv_wonder_construction|E]：[tv_great_engineer|E]把村社压到了极限',
    7207: '[tv_wonder_construction|E]：[tv_great_engineer|E]先把工址折腾坏了',
    7208: '[tv_wonder_construction|E]：[tv_great_engineer|E]把工址买卖压熄了',
    7209: '[tv_wonder_construction|E]：[tv_great_engineer|E]掏空了首都安排',
    7210: '[tv_wonder_construction|E]：[tv_great_engineer|E]把王城生意也压冷了',
    7211: '[tv_wonder_construction|E]：[tv_great_engineer|E]把失误变成了伤亡',
}

DESC_EN = {
    7000: 'A few visible successes at the fence turn curiosity into pride. Guild elders lend names, neighbors stop treating the works as a royal vanity, and the project gains a sharper claim on [tv_wonder_domestic_support|E].',
    7001: 'New measurements reveal ground that can bear a broader footprint. What had looked like ambition on parchment now has a tolerable foundation, and [tv_wonder_scale_competence|E] jumps forward.',
    7002: 'The yard wakes under new rosters. Crews know where to stand, clerks know which tally matters, and [tv_wonder_organization_competence|E] rises because confusion has fewer places to hide.',
    7003: 'A better route links road, water, storeyard, and scaffold. The first convoy to use it arrives almost embarrassingly on time, and [tv_wonder_logistics_competence|E] surges.',
    7004: 'The active part rises past its mark before the light fails. No single miracle explains it; the lifts, joints, and hands simply meet at the right hour, pushing [tv_wonder_construction|E] progress ahead.',
    7005: 'The noise around the site softens. It is not acclaim, but it is permission enough for carts to pass and arguments to end sooner; [tv_wonder_domestic_support|E] rises by a useful margin.',
    7006: 'A cramped angle is redrawn, a service path widened, and the main line of the monument breathes again. The improvement to [tv_wonder_scale_competence|E] is small but real.',
    7007: 'A set of missing handovers is repaired. The work is too dry for ceremony, but it keeps tools moving and improves [tv_wonder_organization_competence|E].',
    7008: 'One bad turn in the supply line is corrected. Fewer carts wait empty, fewer loads arrive cracked, and [tv_wonder_logistics_competence|E] improves.',
    7009: 'A stubborn joint finally fits, and the next crew can begin without another month of waiting. [tv_wonder_construction|E] progress moves forward in the most satisfying way: visibly.',
    7075: 'A public demonstration at the site draws a crowd that may become loyal spectators or offended critics. The scaffolds wait while rumor decides whether [tv_wonder_domestic_support|E] has been helped or harmed.',
    7076: 'A bold adjustment pulls the plan beyond its old limits. It may become the decision that made the monument grand, or the note future clerks underline in red.',
    7077: 'A new chain of command is imposed under the awnings. It may discipline the yard or merely teach every foreman a new way to argue.',
    7078: 'A risky route promises to shorten the supply line. If the weather holds it will be praised as foresight; if it fails, everyone will remember who ordered the turn.',
    7079: 'A faster method is tried on the active part. It may save the month or force the next crew to repair a beautiful mistake.',
    7145: 'The wonder draws coin faster than the ledgers expected. The treasury can explain the shortage, but explanation does not mint silver.',
    7146: 'Royal endorsement is stretched over too many compromises. The seal still holds, but it looks thinner.',
    7147: 'The construction rhythm presses against ordinary life. Markets open late, villages grumble, and order gives a little ground.',
    7148: 'The court lends color to the works and receives dust in return. Prestige fades in small public jokes and half-finished boasts.',
    7149: 'Noble households give way once more. The concession is formal and cold, which is often worse than refusal.',
    7150: 'The sacred calendar bends again for the worksite. The clergy obey, but the obedience has edges.',
    7151: 'Market business is bent around the project. The burghers can profit from grandeur, but not when every road to it is blocked.',
    7152: 'Rural shoulders take another load. The project advances, and village patience becomes a thinner thing.',
    7153: 'The site gives up more of its ordinary fabric. A future wonder gains space, while present streets lose use.',
    7154: 'The site grows commercially quieter as ordinary exchange is pulled toward the monument. Prosperity can be redirected only so many times before it thins.',
    7155: 'Capital projects make way for the wonder again. The royal city remains grand, but some of its frame is being borrowed.',
    7156: 'The capital\'s markets lose a little brightness as the project draws in credit and goods. The court may call it patriotic; merchants call it slower trade.',
    7157: 'Names are added to the injury rolls. The work continues, but each new mark changes how the laborers look at the stone.',
    7158: 'A hard demand from the site leaves the treasury visibly hollow. The monument continues, and the realm pays before it can admire anything.',
    7159: 'The worksite\'s demands force the crown into an undignified posture. The promise of grandeur now leans on damaged authority.',
    7160: 'A harsher disruption spills past the fence. Officials can name the cause, but they cannot make the country feel settled by naming it.',
    7161: 'A public embarrassment at the site travels faster than any official correction. Honor pays for stone that is not yet standing.',
    7162: 'The project cuts into noble patience until courtesy can no longer cover the sound. A monument is a poor guest when it eats inheritance.',
    7163: 'A construction demand tramples too near the altar. The clergy do not forget when piety is treated as open space.',
    7164: 'Anger reaches the shopfronts as the worksite swallows space, time, and credit. The city hears the monument before it sees it.',
    7165: 'Rural anger will not stay quiet after this levy. The wonder\'s shadow reaches farms that may never see its finished face.',
    7166: 'The works hollow the site hard enough to set it back. The monument has not yet risen, but the place around it has already paid.',
    7167: 'The worksite smothers the local market for a time. Carts still arrive, but fewer of them are serving the town around the stone.',
    7168: 'The capital pays in stone, labor, and delayed repairs. A distant monument becomes more real while nearby plans grow hollow.',
    7169: 'The royal city\'s trade is pressed low by the works. Grandeur far away dulls the streets that must finance it.',
    7170: 'Sweat crosses into blood at the site. The monument is not cancelled, which may be the cruelest part of the lesson.',
    7171: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] turns a technical tour into a public triumph. The result is a major improvement in [tv_wonder_domestic_support|E].\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 80.#!',
    7172: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] redraws the main axis with a confidence that makes the larger plan credible. The result is a major improvement in [tv_wonder_scale_competence|E].\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 80.#!',
    7173: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] rebuilds the schedule so cleanly that even rival foremen obey it. The result is a major improvement in [tv_wonder_organization_competence|E].\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 80.#!',
    7174: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] opens a supply route that makes the old delays look almost foolish. The result is a major improvement in [tv_wonder_logistics_competence|E].\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 80.#!',
    7175: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] drives the main works through a problem that had stalled lesser hands. The result is a major improvement in [tv_wonder_construction|E] progress.\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 80.#!',
    7176: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] answers rumors with enough plain explanation to steady public confidence. The project gains a steadier improvement in [tv_wonder_domestic_support|E].\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 50.#!',
    7177: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] finds enough margin in the site to spare the project from a timid design. The project gains a steadier improvement in [tv_wonder_scale_competence|E].\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 50.#!',
    7178: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] straightens a stubborn mess of crews, tools, and watches. The project gains a steadier improvement in [tv_wonder_organization_competence|E].\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 50.#!',
    7179: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] clears the worst knot in the convoy schedule. The project gains a steadier improvement in [tv_wonder_logistics_competence|E].\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 50.#!',
    7180: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] fits the critical piece and lets the next stage begin sooner. The project gains a steadier improvement in [tv_wonder_construction|E] progress.\\n\\n#G This event occurred because the current [tv_great_engineer|E] has effective military ability above 50.#!',
    7181: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] places the unfinished works before the crowd and trusts the spectacle. The decision may lift [tv_wonder_domestic_support|E] or cost the site dearly.\\n\\n#Y This event occurred because the current [tv_great_engineer|E] has effective military ability between 20 and 80.#!',
    7182: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] orders the plan enlarged before all doubts have been paid for. The decision may lift [tv_wonder_scale_competence|E] or cost the site dearly.\\n\\n#Y This event occurred because the current [tv_great_engineer|E] has effective military ability between 20 and 80.#!',
    7183: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] rewrites the shifts in a single afternoon and dares the yard to keep up. The decision may lift [tv_wonder_organization_competence|E] or cost the site dearly.\\n\\n#Y This event occurred because the current [tv_great_engineer|E] has effective military ability between 20 and 80.#!',
    7184: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] sends the carts by a difficult road and trusts calculation over habit. The decision may lift [tv_wonder_logistics_competence|E] or cost the site dearly.\\n\\n#Y This event occurred because the current [tv_great_engineer|E] has effective military ability between 20 and 80.#!',
    7185: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] tests a quicker method where failure would be very public. The decision may lift [tv_wonder_construction|E] progress or cost the site dearly.\\n\\n#Y This event occurred because the current [tv_great_engineer|E] has effective military ability between 20 and 80.#!',
    7186: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] misjudges the cost of a fix and leaves the treasury to cover the elegance. The works continue, but [gold|E] suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7187: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] forgets that royal authority is a material too, and spends it carelessly. The works continue, but [legitimacy|E] suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7188: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] underestimates how much disturbance a neat engineering answer can cause. The works continue, but [stability|E] suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7189: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] speaks too confidently before the work can support the boast. The works continue, but [prestige|E] suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7190: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] treats noble patience as if it were another supply stockpile. The works continue, but [estate_satisfaction|E] among the nobles suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7191: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] moves through the religious calendar as if it were a delivery table. The works continue, but [estate_satisfaction|E] among the clergy suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7192: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] blocks ordinary trade while chasing a cleaner line for the site. The works continue, but [estate_satisfaction|E] among the burghers suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7193: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] mistakes exhausted villages for an unused reserve. The works continue, but [estate_satisfaction|E] among the peasants suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7194: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] cuts through the wrong local arrangements and calls the gap useful. The works continue, but [development|E] at the site suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7195: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] crowds out local livelihoods while clearing space for the works. The works continue, but [prosperity|E] at the site suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7196: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] misuses capital resources as though the royal city had no plans of its own. The works continue, but [development|E] in the capital suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7197: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] disturbs the royal city\'s trade while solving a local engineering problem. The works continue, but [prosperity|E] in the capital suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7198: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] misjudges the limit of laboring bodies. The works continue, but laboring [population|E] at the site suffers for the oversight.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 50.#!',
    7199: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] lets an avoidable mistake break through the accounts and empty more coin than pride can excuse. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7200: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] turns a preventable site failure into a visible wound to the crown. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7201: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] pushes the country into disorder while trying to solve a site problem. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7202: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] makes the site a spectacle and drags courtly honor into it. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7203: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] angers the houses by solving a site problem through their privileges. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7204: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] offends the clergy by making sacred patience pay for secular stone. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7205: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] provokes the burghers by treating commerce as loose scaffolding. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7206: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] breaks village patience with a demand that should have been avoided. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7207: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] injures the site by solving a technical problem with local destruction. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7208: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] snuffs out the site\'s markets through a preventable decision. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7209: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] hollows the capital\'s plans to cover a mistake at the site. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7210: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] dims capital prosperity through a failure that should never have reached the market. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
    7211: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName] causes casualties by letting a preventable failure pass through the crews. The error is not enough to end the wonder, which may be the ugliest part of it.\\n\\n#R This event occurred because the current [tv_great_engineer|E] has effective military ability below 20.#!',
}

DESC_ZH = {
    7000: '围栏外的议论好转了不少。行会愿意具名支持，乡绅也不再多问，路人开始把这项工程说成一件体面事。[tv_wonder_domestic_support|E]因此大幅提高。',
    7001: '新的测量结果显示，地基能承受更大的建筑规模。图纸上原本偏大的方案，现在有了着落，[tv_wonder_scale_competence|E]因此大幅提高。',
    7002: '新的名册贴到了工棚里，各工种该在哪里、什么时候上工都写清楚了。混乱的地方少了，[tv_wonder_organization_competence|E]因此大幅提高。',
    7003: '一条更顺的路线把道路、水路、堆场和脚手架连了起来。第一支车队准时到达，[tv_wonder_logistics_competence|E]因此大幅提高。',
    7004: '当前部件在天黑前就越过了预定标线。起吊、拼接和人手都配合得很好，[tv_wonder_construction|E]进度因此大幅推进。',
    7005: '工地外的闲话少了一些，石料车经过时也不再有人拦路。算不上什么大事，但[tv_wonder_domestic_support|E]确实往前挪动了一些。',
    7006: '一处狭窄的转角被重新改过，主轴线也宽了一些。改动不大，但[tv_wonder_scale_competence|E]确实提高了一点。',
    7007: '几处一直被漏掉的交接工作补上了，工具、夜班和守卫的安排也都说清楚了。[tv_wonder_organization_competence|E]因此有所改善。',
    7008: '补给线上一处不好走的转弯改直了。空跑的车少了，摔坏的货也少了，[tv_wonder_logistics_competence|E]因此有所改善。',
    7009: '一处拖了很久的接口终于装上了，下一批工匠不用再多等一个月。[tv_wonder_construction|E]进度因此稳步推进。',
    7075: '工地打算在公众面前做一次展示。这可能拉近工地和民众的距离，也可能招来批评，[tv_wonder_domestic_support|E]会因此提高还是下降，现在还说不准。',
    7076: '有人提出把设计规模再扩大一些。这个决定要么让工程变得更宏伟，要么日后被证明是个失误。',
    7077: '工地打算换一套新的指挥办法。这可能让工地更有秩序，也可能只是换了个吵架的由头。',
    7078: '有一条路能缩短运输时间，但不太好走。天气配合的话是件好事，天气不配合，下令的人就要担这个责任。',
    7079: '当前部件打算试用一种更快的工法。顺利的话能赶上进度，不顺利就要多花一个月返工。',
    7145: '奇观建设花钱的速度比预计的要快。国库能说清楚钱花在哪儿，但说明并不能把亏空补上。',
    7146: '王室的名义被工地反复借用，用来说服反对的人。印玺还作数，只是分量轻了一些。',
    7147: '施工的节奏打乱了平常的生活。市场开门晚了，村镇里有些抱怨，秩序稍微松动了一些。',
    7148: '宫廷为工程说了不少好话，换来的却是几句闲话。这些没兑现的场面话，多少磨损了一点声望。',
    7149: '贵族家族又一次为工程让步。这次的让步很客气，也很冷淡，反而比直接拒绝更让人不舒服。',
    7150: '宗教活动的日程又一次为工地调整。教士照做了，但看得出来并不情愿。',
    7151: '市场上的生意为了绕开工地，多走了不少弯路。商人能从工程里得到好处，但路都被堵住时就谈不上了。',
    7152: '乡下又添了一份差事。工程是往前走了，但村社这边的耐心也在变薄。',
    7153: '工址又拆掉了一部分原有的街巷。将来的奇观多了一块地方，眼前的街区却少了一块。',
    7154: '工地把周边的生意拉了过去，当地的市场因此冷清了一些。这样的调用不能一直做下去。',
    7155: '首都的一些工程项目再次为奇观让路。王城依然气派，只是有些原本该修的地方被搁下了。',
    7156: '工程从首都抽走了信用和物资，市场因此少了一些活力。宫廷说这是为国出力，商人只当是生意变差了。',
    7157: '伤亡名册上又添了名字。工程照常进行，但劳工们看这堆石头的眼神变了。',
    7158: '工地这次开口要的数目不小，国库明显被掏空了一块。奇观还没建成，钱已经先花出去了。',
    7159: '工地这次的要求逼得王室不得不让步。原本用来撑场面的权威，如今被压低了一些。',
    7160: '这次的扰动传得比往常远，越过了围栏。官员能解释清楚原因，但解释并不能让地方安定下来。',
    7161: '工地上的一次失礼，传得比官方的澄清还快。工程还没立起来，宫廷的脸面已经先受了损。',
    7162: '工程这次动用了不少贵族的产业，客气话已经遮不住不满的声音了。',
    7163: '这次的施工需求，占用了太靠近祭坛的时间和地方。教士不会轻易忘记这件事。',
    7164: '愤怒的情绪已经传到了店铺门口。工地占用了空间、时间和信用，市民先感受到麻烦，后来才看到工程本身。',
    7165: '这次的征调让乡下人不再沉默。工程带来的影响，落到了一些可能永远看不到成果的人身上。',
    7166: '工地这次挖空了不少地方，让工址明显退步了一截。奇观还没建起来，周边地方已经先付出了代价。',
    7167: '本地的市场被工地压得冷清了一阵子。车队还在来往，只是很少再为周边的城镇服务。',
    7168: '首都这次拿出了石料、人力，还有一些本该完成的修缮。远方的奇观变得更真实了，首都自己的计划却空了下来。',
    7169: '首都的贸易被工程压低了不少。远方的奇观越来越有分量，供养它的首都街道却暗淡了下来。',
    7170: '工地上出了人命。工程没有因此停下，这大概是最让人难受的一点。',
    7171: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把一次普通的巡视办成了一场公开的胜利，[tv_wonder_domestic_support|E]因此大幅提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于80。#!',
    7172: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]重新画了主轴线，让更大的方案一下子变得可行，[tv_wonder_scale_competence|E]因此大幅提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于80。#!',
    7173: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把排班重新安排了一遍，连最挑剔的工头都没话可说，[tv_wonder_organization_competence|E]因此大幅提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于80。#!',
    7174: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]打通了一条补给线，让过去的拖延显得没有必要，[tv_wonder_logistics_competence|E]因此大幅提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于80。#!',
    7175: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]亲自带着主体工程越过了一处一直卡住的难题，[tv_wonder_construction|E]进度因此大幅提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于80。#!',
    7176: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]用清楚的解释压下了流言，[tv_wonder_domestic_support|E]因此稳步提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于50。#!',
    7177: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]在场地里找出了多余的空间，[tv_wonder_scale_competence|E]因此稳步提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于50。#!',
    7178: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]理顺了工队、工具和夜班之间的混乱，[tv_wonder_organization_competence|E]因此稳步提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于50。#!',
    7179: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]解开了车队日程上最难缠的一个结，[tv_wonder_logistics_competence|E]因此稳步提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于50。#!',
    7180: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把一个关键部件装上了，[tv_wonder_construction|E]进度因此稳步提高。\\n\\n#G 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力高于50。#!',
    7181: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把还没完工的部分提前展示给了公众。这个决定可能提高[tv_wonder_domestic_support|E]，也可能让工地付出代价。\\n\\n#Y 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力处于20到80之间。#!',
    7182: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]在疑虑还没消除之前，就下令扩大了图纸。这个决定可能提高[tv_wonder_scale_competence|E]，也可能让工地付出代价。\\n\\n#Y 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力处于20到80之间。#!',
    7183: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]在一个下午之内改写了班次安排。这个决定可能提高[tv_wonder_organization_competence|E]，也可能让工地付出代价。\\n\\n#Y 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力处于20到80之间。#!',
    7184: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]让车队改走一条更难走的路。这个决定可能提高[tv_wonder_logistics_competence|E]，也可能让工地付出代价。\\n\\n#Y 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力处于20到80之间。#!',
    7185: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]在最显眼的部件上试用了一种更快的工法。这个决定可能提高[tv_wonder_construction|E]进度，也可能让工地付出代价。\\n\\n#Y 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力处于20到80之间。#!',
    7186: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]低估了一项维修的花费。工程还能继续，但[gold|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7187: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把王室的名义用得太随意了。工程还能继续，但[legitimacy|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7188: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]低估了一项工程方案会引起多大的动静。工程还能继续，但[stability|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7189: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]在工程还没做出成绩之前，就把话说满了。工程还能继续，但[prestige|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7190: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把贵族的耐心当成了可以随时支取的储备。工程还能继续，但贵族[estate_satisfaction|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7191: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把宗教日程当成了普通的运输安排来对待。工程还能继续，但教士[estate_satisfaction|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7192: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]为了让工程线路更顺畅，挡住了平常的买卖。工程还能继续，但市民[estate_satisfaction|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7193: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把已经疲惫的村社当成了还没动用的人手。工程还能继续，但平民[estate_satisfaction|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7194: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]拆错了当地的一处安排，还把这个缺口当成可用的空间。工程还能继续，但工址[development|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7195: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]为了腾出场地，挤走了当地的一些生计。工程还能继续，但工址[prosperity|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7196: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]挪用了首都的一些资源，像是忘了首都本身也有安排。工程还能继续，但首都[development|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7197: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]为了解决本地的工程问题，扰乱了首都的生意。工程还能继续，但首都[prosperity|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7198: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]看错了劳工体力的极限。工程还能继续，但工址劳工[population|E]要为这次疏忽受损。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于50。#!',
    7199: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]让一个本可以避免的失误捅穿了账目，花掉了一大笔说不清楚的钱。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7200: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把一次本可以避免的现场失误，变成了王室脸上一道看得见的伤痕。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7201: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]为了解决工地上的问题，把地方推入了不必要的动荡。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7202: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把工地闹成了一场公开的笑话，连带丢了宫廷的脸面。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7203: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]动用了贵族的特权来填补工地上的失误，惹恼了各大家族。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7204: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]让宗教上的耐心为世俗的石料买了单，冒犯了教士。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7205: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]把市面上的生意当成了可以随意挪用的东西，惹恼了市民。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7206: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]提出了一个本可以避免的要求，耗尽了村社的耐心。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7207: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]为了解决技术问题，损毁了当地的一些设施。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7208: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]一次本可以避免的决定，让工址周边的市场彻底冷清了下来。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7209: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]为了掩盖工地上的失误，掏空了首都原本的规划。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7210: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]让一次本不该传到市面上的失败，压暗了首都的繁荣。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
    7211: '[SCOPE.sCharacter(\'tv_wonder_event_engineer\').GetShortName]让一次本可以避免的失误穿过了工队，造成了人员伤亡。这个错误还不至于让奇观停工，这大概才是最让人难堪的地方。\\n\\n#R 该事件出现是因为当前[tv_great_engineer|E]的等效军事能力低于20。#!',
}

# id -> {slot: (en_text, zh_text, category)}
OPTION_EN = {
    7000: {'a': 'Lets the guild elders\' new goodwill carry the work forward.'},
    7001: {'a': 'Lays claim to the broader ground the survey just proved.'},
    7002: {'a': 'We lock the new rosters in before confusion finds its way back.'},
    7003: {'a': 'Keep those carts rolling on time!'},
    7004: {'a': 'Lets the lifts press on past the mark.'},
    7005: {'a': 'Lets the carts through and the arguments die down.'},
    7006: {'a': 'Widens the path and lets the design breathe.'},
    7007: {'a': 'We patch the handover and keep the tools moving.'},
    7008: {'a': 'Straightens the bad turn before more loads crack.'},
    7009: {'a': 'At last, it fits!'},
    7075: {'a': 'Lets the demonstration speak for itself.'},
    7076: {'a': 'Pushes the design past its old limits.'},
    7077: {'a': 'We push the new chain of command through the yard.'},
    7078: {'a': 'Take the shorter road!'},
    7079: {'a': 'Tries the faster method on the active section.'},
    7145: {'a': 'Stretches the ledgers to cover the gap.'},
    7146: {'a': 'Lets the royal seal wear a touch thinner.'},
    7147: {'a': 'We let the villages grumble and press on regardless.'},
    7148: {'a': 'Trades a little shine for a few court jokes.'},
    7149: {'a': 'Accepts the nobles\' cold, formal concession.'},
    7150: {'a': 'We accept the clergy\'s obedience, edges and all.'},
    7151: {'a': 'Clear the roads and keep building!'},
    7152: {'a': 'Piles the extra load onto rural shoulders.'},
    7153: {'a': 'Signs away these streets for tomorrow\'s wonder.'},
    7154: {'a': 'We steer the site\'s trade toward the monument once more.'},
    7155: {'a': 'Lends the capital\'s own frame to the wonder.'},
    7156: {'a': 'Every monument borrows its brightness from somewhere.'},
    7157: {'a': 'Note the names, and carry on!'},
    7158: {'a': 'Empties the treasury and lets the stone go up regardless.'},
    7159: {'a': 'We let the crown bend so the walls can rise.'},
    7160: {'a': 'Lets the unrest run its course beyond the fence.'},
    7161: {'a': 'Let them talk!'},
    7162: {'a': 'Lets the nobles grumble while the masonry advances.'},
    7163: {'a': 'We accept the clergy\'s cold silence as the price of stone.'},
    7164: {'a': 'Lets the shopfronts grumble while the scaffolding climbs.'},
    7165: {'a': 'Let the fields bear it!'},
    7166: {'a': 'Sets the site back so the monument can move forward.'},
    7167: {'a': 'Lets the local market thin out while the works carry on.'},
    7168: {'a': 'We let the capital\'s own repairs wait for the distant wonder.'},
    7169: {'a': 'Dulls the royal city\'s streets to fund grandeur elsewhere.'},
    7170: {'a': 'We press on, though the site has paid in blood.'},
    7171: {'a': 'Turns a routine inspection into a public triumph.'},
    7172: {'a': 'Makes the grand axis look inevitable, not reckless.'},
    7173: {'a': 'We fall in line behind the new schedule.'},
    7174: {'a': 'The road is open at last!'},
    7175: {'a': 'Drives the stalled works clean through.'},
    7176: {'a': 'Quiets the rumors with plain talk.'},
    7177: {'a': 'We give the plan room enough to be bold.'},
    7178: {'a': 'Sets the crews, tools, and watches back in order.'},
    7179: {'a': 'Clears the worst knot in the supply line.'},
    7180: {'a': 'Full speed ahead!'},
    7181: {'a': 'Lets the crowd pass judgment on the unfinished stones.'},
    7182: {'a': 'Orders the blueprint enlarged before the doubts are settled.'},
    7183: {'a': 'We rewrite the shifts and dare the yard to keep up.'},
    7184: {'a': 'Sends the carts down the harder road, trusting calculation over habit.'},
    7185: {'a': 'Try the faster method - let it prove itself in public!'},
    7186: {'a': 'Quietly settles the shortfall before the account is questioned.'},
    7187: {'a': 'We rein in the careless use of the crown\'s name.'},
    7188: {'a': 'Smooths over the disturbance the tidy solution left behind.'},
    7189: {'a': 'Walk the boast back!'},
    7190: {'a': 'Reminds the engineer that noble patience is not a stockpile to draw from.'},
    7191: {'a': 'Lets the altars keep their own calendar after all.'},
    7192: {'a': 'We reopen the market lane the site had closed off.'},
    7193: {'a': 'Lets the exhausted villages rest instead of being drawn on again.'},
    7194: {'a': 'Patches over the arrangements that were cut through by mistake.'},
    7195: {'a': 'We make room again for the livelihoods the clearing crowded out.'},
    7196: {'a': 'Returns the misused resources to the capital\'s own plans.'},
    7197: {'a': 'We calm the royal city\'s trade before the disruption spreads.'},
    7198: {'a': 'Ease the strain before more give out!'},
    7199: {'a': 'Chalks up the loss and quietly shuts the ledger.'},
    7200: {'a': 'We wear the crown\'s new scar and carry on.'},
    7201: {'a': 'Leaves the disorder to burn itself out.'},
    7202: {'a': 'Let the court have its spectacle!'},
    7203: {'a': 'Spends the houses\' goodwill to keep the work moving.'},
    7204: {'a': 'We let sacred patience foot the bill for secular stone.'},
    7205: {'a': 'Leaves the merchants to mend their own scaffolding.'},
    7206: {'a': 'We ask the villages\' pardon for a demand we could have spared them.'},
    7207: {'a': 'Patches the wound the repairs themselves caused.'},
    7208: {'a': 'So be it—let the stalls fall silent!'},
    7209: {'a': 'Guts the capital\'s own plans to patch the site\'s mistake.'},
    7210: {'a': 'We watch the capital\'s shine dim over a failure it never should have seen.'},
    7211: {'a': 'Counts the dead the crews should never have lost.'},
}

OPTION_ZH = {
    7000: {'a': '就顺着行会这份支持，把工程继续办下去。'},
    7001: {'a': '照这次测量的结果，把地基铺得更宽一些。'},
    7002: {'a': '把新名册定下来，免得又乱回去。'},
    7003: {'a': '车队就照这个点，继续跑下去！'},
    7004: {'a': '让施工照这个势头，继续往前赶。'},
    7005: {'a': '先把路让开，争论也就慢慢平息了。'},
    7006: {'a': '把这条路拓宽，图纸也就宽松一些。'},
    7007: {'a': '把交接的漏洞补上，工具就不会再停摆。'},
    7008: {'a': '早点把这处转角改掉，免得更多货摔坏。'},
    7009: {'a': '终于装上了！'},
    7075: {'a': '让这次展示的结果说明一切。'},
    7076: {'a': '把设计规模再放大一些。'},
    7077: {'a': '把这套新的指挥办法推行下去。'},
    7078: {'a': '走这条近路！'},
    7079: {'a': '在当前部件上试用这套新工法。'},
    7145: {'a': '先把账上的窟窿填上。'},
    7146: {'a': '再借用一次王室的名义。'},
    7147: {'a': '不理会村镇的抱怨，工程照旧推进。'},
    7148: {'a': '拿一点体面，换几句宫廷里的闲话。'},
    7149: {'a': '接受贵族这次冷淡的让步。'},
    7150: {'a': '接受教士这次不太情愿的服从。'},
    7151: {'a': '清开道路，工程照旧！'},
    7152: {'a': '让乡下再多担一份差事。'},
    7153: {'a': '拆掉这片街巷，换将来的奇观。'},
    7154: {'a': '再一次把这片生意引到工程这边。'},
    7155: {'a': '把首都的这部分工程，再让给奇观一次。'},
    7156: {'a': '这份光彩，本就是从别处借来的。'},
    7157: {'a': '记下伤名，继续开工！'},
    7158: {'a': '先把国库掏空一些，工程照常往上砌。'},
    7159: {'a': '宁可让王室这次让步，也要把墙砌起来。'},
    7160: {'a': '不去管它，让围栏外的骚动自己平息。'},
    7161: {'a': '由他们说去！'},
    7162: {'a': '任凭贵族抱怨，泥瓦照旧往上砌。'},
    7163: {'a': '教士的这份不满，就当作是石料的代价收下了。'},
    7164: {'a': '任由店铺发牢骚，脚手架照样往上搭。'},
    7165: {'a': '让田地扛着去吧！'},
    7166: {'a': '工址退一步，只为让奇观往前迈一步。'},
    7167: {'a': '由着本地市场淡下去，工程照旧不停。'},
    7168: {'a': '让首都自己的修缮先等一等，给远方的奇观让路。'},
    7169: {'a': '压低首都的生意，去供养别处的这座奇观。'},
    7170: {'a': '工地已经出了人命，我们仍然往前走。'},
    7171: {'a': '把一次普通的巡视，办成了满城称赞的事。'},
    7172: {'a': '让这条主轴显得站得住脚，而不是孤注一掷。'},
    7173: {'a': '干脆照这套新排班来。'},
    7174: {'a': '路终于通了！'},
    7175: {'a': '把卡住的工段硬生生推了过去。'},
    7176: {'a': '拿实话把流言压了下去。'},
    7177: {'a': '给这个方案，留出了足够的余地。'},
    7178: {'a': '把工队、工具和更次都理顺了。'},
    7179: {'a': '解开了补给线上最糟的死结。'},
    7180: {'a': '即刻推进，毫不耽搁！'},
    7181: {'a': '任由人群评判这堆未完工的石头。'},
    7182: {'a': '趁疑虑未消，先把蓝图放大。'},
    7183: {'a': '我们改写班次，看工地能否跟得上。'},
    7184: {'a': '让车队改走这条难路，赌的是算得准，不是图省事。'},
    7185: {'a': '试试这更快的工法，就让它当众见分晓！'},
    7186: {'a': '先把这笔亏空补上，免得账目被人追问。'},
    7187: {'a': '这次滥用王室名义的做法，得收一收。'},
    7188: {'a': '把这套整齐方案惹出的骚动抚平。'},
    7189: {'a': '把话收回来！'},
    7190: {'a': '提醒工程师，贵族的耐性可不是随取随用的库存。'},
    7191: {'a': '把祭坛的日历还给祭坛自己。'},
    7192: {'a': '我们把工地挡住的商路重新开出来。'},
    7193: {'a': '让已经疲惫的村社喘一口气，别再被当储备使唤。'},
    7194: {'a': '把这处切错的地方重新补上。'},
    7195: {'a': '我们把被工地挤走的生计再腾出些地方。'},
    7196: {'a': '把这些被挪用的资源还给首都自己的安排。'},
    7197: {'a': '我们先把王城的生意稳下来，别让乱子扩散。'},
    7198: {'a': '先松一松，别再累垮更多人！'},
    7199: {'a': '咬牙认下这笔亏空，悄悄合上账册。'},
    7200: {'a': '这道新添的伤痕，我们记下，继续往前走。'},
    7201: {'a': '由着这场动乱自行平息。'},
    7202: {'a': '就让宫廷看这出热闹去吧！'},
    7203: {'a': '拿贵族的情面换工程继续推进。'},
    7204: {'a': '让教士的这份耐心，替这些石料买了单。'},
    7205: {'a': '由商人自己去修补那些脚手架。'},
    7206: {'a': '这份本可以省去的要求，我们向村社赔个不是。'},
    7207: {'a': '草草包扎了那道由抢修引出的创伤。'},
    7208: {'a': '罢了——就让摊位安静下来吧！'},
    7209: {'a': '掏空首都的规划，来填补工地的这个窟窿。'},
    7210: {'a': '这场本不该传到市面上的失败，还是让首都的生意暗淡了下去。'},
    7211: {'a': '清点了那些工队本不该失去的性命。'},
}

COMBO_DESC_POOL = {
    'trade_noneng_for_eng': [
        {'en': 'Somewhere in the ledgers, a clerk finds a line that can be crossed out without anyone asking twice: {noneng} bends a little so that {eng} can move forward. It is the kind of arithmetic that works today and gets reread, unkindly, next season.', 'zh': '工程部门这个月做了一次临时调度：以{noneng}为代价，换来{eng}上看得见的进展。这笔账现在划得来，只是这种调度不能一直用。'},
        {'en': 'Like drawing water from one field to save another, the foremen suggest letting {noneng} run a little dry so that {eng} can be irrigated properly. Nobody upstream will thank them for it, but the crop of progress comes in regardless.', 'zh': '工头们商量了一下，决定这个月先耗一些{noneng}，换{eng}往前挪一挪。这样做马上就能见效，只是{noneng}这个月确实要吃点亏。'},
        {'en': 'The [tv_engineering_department|E] asks, in effect, to borrow against {noneng}: spend it down now, promise nothing about paying it back, and let the difference show up as hard movement on {eng}. Debts like this rarely stay quiet forever.', 'zh': '工程部门这次是先斩后奏：先动用了{noneng}，才换来{eng}上看得见的进展。至于这笔账以后要不要找补，暂时没人细算。'},
        {'en': 'Someone has to sit on the heavier side of the scale, and this month it is {noneng}. Let it settle a little lower, and {eng} rises to match, though the balance rarely stays where you last left it.', 'zh': '这个月的账不太好看：要让{eng}往前挪一挪，就得先在{noneng}上吃点亏。工头们说这笔账划算，但{noneng}这个月确实吃了亏，谁看了都清楚。'},
        {'en': 'The foremen put it plainly: give up a slice of {noneng} this month, and they will turn it directly into {eng}. No one pretends it is a generous exchange, only a workable one.', 'zh': '工头们把话说得很直接：这个月先在{noneng}上让一步，马上就能换成{eng}上的进展。没人说这是笔多体面的买卖，只说这么做管用。'},
        {'en': 'Stores meant to last the season get opened early. What leaves as {noneng} does not vanish so much as change shape, arriving on the far side of the ledger as fresh {eng}. Whether that shape is worth the emptied shelf is a question for later.', 'zh': '这笔账说白了很简单：这个月要紧一紧{noneng}这头，才能让{eng}松动一步。工程部门没打算隐瞒这一点，只是提醒大家，这个月紧出来的这部分不会自己松回来。'},
        {'en': 'It amounts to a wager: stake {noneng} on the table and see it returned, transformed, as movement on {eng}. The house — in this case, the works themselves — tends to collect on such bets one way or another.', 'zh': '工程部门这次是拿{noneng}赌了一把，赌的是能换回{eng}上的进展。这一手算是赌对了，工地这次是真的往前走了。'},
        {'en': 'There is no clean way to say it: {noneng} must give a little ground this month if {eng} is to move at all. The engineers accept the trade without much ceremony, aware that ground given rarely returns on its own.', 'zh': '说白了没什么好粉饰的：这个月要先动{noneng}，{eng}才能往前挪。工程师们没多说什么，直接照办了，心里清楚这部分损失不会自己补回来。'},
        {'en': 'Building anything worth having means burning something else to light the way. This time the fuel is {noneng}, and the light it throws falls squarely on {eng} — bright enough to notice, costly enough to remember.', 'zh': '要把工程往前推一步，总得先花掉点别的东西。这次花的是{noneng}，换来的是{eng}上看得见的进展，代价不小，但确实管用。'},
        {'en': 'Someone will have to call in a favor, and this time the favor is paid out of {noneng}. It buys the works an unmistakable step forward in {eng}, but favors spent do not refill themselves.', 'zh': '工程部门这个月做了个决定：先在{noneng}上退一步，才能让{eng}往前挪一步。这笔账划得来，只是退让的这部分，往后是要有人惦记的。'},
    ],
    'choose_eng_or_noneng_loss': [
        {'en': 'There is no way to absorb this loss cleanly. Either {eng} takes the weight and holds its ground, or the strain lands on {noneng} instead. Someone always pays, one way or another.', 'zh': '这个月的损失躲不掉，只能决定让谁来承担：是让{eng}受损，还是把代价转到{noneng}身上。不管选哪边，总得有一方吃亏。'},
        {'en': 'A shock has found its way to the site, and it must land somewhere. Hold firm and let {eng} take the brunt of it, or turn it aside and let {noneng} absorb the fallout.', 'zh': '工地上出了点意外，损失总要落在什么地方。可以让{eng}直接受损，也可以把这份压力转出去，让{noneng}来承担。'},
        {'en': 'Something on this scaffold must give. Either {eng} takes the sag, or the load shifts onto {noneng} instead.', 'zh': '工程遇到了麻烦，总得有个地方吃亏。要么让{eng}先受影响，要么把这份负担转给{noneng}。'},
        {'en': 'Two doors stand open, and only one can be shut in time. Close it on {eng}, and the setback lands there; leave it be, and {noneng} takes the fall instead.', 'zh': '现在有两个办法，只能挑一个：让{eng}承受这次损失，或者把损失转移出去，让{noneng}来承受。'},
        {'en': 'The trouble behaves like floodwater looking for the lowest ground. Dam it here and {eng} takes the first surge; open the sluice elsewhere and {noneng} takes the water instead.', 'zh': '这次的麻烦总要落在什么地方。挡在这里，损失的就是{eng}；放到别处去，受影响的就变成{noneng}。'},
        {'en': 'Somebody must carry this debt through the month. Let {eng} sign for it and wear the cost, or push the note across the table so {noneng} settles it instead.', 'zh': '这个月的代价必须有人承担。可以让{eng}直接背这笔账，也可以把账转出去，让{noneng}来还。'},
        {'en': 'The blow is already swinging and cannot be stopped, only redirected. Take it on {eng}, or send it wide so {noneng} catches it instead.', 'zh': '损失已经无法避免，唯一能定的是它落在哪里。可以让它冲击{eng}，也可以把它引开，让{noneng}承受。'},
        {'en': 'A crack has opened somewhere in the work, and mortar alone will not seal it. Let it run through {eng}, or brace that line and let it surface instead in {noneng}.', 'zh': '工程出了问题，代价必须有人承担。让{eng}直接受损是一种办法，把压力转给{noneng}也是一种办法。'},
        {'en': 'The scales will not sit level no matter how the numbers are read. Tip them so {eng} carries the difference, or tip them the other way and hand the difference to {noneng}.', 'zh': '这笔账无论怎么算都要吃亏。可以让{eng}来承担这个差额，也可以把差额转出去，交给{noneng}。'},
    ],
}

COMBO_OPTION_POOL = {
    'trade_noneng_for_eng': {
        'a': [
            {'en': 'Puts the cost to good use.', 'zh': '把这笔支出花在了刀刃上。', 'category': 'third_person'},
            {'en': 'Turns the sacrifice into progress.', 'zh': '把这份牺牲换成了实打实的进展。', 'category': 'third_person'},
            {'en': 'Makes the trade without hesitation.', 'zh': '毫不犹豫地应下了这笔交易。', 'category': 'third_person'},
            {'en': 'Accepts the bargain.', 'zh': '收下了这笔买卖。', 'category': 'third_person'},
            {'en': 'Cashes in the opportunity.', 'zh': '抓住了这难得的机会。', 'category': 'third_person'},
            {'en': 'Signs off on the exchange.', 'zh': '落笔签下了这笔交换。', 'category': 'third_person'},
            {'en': 'We\'ll pay the price.', 'zh': '这个价，我们认了。', 'category': 'first_person'},
            {'en': 'We accept the trade.', 'zh': '这笔交易，我们接下了。', 'category': 'first_person'},
            {'en': 'We\'ll make it count.', 'zh': '我们会让它物有所值。', 'category': 'first_person'},
            {'en': 'We take the deal.', 'zh': '这笔买卖，我们拿下了。', 'category': 'first_person'},
            {'en': 'Do it!', 'zh': '就这么办！', 'category': 'interjection'},
            {'en': 'Make the trade!', 'zh': '促成这笔交易！', 'category': 'interjection'},
            {'en': 'Nothing ventured, nothing gained.', 'zh': '舍不得孩子套不住狼。', 'category': 'proverb'},
        ],
        'b': [
            {'en': 'Lets the month pass quietly.', 'zh': '由着这个月悄悄过去。', 'category': 'third_person'},
            {'en': 'Leaves the offer on the table.', 'zh': '把这个提议撂在了一边。', 'category': 'third_person'},
            {'en': 'Holds off for now.', 'zh': '先按兵不动。', 'category': 'third_person'},
            {'en': 'Passes on the bargain.', 'zh': '婉拒了这笔交易。', 'category': 'third_person'},
            {'en': 'We\'ll wait this one out.', 'zh': '这次，我们先观望。', 'category': 'first_person'},
            {'en': 'We decline for now.', 'zh': '我们暂时不接这个茬。', 'category': 'first_person'},
            {'en': 'We keep our reserves untouched.', 'zh': '我们按兵不动，留住这份底子。', 'category': 'first_person'},
            {'en': 'Not this month!', 'zh': '这个月不行！', 'category': 'interjection'},
            {'en': 'Better safe than sorry.', 'zh': '小心驶得万年船。', 'category': 'proverb'},
        ],
    },
    'choose_eng_or_noneng_loss': {
        'a': [
            {'en': 'Lets it take the hit.', 'zh': '由它先扛下这一下。', 'category': 'third_person'},
            {'en': 'Puts the strain here and holds the line.', 'zh': '把压力扛在这里，稳住阵脚。', 'category': 'third_person'},
            {'en': 'Takes the weight without flinching.', 'zh': '眼都不眨，接下了这份重量。', 'category': 'third_person'},
            {'en': 'Keeps the loss close and bears it.', 'zh': '把损失留在自己身上，扛下来。', 'category': 'third_person'},
            {'en': 'Absorbs the blow rather than pass it on.', 'zh': '自己吞下这一击，不转嫁给旁人。', 'category': 'third_person'},
            {'en': 'Shoulders the cost outright.', 'zh': '干脆利落地把代价扛了下来。', 'category': 'third_person'},
            {'en': 'We\'ll take the hit here.', 'zh': '这一下，我们就在这里扛下。', 'category': 'first_person'},
            {'en': 'We absorb it and move on.', 'zh': '我们咽下这口气，继续往前走。', 'category': 'first_person'},
            {'en': 'We hold the line, whatever it costs.', 'zh': '不管代价多少，我们守住这里。', 'category': 'first_person'},
            {'en': 'We\'ll wear this one ourselves.', 'zh': '这次，我们自己扛下。', 'category': 'first_person'},
            {'en': 'Take the hit!', 'zh': '扛下来！', 'category': 'interjection'},
            {'en': 'Better a known wound than a hidden one.', 'zh': '宁受明伤，不留暗患。', 'category': 'proverb'},
        ],
        'b': [
            {'en': 'Pushes the burden elsewhere.', 'zh': '把这份负担推到了别处。', 'category': 'third_person'},
            {'en': 'Shifts the weight outward.', 'zh': '把这份重量转移了出去。', 'category': 'third_person'},
            {'en': 'Spares it and lets the strain fall on the rest.', 'zh': '护住这一头，让压力落到旁处。', 'category': 'third_person'},
            {'en': 'Turns the loss aside.', 'zh': '把这份损失挡开，转向了别处。', 'category': 'third_person'},
            {'en': 'We\'ll let the rest absorb this one.', 'zh': '这次，就让别处承担吧。', 'category': 'first_person'},
            {'en': 'We spare it and pay elsewhere.', 'zh': '我们护住这里，代价挪去别处。', 'category': 'first_person'},
            {'en': 'We turn the blow aside.', 'zh': '我们把这一击引向了别处。', 'category': 'first_person'},
            {'en': 'Turn it aside!', 'zh': '转个方向！', 'category': 'interjection'},
            {'en': 'Spare the roof; let the rain find another eave.', 'zh': '留住这片屋顶，任雨水改道别檐。', 'category': 'proverb'},
        ],
    },
}

# ---- End generated data tables ----

def load_data() -> dict:
    with DATA_FILE.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def event_weight(kind: str, eng: dict | None = None, noneng: dict | None = None) -> int:
    weight = EVENT_KIND_WEIGHTS[kind]
    if eng is not None:
        weight *= eng["weight"]
    if noneng is not None:
        weight *= noneng["weight"]
    return weight


def build_events(data: dict) -> list[dict]:
    events: list[dict] = []
    event_id = int(data["event_id_start"])
    eng_tokens = data["engineering_tokens"]
    noneng_tokens = data["non_engineering_tokens"]

    def add(kind: str, eng: dict | None = None, noneng: dict | None = None) -> None:
        nonlocal event_id
        events.append(
            {
                "id": event_id,
                "kind": kind,
                "eng": eng,
                "noneng": noneng,
                "outcome": KIND_OUTCOMES[kind],
                "weight": event_weight(kind, eng, noneng),
            }
        )
        event_id += 1

    for eng in eng_tokens:
        add("gain_engineering_2", eng=eng)
    for eng in eng_tokens:
        add("gain_engineering_1", eng=eng)
    for eng in eng_tokens:
        for noneng in noneng_tokens:
            add("trade_noneng_for_eng", eng=eng, noneng=noneng)
    for eng in eng_tokens:
        add("swing_engineering_1", eng=eng)
    for eng in eng_tokens:
        for noneng in noneng_tokens:
            add("choose_eng_or_noneng_loss", eng=eng, noneng=noneng)
    for noneng in noneng_tokens:
        add("lose_noneng_1", noneng=noneng)
    for noneng in noneng_tokens:
        add("lose_noneng_2", noneng=noneng)
    for eng in eng_tokens:
        add("engineer_gain_engineering_2", eng=eng)
    for eng in eng_tokens:
        add("engineer_gain_engineering_1", eng=eng)
    for eng in eng_tokens:
        add("engineer_swing_engineering_1", eng=eng)
    for noneng in noneng_tokens:
        add("engineer_lose_noneng_1", noneng=noneng)
    for noneng in noneng_tokens:
        add("engineer_lose_noneng_2", noneng=noneng)
    return events


def _combo_index(event: dict, salt: int = 0) -> int:
    """Stable index for picking a pool variant for a combinatorial-kind event.

    Deterministic on (eng, noneng) so regeneration is idempotent; `salt` lets desc
    and option-slot lookups land on different pool entries for the same event
    instead of moving in lockstep.
    """
    eng_index = ENG_TOKEN_ORDER.index(event["eng"]["id"])
    noneng_index = NONENG_TOKEN_ORDER.index(event["noneng"]["id"])
    return eng_index * len(NONENG_TOKEN_ORDER) + noneng_index + salt


def format_title(event: dict, lang: str) -> str:
    table = TITLE_EN if lang == "en" else TITLE_ZH
    return table[event["id"]]


def format_desc(event: dict, lang: str) -> str:
    kind = event["kind"]
    if kind not in COMBINATORIAL_KINDS:
        table = DESC_EN if lang == "en" else DESC_ZH
        return table[event["id"]]

    pool = COMBO_DESC_POOL[kind]
    variant = pool[_combo_index(event) % len(pool)]
    eng_ref = (ENGINEERING_CONCEPT_REF_EN if lang == "en" else ENGINEERING_CONCEPT_REF_ZH)[event["eng"]["id"]]
    noneng_ref = (NON_ENGINEERING_CONCEPT_REF_EN if lang == "en" else NON_ENGINEERING_CONCEPT_REF_ZH)[event["noneng"]["id"]]
    return variant[lang].format(eng=eng_ref, noneng=noneng_ref)


def option_loc(event: dict, suffix: str, lang: str) -> str:
    kind = event["kind"]
    if kind not in COMBINATORIAL_KINDS:
        table = OPTION_EN if lang == "en" else OPTION_ZH
        return table[event["id"]][suffix]

    pool = COMBO_OPTION_POOL[kind][suffix]
    salt = 7 if suffix == "a" else 13
    return pool[_combo_index(event, salt=salt) % len(pool)][lang]


def indent_lines(text: str, level: int) -> str:
    return "\n".join((T * level + line if line.strip() else "") for line in text.rstrip().splitlines())


def render_header(script: str, data: str, extra: str = "") -> str:
    suffix = f"\n{extra.rstrip()}\n" if extra else "\n"
    return (
        f"# @Generated by {script}\n"
        f"#   Data:    {data}\n"
        f"#   Regen:   conda run --no-capture-output -n eu5 python {script}\n"
        "# Do not edit directly - modify the data file and re-run the generator.\n"
        f"{suffix}"
    )

