"""Generate victory path tab and reward selection generic actions."""

import sys
import argparse
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "victory_paths.yaml"
OUT_FILE = (
    REPO_ROOT
    / "src"
    / "in_game"
    / "common"
    / "generic_actions"
    / "towards_victory_reward_actions.txt"
)

HEADER = """\
# @Generated by scripts/in_game/common/generic_actions/gen_towards_victory_reward_actions.py
#   Data:    data/victory_paths.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/generic_actions/gen_towards_victory_reward_actions.py
# Do not edit directly - modify the data file and re-run the generator.
"""


def _action_common() -> str:
    return """\
\ttype = owncountry
\tsound = UI_action_religion_generic
\tshow_message = no
\tai_tick = never
\tautomation_tick = never"""


def gen_path_action(path: dict) -> str:
    pid = path["id"]
    order = int(path["gui"]["order"])
    return f"""\
tv_victory_select_path_{pid} = {{
{_action_common()}
\tpotential = {{ always = yes }}
\tallow = {{ always = yes }}
\teffect = {{
\t\tscope:actor = {{
\t\t\thidden_effect = {{
\t\t\t\tif = {{
\t\t\t\t\tlimit = {{ NOT = {{ var:tv_victory_selected_path ?= {order} }} }}
\t\t\t\t\tset_variable = {{ name = tv_victory_selected_path value = {order} }}
\t\t\t\t}}
\t\t\t}}
\t\t}}
\t}}
\tai_will_do = {{ add = -100 }}
}}
"""


def gen_reward_action(path: dict, milestone: dict, choice: int) -> str:
    pid = path["id"]
    n = int(milestone["n"])
    return f"""\
tv_victory_select_{pid}_m{n}_reward_{choice} = {{
{_action_common()}
\tpotential = {{ always = yes }}
\tallow = {{
\t\tscope:actor = {{
\t\t\tcustom_tooltip = {{
\t\t\t\ttext = TV_HAS_{pid.upper()}_MILESTONE_TT
\t\t\t\thas_variable = tv_{pid}_milestone
\t\t\t}}
\t\t\tvar:tv_{pid}_milestone ?= {{ this >= {n} }}
\t\t}}
\t}}
\teffect = {{
\t\tscope:actor = {{
\t\t\ttv_select_{pid}_m{n}_reward_effect = {{ choice = {choice} }}
\t\t}}
\t}}
\tai_will_do = {{ add = -100 }}
}}
"""


def generate(data: dict) -> str:
    paths = sorted(data["paths"], key=lambda path: int(path["gui"]["order"]))
    parts = [HEADER]
    for path in paths:
        parts.append(gen_path_action(path))
    for path in paths:
        for milestone in path["milestones"]:
            for choice in range(1, 4):
                parts.append(gen_reward_action(path, milestone, choice))
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with DATA_FILE.open(encoding="utf-8-sig") as file:
        data = yaml.safe_load(file)

    content = generate(data)
    if args.dry:
        print(content)
    else:
        OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        OUT_FILE.write_text(content, encoding="utf-8-sig")
        print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
