"""
Generate src/in_game/common/generic_actions/tv_io_leader_actions.txt from data/io_leaders.yaml.

Pattern: 3 IOs × 3 actions (Appoint / Remove / Change) = 9 generic_action blocks.
Each block shares identical structural boilerplate; only the IO-specific strings differ.
"""

import sys
import argparse
import textwrap
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "io_leaders.yaml"
OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "generic_actions" / "tv_io_leader_actions.txt"

HEADER = """\
# @Generated by scripts/in_game/common/generic_actions/gen_tv_io_leader_actions.py
#   Data:    data/io_leaders.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/generic_actions/gen_tv_io_leader_actions.py
# Do not edit directly — modify the data file and re-run the generator.
"""

SECTION_BANNER = """\
# ═════════════════════════════════════════════════════════════════════════════
# {title} (non-unique IO)
# ═════════════════════════════════════════════════════════════════════════════
"""


def _char_selector_block(io: dict, action: str) -> str:
    """Return the select_trigger block for Appoint and Change actions."""
    lines = ["\tselect_trigger = {"]
    lines.append("\t\tlooking_for_a = character")
    lines.append("\t\tsource = actor")
    lines.append("\t\ttarget_flag = target")
    lines.append(f'\t\tname = "{io["select_name"]}"')
    lines.append(f'\t\tnone_available_msg_key = "{io["no_leader_msg"]}"')
    lines.append("\t\tcolumn = { data = character_info }")
    lines.append("\t\tvisible = {")
    lines.append("\t\t\tis_alive = yes")
    char_filter = io.get("char_filter", "").strip()
    if char_filter:
        for line in char_filter.splitlines():
            lines.append(f"\t\t\t{line.strip()}")
    lines.append("\t\t\tis_ruler = no")
    lines.append("\t\t\tis_heir = no")
    lines.append("\t\t\tis_consort = no")
    lines.append("\t\t}")
    lines.append("\t}")
    return "\n".join(lines)


def gen_appoint(io: dict) -> str:
    selector = _char_selector_block(io, "appoint")
    return f"""\
tv_appoint_{io["id"]}_leader = {{
\ttype = owncountry
\tsound = UI_action_religion_generic
\tai_tick = monthly
\tai_tick_frequency = 99999

\tpotential = {{
\t\tscope:actor = {{ has_variable = {io["member_var"]} }}
\t\tscope:actor = {{
\t\t\tany_international_organizations_member_of = {{
\t\t\t\tinternational_organization_type = international_organization_type:{io["io_type"]}
\t\t\t\tinternational_organization_has_leader = no
\t\t\t}}
\t\t}}
\t}}

\tallow = {{ always = yes }}

{selector}

\teffect = {{
\t\tif = {{
\t\t\tlimit = {{ exists = scope:target }}
\t\t\tscope:actor = {{
\t\t\t\tset_variable = {{ name = {io["leader_var"]} value = scope:target }}
\t\t\t\tevery_international_organizations_member_of = {{
\t\t\t\t\tlimit = {{
\t\t\t\t\t\tinternational_organization_type = international_organization_type:{io["io_type"]}
\t\t\t\t\t\tleader_country ?= scope:actor
\t\t\t\t\t}}
\t\t\t\t\tinternational_organization_chooses_new_leader = this
\t\t\t\t}}
\t\t\t}}
\t\t}}
\t}}

\tai_will_do = {{ add = -100 }}
}}
"""


def gen_remove(io: dict) -> str:
    return f"""\
tv_remove_{io["id"]}_leader = {{
\ttype = owncountry
\tsound = UI_action_religion_generic
\tai_tick = monthly
\tai_tick_frequency = 99999

\tpotential = {{
\t\tscope:actor = {{ has_variable = {io["member_var"]} }}
\t\tscope:actor = {{
\t\t\tany_international_organizations_member_of = {{
\t\t\t\tinternational_organization_type = international_organization_type:{io["io_type"]}
\t\t\t\tinternational_organization_has_leader = yes
\t\t\t}}
\t\t}}
\t}}

\tallow = {{ always = yes }}

\teffect = {{
\t\tscope:actor = {{
\t\t\tremove_variable = {io["leader_var"]}
\t\t\tevery_international_organizations_member_of = {{
\t\t\t\tlimit = {{
\t\t\t\t\tinternational_organization_type = international_organization_type:{io["io_type"]}
\t\t\t\t\tleader_country ?= scope:actor
\t\t\t\t}}
\t\t\t\tinternational_organization_chooses_new_leader = this
\t\t\t}}
\t\t}}
\t}}

\tai_will_do = {{ add = -100 }}
}}
"""


def gen_change(io: dict) -> str:
    selector = _char_selector_block(io, "change")
    return f"""\
tv_change_{io["id"]}_leader = {{
\ttype = owncountry
\tsound = UI_action_religion_generic
\tai_tick = monthly
\tai_tick_frequency = 99999

\tpotential = {{
\t\tscope:actor = {{ has_variable = {io["member_var"]} }}
\t\tscope:actor = {{
\t\t\tany_international_organizations_member_of = {{
\t\t\t\tinternational_organization_type = international_organization_type:{io["io_type"]}
\t\t\t\tinternational_organization_has_leader = yes
\t\t\t}}
\t\t}}
\t}}

\tallow = {{ always = yes }}

{selector}

\teffect = {{
\t\tif = {{
\t\t\tlimit = {{ exists = scope:target }}
\t\t\tscope:actor = {{
\t\t\t\tset_variable = {{ name = {io["leader_var"]} value = scope:target }}
\t\t\t\tevery_international_organizations_member_of = {{
\t\t\t\t\tlimit = {{
\t\t\t\t\t\tinternational_organization_type = international_organization_type:{io["io_type"]}
\t\t\t\t\t\tleader_country ?= scope:actor
\t\t\t\t\t}}
\t\t\t\t\tinternational_organization_chooses_new_leader = this
\t\t\t\t}}
\t\t\t}}
\t\t}}
\t}}

\tai_will_do = {{ add = -100 }}
}}
"""


def _io_title(io: dict) -> str:
    return io.get("display_name", io["id"].replace("_", " ").title())


def generate(data: dict) -> str:
    parts = [HEADER]
    for io in data["ios"]:
        parts.append(SECTION_BANNER.format(title=_io_title(io)))
        parts.append(gen_appoint(io))
        parts.append(gen_remove(io))
        parts.append(gen_change(io))
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with open(DATA_FILE, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    content = generate(data)

    if args.dry:
        print(content)
    else:
        OUT_FILE.write_text(content, encoding="utf-8-sig")
        print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
