"""
Generate src/in_game/common/generic_actions/tv_io_leader_actions.txt from data/io_leaders.yaml.

Pattern: one data entry per character-led IO, each generating Appoint / Remove / Change actions.
Each block shares identical structural boilerplate; only the IO-specific strings differ.
"""

import sys
import argparse
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "io_leaders.yaml"
OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "generic_actions" / "tv_io_leader_actions.txt"

HEADER = """\
# @Generated by scripts/in_game/common/generic_actions/gen_tv_io_leader_actions.py
#   Data:    data/io_leaders.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/generic_actions/gen_tv_io_leader_actions.py
# Do not edit directly — modify the data file and re-run the generator.
"""

SECTION_BANNER = """\
# ═════════════════════════════════════════════════════════════════════════════
# {title} (non-unique IO)
# ═════════════════════════════════════════════════════════════════════════════
"""


def _char_selector_block(io: dict) -> str:
    """Return the select_trigger block for Appoint and Change actions."""
    character_column = io.get("character_column", "character_info")
    lines = ["\tselect_trigger = {"]
    lines.append("\t\tlooking_for_a = character")
    lines.append("\t\tsource = actor")
    lines.append("\t\ttarget_flag = target")
    lines.append(f'\t\tname = "{io["select_name"]}"')
    lines.append(f'\t\tnone_available_msg_key = "{io["no_leader_msg"]}"')
    lines.append(f"\t\tcolumn = {{ data = {character_column} }}")
    lines.append("\t\tvisible = {")
    lines.append("\t\t\tis_alive = yes")
    char_filter = io.get("char_filter", "").strip()
    if char_filter:
        for line in char_filter.splitlines():
            lines.append(f"\t\t\t{line.strip()}")
    lines.append("\t\t\tis_ruler = no")
    lines.append("\t\t\tis_heir = no")
    lines.append("\t\t\tis_consort = no")
    lines.append("\t\t}")
    lines.append("\t}")
    return "\n".join(lines)


def _extra_effect_block(io: dict, key: str, indent: str) -> str:
    """Return an optional YAML-provided effect snippet at the requested indent."""
    effect = io.get(key, "").rstrip()
    if not effect:
        return ""
    lines = []
    for line in effect.splitlines():
        if line:
            lines.append(f"{indent}{line.rstrip()}")
        else:
            lines.append("")
    return "\n".join(lines) + "\n"


def gen_appoint(io: dict) -> str:
    selector = _char_selector_block(io)
    title_mod = io.get("title_modifier", "")
    extra_effect = _extra_effect_block(io, "on_appoint_effect", "\t\t\t\t")
    title_effect = (
        f"\t\t\tscope:target = {{\n"
        f"\t\t\t\tadd_character_modifier = {{ modifier = {title_mod} years = -1 mode = add_and_extend }}\n"
        f"\t\t\t}}\n"
    ) if title_mod else ""
    return (
        f"tv_appoint_{io['id']}_leader = {{\n"
        f"\ttype = owncountry\n"
        f"\tsound = UI_action_religion_generic\n"
        f"\tai_tick = monthly\n"
        f"\tai_tick_frequency = 99999\n"
        f"\n"
        f"\tpotential = {{\n"
        f"\t\tscope:actor = {{ has_variable = {io['member_var']} }}\n"
        f"\t}}\n"
        f"\n"
        f"\tallow = {{ always = yes }}\n"
        f"\n"
        f"{selector}\n"
        f"\n"
        f"\teffect = {{\n"
        f"\t\tif = {{\n"
        f"\t\t\tlimit = {{ exists = scope:target }}\n"
        f"\t\t\tscope:actor = {{\n"
        f"\t\t\t\tset_variable = {{ name = {io['leader_var']} value = scope:target }}\n"
        f"{extra_effect}"
        f"\t\t\t}}\n"
        f"{title_effect}"
        f"\t\t}}\n"
        f"\t}}\n"
        f"\n"
        f"\tai_will_do = {{ add = -100 }}\n"
        f"}}\n"
    )


def gen_remove(io: dict) -> str:
    title_mod = io.get("title_modifier", "")
    extra_effect = _extra_effect_block(io, "on_remove_effect", "\t\t\t")
    title_effect = (
        f"\t\t\tif = {{\n"
        f"\t\t\t\tlimit = {{ has_variable = {io['leader_var']} }}\n"
        f"\t\t\t\tvar:{io['leader_var']} ?= {{\n"
        f"\t\t\t\t\tremove_character_modifier = {title_mod}\n"
        f"\t\t\t\t}}\n"
        f"\t\t\t}}\n"
    ) if title_mod else ""
    return (
        f"tv_remove_{io['id']}_leader = {{\n"
        f"\ttype = owncountry\n"
        f"\tsound = UI_action_religion_generic\n"
        f"\tai_tick = monthly\n"
        f"\tai_tick_frequency = 99999\n"
        f"\n"
        f"\tpotential = {{\n"
        f"\t\tscope:actor = {{ has_variable = {io['member_var']} }}\n"
        f"\t}}\n"
        f"\n"
        f"\tallow = {{ always = yes }}\n"
        f"\n"
        f"\teffect = {{\n"
        f"\t\tscope:actor = {{\n"
        f"{title_effect}"
        f"{extra_effect}"
        f"\t\t\tremove_variable = {io['leader_var']}\n"
        f"\t\t}}\n"
        f"\t}}\n"
        f"\n"
        f"\tai_will_do = {{ add = -100 }}\n"
        f"}}\n"
    )


def gen_change(io: dict) -> str:
    selector = _char_selector_block(io)
    title_mod = io.get("title_modifier", "")
    extra_effect = _extra_effect_block(io, "on_change_effect", "\t\t\t")
    remove_old_title_inner = (
        f"\t\t\tif = {{\n"
        f"\t\t\t\tlimit = {{ has_variable = {io['leader_var']} }}\n"
        f"\t\t\t\tvar:{io['leader_var']} ?= {{\n"
        f"\t\t\t\t\tremove_character_modifier = {title_mod}\n"
        f"\t\t\t\t}}\n"
        f"\t\t\t}}\n"
    ) if title_mod else ""
    pre_change_actor_effect = (
        f"\t\tscope:actor = {{\n"
        f"{remove_old_title_inner}"
        f"{extra_effect}"
        f"\t\t}}\n"
    ) if (remove_old_title_inner or extra_effect) else ""
    add_new_title = (
        f"\t\t\tscope:target = {{\n"
        f"\t\t\t\tadd_character_modifier = {{ modifier = {title_mod} years = -1 mode = add_and_extend }}\n"
        f"\t\t\t}}\n"
    ) if title_mod else ""
    return (
        f"tv_change_{io['id']}_leader = {{\n"
        f"\ttype = owncountry\n"
        f"\tsound = UI_action_religion_generic\n"
        f"\tai_tick = monthly\n"
        f"\tai_tick_frequency = 99999\n"
        f"\n"
        f"\tpotential = {{\n"
        f"\t\tscope:actor = {{ has_variable = {io['member_var']} }}\n"
        f"\t}}\n"
        f"\n"
        f"\tallow = {{ always = yes }}\n"
        f"\n"
        f"{selector}\n"
        f"\n"
        f"\teffect = {{\n"
        f"{pre_change_actor_effect}"
        f"\t\tif = {{\n"
        f"\t\t\tlimit = {{ exists = scope:target }}\n"
        f"\t\t\tscope:actor = {{\n"
        f"\t\t\t\tset_variable = {{ name = {io['leader_var']} value = scope:target }}\n"
        f"\t\t\t}}\n"
        f"{add_new_title}"
        f"\t\t}}\n"
        f"\t}}\n"
        f"\n"
        f"\tai_will_do = {{ add = -100 }}\n"
        f"}}\n"
    )


def _io_title(io: dict) -> str:
    return io.get("display_name", io["id"].replace("_", " ").title())


def generate(data: dict) -> str:
    parts = [HEADER]
    for io in data["ios"]:
        parts.append(SECTION_BANNER.format(title=_io_title(io)))
        parts.append(gen_appoint(io))
        parts.append(gen_remove(io))
        parts.append(gen_change(io))
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with open(DATA_FILE, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    content = generate(data)

    if args.dry:
        print(content)
    else:
        OUT_FILE.write_text(content, encoding="utf-8-sig")
        print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
