"""
Generate philosophy debate generic actions for the Academy of Sciences panel.

The current Academy philosophy debate UI has no player action cards. The generated
file is intentionally kept as an empty action file so the registered generated
output remains stable while the old action-slot system is removed.
"""

import sys
import argparse
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "philosophy_debate_actions.yaml"
OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "generic_actions" / "tv_philosophy_actions.txt"

HEADER = """\
# @Generated by scripts/in_game/common/generic_actions/gen_tv_philosophy_actions.py
#   Data:    data/philosophy_debate_actions.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/generic_actions/gen_tv_philosophy_actions.py
# Do not edit directly - modify the data file and re-run the generator.
"""


def generate(data: dict) -> str:
    return HEADER + "\n# Philosophy debate action cards are disabled in the current Academy debate UI.\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with DATA_FILE.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)

    content = generate(data)
    if args.dry:
        print(content)
    else:
        OUT_FILE.write_text(content, encoding="utf-8-sig")
        print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
