l_braz_por:
 cmf_settings_title: "Framework de Mods da Comunidade"
 cmf_settings_page_action_bar: "Barra de Ações"
 cmf_settings_action_bar_group_layout: "Layout"
 cmf_settings_action_bar_position_activate: "Ativar esta posição"
 cmf_settings_action_bar_position: "Posição da Barra de Ação"
 cmf_settings_action_bar_position_top: "Topo"
 cmf_settings_action_bar_position_bottom_left: "Inferior Esquerdo"
 cmf_settings_action_bar_position_bottom_right: "Inferior Direito"
 cmf_settings_action_bar_group_active_buttons: "Botões Ativos"
 cmf_settings_action_bar_group_active_button_activate: "Ativar Botão"
 cmf_settings_action_bar_group_active_button_deactivate: "Botão Desativar"
