"""Shared rendering helpers for the standalone Court Positions mod."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Iterable

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = REPO_ROOT / "data" / "court_positions.yaml"
DATA_REL = "data/court_positions.yaml"


def load_positions() -> list[dict]:
    with DATA_FILE.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)
    positions = data.get("positions", [])
    if len(positions) != 6:
        raise ValueError("Court Positions must define exactly six launch positions")
    ids = [position["id"] for position in positions]
    if len(set(ids)) != len(ids):
        raise ValueError("Court position ids must be unique")
    for position in positions:
        if position["ability"] not in {"adm", "dip", "mil", "artist_skill"}:
            raise ValueError(f"Unsupported ability for {position['id']}")
    return positions


def header(script_rel: str) -> str:
    return (
        f"# @Generated by {script_rel}\n"
        f"#   Data:    {DATA_REL}\n"
        f"#   Regen:   conda run --no-capture-output -n eu5 python {script_rel}\n"
        "# Do not edit directly — modify the data file and re-run the generator.\n\n"
    )


def char_var(position: dict) -> str:
    return f"tv_court_{position['id']}_character"


def ability_var(position: dict) -> str:
    return f"tv_court_{position['id']}_ability"


def salary_var(position: dict) -> str:
    return f"tv_court_{position['id']}_salary"


def effect_modifier(position: dict) -> str:
    return f"tv_court_{position['id']}_effect"


def display_modifier(position: dict, ability: int) -> str:
    return f"tv_court_{position['id']}_display_{ability}"


def appointment_action(position: dict) -> str:
    return f"tv_court_appoint_{position['id']}"


def character_appointment_action(position: dict) -> str:
    return f"tv_court_appoint_{position['id']}_character"


def dismissal_action(position: dict) -> str:
    return f"tv_court_dismiss_{position['id']}"


def format_number(value: float) -> str:
    text = f"{value:.5f}".rstrip("0").rstrip(".")
    return text or "0"


def effect_value(position: dict, ability: int) -> str:
    return format_number(float(position["effect_at_100"]) * ability / 100)


def ability_value_lines(position: dict, holder_scope: str, indent: str) -> list[str]:
    if position["ability"] == "artist_skill":
        return [
            f"{indent}value = {{",
            f"{indent}\tvalue = {holder_scope}.artist_skill",
            f"{indent}\tmultiply = 100",
            f"{indent}}}",
        ]
    return [f"{indent}value = {holder_scope}.{position['ability']}"]


def character_eligibility_lines(position: dict, indent: str) -> list[str]:
    artist = "yes" if position["artist_only"] else "no"
    return [
        f"{indent}is_alive = yes",
        f"{indent}is_adult = yes",
        f"{indent}is_artist = {artist}",
        f"{indent}is_ruler = no",
        f"{indent}is_heir = no",
        f"{indent}is_consort = no",
        f"{indent}in_cabinet = no",
        f"{indent}is_general = no",
        f"{indent}is_admiral = no",
        f"{indent}is_explorer = no",
        f"{indent}is_loyal = yes",
        f"{indent}NOT = {{ has_character_modifier = busy_modifier }}",
    ]


def render_static_modifiers(positions: Iterable[dict], script_rel: str) -> str:
    blocks: list[str] = []
    for position in positions:
        blocks.append(
            f"{effect_modifier(position)} = {{\n"
            f"\t{position['modifier']} = {format_number(float(position['effect_at_100']))}\n"
            "}"
        )
        for ability in range(101):
            blocks.append(
                f"{display_modifier(position, ability)} = {{\n"
                f"\t{position['modifier']} = {effect_value(position, ability)}\n"
                "}"
            )
    return header(script_rel) + "\n\n".join(blocks) + "\n"


def _render_remove_effect(position: dict) -> str:
    return (
        f"tv_court_positions_remove_{position['id']}_effect = {{\n"
        f"\tremove_country_modifier = {effect_modifier(position)}\n"
        f"\tvar:{char_var(position)} ?= {{\n"
        "\t\tremove_character_modifier = busy_modifier\n"
        "\t}\n"
        f"\tremove_variable = {char_var(position)}\n"
        f"\tremove_variable = {ability_var(position)}\n"
        f"\tremove_variable = {salary_var(position)}\n"
        "}"
    )


def _render_refresh_effect(position: dict) -> str:
    pid = position["id"]
    country_scope = f"tv_court_{pid}_country"
    holder_scope = f"tv_court_{pid}_holder"
    ability_lines = ability_value_lines(position, f"scope:{holder_scope}", "\t\t\t\t")
    ability_block = "\n".join(ability_lines)
    return (
        f"tv_court_positions_refresh_{pid}_effect = {{\n"
        f"\tsave_scope_as = {country_scope}\n"
        f"\tremove_country_modifier = {effect_modifier(position)}\n"
        f"\tif = {{\n"
        f"\t\tlimit = {{ has_variable = {char_var(position)} }}\n"
        f"\t\tvar:{char_var(position)} ?= {{ save_scope_as = {holder_scope} }}\n"
        f"\t\tif = {{\n"
        f"\t\t\tlimit = {{ scope:{holder_scope} = {{ is_alive = yes }} }}\n"
        f"\t\t\tscope:{holder_scope} = {{\n"
        "\t\t\t\tadd_character_modifier = { modifier = busy_modifier years = -1 mode = add_and_extend }\n"
        "\t\t\t}\n"
        f"\t\t\tscope:{country_scope} = {{\n"
        f"\t\t\t\tset_variable = {{ name = {ability_var(position)}\n{ability_block}\n\t\t\t\t}}\n"
        f"\t\t\t\tclamp_variable = {{ name = {ability_var(position)} min = 0 max = 100 }}\n"
        f"\t\t\t\tset_variable = {{\n"
        f"\t\t\t\t\tname = {salary_var(position)}\n"
        "\t\t\t\t\tvalue = {\n"
        f"\t\t\t\t\t\tvalue = var:{ability_var(position)}\n"
        "\t\t\t\t\t\tdivide = 100\n"
        "\t\t\t\t\t\tmultiply = {\n"
        "\t\t\t\t\t\t\tvalue = 1\n"
        "\t\t\t\t\t\t\tadd = { value = country_economical_base multiply = 0.1 }\n"
        "\t\t\t\t\t\t}\n"
        "\t\t\t\t\t}\n"
        "\t\t\t\t}\n"
        f"\t\t\t\tadd_country_modifier = {{\n"
        f"\t\t\t\t\tmodifier = {effect_modifier(position)}\n"
        "\t\t\t\t\tdays = -1\n"
        "\t\t\t\t\tmode = replace\n"
        f"\t\t\t\t\tsize = {{ value = var:{ability_var(position)} divide = 100 }}\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n"
        "\t\t}\n"
        "\t\telse = {\n"
        f"\t\t\tscope:{country_scope} = {{ tv_court_positions_remove_{pid}_effect = yes }}\n"
        "\t\t}\n"
        "\t}\n"
        "\telse = {\n"
        f"\t\tset_variable = {{ name = {ability_var(position)} value = 0 }}\n"
        f"\t\tset_variable = {{ name = {salary_var(position)} value = 0 }}\n"
        "\t}\n"
        f"\tclear_saved_scope = {holder_scope}\n"
        f"\tclear_saved_scope = {country_scope}\n"
        "}"
    )


def _render_appoint_effect(position: dict) -> str:
    return (
        f"tv_court_positions_appoint_{position['id']}_effect = {{\n"
        f"\ttv_court_positions_remove_{position['id']}_effect = yes\n"
        f"\tset_variable = {{ name = {char_var(position)} value = scope:target }}\n"
        "\tscope:target = { add_character_modifier = { modifier = busy_modifier years = -1 mode = add_and_extend } }\n"
        f"\ttv_court_positions_refresh_{position['id']}_effect = yes\n"
        "}"
    )


def _render_direct_appoint_effect(position: dict) -> str:
    return (
        f"tv_court_positions_appoint_{position['id']}_direct_effect = {{\n"
        f"\ttv_court_positions_remove_{position['id']}_effect = yes\n"
        f"\tset_variable = {{ name = {char_var(position)} value = scope:recipient }}\n"
        "\tscope:recipient = { add_character_modifier = { modifier = busy_modifier years = -1 mode = add_and_extend } }\n"
        f"\ttv_court_positions_refresh_{position['id']}_effect = yes\n"
        "}"
    )


def render_scripted_effects(positions: Iterable[dict], script_rel: str) -> str:
    positions = list(positions)
    blocks: list[str] = []
    blocks.extend(_render_remove_effect(position) for position in positions)
    blocks.extend(_render_refresh_effect(position) for position in positions)
    blocks.extend(_render_appoint_effect(position) for position in positions)
    blocks.extend(_render_direct_appoint_effect(position) for position in positions)
    lines = [
        "tv_court_positions_refresh_all_effect = {",
        *[f"\ttv_court_positions_refresh_{position['id']}_effect = yes" for position in positions],
        "}",
        "",
        "tv_court_positions_initialize_country_effect = {",
        "\tset_variable = { name = tv_court_positions_initialized value = 1 }",
        *[f"\tif = {{ limit = {{ NOT = {{ has_variable = {ability_var(position)} }} }} set_variable = {{ name = {ability_var(position)} value = 0 }} }}" for position in positions],
        *[f"\tif = {{ limit = {{ NOT = {{ has_variable = {salary_var(position)} }} }} set_variable = {{ name = {salary_var(position)} value = 0 }} }}" for position in positions],
        "\ttv_court_positions_refresh_all_effect = yes",
        "}",
        "",
        "tv_court_positions_monthly_effect = {",
        "\ttv_court_positions_refresh_all_effect = yes",
    ]
    for position in positions:
        lines.extend([
            "\tif = {",
            f"\t\tlimit = {{ has_variable = {char_var(position)} }}",
            f"\t\tadd_gold = {{ value = var:{salary_var(position)} multiply = -1 }}",
            "\t}",
        ])
    lines.append("}")
    blocks.append("\n".join(lines))
    # Static, unreachable references retain every dynamic ShowModifierEffect target
    # in script scans as well as in the generated static-modifier file.
    ref_lines = ["tv_court_positions_display_modifier_static_reference_effect = {", "\tif = {", "\t\tlimit = { always = no }"]
    for position in positions:
        for ability in range(101):
            ref_lines.append(f"\t\tadd_country_modifier = {{ modifier = {display_modifier(position, ability)} days = 1 }}")
    ref_lines.extend(["\t}", "}"])
    blocks.append("\n".join(ref_lines))
    return header(script_rel) + "\n\n".join(blocks) + "\n"


def _render_appointment_action(position: dict) -> str:
    eligibility = "\n".join(character_eligibility_lines(position, "\t\t\t"))
    action = appointment_action(position)
    return (
        f"{action} = {{\n"
        "\ttype = owncountry\n"
        "\tsound = UI_action_religion_generic\n"
        "\tai_tick = monthly\n"
        "\tai_tick_frequency = 99999\n"
        "\tpotential = { scope:actor = { has_variable = tv_court_positions_initialized } }\n"
        "\tallow = { scope:actor = { always = yes } }\n"
        "\tselect_trigger = {\n"
        "\t\tlooking_for_a = character\n"
        "\t\tsource = actor\n"
        "\t\ttarget_flag = target\n"
        f"\t\tname = \"tv_court_select_{position['id']}\"\n"
        f"\t\tnone_available_msg_key = \"tv_court_no_{position['id']}_available\"\n"
        f"\t\tcolumn = {{ data = {'character_artist' if position['artist_only'] else 'character_info'} }}\n"
        "\t\tvisible = {\n"
        f"{eligibility}\n"
        "\t\t}\n"
        "\t}\n"
        "\teffect = {\n"
        "\t\tif = {\n"
        "\t\t\tlimit = { exists = scope:target }\n"
        f"\t\t\tscope:actor = {{ tv_court_positions_appoint_{position['id']}_effect = yes }}\n"
        "\t\t}\n"
        "\t}\n"
        "\tai_will_do = { add = -100 }\n"
        "}"
    )


def _render_direct_appointment_interaction(position: dict) -> str:
    """Render the native character-menu appointment interaction."""
    eligibility = "\n".join(character_eligibility_lines(position, "\t\t\t"))
    action = character_appointment_action(position)
    return (
        f"{action} = {{\n"
        "\tsound = UI_action_religion_generic\n"
        "\tmessage = yes\n"
        "\ton_own_nation = yes\n"
        "\tai_tick = never\n"
        "\tai_tick_frequency = 99999\n"
        "\tpotential = { scope:actor = { has_variable = tv_court_positions_initialized } }\n"
        "\tallow = { scope:actor = { always = yes } }\n"
        "\tselect_trigger = {\n"
        "\t\tlooking_for_a = character\n"
        "\t\tsource = actor\n"
        "\t\ttarget_flag = recipient\n"
        f"\t\tname = \"tv_court_select_{position['id']}\"\n"
        f"\t\tnone_available_msg_key = \"tv_court_no_{position['id']}_available\"\n"
        f"\t\tcolumn = {{ data = {'character_artist' if position['artist_only'] else 'character_info'} }}\n"
        "\t\tvisible = {\n"
        f"{eligibility}\n"
        "\t\t}\n"
        "\t}\n"
        "\teffect = {\n"
        "\t\tif = {\n"
        "\t\t\tlimit = { exists = scope:recipient }\n"
        f"\t\t\tscope:actor = {{ tv_court_positions_appoint_{position['id']}_direct_effect = yes }}\n"
        "\t\t}\n"
        "\t}\n"
        "\tai_will_do = { add = -100 }\n"
        "}"
    )


def _render_dismissal_action(position: dict) -> str:
    action = dismissal_action(position)
    return (
        f"{action} = {{\n"
        "\ttype = owncountry\n"
        "\tsound = UI_action_religion_generic\n"
        "\tai_tick = monthly\n"
        "\tai_tick_frequency = 99999\n"
        "\tpotential = { scope:actor = { has_variable = tv_court_positions_initialized } }\n"
        f"\tallow = {{ scope:actor = {{ has_variable = {char_var(position)} }} }}\n"
        "\teffect = {\n"
        f"\t\tscope:actor = {{ hidden_effect = {{ tv_court_positions_remove_{position['id']}_effect = yes }} }}\n"
        "\t}\n"
        "\tai_will_do = { add = -100 }\n"
        "}"
    )


def render_generic_actions(positions: Iterable[dict], script_rel: str) -> str:
    positions = list(positions)
    blocks = []
    for position in positions:
        blocks.append(_render_appointment_action(position))
        blocks.append(_render_dismissal_action(position))
    return header(script_rel) + "\n\n".join(blocks) + "\n"


def render_character_interactions(positions: Iterable[dict], script_rel: str) -> str:
    """Render direct appointment actions for the character lateral view/context menu."""
    return header(script_rel) + "\n\n".join(
        _render_direct_appointment_interaction(position) for position in positions
    ) + "\n"


def render_action_ai_list(positions: Iterable[dict], script_rel: str) -> str:
    actions = [
        action
        for position in positions
        for action in (appointment_action(position), dismissal_action(position))
    ]
    lines = [
        header(script_rel).rstrip(),
        "",
        "tv_court_positions_actions_list = {",
        "\tpotential = { has_variable = tv_court_positions_initialized }",
        "\tactions = {",
        *[f"\t\t{action}" for action in actions],
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_situation(positions: Iterable[dict], script_rel: str) -> str:
    _ = positions
    return header(script_rel) + (
        "tv_court_positions_situation = {\n"
        "\tmonthly_spawn_chance = monthly_spawn_chance_unique\n\n"
        "\tcan_start = { always = yes }\n"
        "\tcan_end = { always = no }\n"
        "\tvisible = { always = yes }\n\n"
        "\ton_start = {\n"
        "\t\thidden_effect = { every_country = { tv_court_positions_initialize_country_effect = yes } }\n"
        "\t}\n"
        "\ton_monthly = { }\n"
        "\ton_ended = { }\n"
        "}\n"
    )


def render_on_actions(positions: Iterable[dict], script_rel: str) -> str:
    positions = list(positions)
    death_lines = []
    for position in positions:
        death_lines.extend([
            "\tif = {",
            f"\t\tlimit = {{ var:{char_var(position)} ?= scope:target }}",
            f"\t\ttv_court_positions_remove_{position['id']}_effect = yes",
            "\t}",
        ])
    return header(script_rel) + (
        "tv_court_positions_initialize_on_game_start = {\n"
        "\teffect = { hidden_effect = { every_country = { tv_court_positions_initialize_country_effect = yes } } }\n"
        "}\n\n"
        "tv_court_positions_initialize_on_game_load = {\n"
        "\teffect = { hidden_effect = { every_country = { tv_court_positions_initialize_country_effect = yes } } }\n"
        "}\n\n"
        "tv_court_positions_monthly_pulse = {\n"
        "\teffect = { hidden_effect = { tv_court_positions_monthly_effect = yes } }\n"
        "}\n\n"
        "tv_court_positions_character_death = {\n"
        "\teffect = {\n"
        + "\n".join(death_lines)
        + "\n\t}\n}\n"
    )


def render_gui(positions: Iterable[dict], script_rel: str) -> str:
    card_blocks = "\n\n".join(_render_gui_card(position) for position in positions)
    return header(script_rel) + (
        "situation_panel = {\n"
        "\tblockoverride \"panel_header\" {\n"
        "\t\twindow_header_alt = {\n"
        "\t\t\tblockoverride \"header_text_object\" {\n"
        "\t\t\t\thbox = {\n"
        "\t\t\t\t\tspacing = 5\n"
        "\t\t\t\t\texpand = {}\n"
        "\t\t\t\t\ttext_single = {\n"
        "\t\t\t\t\t\talign = nobaseline\n"
        "\t\t\t\t\t\tusing = Font_Type_Headers\n"
        "\t\t\t\t\t\tusing = Font_Size_Big\n"
        "\t\t\t\t\t\tmaximumsize = { 390 -1 }\n"
        "\t\t\t\t\t\tautoresize = yes\n"
        "\t\t\t\t\t\tdefault_format = \"#header_titles\"\n"
        "\t\t\t\t\t\ttext = \"TV_COURT_POSITIONS_TITLE\"\n"
        "\t\t\t\t\t}\n"
        "\t\t\t\t\texpand = {}\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n"
        "\t\t}\n"
        "\t}\n"
        "\tblockoverride \"panel_content\" {\n"
        "\t\tscrollarea = {\n"
        "\t\t\tusing = layoutpolicy_expanding\n"
        "\t\t\tscrollbarpolicy_horizontal = always_off\n"
        "\t\t\tscrollbar_vertical = { using = Scrollbar_Vertical }\n"
        "\t\t\tscrollwidget = {\n"
        "\t\t\t\tvbox = {\n"
        "\t\t\t\t\tusing = layoutpolicy_expanding\n"
        "\t\t\t\t\tusing = bg_main_inner_notabs_alt\n"
        "\t\t\t\t\tusing = window_main_tabs_margin_alt\n"
        "\t\t\t\t\tspacing = 8\n"
        "\t\t\t\t\ttext_multi = { max_width = 610 autoresize = yes text = \"TV_COURT_POSITIONS_INTRO\" }\n"
        + card_blocks
        + "\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n}\n"
    )


def _render_gui_card(position: dict) -> str:
    pid = position["id"]
    player = "SituationView.GetPlayer.MakeScope"
    char = char_var(position)
    ability = ability_var(position)
    salary = salary_var(position)
    return (
        "\t\t\t\t\tsituation_card_common = {\n"
        "\t\t\t\t\t\tmaximumsize = { 620 -1 }\n"
        "\t\t\t\t\t\tblockoverride \"common_header\" {\n"
        f"\t\t\t\t\t\t\ttext_single = {{ layoutpolicy_horizontal = expanding text = \"TV_COURT_{pid.upper()}_TITLE\" align = center fontsize = 15 }}\n"
        "\t\t\t\t\t\t}\n"
        "\t\t\t\t\t\tblockoverride \"card_common_bottom_margin\" { margin = { 8 8 } }\n"
        "\t\t\t\t\t\tblockoverride \"common_bottom_content\" {\n"
        "\t\t\t\t\t\t\thbox = {\n"
        "\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding\n"
        "\t\t\t\t\t\t\t\tspacing = 8\n"
        "\t\t\t\t\t\t\t\twidget = {\n"
        "\t\t\t\t\t\t\t\t\tsize = { 76 92 }\n"
        "\t\t\t\t\t\t\t\t\tallow_outside = yes\n"
        "\t\t\t\t\t\t\t\t\tportrait_standard_head_button = {\n"
        "\t\t\t\t\t\t\t\t\t\tusing = character_portrait_bg\n"
        f"\t\t\t\t\t\t\t\t\t\tvisible = \"[{player}.GetVariable('{char}').IsSet]\"\n"
        "\t\t\t\t\t\t\t\t\t\tparentanchor = center\n"
        "\t\t\t\t\t\t\t\t\t\twidgetanchor = center\n"
        "\t\t\t\t\t\t\t\t\t\tsize = { 64 78 }\n"
        f"\t\t\t\t\t\t\t\t\t\tdatacontext = \"[{player}.GetVariable('{char}').GetCharacter]\"\n"
        "\t\t\t\t\t\t\t\t\t\ticon = { block \"character_frame_texture\" { texture = \"gfx/interface/component_decoration/character_frames/character_frame_1.dds\" } texture_density = 2 size = { 100% 100% } }\n"
        "\t\t\t\t\t\t\t\t\t}\n"
        f"\t\t\t\t\t\t\t\t\ttext_single = {{ visible = \"[Not({player}.GetVariable('{char}').IsSet)]\" size = {{ 76 92 }} raw_text = \"+\" fontsize = 32 align = center|nobaseline default_format = \"#yellow_titles\" }}\n"
        "\t\t\t\t\t\t\t\t}\n"
        "\t\t\t\t\t\t\t\tvbox = {\n"
        "\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding\n"
        "\t\t\t\t\t\t\t\t\tignoreinvisible = yes\n"
        f"\t\t\t\t\t\t\t\t\ttext_single = {{ visible = \"[{player}.GetVariable('{char}').IsSet]\" datacontext = \"[{player}.GetVariable('{char}').GetCharacter]\" text = \"[Character.GetShortNameWithNoTooltip]\" fontsize = 15 align = nobaseline }}\n"
        f"\t\t\t\t\t\t\t\t\ttext_single = {{ visible = \"[Not({player}.GetVariable('{char}').IsSet)]\" text = \"TV_COURT_POSITION_VACANT\" fontsize = 15 align = nobaseline }}\n"
        f"\t\t\t\t\t\t\t\t\ttext_single = {{ raw_text = \"[Localize('TV_COURT_ABILITY_LABEL')] [ToString_int32(FixedPointToInt({player}.GetVariable('{ability}').GetValue))] / 100   [Localize('TV_COURT_SALARY_LABEL')] [{player}.GetVariable('{salary}').GetValue|2]\" fontsize = 12 align = nobaseline }}\n"
        "\t\t\t\t\t\t\t\t\tTooltipStringPairList = {\n"
        "\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed\n"
        "\t\t\t\t\t\t\t\t\t\tmaximumsize = { 500 -1 }\n"
        "\t\t\t\t\t\t\t\t\t\tblockoverride \"tooltip_minimumsize\" { minimumsize = { 500 -1 } }\n"
        "\t\t\t\t\t\t\t\t\t\tblockoverride \"field_text_format\" { fontsize = 12 autoresize = yes max_width = 140 elide = right }\n"
        f"\t\t\t\t\t\t\t\t\t\ttextcontext = \"[ShowModifierEffect(Concatenate('tv_court_{pid}_display_', ToString_int32(FixedPointToInt({player}.GetVariable('{ability}').GetValue))))]\"\n"
        "\t\t\t\t\t\t\t\t\t}\n"
        "\t\t\t\t\t\t\t\t}\n"
        "\t\t\t\t\t\t\t}\n"
        f"\t\t\t\t\t\t\taction_button = {{ size = {{ 100% 100% }} alpha = 0 alwaystransparent = no using = action_button_common_template title = \"{appointment_action(position)}\" description = \"{appointment_action(position)}_desc\" actor = \"[SituationView.GetPlayer]\" left_action = {{ action_name = \"{appointment_action(position)}\" }} right_action = {{ action_name = \"{dismissal_action(position)}\" }} }}\n"
        "\t\t\t\t\t\t}\n"
        "\t\t\t\t\t}\n"
    )


def _action_localization_entries(position: dict, language: str) -> list[tuple[str, str]]:
    zh = language == "simp_chinese"
    name = position["name_zh"] if zh else position["name_en"]
    appoint = appointment_action(position)
    direct = character_appointment_action(position)
    dismiss = dismissal_action(position)
    suffix = "。" if zh else "."
    return [
        (appoint, f"任命{name}" if zh else f"Appoint {name}"),
        (f"{appoint}_desc", f"从本国合资格人物中任命{name}{suffix}" if zh else f"Choose an eligible character in our country to become the {name}."),
        (direct, f"任命为{name}" if zh else f"Appoint as {name}"),
        (f"{direct}_concept", "[character|e]"),
        (f"{direct}_act", f"${direct}$"),
        (f"{direct}_desc", f"该人物将担任{name}{suffix}" if zh else f"The character will serve as the {name}."),
        (f"{direct}_desc_specific", f"[recipient.GetName]将担任{name}{suffix}" if zh else f"[recipient.GetName] will serve as the {name}."),
        (f"{direct}_past", f"{name}已任命" if zh else f"{name} Appointed"),
        (f"{direct}_act_past", f"[SCOPE.sCharacter('recipient').GetName]已被任命为{name}{suffix}" if zh else f"[SCOPE.sCharacter('recipient').GetName] has been appointed as the {name}."),
        (dismiss, f"解任{name}" if zh else f"Dismiss {name}"),
        (f"{dismiss}_desc", f"解除当前{name}的职务{suffix}" if zh else f"Remove the current {name} from office."),
        (f"tv_court_select_{position['id']}", f"选择{name}" if zh else f"Select {name}"),
        (f"tv_court_no_{position['id']}_available", f"@trigger_no! 没有可担任{name}的合资格人物。" if zh else f"@trigger_no! No eligible character is available to serve as {name}."),
    ]


def _message_localization_entries(action: str, language: str) -> list[tuple[str, str]]:
    zh = language == "simp_chinese"
    return [
        (f"PERFORM_{action}_ACTION_SETUP", "执行宫廷职位操作。" if zh else "When we manage a Court Position."),
        (f"PERFORM_{action}_ACTION_LOG", "我们调整了一项宫廷职位。" if zh else "We changed a Court Position."),
        (f"PERFORM_{action}_ACTION_MAP", ""),
    ]


def render_localization(positions: Iterable[dict], script_rel: str, language: str) -> bytes:
    zh = language == "simp_chinese"
    header_key = "l_simp_chinese" if zh else "l_english"
    entries: list[tuple[str, str]] = [
        ("TV_COURT_POSITIONS_TITLE", "宫廷职位" if zh else "Court Positions"),
        ("TV_COURT_POSITIONS_INTRO", "左键卡片可任命或更换职位；右键卡片可解任。职位效果与薪水均随人物能力线性变化。" if zh else "Left-click a card to appoint or replace its holder; right-click to dismiss. Effects and salaries scale linearly with the holder's ability."),
        ("TV_COURT_POSITION_VACANT", "职位空缺" if zh else "Vacant Position"),
        ("TV_COURT_ABILITY_LABEL", "能力：" if zh else "Ability:"),
        ("TV_COURT_SALARY_LABEL", "月薪：" if zh else "Monthly Salary:"),
        ("TV_COURT_SALARY_FORMULA", "月薪 = 能力 / 100 × (1 + [economical_base|e] × 0.1)。" if zh else "Monthly salary = Ability / 100 × (1 + [economical_base|e] × 0.1)."),
    ]
    for position in positions:
        prefix = f"TV_COURT_{position['id'].upper()}"
        entries.extend([
            (f"{prefix}_TITLE", position["name_zh"] if zh else position["name_en"]),
            (f"STATIC_MODIFIER_NAME_{effect_modifier(position)}", position["name_zh"] if zh else position["name_en"]),
        ])
        for ability in range(101):
            entries.append((f"STATIC_MODIFIER_NAME_{display_modifier(position, ability)}", position["name_zh"] if zh else position["name_en"]))
        entries.extend(_action_localization_entries(position, language))
        for action in (appointment_action(position), dismissal_action(position)):
            entries.extend(_message_localization_entries(action, language))
    lines = [
        f"{header_key}:",
        f"# @Generated by {script_rel}",
        f"#   Data:    {DATA_REL}",
        f"#   Regen:   conda run --no-capture-output -n eu5 python {script_rel}",
        "# Do not edit directly — modify the data file and re-run the generator.",
        "",
    ]
    for key, value in entries:
        lines.append(f' {key}: "{value.replace(chr(34), chr(92) + chr(34))}"')
    return b"\xef\xbb\xbf" + ("\n".join(lines) + "\n").encode("utf-8")
