"""Shared rendering helpers for the standalone Court Positions mod."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Iterable

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = REPO_ROOT / "data" / "court_positions.yaml"
DATA_REL = "data/court_positions.yaml"

ABILITY_IDS = {"adm", "dip", "mil", "artist_skill"}
CARD_COLUMNS = 3
CARD_WIDTH = 160
CARD_HEIGHT = 240
CARD_SPACING = 10
GRID_MARGIN = 4
CARD_MARGIN = 4
CARD_CONTENT_SPACING = 2
TITLE_CARD_HEIGHT = 28
ROLE_FRAME_HEIGHT = 138
INFO_CARD_HEIGHT = 62
CARD_INNER_WIDTH = CARD_WIDTH - CARD_MARGIN * 2
INFO_CARD_MARGIN_X = 5
INFO_CARD_MARGIN_Y = 4
INFO_CARD_CONTENT_WIDTH = CARD_INNER_WIDTH - INFO_CARD_MARGIN_X * 2
TITLE_TEXT_WIDTH = 106
VACANT_PROMPT_WIDTH = CARD_INNER_WIDTH - 20
INFO_TEXT_WIDTH = INFO_CARD_CONTENT_WIDTH
MODIFIER_TOOLTIP_WIDTH = INFO_CARD_CONTENT_WIDTH
MODIFIER_TOOLTIP_ROW_HEIGHT = 17
MODIFIER_TOOLTIP_MARGIN = 2
MODIFIER_TOOLTIP_SPACING = 2
MODIFIER_TOOLTIP_TEXT_WIDTH = 96
ROLE_ACTION_BUTTON_SIZE = 24
ROLE_ACTION_SLOT_SIZE = 34
ROLE_ACTION_SPACING = 2
ROLE_ACTION_COUNT = 3
REPLACE_BUTTON_ICON_SIZE = 18
THEME_COLOR_TEXTURES = (
    "color_red_texture",
    "color_light_green_texture",
    "color_yellow_texture",
    "color_blue_texture",
    "color_purple_texture",
    "color_white_texture",
    "color_turquoise_texture",
    "color_bronze_texture",
    "color_mid_orange_texture",
)
ABILITY_BACKGROUND = {
    "adm": "gfx/interface/illustrations/cabinet/adm_cabinet.dds",
    "dip": "gfx/interface/illustrations/cabinet/dip_cabinet.dds",
    "mil": "gfx/interface/illustrations/cabinet/mil_cabinet.dds",
    "artist_skill": "gfx/interface/illustrations/cabinet/dip_cabinet.dds",
}


def load_positions() -> list[dict]:
    with DATA_FILE.open(encoding="utf-8-sig") as file:
        data = yaml.safe_load(file)
    positions = data.get("positions", [])
    if not positions:
        raise ValueError("Court Positions must define at least one position")
    ids = [position["id"] for position in positions]
    if len(set(ids)) != len(ids):
        raise ValueError("Court position ids must be unique")
    for position in positions:
        if position["ability"] not in ABILITY_IDS:
            raise ValueError(f"Unsupported ability for {position['id']}")
        for key in ("name_en", "name_zh", "icon", "description_en", "description_zh", "effect_en", "effect_zh"):
            if not position.get(key):
                raise ValueError(f"Court position {position['id']} is missing {key}")
    return positions


def header(script_rel: str) -> str:
    return (
        f"# @Generated by {script_rel}\n"
        f"#   Data:    {DATA_REL}\n"
        f"#   Regen:   python {script_rel}\n"
        "# Do not edit directly - modify the data file and re-run the generator.\n\n"
    )


def char_var(position: dict) -> str:
    return f"tv_court_{position['id']}_character"


def ability_var(position: dict) -> str:
    return f"tv_court_{position['id']}_ability"


def role_action_var(position: dict) -> str:
    return f"tv_court_{position['id']}_action"


def effect_modifier(position: dict) -> str:
    return f"tv_court_{position['id']}_effect"


def court_cost_auto_modifier(position: dict) -> str:
    return f"tv_court_{position['id']}_court_cost"


def display_modifier(position: dict, ability: int) -> str:
    return f"tv_court_{position['id']}_display_{ability}"


def appointment_action(position: dict) -> str:
    return f"tv_court_appoint_{position['id']}"


def replace_action(position: dict) -> str:
    return f"tv_court_replace_{position['id']}"


def character_appointment_action(position: dict) -> str:
    return f"tv_court_appoint_{position['id']}_character"


def dismissal_action(position: dict) -> str:
    return f"tv_court_dismiss_{position['id']}"


def role_action(position: dict, index: int) -> str:
    return f"tv_court_{position['id']}_select_action_{index}"


def is_physician(position: dict) -> bool:
    return position["id"] == "physician"


def loc_prefix(position: dict) -> str:
    return f"TV_COURT_{position['id'].upper()}"


def format_number(value: float) -> str:
    text = f"{value:.5f}".rstrip("0").rstrip(".")
    return text or "0"


def effect_value(position: dict, ability: int) -> str:
    return format_number(float(position["effect_at_100"]) * ability / 100)


def emit(lines: list[str], level: int, text: str = "") -> None:
    lines.append("\t" * level + text if text else "")


def ability_value_lines(position: dict, holder_scope: str, indent: str) -> list[str]:
    if position["ability"] == "artist_skill":
        return [
            f"{indent}value = {{",
            f"{indent}\tvalue = {holder_scope}.artist_skill",
            f"{indent}\tmultiply = 100",
            f"{indent}}}",
        ]
    return [f"{indent}value = {holder_scope}.{position['ability']}"]


def character_eligibility_lines(position: dict, indent: str) -> list[str]:
    artist = "yes" if position["artist_only"] else "no"
    return [
        f"{indent}is_alive = yes",
        f"{indent}is_adult = yes",
        f"{indent}is_artist = {artist}",
        f"{indent}is_ruler = no",
        f"{indent}is_heir = no",
        f"{indent}is_consort = no",
        f"{indent}in_cabinet = no",
        f"{indent}is_general = no",
        f"{indent}is_admiral = no",
        f"{indent}is_explorer = no",
        f"{indent}is_loyal = yes",
        f"{indent}NOT = {{ has_character_modifier = busy_modifier }}",
    ]


def render_static_modifiers(positions: Iterable[dict], script_rel: str) -> str:
    blocks: list[str] = []
    for position in positions:
        blocks.append(
            f"{effect_modifier(position)} = {{\n"
            f"\t{position['modifier']} = {format_number(float(position['effect_at_100']))}\n"
            "}"
        )
        for ability in range(101):
            blocks.append(
                f"{display_modifier(position, ability)} = {{\n"
                f"\t{position['modifier']} = {effect_value(position, ability)}\n"
                "}"
            )
        if is_physician(position):
            blocks.append(
                "tv_court_physician_disease_control_modifier = {\n"
                "\tlocal_disease_resistance = 0.20\n"
                "}"
            )
    return header(script_rel) + "\n\n".join(blocks) + "\n"


def render_auto_modifiers(positions: Iterable[dict], script_rel: str) -> str:
    blocks: list[str] = []
    for position in positions:
        blocks.append(
            f"{court_cost_auto_modifier(position)} = {{\n"
            "\tcategory = country\n"
            "\tpotential_trigger = {\n"
            f"\t\thas_variable = {char_var(position)}\n"
            f"\t\thas_variable = {ability_var(position)}\n"
            f"\t\tvar:{char_var(position)} ?= {{ is_alive = yes }}\n"
            "\t}\n"
            "\tscales_with = {\n"
            f"\t\tvalue = var:{ability_var(position)}\n"
            "\t}\n"
            "\tcourt_spending_efficiency = -0.001\n"
            "}"
        )
    return header(script_rel) + "\n\n".join(blocks) + "\n"


def _render_remove_effect(position: dict) -> str:
    if is_physician(position):
        return (
            "tv_court_positions_remove_physician_effect = {\n"
            "\tvar:tv_court_physician_character ?= {\n"
            "\t\tremove_character_modifier = tv_court_physician_effect\n"
            "\t\tremove_character_modifier = busy_modifier\n"
            "\t}\n"
            "\tvar:tv_court_physician_location ?= { remove_location_modifier = tv_court_physician_disease_control_modifier }\n"
            "\tremove_variable = tv_court_physician_character\n"
            "\tremove_variable = tv_court_physician_location\n"
            "\tset_variable = { name = tv_court_physician_ability value = 0 }\n"
            "\tset_variable = { name = tv_court_physician_action value = 0 }\n"
            "}"
        )
    return (
        f"tv_court_positions_remove_{position['id']}_effect = {{\n"
        f"\tremove_country_modifier = {effect_modifier(position)}\n"
        f"\tvar:{char_var(position)} ?= {{\n"
        "\t\tremove_character_modifier = busy_modifier\n"
        "\t}\n"
        f"\tremove_variable = {char_var(position)}\n"
        f"\tset_variable = {{ name = {ability_var(position)} value = 0 }}\n"
        f"\tset_variable = {{ name = {role_action_var(position)} value = 0 }}\n"
        "}"
    )


def _render_refresh_effect(position: dict) -> str:
    pid = position["id"]
    if is_physician(position):
        return (
            "tv_court_positions_refresh_physician_effect = {\n"
            "\tsave_scope_as = tv_court_physician_country\n"
            "\tvar:tv_court_physician_character ?= { remove_character_modifier = tv_court_physician_effect }\n"
            "\tvar:tv_court_physician_location ?= { remove_location_modifier = tv_court_physician_disease_control_modifier }\n"
            "\tif = {\n"
            "\t\tlimit = { has_variable = tv_court_physician_character }\n"
            "\t\tvar:tv_court_physician_character ?= { save_scope_as = tv_court_physician_holder }\n"
            "\t\tif = {\n"
            "\t\t\tlimit = { scope:tv_court_physician_holder = { is_alive = yes } }\n"
            "\t\t\tscope:tv_court_physician_country = {\n"
            "\t\t\t\tset_variable = { name = tv_court_physician_ability value = scope:tv_court_physician_holder.adm }\n"
            "\t\t\t\tclamp_variable = { name = tv_court_physician_ability min = 0 max = 100 }\n"
            "\t\t\t\tif = { limit = { OR = { NOT = { has_variable = tv_court_physician_action } var:tv_court_physician_action < 1 var:tv_court_physician_action > 3 } } set_variable = { name = tv_court_physician_action value = 1 } }\n"
            "\t\t\t\tif = {\n"
            "\t\t\t\t\tlimit = { var:tv_court_physician_action = 1 has_variable = tv_court_physician_location }\n"
            "\t\t\t\t\tvar:tv_court_physician_location ?= { add_location_modifier = { modifier = tv_court_physician_disease_control_modifier days = -1 mode = replace size = { value = var:tv_court_physician_ability divide = 100 } } }\n"
            "\t\t\t\t}\n"
            "\t\t\t}\n"
            "\t\t\tscope:tv_court_physician_holder = {\n"
            "\t\t\t\tadd_character_modifier = { modifier = busy_modifier years = -1 mode = add_and_extend }\n"
            "\t\t\t\tadd_character_modifier = { modifier = tv_court_physician_effect days = -1 mode = replace size = { value = scope:tv_court_physician_country.var:tv_court_physician_ability divide = 100 } }\n"
            "\t\t\t}\n"
            "\t\t}\n"
            "\t\telse = { scope:tv_court_physician_country = { tv_court_positions_remove_physician_effect = yes } }\n"
            "\t}\n"
            "\telse = { set_variable = { name = tv_court_physician_ability value = 0 } set_variable = { name = tv_court_physician_action value = 0 } }\n"
            "\tclear_saved_scope = tv_court_physician_holder\n"
            "\tclear_saved_scope = tv_court_physician_country\n"
            "}"
        )
    country_scope = f"tv_court_{pid}_country"
    holder_scope = f"tv_court_{pid}_holder"
    ability_lines = ability_value_lines(position, f"scope:{holder_scope}", "\t\t\t\t")
    ability_block = "\n".join(ability_lines)
    return (
        f"tv_court_positions_refresh_{pid}_effect = {{\n"
        f"\tsave_scope_as = {country_scope}\n"
        f"\tremove_country_modifier = {effect_modifier(position)}\n"
        "\tif = {\n"
        f"\t\tlimit = {{ has_variable = {char_var(position)} }}\n"
        f"\t\tvar:{char_var(position)} ?= {{ save_scope_as = {holder_scope} }}\n"
        "\t\tif = {\n"
        f"\t\t\tlimit = {{ scope:{holder_scope} = {{ is_alive = yes }} }}\n"
        f"\t\t\tscope:{holder_scope} = {{\n"
        "\t\t\t\tadd_character_modifier = { modifier = busy_modifier years = -1 mode = add_and_extend }\n"
        "\t\t\t}\n"
        f"\t\t\tscope:{country_scope} = {{\n"
        f"\t\t\t\tset_variable = {{ name = {ability_var(position)}\n{ability_block}\n\t\t\t\t}}\n"
        f"\t\t\t\tclamp_variable = {{ name = {ability_var(position)} min = 0 max = 100 }}\n"
        f"\t\t\t\tif = {{ limit = {{ OR = {{ NOT = {{ has_variable = {role_action_var(position)} }} var:{role_action_var(position)} < 1 var:{role_action_var(position)} > {ROLE_ACTION_COUNT} }} }} set_variable = {{ name = {role_action_var(position)} value = 1 }} }}\n"
        "\t\t\t\tadd_country_modifier = {\n"
        f"\t\t\t\t\tmodifier = {effect_modifier(position)}\n"
        "\t\t\t\t\tdays = -1\n"
        "\t\t\t\t\tmode = replace\n"
        f"\t\t\t\t\tsize = {{ value = var:{ability_var(position)} divide = 100 }}\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n"
        "\t\t}\n"
        "\t\telse = {\n"
        f"\t\t\tscope:{country_scope} = {{ tv_court_positions_remove_{pid}_effect = yes }}\n"
        "\t\t}\n"
        "\t}\n"
        "\telse = {\n"
        f"\t\tset_variable = {{ name = {ability_var(position)} value = 0 }}\n"
        f"\t\tset_variable = {{ name = {role_action_var(position)} value = 0 }}\n"
        "\t}\n"
        f"\tclear_saved_scope = {holder_scope}\n"
        f"\tclear_saved_scope = {country_scope}\n"
        "}"
    )


def _render_appoint_effect(position: dict) -> str:
    return (
        f"tv_court_positions_appoint_{position['id']}_effect = {{\n"
        f"\ttv_court_positions_remove_{position['id']}_effect = yes\n"
        f"\tset_variable = {{ name = {char_var(position)} value = scope:target }}\n"
        f"\tset_variable = {{ name = {role_action_var(position)} value = 1 }}\n"
        "\tscope:target = { add_character_modifier = { modifier = busy_modifier years = -1 mode = add_and_extend } }\n"
        f"\ttv_court_positions_refresh_{position['id']}_effect = yes\n"
        "}"
    )


def _render_direct_appoint_effect(position: dict) -> str:
    return (
        f"tv_court_positions_appoint_{position['id']}_direct_effect = {{\n"
        f"\ttv_court_positions_remove_{position['id']}_effect = yes\n"
        f"\tset_variable = {{ name = {char_var(position)} value = scope:recipient }}\n"
        f"\tset_variable = {{ name = {role_action_var(position)} value = 1 }}\n"
        "\tscope:recipient = { add_character_modifier = { modifier = busy_modifier years = -1 mode = add_and_extend } }\n"
        f"\ttv_court_positions_refresh_{position['id']}_effect = yes\n"
        "}"
    )


def render_scripted_effects(positions: Iterable[dict], script_rel: str) -> str:
    positions = list(positions)
    blocks: list[str] = []
    blocks.extend(_render_remove_effect(position) for position in positions)
    blocks.extend(_render_refresh_effect(position) for position in positions)
    blocks.extend(_render_appoint_effect(position) for position in positions)
    blocks.extend(_render_direct_appoint_effect(position) for position in positions)
    lines = [
        "tv_court_positions_refresh_all_effect = {",
        *[f"\ttv_court_positions_refresh_{position['id']}_effect = yes" for position in positions],
        "}",
        "",
        "tv_court_positions_initialize_country_effect = {",
        "\tset_variable = { name = tv_court_positions_initialized value = 1 }",
        *[
            f"\tif = {{ limit = {{ NOT = {{ has_variable = {ability_var(position)} }} }} set_variable = {{ name = {ability_var(position)} value = 0 }} }}"
            for position in positions
        ],
        *[
            f"\tif = {{ limit = {{ NOT = {{ has_variable = {role_action_var(position)} }} }} set_variable = {{ name = {role_action_var(position)} value = 0 }} }}"
            for position in positions
        ],
        "\ttv_court_positions_refresh_all_effect = yes",
        "}",
        "",
        "tv_court_positions_monthly_effect = {",
        "\ttv_court_positions_refresh_all_effect = yes",
        "\ttv_court_physician_disease_scan_effect = yes",
        "}",
        "",
        "tv_court_positions_yearly_effect = {",
        "\tif = {",
        "\t\tlimit = { has_variable = tv_court_physician_character var:tv_court_physician_character ?= { is_alive = yes } var:tv_court_physician_action = 2 }",
        "\t\trandom = { chance = 10 trigger_event_non_silently = { id = tv_court_physician.1 days = 1 } }",
        "\t}",
        "\tif = {",
        "\t\tlimit = { has_variable = tv_court_physician_character var:tv_court_physician_character ?= { is_alive = yes } var:tv_court_physician_action = 3 }",
        "\t\trandom = { chance = 20 trigger_event_non_silently = { id = tv_court_physician.2 days = 1 } }",
        "\t}",
        "}",
        "",
        "tv_court_physician_disease_scan_effect = {",
        "\tsave_scope_as = tv_court_physician_scan_country",
        "\trandom_character = {",
        "\t\tlimit = {",
        "\t\t\tis_alive = yes",
        "\t\t\tNOT = { has_variable = tv_court_physician_disease_notified }",
        "\t\t\tOR = { has_trait = sickly has_trait = smallpox_trait has_trait = bubonic_plague_trait }",
        "\t\t}",
        "\t\tif = {",
        "\t\t\tlimit = { NOT = { has_variable = tv_court_physician_disease_notified } }",
        "\t\t\tset_variable = { name = tv_court_physician_disease_notified value = 1 }",
        "\t\t\tsave_scope_as = tv_court_physician_candidate",
        "\t\t\tscope:tv_court_physician_scan_country = {",
        "\t\t\t\tset_variable = { name = tv_court_physician_pending_patient value = scope:tv_court_physician_candidate }",
        "\t\t\t\ttrigger_event_non_silently = { id = tv_court_physician.10 days = 1 }",
        "\t\t\t}",
        "\t\t\t}",
        "\t\t}",
        "\tevery_character = {",
        "\t\tlimit = {",
        "\t\t\tNOT = { OR = { has_trait = sickly has_trait = smallpox_trait has_trait = bubonic_plague_trait } }",
        "\t\t\thas_variable = tv_court_physician_disease_notified",
        "\t\t}",
        "\t\tremove_variable = tv_court_physician_disease_notified",
        "\t}",
        "\tclear_saved_scope = tv_court_physician_candidate",
        "\tclear_saved_scope = tv_court_physician_scan_country",
        "}",
    ]
    blocks.append("\n".join(lines))
    # Static, unreachable references retain every dynamic ShowModifierEffect target
    # in script scans as well as in the generated static-modifier file.
    ref_lines = ["tv_court_positions_display_modifier_static_reference_effect = {", "\tif = {", "\t\tlimit = { always = no }"]
    for position in positions:
        for ability in range(101):
            effect_target = "add_character_modifier" if is_physician(position) else "add_country_modifier"
            ref_lines.append(f"\t\t{effect_target} = {{ modifier = {display_modifier(position, ability)} days = 1 }}")
    ref_lines.extend(["\t}", "}"])
    blocks.append("\n".join(ref_lines))
    return header(script_rel) + "\n\n".join(blocks) + "\n"


def _render_position_select_action(position: dict, action: str, require_holder: bool) -> str:
    eligibility = "\n".join(character_eligibility_lines(position, "\t\t\t"))
    holder_condition = (
        f"\t\t\thas_variable = {char_var(position)}"
        if require_holder
        else f"\t\t\tNOT = {{ has_variable = {char_var(position)} }}"
    )
    return (
        f"{action} = {{\n"
        "\ttype = owncountry\n"
        "\tsound = UI_action_religion_generic\n"
        "\tai_tick = monthly\n"
        "\tai_tick_frequency = 99999\n"
        "\tpotential = { scope:actor = { has_variable = tv_court_positions_initialized } }\n"
        "\tallow = {\n"
        "\t\tscope:actor = {\n"
        f"{holder_condition}\n"
        "\t\t}\n"
        "\t}\n"
        "\tselect_trigger = {\n"
        "\t\tlooking_for_a = character\n"
        "\t\tsource = actor\n"
        "\t\ttarget_flag = target\n"
        f"\t\tname = \"tv_court_select_{position['id']}\"\n"
        f"\t\tnone_available_msg_key = \"tv_court_no_{position['id']}_available\"\n"
        f"\t\tcolumn = {{ data = {'character_artist' if position['artist_only'] else 'character_info'} }}\n"
        "\t\tvisible = {\n"
        f"{eligibility}\n"
        "\t\t}\n"
        "\t}\n"
        "\teffect = {\n"
        "\t\tif = {\n"
        "\t\t\tlimit = { exists = scope:target }\n"
        f"\t\t\tscope:actor = {{ hidden_effect = {{ tv_court_positions_appoint_{position['id']}_effect = yes }} }}\n"
        "\t\t}\n"
        "\t}\n"
        "\tai_will_do = { add = -100 }\n"
        "}"
    )


def _render_appointment_action(position: dict) -> str:
    return _render_position_select_action(position, appointment_action(position), require_holder=False)


def _render_replace_action(position: dict) -> str:
    return _render_position_select_action(position, replace_action(position), require_holder=True)


def _render_direct_appointment_interaction(position: dict) -> str:
    """Render the native character-menu appointment interaction."""
    eligibility = "\n".join(character_eligibility_lines(position, "\t\t\t"))
    action = character_appointment_action(position)
    return (
        f"{action} = {{\n"
        "\tsound = UI_action_religion_generic\n"
        "\tmessage = yes\n"
        "\ton_own_nation = yes\n"
        "\tai_tick = never\n"
        "\tai_tick_frequency = 99999\n"
        "\tpotential = { scope:actor = { has_variable = tv_court_positions_initialized } }\n"
        "\tallow = { scope:actor = { always = yes } }\n"
        "\tselect_trigger = {\n"
        "\t\tlooking_for_a = character\n"
        "\t\tsource = actor\n"
        "\t\ttarget_flag = recipient\n"
        f"\t\tname = \"tv_court_select_{position['id']}\"\n"
        f"\t\tnone_available_msg_key = \"tv_court_no_{position['id']}_available\"\n"
        f"\t\tcolumn = {{ data = {'character_artist' if position['artist_only'] else 'character_info'} }}\n"
        "\t\tvisible = {\n"
        f"{eligibility}\n"
        "\t\t}\n"
        "\t}\n"
        "\teffect = {\n"
        "\t\tif = {\n"
        "\t\t\tlimit = { exists = scope:recipient }\n"
        f"\t\t\tscope:actor = {{ hidden_effect = {{ tv_court_positions_appoint_{position['id']}_direct_effect = yes }} }}\n"
        "\t\t}\n"
        "\t}\n"
        "\tai_will_do = { add = -100 }\n"
        "}"
    )


def _render_dismissal_action(position: dict) -> str:
    action = dismissal_action(position)
    return (
        f"{action} = {{\n"
        "\ttype = owncountry\n"
        "\tsound = UI_action_religion_generic\n"
        "\tai_tick = monthly\n"
        "\tai_tick_frequency = 99999\n"
        "\tpotential = { scope:actor = { has_variable = tv_court_positions_initialized } }\n"
        f"\tallow = {{ scope:actor = {{ has_variable = {char_var(position)} }} }}\n"
        "\teffect = {\n"
        f"\t\tscope:actor = {{ hidden_effect = {{ tv_court_positions_remove_{position['id']}_effect = yes }} }}\n"
        "\t}\n"
        "\tai_will_do = { add = -100 }\n"
        "}"
    )


def _render_role_action(position: dict, index: int) -> str:
    action = role_action(position, index)
    if is_physician(position) and index == 1:
        return (
            f"{action} = {{\n"
            "\ttype = owncountry\n"
            "\tsound = UI_action_religion_generic\n"
            "\tai_tick = monthly\n"
            "\tai_tick_frequency = 99999\n"
            "\tpotential = { scope:actor = { has_variable = tv_court_positions_initialized } }\n"
            "\tallow = { scope:actor = { has_variable = tv_court_physician_character var:tv_court_physician_character ?= { is_alive = yes } } }\n"
            "\tselect_trigger = {\n"
            "\t\tlooking_for_a = location\n"
            "\t\tsource = actor\n"
            "\t\tinteraction_source_list = {\n"
            "\t\t\tscope:actor = { every_owned_location = { add_to_list = source } }\n"
            "\t\t}\n"
            "\t\ttarget_flag = target\n"
            "\t\tname = \"tv_court_select_physician_disease_control_location\"\n"
            "\t\tnone_available_msg_key = \"tv_court_no_physician_disease_control_location_available\"\n"
            "\t\tcolumn = { data = name }\n"
            "\t\tcolumn = { data = population }\n"
            "\t\tvisible = { owner ?= scope:actor }\n"
            "\t}\n"
            "\teffect = {\n"
            "\t\tif = {\n"
            "\t\t\tlimit = { exists = scope:target }\n"
            "\t\t\tscope:actor = {\n"
            "\t\t\t\tvar:tv_court_physician_location ?= { remove_location_modifier = tv_court_physician_disease_control_modifier }\n"
            "\t\t\t\tset_variable = { name = tv_court_physician_location value = scope:target }\n"
            "\t\t\t\tset_variable = { name = tv_court_physician_action value = 1 }\n"
            "\t\t\t\ttv_court_positions_refresh_physician_effect = yes\n"
            "\t\t\t}\n"
            "\t\t}\n"
            "\t}\n"
            "\tai_will_do = { add = -100 }\n"
            "}"
        )
    return (
        f"{action} = {{\n"
        "\ttype = owncountry\n"
        "\tsound = UI_action_religion_generic\n"
        "\tai_tick = monthly\n"
        "\tai_tick_frequency = 99999\n"
        "\tpotential = { scope:actor = { has_variable = tv_court_positions_initialized } }\n"
        "\tallow = {\n"
        "\t\tscope:actor = {\n"
        f"\t\t\thas_variable = {char_var(position)}\n"
        f"\t\t\tvar:{char_var(position)} ?= {{ is_alive = yes }}\n"
        "\t\t}\n"
        "\t}\n"
        "\teffect = {\n"
        f"\t\tscope:actor = {{ set_variable = {{ name = {role_action_var(position)} value = {index} }} {('tv_court_positions_refresh_physician_effect = yes' if is_physician(position) else '')} }}\n"
        "\t}\n"
        "\tai_will_do = { add = -100 }\n"
        "}"
    )


def render_generic_actions(positions: Iterable[dict], script_rel: str) -> str:
    positions = list(positions)
    blocks = []
    for position in positions:
        blocks.append(_render_appointment_action(position))
        blocks.append(_render_replace_action(position))
        blocks.append(_render_dismissal_action(position))
        for index in range(1, ROLE_ACTION_COUNT + 1):
            blocks.append(_render_role_action(position, index))
    return header(script_rel) + "\n\n".join(blocks) + "\n"


def render_character_interactions(positions: Iterable[dict], script_rel: str) -> str:
    """Render direct appointment actions for the character lateral view/context menu."""
    return header(script_rel) + "\n\n".join(
        _render_direct_appointment_interaction(position) for position in positions
    ) + "\n"


def render_action_ai_list(positions: Iterable[dict], script_rel: str) -> str:
    actions = []
    for position in positions:
        actions.extend((appointment_action(position), replace_action(position), dismissal_action(position)))
        actions.extend(role_action(position, index) for index in range(1, ROLE_ACTION_COUNT + 1))
    lines = [
        header(script_rel).rstrip(),
        "",
        "tv_court_positions_actions_list = {",
        "\tpotential = { has_variable = tv_court_positions_initialized }",
        "\tactions = {",
        *[f"\t\t{action}" for action in actions],
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_situation(positions: Iterable[dict], script_rel: str) -> str:
    _ = positions
    return header(script_rel) + (
        "tv_court_positions_situation = {\n"
        "\tmonthly_spawn_chance = monthly_spawn_chance_unique\n\n"
        "\tcan_start = { always = yes }\n"
        "\tcan_end = { always = no }\n"
        "\tvisible = { always = yes }\n\n"
        "\ton_start = {\n"
        "\t\thidden_effect = { every_country = { tv_court_positions_initialize_country_effect = yes } }\n"
        "\t}\n"
        "\ton_monthly = { }\n"
        "\ton_ended = { }\n"
        "}\n"
    )


def render_on_actions(positions: Iterable[dict], script_rel: str) -> str:
    positions = list(positions)
    death_lines = []
    for position in positions:
        death_lines.extend([
            "\tif = {",
            f"\t\tlimit = {{ var:{char_var(position)} ?= scope:target }}",
            f"\t\ttv_court_positions_remove_{position['id']}_effect = yes",
            "\t}",
        ])
    return header(script_rel) + (
        "tv_court_positions_initialize_on_game_start = {\n"
        "\teffect = { hidden_effect = { every_country = { tv_court_positions_initialize_country_effect = yes } } }\n"
        "}\n\n"
        "tv_court_positions_initialize_on_game_load = {\n"
        "\teffect = { hidden_effect = { every_country = { tv_court_positions_initialize_country_effect = yes } } }\n"
        "}\n\n"
        "tv_court_positions_monthly_pulse = {\n"
        "\teffect = { hidden_effect = { tv_court_positions_monthly_effect = yes } }\n"
        "}\n\n"
        "tv_court_positions_yearly_pulse = {\n"
        "\teffect = { hidden_effect = { tv_court_positions_yearly_effect = yes } }\n"
        "}\n\n"
        "tv_court_positions_character_death = {\n"
        "\teffect = {\n"
        + "\n".join(death_lines)
        + "\n\t}\n}\n"
    )


def render_gui(positions: Iterable[dict], script_rel: str) -> str:
    positions = list(positions)
    lines: list[str] = []
    emit(lines, 0, "situation_panel = {")
    emit(lines, 1, "# The vanilla situation panel owns the header, tabs, and scroll area.")
    emit(lines, 1, "# Situation-specific cards must be injected into this named content block.")
    emit(lines, 1, 'blockoverride "situation_panel_main_content" {')
    emit(lines, 2, "vbox = {")
    grid_width = CARD_COLUMNS * CARD_WIDTH + (CARD_COLUMNS - 1) * CARD_SPACING
    emit(lines, 3, "layoutpolicy_horizontal = fixed")
    emit(lines, 3, f"minimumsize = {{ {grid_width} -1 }}")
    emit(lines, 3, f"maximumsize = {{ {grid_width} -1 }}")
    emit(lines, 3, f"spacing = {CARD_SPACING}")
    emit(lines, 3, f"margin = {{ {GRID_MARGIN} {GRID_MARGIN} }}")
    for start in range(0, len(positions), CARD_COLUMNS):
        row = positions[start:start + CARD_COLUMNS]
        emit(lines, 3, "hbox = {")
        emit(lines, 4, "layoutpolicy_horizontal = fixed")
        emit(lines, 4, f"spacing = {CARD_SPACING}")
        for offset, position in enumerate(row):
            _append_gui_card(lines, 4, position, start + offset)
        for _ in range(CARD_COLUMNS - len(row)):
            emit(lines, 4, f"widget = {{ size = {{ {CARD_WIDTH} {CARD_HEIGHT} }} }}")
        emit(lines, 3, "}")
    emit(lines, 2, "}")
    emit(lines, 1, "}")
    emit(lines, 0, "}")
    return header(script_rel) + "\n".join(lines) + "\n"


def _append_gui_card(lines: list[str], level: int, position: dict, index: int) -> None:
    pid = position["id"]
    prefix = loc_prefix(position)
    theme = THEME_COLOR_TEXTURES[index % len(THEME_COLOR_TEXTURES)]
    player_scope = "SituationView.GetPlayer.MakeScope"
    player = "SituationView.GetPlayer"
    char = char_var(position)
    ability = ability_var(position)
    role = role_action_var(position)
    assigned = f"{player_scope}.GetVariable('{char}').IsSet"
    vacant = f"Not({assigned})"
    ability_value = f"ToString_int32(FixedPointToInt({player_scope}.GetVariable('{ability}').GetValue))"
    current_modifier = f"ShowModifierEffect(Concatenate('tv_court_{pid}_display_', {ability_value}))"

    emit(lines, level, "widget = {")
    emit(lines, level + 1, f"size = {{ {CARD_WIDTH} {CARD_HEIGHT} }}")
    emit(lines, level + 1, "layoutpolicy_horizontal = fixed")
    emit(lines, level + 1, "layoutpolicy_vertical = fixed")
    emit(lines, level + 1, "using = bg_paper_card")
    emit(lines, level + 1, "using = bg_cabinet_card_frame")
    emit(lines, level + 1, 'blockoverride "cabinet_card_frame_color" {')
    emit(lines, level + 2, f"using = {theme}")
    emit(lines, level + 1, "}")
    emit(lines, level + 1, "vbox = {")
    emit(lines, level + 2, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 2, "layoutpolicy_vertical = expanding")
    emit(lines, level + 2, f"margin = {{ {CARD_MARGIN} {CARD_MARGIN} }}")
    emit(lines, level + 2, f"spacing = {CARD_CONTENT_SPACING}")
    _append_gui_title_card(lines, level + 2, position, theme)
    _append_gui_role_frame(lines, level + 2, position, theme, assigned, vacant, player, player_scope, current_modifier)
    _append_gui_info_card(lines, level + 2, position, theme, assigned, ability_value, current_modifier)
    emit(lines, level + 1, "}")
    emit(lines, level, "}")


def _append_tooltip_text_block(lines: list[str], level: int, text_key: str, visible: str | None = None) -> None:
    emit(lines, level, "TooltipTextBlock = {")
    if visible is not None:
        emit(lines, level + 1, f'visible = "[{visible}]"')
    emit(lines, level + 1, 'blockoverride "text" {')
    emit(lines, level + 2, f'text = "{text_key}"')
    emit(lines, level + 1, "}")
    emit(lines, level, "}")


def _append_gui_title_card(lines: list[str], level: int, position: dict, theme: str) -> None:
    prefix = loc_prefix(position)
    pid = position["id"]
    emit(lines, level, "widget = {")
    emit(lines, level + 1, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 1, f"size = {{ -1 {TITLE_CARD_HEIGHT} }}")
    emit(lines, level + 1, "using = bg_dark_paper_card")
    emit(lines, level + 1, "using = bg_cabinet_inner_frame")
    emit(lines, level + 1, 'blockoverride "cabinet_card_frame_color" {')
    emit(lines, level + 2, f"using = {theme}")
    emit(lines, level + 1, "}")
    emit(lines, level + 1, "hbox = {")
    emit(lines, level + 2, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 2, "margin = { 5 2 }")
    emit(lines, level + 2, "spacing = 4")
    emit(lines, level + 2, "text_single = {")
    emit(lines, level + 3, "size = { 20 20 }")
    emit(lines, level + 3, f'raw_text = "{position["icon"]}"')
    emit(lines, level + 3, "fontsize = 15")
    emit(lines, level + 3, "align = center|nobaseline")
    emit(lines, level + 2, "}")
    emit(lines, level + 2, "text_single = {")
    emit(lines, level + 3, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 3, f"maximumsize = {{ {TITLE_TEXT_WIDTH} -1 }}")
    emit(lines, level + 3, "autoresize = yes")
    emit(lines, level + 3, "elide = right")
    emit(lines, level + 3, f'text = "{prefix}_TITLE"')
    emit(lines, level + 3, "fontsize = 11")
    emit(lines, level + 3, "align = left|nobaseline")
    emit(lines, level + 3, 'default_format = "#yellow_titles"')
    emit(lines, level + 2, "}")
    emit(lines, level + 1, "}")
    emit(lines, level, "}")


def _append_gui_role_frame(
    lines: list[str],
    level: int,
    position: dict,
    theme: str,
    assigned: str,
    vacant: str,
    player: str,
    player_scope: str,
    current_modifier: str,
) -> None:
    pid = position["id"]
    prefix = loc_prefix(position)
    char = char_var(position)
    emit(lines, level, "widget = {")
    emit(lines, level + 1, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 1, f"size = {{ -1 {ROLE_FRAME_HEIGHT} }}")
    emit(lines, level + 1, "allow_outside = yes")
    emit(lines, level + 1, "using = bg_dark_paper_card")
    emit(lines, level + 1, "using = bg_cabinet_inner_frame")
    emit(lines, level + 1, 'blockoverride "cabinet_card_frame_color" {')
    emit(lines, level + 2, f"using = {theme}")
    emit(lines, level + 1, "}")
    emit(lines, level + 1, "background = {")
    emit(lines, level + 2, f'texture = "{ABILITY_BACKGROUND[position["ability"]]}"')
    emit(lines, level + 2, "alpha = 0.28")
    emit(lines, level + 1, "}")
    _append_replace_action_button(lines, level + 1, position, theme, assigned, player, current_modifier)
    emit(lines, level + 1, "portrait_standard_full_body_center_button = {")
    emit(lines, level + 2, f'visible = "[{assigned}]"')
    emit(lines, level + 2, "parentanchor = bottom|hcenter")
    emit(lines, level + 2, "widgetanchor = bottom|hcenter")
    emit(lines, level + 2, "size = { 150 120 }")
    emit(lines, level + 2, "position = { 0 3 }")
    emit(lines, level + 2, "block \"character_right_visible\" { visible = yes }")
    emit(lines, level + 2, f'datacontext = "[{player_scope}.GetVariable(\'{char}\').GetCharacter]"')
    emit(lines, level + 1, "}")
    emit(lines, level + 1, "vbox = {")
    emit(lines, level + 2, f'visible = "[{vacant}]"')
    emit(lines, level + 2, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 2, "layoutpolicy_vertical = expanding")
    emit(lines, level + 2, "margin = { 10 12 }")
    emit(lines, level + 2, "expand = {}")
    emit(lines, level + 2, "text_single = {")
    emit(lines, level + 3, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 3, 'raw_text = "+"')
    emit(lines, level + 3, "fontsize = 38")
    emit(lines, level + 3, "align = center|nobaseline")
    emit(lines, level + 3, 'default_format = "#yellow_titles"')
    emit(lines, level + 2, "}")
    emit(lines, level + 2, "text_multi = {")
    emit(lines, level + 3, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 3, f"max_width = {VACANT_PROMPT_WIDTH}")
    emit(lines, level + 3, f"minimumsize = {{ {VACANT_PROMPT_WIDTH} -1 }}")
    emit(lines, level + 3, "autoresize = yes")
    emit(lines, level + 3, f'text = "{prefix}_VACANT_PROMPT"')
    emit(lines, level + 3, "fontsize = 12")
    emit(lines, level + 3, "align = center")
    emit(lines, level + 2, "}")
    emit(lines, level + 2, "expand = {}")
    emit(lines, level + 1, "}")
    _append_appoint_action_overlay(lines, level + 1, position, vacant, player)
    _append_role_action_buttons(lines, level + 1, position, theme, assigned, player_scope, player)
    emit(lines, level, "}")


def _append_action_button_tooltip(
    lines: list[str],
    level: int,
    position: dict,
    current_modifier: str | None = None,
    current_visible: str | None = None,
) -> None:
    prefix = loc_prefix(position)
    emit(lines, level, "tooltipwidget = {")
    emit(lines, level + 1, "ContextualTooltipType = {")
    emit(lines, level + 2, 'blockoverride "title_text" {')
    emit(lines, level + 3, "text = \"[Select_CString(PdxGuiWidget.HasTooltipMetaTitle, PdxGuiWidget.GetTooltipMetaTitle, UIAction.GetTitle)]\"")
    emit(lines, level + 2, "}")
    emit(lines, level + 2, 'blockoverride "tooltip_content" {')
    emit(lines, level + 3, "using = action_tooltip_inner_content")
    emit(lines, level + 2, "}")
    emit(lines, level + 2, 'blockoverride "extra_tooltip_content" {')
    emit(lines, level + 3, 'datacontext = "[SituationView.GetPlayer]"')
    _append_tooltip_text_block(lines, level + 3, f"{prefix}_DESC")
    _append_tooltip_text_block(lines, level + 3, f"{prefix}_ABILITY_TOOLTIP")
    _append_tooltip_text_block(lines, level + 3, "TV_COURT_TOOLTIP_EFFECT_AT_100")
    emit(lines, level + 3, "TooltipStringPairList = {")
    emit(lines, level + 4, "layoutpolicy_horizontal = fixed")
    emit(lines, level + 4, "maximumsize = { 400 -1 }")
    emit(lines, level + 4, f'textcontext = "[ShowModifierEffect(\'{display_modifier(position, 100)}\')]"')
    emit(lines, level + 3, "}")
    if current_modifier is not None and current_visible is not None:
        _append_tooltip_text_block(lines, level + 3, "TV_COURT_TOOLTIP_CURRENT_EFFECT", current_visible)
        emit(lines, level + 3, "TooltipStringPairList = {")
        emit(lines, level + 4, f'visible = "[{current_visible}]"')
        emit(lines, level + 4, "layoutpolicy_horizontal = fixed")
        emit(lines, level + 4, "maximumsize = { 400 -1 }")
        emit(lines, level + 4, f'textcontext = "[{current_modifier}]"')
        emit(lines, level + 3, "}")
        _append_tooltip_text_block(lines, level + 3, "TV_COURT_TOOLTIP_COURT_COST", current_visible)
    emit(lines, level + 2, "}")
    emit(lines, level + 1, "}")
    emit(lines, level, "}")


def _append_assignment_action_button(
    lines: list[str],
    level: int,
    position: dict,
    visible: str,
    player: str,
    action: str,
    right_action: str | None = None,
    current_modifier: str | None = None,
    current_visible: str | None = None,
) -> None:
    emit(lines, level, "action_button = {")
    emit(lines, level + 1, f'visible = "[{visible}]"')
    emit(lines, level + 1, "parentanchor = center")
    emit(lines, level + 1, "widgetanchor = center")
    emit(lines, level + 1, "size = { 100% 100% }")
    emit(lines, level + 1, "alpha = 0")
    emit(lines, level + 1, "alwaystransparent = no")
    emit(lines, level + 1, "using = action_button_common_template")
    emit(lines, level + 1, f'title = "{action}"')
    emit(lines, level + 1, f'description = "{action}_desc"')
    emit(lines, level + 1, f'actor = "[{player}]"')
    emit(lines, level + 1, f'left_action = {{ action_name = "{action}" }}')
    if right_action is not None:
        emit(lines, level + 1, f'right_action = {{ action_name = "{right_action}" }}')
    _append_action_button_tooltip(lines, level + 1, position, current_modifier, current_visible)
    emit(lines, level, "}")


def _append_appoint_action_overlay(
    lines: list[str],
    level: int,
    position: dict,
    visible: str,
    player: str,
) -> None:
    _append_assignment_action_button(lines, level, position, visible, player, appointment_action(position))


def _append_replace_action_button(
    lines: list[str],
    level: int,
    position: dict,
    theme: str,
    visible: str,
    player: str,
    current_modifier: str,
) -> None:
    action = replace_action(position)
    dismiss = dismissal_action(position)
    slot_x = CARD_INNER_WIDTH - ROLE_ACTION_SLOT_SIZE
    button_offset = (ROLE_ACTION_SLOT_SIZE - ROLE_ACTION_BUTTON_SIZE) // 2
    icon_offset = (ROLE_ACTION_BUTTON_SIZE - REPLACE_BUTTON_ICON_SIZE) // 2
    emit(lines, level, "widget = {")
    emit(lines, level + 1, f'visible = "[{visible}]"')
    emit(lines, level + 1, f"position = {{ {slot_x} 0 }}")
    emit(lines, level + 1, f"size = {{ {ROLE_ACTION_SLOT_SIZE} {ROLE_ACTION_SLOT_SIZE} }}")
    emit(lines, level + 1, "icon = {")
    emit(lines, level + 2, f"size = {{ {ROLE_ACTION_SLOT_SIZE} {ROLE_ACTION_SLOT_SIZE} }}")
    emit(lines, level + 2, "position = { 0 0 }")
    emit(lines, level + 2, 'texture = "gfx/interface/component_tiles/hud_corners/circle_progress_bg.dds"')
    emit(lines, level + 2, "modify_texture = {")
    emit(lines, level + 3, f"using = {theme}")
    emit(lines, level + 2, "}")
    emit(lines, level + 2, "alpha = 0.72")
    emit(lines, level + 1, "}")
    emit(lines, level + 1, "widget = {")
    emit(lines, level + 2, f"size = {{ {ROLE_ACTION_BUTTON_SIZE} {ROLE_ACTION_BUTTON_SIZE} }}")
    emit(lines, level + 2, f"position = {{ {button_offset} {button_offset} }}")
    emit(lines, level + 2, "using = bg_circle_piechart_big")
    emit(lines, level + 2, "icon = {")
    emit(lines, level + 3, f"size = {{ {REPLACE_BUTTON_ICON_SIZE} {REPLACE_BUTTON_ICON_SIZE} }}")
    emit(lines, level + 3, f"position = {{ {icon_offset} {icon_offset} }}")
    emit(lines, level + 3, 'texture = "gfx/interface/buttons/flats/replace.dds"')
    emit(lines, level + 3, "modify_texture = {")
    emit(lines, level + 4, "using = color_new_gold_texture")
    emit(lines, level + 4, "blend_mode = add")
    emit(lines, level + 3, "}")
    emit(lines, level + 3, "glow = {")
    emit(lines, level + 4, 'name = "drop_shadow"')
    emit(lines, level + 4, "glow_radius = 3")
    emit(lines, level + 4, "color = { 0.0 0.0 0.0 1.0 }")
    emit(lines, level + 4, "alpha = 0.8")
    emit(lines, level + 3, "}")
    emit(lines, level + 2, "}")
    emit(lines, level + 1, "}")
    emit(lines, level + 1, "action_button = {")
    emit(lines, level + 2, f"size = {{ {ROLE_ACTION_BUTTON_SIZE} {ROLE_ACTION_BUTTON_SIZE} }}")
    emit(lines, level + 2, f"position = {{ {button_offset} {button_offset} }}")
    emit(lines, level + 2, "alpha = 0")
    emit(lines, level + 2, "alwaystransparent = no")
    emit(lines, level + 2, "using = action_button_common_template")
    emit(lines, level + 2, f'title = "{action}"')
    emit(lines, level + 2, f'description = "{action}_desc"')
    emit(lines, level + 2, f'actor = "[{player}]"')
    emit(lines, level + 2, f'left_action = {{ action_name = "{action}" }}')
    emit(lines, level + 2, f'right_action = {{ action_name = "{dismiss}" }}')
    _append_action_button_tooltip(lines, level + 2, position, current_modifier, visible)
    emit(lines, level + 1, "}")
    emit(lines, level, "}")


def _append_role_action_buttons(
    lines: list[str],
    level: int,
    position: dict,
    theme: str,
    assigned: str,
    player_scope: str,
    player: str,
) -> None:
    role = role_action_var(position)
    emit(lines, level, "widget = {")
    emit(lines, level + 1, f'visible = "[{assigned}]"')
    emit(lines, level + 1, "position = { 0 0 }")
    emit(lines, level + 1, f"size = {{ {ROLE_ACTION_SLOT_SIZE} {ROLE_ACTION_COUNT * ROLE_ACTION_SLOT_SIZE + (ROLE_ACTION_COUNT - 1) * ROLE_ACTION_SPACING} }}")
    for index, label in enumerate(("I", "II", "III"), start=1):
        selected = f"EqualTo_CFixedPoint({player_scope}.GetVariable('{role}').GetValue, '(CFixedPoint){index}.0')"
        action = role_action(position, index)
        button_offset = (ROLE_ACTION_SLOT_SIZE - ROLE_ACTION_BUTTON_SIZE) // 2
        slot_y = (index - 1) * (ROLE_ACTION_SLOT_SIZE + ROLE_ACTION_SPACING)
        emit(lines, level + 1, "widget = {")
        emit(lines, level + 2, f"size = {{ {ROLE_ACTION_SLOT_SIZE} {ROLE_ACTION_SLOT_SIZE} }}")
        emit(lines, level + 2, f"position = {{ 0 {slot_y} }}")
        emit(lines, level + 2, "icon = {")
        emit(lines, level + 3, f'visible = "[{selected}]"')
        emit(lines, level + 3, f"size = {{ {ROLE_ACTION_SLOT_SIZE} {ROLE_ACTION_SLOT_SIZE} }}")
        emit(lines, level + 3, "position = { 0 0 }")
        emit(lines, level + 3, 'texture = "gfx/interface/component_tiles/hud_corners/circle_progress_bg.dds"')
        emit(lines, level + 3, "modify_texture = {")
        emit(lines, level + 4, f"using = {theme}")
        emit(lines, level + 3, "}")
        emit(lines, level + 3, "alpha = 0.95")
        emit(lines, level + 2, "}")
        emit(lines, level + 2, "widget = {")
        emit(lines, level + 3, f"size = {{ {ROLE_ACTION_BUTTON_SIZE} {ROLE_ACTION_BUTTON_SIZE} }}")
        emit(lines, level + 3, f"position = {{ {button_offset} {button_offset} }}")
        emit(lines, level + 3, "using = bg_circle_piechart_big")
        emit(lines, level + 3, "text_single = {")
        emit(lines, level + 4, f"size = {{ {ROLE_ACTION_BUTTON_SIZE} {ROLE_ACTION_BUTTON_SIZE} }}")
        emit(lines, level + 4, f'raw_text = "{label}"')
        emit(lines, level + 4, "fontsize = 8")
        emit(lines, level + 4, "fontsize_min = 7")
        emit(lines, level + 4, "align = center|nobaseline")
        emit(lines, level + 4, 'default_format = "#yellow_titles"')
        emit(lines, level + 3, "}")
        emit(lines, level + 2, "}")
        emit(lines, level + 2, "action_button = {")
        emit(lines, level + 3, f"size = {{ {ROLE_ACTION_BUTTON_SIZE} {ROLE_ACTION_BUTTON_SIZE} }}")
        emit(lines, level + 3, f"position = {{ {button_offset} {button_offset} }}")
        emit(lines, level + 3, "alpha = 0")
        emit(lines, level + 3, "alwaystransparent = no")
        emit(lines, level + 3, "using = action_button_common_template")
        emit(lines, level + 3, f'title = "{action}"')
        emit(lines, level + 3, f'description = "{action}_desc"')
        emit(lines, level + 3, f'actor = "[{player}]"')
        emit(lines, level + 3, f'left_action = {{ action_name = "{action}" }}')
        emit(lines, level + 2, "}")
        emit(lines, level + 1, "}")
    emit(lines, level, "}")


def _append_gui_info_card(
    lines: list[str],
    level: int,
    position: dict,
    theme: str,
    assigned: str,
    ability_value: str,
    current_modifier: str,
) -> None:
    prefix = loc_prefix(position)
    emit(lines, level, "widget = {")
    emit(lines, level + 1, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 1, f"size = {{ -1 {INFO_CARD_HEIGHT} }}")
    emit(lines, level + 1, "using = bg_dark_paper_card")
    emit(lines, level + 1, "using = bg_cabinet_inner_frame")
    emit(lines, level + 1, 'blockoverride "cabinet_card_frame_color" {')
    emit(lines, level + 2, f"using = {theme}")
    emit(lines, level + 1, "}")
    emit(lines, level + 1, "vbox = {")
    emit(lines, level + 2, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 2, "layoutpolicy_vertical = expanding")
    emit(lines, level + 2, f"margin = {{ {INFO_CARD_MARGIN_X} {INFO_CARD_MARGIN_Y} }}")
    emit(lines, level + 2, "spacing = 1")
    emit(lines, level + 2, "text_single = {")
    emit(lines, level + 3, f'visible = "[{assigned}]"')
    emit(lines, level + 3, f'datacontext = "[SituationView.GetPlayer.MakeScope.GetVariable(\'{char_var(position)}\').GetCharacter]"')
    emit(lines, level + 3, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 3, f"maximumsize = {{ {INFO_TEXT_WIDTH} 16 }}")
    emit(lines, level + 3, "autoresize = yes")
    emit(lines, level + 3, "elide = right")
    emit(lines, level + 3, f'text = "[Localize(\'{prefix}_TITLE\')] [Character.GetNameWithNoTooltip]"')
    emit(lines, level + 3, "fontsize = 11")
    emit(lines, level + 3, "align = left|nobaseline")
    emit(lines, level + 3, 'default_format = "#yellow_titles"')
    emit(lines, level + 2, "}")
    emit(lines, level + 2, "text_single = {")
    emit(lines, level + 3, f'visible = "[Not({assigned})]"')
    emit(lines, level + 3, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 3, 'text = "TV_COURT_POSITION_VACANT"')
    emit(lines, level + 3, "fontsize = 12")
    emit(lines, level + 3, "align = center|nobaseline")
    emit(lines, level + 2, "}")
    character_context = f"SituationView.GetPlayer.MakeScope.GetVariable('{char_var(position)}').GetCharacter"
    _append_ability_row(lines, level + 2, assigned, character_context)
    emit(lines, level + 2, "TooltipStringPairList = {")
    emit(lines, level + 3, f'visible = "[{assigned}]"')
    emit(lines, level + 3, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 3, f"maximumsize = {{ {MODIFIER_TOOLTIP_WIDTH} {MODIFIER_TOOLTIP_ROW_HEIGHT} }}")
    emit(lines, level + 3, f'blockoverride "tooltip_minimumsize" {{ minimumsize = {{ {MODIFIER_TOOLTIP_WIDTH} -1 }} }}')
    emit(lines, level + 3, f'blockoverride "row_size" {{ maximumsize = {{ -1 {MODIFIER_TOOLTIP_ROW_HEIGHT} }} minimumsize = {{ -1 {MODIFIER_TOOLTIP_ROW_HEIGHT} }} }}')
    emit(lines, level + 3, 'blockoverride "field_margin" {}')
    emit(lines, level + 3, 'blockoverride "field_content" {')
    emit(lines, level + 4, f'blockoverride "table_field_margin" {{ margin = {{ {MODIFIER_TOOLTIP_MARGIN} 0 }} }}')
    emit(lines, level + 4, f"spacing = {MODIFIER_TOOLTIP_SPACING}")
    emit(lines, level + 3, "}")
    emit(lines, level + 3, f'blockoverride "field_text_format" {{ fontsize = 9 autoresize = yes max_width = {MODIFIER_TOOLTIP_TEXT_WIDTH} elide = right }}')
    emit(lines, level + 3, f'textcontext = "[{current_modifier}]"')
    emit(lines, level + 2, "}")
    emit(lines, level + 1, "}")
    emit(lines, level, "}")


def _append_ability_row(lines: list[str], level: int, assigned: str, character_context: str) -> None:
    emit(lines, level, "hbox = {")
    emit(lines, level + 1, f'visible = "[{assigned}]"')
    emit(lines, level + 1, "layoutpolicy_horizontal = expanding")
    emit(lines, level + 1, "spacing = 4")
    emit(lines, level + 1, f'datacontext = "[{character_context}]"')
    for ability, icon in (("adm", "icon_adm_alt"), ("dip", "icon_dip_alt"), ("mil", "icon_mil_alt")):
        emit(lines, level + 1, "hbox = {")
        emit(lines, level + 2, "spacing = 2")
        emit(lines, level + 2, "icon = {")
        emit(lines, level + 3, "size = { 14 14 }")
        emit(lines, level + 3, f"using = {icon}")
        emit(lines, level + 2, "}")
        emit(lines, level + 2, "text_single = {")
        emit(lines, level + 3, "size = { 19 14 }")
        emit(lines, level + 3, f'text = "[Character.GetAbility(\'{ability}\')]"')
        emit(lines, level + 3, "fontsize = 10")
        emit(lines, level + 3, "align = left|nobaseline")
        emit(lines, level + 2, "}")
        emit(lines, level + 1, "}")
    emit(lines, level, "}")


def _action_localization_entries(position: dict, language: str) -> list[tuple[str, str]]:
    zh = language == "simp_chinese"
    name = position["name_zh"] if zh else position["name_en"]
    appoint = appointment_action(position)
    replace = replace_action(position)
    direct = character_appointment_action(position)
    dismiss = dismissal_action(position)
    suffix = "。" if zh else "."
    entries = [
        (appoint, f"任命{name}" if zh else f"Appoint {name}"),
        (f"{appoint}_desc", f"从本国合资格人物中任命一位{name}{suffix}" if zh else f"Choose an eligible character in our country to become the {name}."),
        (replace, f"替换{name}" if zh else f"Replace {name}"),
        (f"{replace}_desc", f"选择一位合资格人物替换当前{name}{suffix}" if zh else f"Choose an eligible character to replace the current {name}."),
        (direct, f"任命为{name}" if zh else f"Appoint as {name}"),
        (f"{direct}_concept", "[character|e]"),
        (f"{direct}_act", f"${direct}$"),
        (f"{direct}_desc", f"该人物将担任{name}{suffix}" if zh else f"The character will serve as the {name}."),
        (f"{direct}_desc_specific", f"[recipient.GetName]将担任{name}{suffix}" if zh else f"[recipient.GetName] will serve as the {name}."),
        (f"{direct}_past", f"{name}已任命" if zh else f"{name} Appointed"),
        (f"{direct}_act_past", f"[SCOPE.sCharacter('recipient').GetName]已被任命为{name}{suffix}" if zh else f"[SCOPE.sCharacter('recipient').GetName] has been appointed as the {name}."),
        (dismiss, f"撤销{name}" if zh else f"Dismiss {name}"),
        (f"{dismiss}_desc", f"撤销当前{name}的任命{suffix}" if zh else f"Remove the current {name} from office."),
        (f"tv_court_select_{position['id']}", f"选择{name}" if zh else f"Select {name}"),
        (f"tv_court_no_{position['id']}_available", f"@trigger_no! 没有可担任{name}的合资格人物。" if zh else f"@trigger_no! No eligible character is available to serve as {name}."),
    ]
    for index in range(1, ROLE_ACTION_COUNT + 1):
        action = role_action(position, index)
        if is_physician(position):
            physician_action_text = {
                1: (
                    "控制疫病" if zh else "Disease Control",
                    "选择一个本国地点，由宫廷医生根据行政能力为当地提供至多20%本地疫病抗性。"
                    if zh
                    else "Select an owned location. The Court Physician provides up to 20% local disease resistance there, scaling with administrative skill.",
                ),
                2: (
                    "推进研究" if zh else "Advance Medical Research",
                    "宫廷医生将专注于医学研究。每年有10%概率触发医学研究推进事件：可直接获得5点研究进度，或支付规模为3的金钱获得10点研究进度。"
                    if zh
                    else "The Court Physician focuses on medical research. Each year there is a 10% chance of an event granting 5 research progress, or 10 research progress for a scale 3 gold payment.",
                ),
                3: (
                    "提升技能" if zh else "Improve Medical Skill",
                    "宫廷医生将专注于精进医术。每年有20%概率触发医术精进事件：可直接获得5点行政能力，或支付规模为1的金钱获得10点行政能力。"
                    if zh
                    else "The Court Physician focuses on improving medical skill. Each year there is a 20% chance of an event granting 5 administrative skill, or 10 administrative skill for a scale 1 gold payment.",
                ),
            }
            action_title, action_desc = physician_action_text[index]
        else:
            action_title = f"{name}行动 {index}" if zh else f"{name} Action {index}"
            action_desc = f"将当前{name}切换至行动 {index}{suffix}" if zh else f"Switch the current {name} to action {index}."
        entries.extend([
            (action, action_title),
            (f"{action}_desc", action_desc),
        ])
        if is_physician(position) and index == 1:
            entries.extend([
                (
                    "tv_court_select_physician_disease_control_location",
                    "选择控制疫病地点" if zh else "Select a location for disease control",
                ),
                (
                    "tv_court_no_physician_disease_control_location_available",
                    "@trigger_no! 没有可控制疫病的所属地点。" if zh else "@trigger_no! No owned location is available for disease control.",
                ),
            ])
    return entries


def _message_localization_entries(action: str, language: str) -> list[tuple[str, str]]:
    zh = language == "simp_chinese"
    return [
        (f"PERFORM_{action}_ACTION_SETUP", "执行宫廷职位操作。" if zh else "When we manage a Court Position."),
        (f"PERFORM_{action}_ACTION_LOG", "我们调整了一项宫廷职位。" if zh else "We changed a Court Position."),
        (f"PERFORM_{action}_ACTION_MAP", ""),
    ]


def render_localization(positions: Iterable[dict], script_rel: str, language: str) -> bytes:
    positions = list(positions)
    zh = language == "simp_chinese"
    header_key = "l_simp_chinese" if zh else "l_english"
    entries: list[tuple[str, str]] = [
        ("TV_COURT_POSITIONS_TITLE", "宫廷职位" if zh else "Court Positions"),
        ("tv_court_positions_situation", "宫廷职位" if zh else "Court Positions"),
        (
            "tv_court_positions_situation_desc",
            "任命并管理宫廷职位。职位效果随持有者能力线性变化；每点能力额外提高0.1%宫廷花费。"
            if zh
            else "Appoint and manage Court Positions. Their effects scale linearly with each holder's ability; each ability point also raises court expense by 0.1%.",
        ),
        ("TV_COURT_POSITION_VACANT", "职位空缺" if zh else "Vacant Position"),
        ("TV_COURT_TOOLTIP_EFFECT_AT_100", "100点属性时：" if zh else "At 100 ability:"),
        ("TV_COURT_TOOLTIP_CURRENT_EFFECT", "当前提供：" if zh else "Current effect:"),
        ("TV_COURT_TOOLTIP_COURT_COST", "宫廷花费：每点生效能力 +0.1%，最高 +10%。" if zh else "Court expense: +0.1% per effective ability point, up to +10%."),
    ]
    for position in positions:
        prefix = loc_prefix(position)
        name = position["name_zh"] if zh else position["name_en"]
        ability = position["ability_zh"] if zh else position["ability_en"]
        description = position["description_zh"] if zh else position["description_en"]
        entries.extend([
            (f"{prefix}_TITLE", name),
            (f"{prefix}_DESC", description),
            (f"{prefix}_VACANT_PROMPT", f"点击以安排一位{name}" if zh else f"Click to appoint a {name}"),
            (f"{prefix}_ABILITY_TOOLTIP", f"使用的角色属性：{ability}" if zh else f"Character ability used: {ability}"),
            (f"STATIC_MODIFIER_NAME_{effect_modifier(position)}", name),
            (f"AUTO_MODIFIER_NAME_{court_cost_auto_modifier(position)}", f"{name}宫廷花费" if zh else f"{name} Court Expense"),
        ])
        if is_physician(position):
            entries.extend([
                (
                    "STATIC_MODIFIER_NAME_tv_court_physician_disease_control_modifier",
                    "控制疫病" if zh else "Disease Control",
                ),
                (
                    "STATIC_MODIFIER_DESC_tv_court_physician_disease_control_modifier",
                    "该地点的本地疫病抗性提高，效果取决于宫廷医生的行政能力。" if zh else "Increases local disease resistance based on the Court Physician's administrative skill.",
                ),
            ])
        for ability_value in range(101):
            entries.append((f"STATIC_MODIFIER_NAME_{display_modifier(position, ability_value)}", name))
        entries.extend(_action_localization_entries(position, language))
        action_ids = [appointment_action(position), replace_action(position), dismissal_action(position)]
        action_ids.extend(role_action(position, index) for index in range(1, ROLE_ACTION_COUNT + 1))
        for action in action_ids:
            entries.extend(_message_localization_entries(action, language))
    event_entries = {
        "STATIC_MODIFIER_NAME_tv_court_physician_treatment_good": ("治疗改善" if zh else "Successful Treatment"),
        "STATIC_MODIFIER_NAME_tv_court_physician_treatment_bad": ("治疗恶化" if zh else "Failed Treatment"),
        "STATIC_MODIFIER_DESC_tv_court_physician_treatment_good": ("治疗带来的预期寿命提升。" if zh else "A temporary increase in character life expectancy from successful treatment."),
        "STATIC_MODIFIER_DESC_tv_court_physician_treatment_bad": ("激进治疗失败带来的预期寿命降低。" if zh else "A temporary decrease in character life expectancy after failed aggressive treatment."),
        "tv_court_physician.1.t": ("医学研究推进" if zh else "Medical Research Advances"),
        "tv_court_physician.1.d": ("宫廷医生带来了新的医学见解。" if zh else "The Court Physician has brought forward a new medical insight."),
        "tv_court_physician.1.a": ("直接整理研究成果" if zh else "Record the findings"),
        "tv_court_physician.1.b": ("资助更深入的研究" if zh else "Fund deeper research"),
        "tv_court_physician.2.t": ("医术精进" if zh else "Medical Skill Improves"),
        "tv_court_physician.2.d": ("宫廷医生提出了改进医术的方法。" if zh else "The Court Physician has found a way to improve their practice."),
        "tv_court_physician.2.a": ("勤学苦练" if zh else "Practice diligently"),
        "tv_court_physician.2.b": ("购买器材和书籍" if zh else "Buy equipment and books"),
        "tv_court_physician.10.t": ("宫廷成员染病" if zh else "Illness at Court"),
        "tv_court_physician.10.desc": ("一名宫廷成员获得了疾病特质。" if zh else "A member of the court has fallen ill."),
        "tv_court_physician.10.a": ("立即寻访医生！" if zh else "Find a doctor immediately!"),
        "tv_court_physician.10.b": ("我们还有更重要的事。" if zh else "We have more important matters."),
        "tv_court_physician.10.c": ("不治疗" if zh else "Do not treat it"),
        "tv_court_physician.10.d": ("激进的治疗" if zh else "Aggressive treatment"),
        "tv_court_physician.10.e": ("稳重的治疗" if zh else "Cautious treatment"),
        "tv_court_physician.11.t": ("寻访名医" if zh else "Seeking Physicians"),
        "tv_court_physician.11.desc": ("三名医生来到了宫廷，请选择一人。" if zh else "Three physicians have arrived at court. Choose one."),
        "tv_court_physician.11.a": ("任命著名医生（花费金钱）" if zh else "Appoint the famous physician (pay gold)"),
        "tv_court_physician.11.b": ("任命医生（花费金钱）" if zh else "Appoint the physician (pay gold)"),
        "tv_court_physician.11.c": ("任命江湖道士" if zh else "Appoint the wandering healer"),
        "tv_court_physician.11.d": ("都不要" if zh else "Reject them all"),
        "tv_court_physician.12.t": ("选择治疗方式" if zh else "Choose a Treatment"),
        "tv_court_physician.12.d": ("宫廷医生已经就位，请决定如何治疗。" if zh else "The Court Physician is ready. Decide how to treat the patient."),
        "tv_court_physician.12.a": ("不治疗" if zh else "Do not treat"),
        "tv_court_physician.12.b": ("激进的治疗" if zh else "Aggressive treatment"),
        "tv_court_physician.12.c": ("稳重的治疗" if zh else "Cautious treatment"),
        "tv_court_physician.13.t": ("治疗结果" if zh else "Treatment Results"),
        "tv_court_physician.13.d": ("三十天的治疗终于有了结果。" if zh else "Thirty days of treatment have finally produced a result."),
        "tv_court_physician.13.a": ("接受结果" if zh else "Accept the result"),
        "dynastic.7.e": ("我们的宫廷医生会照料他的" if zh else "Our Court Physician will care for him"),
    }
    entries.extend(event_entries.items())
    lines = [
        f"{header_key}:",
        f"# @Generated by {script_rel}",
        f"#   Data:    {DATA_REL}",
        f"#   Regen:   python {script_rel}",
        "# Do not edit directly - modify the data file and re-run the generator.",
        "",
    ]
    for key, value in entries:
        lines.append(f' {key}: "{value.replace(chr(34), chr(92) + chr(34))}"')
    return b"\xef\xbb\xbf" + ("\n".join(lines) + "\n").encode("utf-8")
