"""
Generate src/in_game/gui/panels/organization/tv_trade_league.gui.

The monopoly tab reads per-player projected display variables. The scripted
effects copy leader-owned monopoly state into those variables so every member
can browse independently while only the leader can manage monopoly actions.
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[5]
DATA_FILE = REPO_ROOT / "data" / "trade_league_goods.yaml"
TRADE_CHAIN_FILE = REPO_ROOT / "data" / "trade_chain.yaml"
OUT_FILE = (
    REPO_ROOT
    / "src"
    / "in_game"
    / "gui"
    / "panels"
    / "organization"
    / "tv_trade_league.gui"
)

HEADER = """\
# @Generated by scripts/in_game/gui/panels/organization/gen_tv_trade_league_gui.py
#   Data:    data/trade_league_goods.yaml + data/trade_chain.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/gui/panels/organization/gen_tv_trade_league_gui.py
# Do not edit directly - modify the data file and re-run the generator.

"""

MONOPOLY_DISPLAY_MAX_PCT = 100
EMBARGO_COST_PCT = 30
MONOPOLY_SLOT_COUNT = 2
INTELLIGENCE_ROW_COUNT = 10

PREFIX = """\
organization_panel = {

\tblockoverride "organization_overview_tab_visible" {}

\tblockoverride "organization_panel_overview_visible" {
\t\tvisible = "[InternationalOrganizationsView.Vars.NotExistOrHasValue( 'organizations', 'overview' )]"
\t}

\tblockoverride "organization_members_tab_down" {
\t\tdown = "[InternationalOrganizationsView.Vars.HasValue( 'organizations', 'members' )]"
\t}

\tblockoverride "organization_panel_members_visible" {
\t\tvisible = "[InternationalOrganizationsView.Vars.HasValue( 'organizations', 'members' )]"
\t}

\tblockoverride "organization_resolutions_tab_visible" {
\t\tvisible = yes
\t}
\tblockoverride "organization_resolutions_tab_text" {
\t\ttext = "TV_TRADE_LEAGUE_INTELLIGENCE_TAB"
\t}
\tblockoverride "organization_resolutions_tooltip" {
\t\ttooltip = "TV_TRADE_LEAGUE_INTELLIGENCE_TAB_TOOLTIP"
\t}

\tblockoverride "organization_laws_tab_visible" {
\t\tvisible = yes
\t}
\tblockoverride "organization_laws_tab_text" {
\t\ttext = "TV_TRADE_LEAGUE_LAWS_TAB"
\t}

\tblockoverride "scroll_overview_empty_visible" { visible = no }

\tblockoverride "country_header_character_visible" {
\t\tvisible = yes
\t}
\tblockoverride "country_header_religion" {}
\tblockoverride "extra_titles" {}
\tblockoverride "country_header_names_visible" {
\t\tvisible = "[InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_grand_merchant_char').IsSet]"
\t}
\tblockoverride "country_header_character_name" {
\t\tdatacontext = "[InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_grand_merchant_char').GetCharacter]"
\t\tmargin = { 2 0 }
\t\tcharacter_label_name = {
\t\t\tmargin_left = 0
\t\t\tmargin_right = 10
\t\t\tblockoverride "character_name_text" {
\t\t\t\traw_text = "[Character.GetNameToFit('(int32)40', '(bool)yes')]"
\t\t\t}
\t\t}
\t}
\tblockoverride "character_widget" {
\t\twidget = {
\t\t\tposition = { 0 -30 }
\t\t\tallow_outside = yes
\t\t\tblock "portrait_io_widget" {
\t\t\t\tsize = { 250 200 }
\t\t\t}

\t\t\tblock "character_portrait_anchor" {
\t\t\t\tparentanchor = bottom
\t\t\t}

\t\t\tportrait_standard_full_body_center_button = {
\t\t\t\tvisible = "[InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_grand_merchant_char').IsSet]"
\t\t\t\tblock "character_right_visible" {
\t\t\t\t\tvisible = yes
\t\t\t\t}
\t\t\t\tparentanchor = bottom

\t\t\t\tsize = { 250 200 }
\t\t\t\tdatacontext = "[InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_grand_merchant_char').GetCharacter]"
\t\t\t}

\t\t\tvbox = {
\t\t\t\tvisible = "[Not(InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_grand_merchant_char').IsSet)]"
\t\t\t\tsize = { 250 200 }
\t\t\t\tparentanchor = center
\t\t\t\twidgetanchor = center
\t\t\t\tposition = { 0 0 }
\t\t\t\tspacing = 2

\t\t\t\texpand = {}
\t\t\t\ttext_single = {
\t\t\t\t\tsize = { 250 32 }
\t\t\t\t\traw_text = "+"
\t\t\t\t\tfontsize = 34
\t\t\t\t\talign = center|nobaseline
\t\t\t\t\tdefault_format = "#yellow_titles"
\t\t\t\t}
\t\t\t\ttext_single = {
\t\t\t\t\tsize = { 250 20 }
\t\t\t\t\ttext = "TV_IO_HEADER_APPOINT_CHIEF_PROMPT"
\t\t\t\t\tfontsize = 14
\t\t\t\t\talign = center|nobaseline
\t\t\t\t\tdefault_format = "#high"
\t\t\t\t}
\t\t\t\texpand = {}
\t\t\t}

\t\t\taction_button = {
\t\t\t\tvisible = "[Not(InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_grand_merchant_char').IsSet)]"
\t\t\t\tsize = { 250 200 }
\t\t\t\tparentanchor = center
\t\t\t\twidgetanchor = center
\t\t\t\tposition = { 0 0 }
\t\t\t\talpha = 0
\t\t\t\talwaystransparent = no
\t\t\t\tusing = action_button_common_template
\t\t\t\ttitle = "tv_appoint_trade_leader"
\t\t\t\tdescription = "tv_appoint_trade_leader_desc"
\t\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\t\tleft_action = { action_name = "tv_appoint_trade_leader" }
\t\t\t}

\t\t\taction_button = {
\t\t\t\tvisible = "[InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_grand_merchant_char').IsSet]"
\t\t\t\tsize = { 78 26 }
\t\t\t\tparentanchor = top|right
\t\t\t\twidgetanchor = top|right
\t\t\t\tposition = { 0 20 }
\t\t\t\tusing = button_regular_texture_alt_yellow
\t\t\t\tusing = action_button_common_template
\t\t\t\tusing = button_common_textobj_template
\t\t\t\tfontsize = 13
\t\t\t\ttitle = "tv_change_trade_leader"
\t\t\t\tdescription = "tv_change_trade_leader_desc"
\t\t\t\ttext = "TV_TRADE_CHANGE_LEADER_SHORT"
\t\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\t\tleft_action = { action_name = "tv_change_trade_leader" }
\t\t\t}
\t\t\taction_button = {
\t\t\t\tvisible = "[InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_grand_merchant_char').IsSet]"
\t\t\t\tsize = { 78 26 }
\t\t\t\tparentanchor = top|right
\t\t\t\twidgetanchor = top|right
\t\t\t\tposition = { 0 49 }
\t\t\t\tusing = button_regular_texture_alt_red
\t\t\t\tusing = action_button_common_template
\t\t\t\tusing = button_common_textobj_template
\t\t\t\tfontsize = 13
\t\t\t\ttitle = "tv_remove_trade_leader"
\t\t\t\tdescription = "tv_remove_trade_leader_desc"
\t\t\t\ttext = "TV_TRADE_REMOVE_LEADER_SHORT"
\t\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\t\tleft_action = { action_name = "tv_remove_trade_leader" }
\t\t\t}
\t\t}
\t}

\tblockoverride "io_main_actions_icon" {
\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t}

\tblockoverride "ios_information_header_visible" {
\t\tvisible = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_grand_merchant_char').IsSet]"
\t}

\tblockoverride "ios_information_header_content_extra_2" {
\t\tusing = ios_header_content_extra_template
\t\tblockoverride "ios_header_content_extra" {
\t\t\tvisible = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_grand_merchant_char').IsSet]"
\t\t\twidget = {
\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\tsize = { 230 42 }
\t\t\t\tbackground = { using = bg_paper_card }
\t\t\t\tbackground = { using = bg_cabinet_card_frame }
\t\t\t\tvbox = {
\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\tsize = { 230 42 }
\t\t\t\t\tmargin = { 8 3 }
\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\tspacing = 1

\t\t\t\t\ttext_single = {
\t\t\t\t\t\tvisible = "[And3(InternationalOrganizationsView.GetInternationalOrganization.GetParliament.IsLawDebate, InternationalOrganizationsView.GetInternationalOrganization.GetParliament.HasOngoingParliamentDebate, InternationalOrganizationsView.GetInternationalOrganization.GetParliament.IsParliamentActive)]"
\t\t\t\t\t\tsize = { 214 18 }
\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_ACTION_LAW_CHANGE"
\t\t\t\t\t\talign = nobaseline|right
\t\t\t\t\t}
\t\t\t\t\ttext_single = {
\t\t\t\t\t\tvisible = "[And(Not(And3(InternationalOrganizationsView.GetInternationalOrganization.GetParliament.IsLawDebate, InternationalOrganizationsView.GetInternationalOrganization.GetParliament.HasOngoingParliamentDebate, InternationalOrganizationsView.GetInternationalOrganization.GetParliament.IsParliamentActive)), InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_commercial_intelligence_active').IsSet)]"
\t\t\t\t\t\tsize = { 214 18 }
\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_ACTION_INTELLIGENCE"
\t\t\t\t\t\talign = nobaseline|right
\t\t\t\t\t}
\t\t\t\t\ttext_single = {
\t\t\t\t\t\tvisible = "[And(Not(And3(InternationalOrganizationsView.GetInternationalOrganization.GetParliament.IsLawDebate, InternationalOrganizationsView.GetInternationalOrganization.GetParliament.HasOngoingParliamentDebate, InternationalOrganizationsView.GetInternationalOrganization.GetParliament.IsParliamentActive)), Not(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_commercial_intelligence_active').IsSet))]"
\t\t\t\t\t\tsize = { 214 18 }
\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_ACTION_ASSIST_CARAVANS"
\t\t\t\t\t\talign = nobaseline|right
\t\t\t\t\t}
\t\t\t\t\ttext_single = {
\t\t\t\t\t\tvisible = "[And(Not(And3(InternationalOrganizationsView.GetInternationalOrganization.GetParliament.IsLawDebate, InternationalOrganizationsView.GetInternationalOrganization.GetParliament.HasOngoingParliamentDebate, InternationalOrganizationsView.GetInternationalOrganization.GetParliament.IsParliamentActive)), Not(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_commercial_intelligence_active').IsSet))]"
\t\t\t\t\t\tsize = { 214 16 }
\t\t\t\t\t\tfontsize = 12
\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_ACTION_ASSIST_CARAVANS_EFFECT"
\t\t\t\t\t\talign = nobaseline|right
\t\t\t\t\t}
\t\t\t\t}
\t\t\t}
\t\t}
\t}

\tblockoverride "organization_main_actions_extra_visible" {
\t\tvisible = yes
\t}

\tblockoverride "organization_overview_list_custom_top_extra" {
\t\tvbox = {
\t\t\tmargin = { 10 0 }
\t\t\tlayoutpolicy_horizontal = expanding
\t\t\tlayoutpolicy_vertical = shrinking
\t\t\tignoreinvisible = yes
\t\t\tspacing = 8

"""

OVERVIEW_ACTIONS_SUFFIX = """\
\tblockoverride "organization_main_actions_extra" {
\t\taction_button_diamond = {
\t\t\tsize = { 470 30 }
\t\t\ttext = "tv_invite_to_trade_league"
\t\t\ttitle = "tv_invite_to_trade_league"
\t\t\tdescription = "tv_invite_to_trade_league_desc"
\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\tleft_action = {
\t\t\t\taction_name = "tv_invite_to_trade_league"
\t\t\t\taction_direction = "offer"
\t\t\t}
\t\t}
\t\taction_button_diamond = {
\t\t\tsize = { 470 30 }
\t\t\ttext = "tv_expel_trade_league_member"
\t\t\ttitle = "tv_expel_trade_league_member"
\t\t\tdescription = "tv_expel_trade_league_member_desc"
\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\tleft_action = { action_name = "tv_expel_trade_league_member" }
\t\t}
\t}

"""

MONOPOLY_PREFIX = """\
\tblockoverride "organization_custom_tab_visible" {
\t\tvisible = yes
\t}
\tblockoverride "organization_custom_tab_text" {
\t\ttext = "TV_TRADE_LEAGUE_MONOPOLY_TAB"
\t}
\tblockoverride "organization_custom_tab_tooltip" {
\t\ttooltip = "TV_TRADE_LEAGUE_MONOPOLY_TAB_TOOLTIP"
\t}

\tblockoverride "organization_custom_content_visible" {
\t\tvisible = "[InternationalOrganizationsView.Vars.HasValue( 'organizations', 'custom' )]"
\t}

\tblockoverride "organization_custom_content" {
\t\tmargin_top = -5
\t\tspacing = 0
\t\tlayoutpolicy_vertical = expanding

\t\tscrollarea = {
\t\t\tusing = layoutpolicy_expanding
\t\t\tscrollbarpolicy_horizontal = always_off

\t\t\tscrollbar_vertical = {
\t\t\t\tusing = Scrollbar_Vertical
\t\t\t}

\t\t\tscrollwidget = {
\t\t\t\tvbox = {
\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\tspacing = 10
\t\t\t\t\tmargin = { 10 2 }

\t\t\t\t\tcard_common = {
\t\t\t\t\t\tvisible = "[Not(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_grand_merchant_char').IsSet)]"
\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\tminimumsize = { 500 -1 }
\t\t\t\t\t\tmaximumsize = { 500 -1 }
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t\t\t}
\t\t\t\t\t\tblockoverride "common_header_text" {
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_MONOPOLY_CARD_TITLE"
\t\t\t\t\t\t}
\t\t\t\t\t\tblockoverride "common_bottom_content" {
\t\t\t\t\t\t\ttext_multi = {
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tautoresize = yes
\t\t\t\t\t\t\t\tmax_width = 462
\t\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_MONOPOLY_LOCKED_TEXT"
\t\t\t\t\t\t\t\tmargin = { 4 6 }
\t\t\t\t\t\t\t}
\t\t\t\t\t\t}
\t\t\t\t\t}

\t\t\t\t\tcard_common = {
\t\t\t\t\t\tvisible = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_grand_merchant_char').IsSet]"
\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\tminimumsize = { 500 -1 }
\t\t\t\t\t\tmaximumsize = { 500 -1 }
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t\t\t}
\t\t\t\t\t\tblockoverride "common_header_text" {
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_MONOPOLY_CARD_TITLE"
\t\t\t\t\t\t}
\t\t\t\t\t\tblockoverride "common_bottom_content" {
\t\t\t\t\t\t\tvbox = {
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\tsize = { 462 -1 }
\t\t\t\t\t\t\t\tspacing = 2
\t\t\t\t\t\t\t\tmargin = { 4 6 }
"""

TABLE_HEADER = """\
\t\t\t\t\t\t\t\twidget = {
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = { 462 24 }
\t\t\t\t\t\t\t\t\tbackground = {
\t\t\t\t\t\t\t\t\t\tusing = tooltip_table_field_texture
\t\t\t\t\t\t\t\t\t\talpha = 0.28
\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\thbox = {
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = { 462 24 }
\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 86 22 } text_single = { size = { 86 22 } text = "TV_TRADE_LEAGUE_GOOD_COLUMN" align = nobaseline|left } }
\t\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 72 22 } text_single = { size = { 72 22 } text = "TV_TRADE_LEAGUE_ORIGIN_CONTROL_COLUMN" align = nobaseline|right } }
\t\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 72 22 } text_single = { size = { 72 22 } text = "TV_TRADE_LEAGUE_NODE_CONTROL_COLUMN" align = nobaseline|right } }
\t\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 72 22 } text_single = { size = { 72 22 } text = "TV_TRADE_LEAGUE_CONSUMER_CONTROL_COLUMN" align = nobaseline|right } }
\t\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 62 22 } text_single = { size = { 62 22 } text = "TV_TRADE_LEAGUE_MONOPOLY_COLUMN" align = nobaseline|center } }
\t\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 78 22 } text_single = { size = { 78 22 } text = "TV_TRADE_LEAGUE_LEVEL_COLUMN" align = nobaseline|right } }
\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t}
"""

LIST_CARD_SUFFIX = """\
\t\t\t\t\t\t\t}
\t\t\t\t\t\t}
\t\t\t\t\t}
\n"""

SUFFIX = """\
\t\t\t\t}
\t\t\t}
\t\t}
\t}
}
"""


def selected_visible(index: int) -> str:
    return (
        "[EqualTo_CFixedPoint(InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_trade_selected_good').GetValue, "
        f"'(CFixedPoint){index}.0')]"
    )


def action_row(good: str, action: str, title: str, icon: str) -> str:
    amount_var = f"tv_trade_{action}_amount_{good}"
    used_var = f"tv_trade_{action}_used_pct_{good}"
    active_var = f"tv_trade_{action}_active_{good}"
    location_var = f"tv_trade_{action}_location_{good}"
    return f"""\
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "[GreaterThanOrEqualTo_CFixedPoint(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('{active_var}').GetValue, '(CFixedPoint)1.0')]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 28 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 140 26 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 140 26 }} raw_text = "@market! [InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('{location_var}').GetLocation.GetMarket.GetNameWithNoTooltip]" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 116 26 }}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 116 26 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 20 26 }} raw_text = "{icon}" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 92 26 }} text = "{title}" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 74 26 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 74 26 }} raw_text = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('{amount_var}').GetValue|0]" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 48 26 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 48 26 }} raw_text = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('{used_var}').GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\taction_button = {{ size = {{ 24 24 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "+" title = "tv_trade_increase_{action}_{good}" description = "tv_trade_increase_{action}_{good}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_increase_{action}_{good}" }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ size = {{ 24 24 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "-" title = "tv_trade_decrease_{action}_{good}" description = "tv_trade_decrease_{action}_{good}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_decrease_{action}_{good}" }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ size = {{ 28 24 }} using = button_regular_texture_alt_red using = action_button_common_template using = button_common_textobj_template text = "X" title = "tv_trade_cancel_{action}_{good}" description = "tv_trade_cancel_{action}_{good}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_cancel_{action}_{good}" }} }}
\t\t\t\t\t\t\t\t}}
"""


def embargo_row(good: str) -> str:
    return f"""\
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "[GreaterThanOrEqualTo_CFixedPoint(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_embargo_active_{good}').GetValue, '(CFixedPoint)1.0')]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 28 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 140 26 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 140 26 }} raw_text = "@market! [InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_embargo_location_{good}').GetLocation.GetMarket.GetNameWithNoTooltip]" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 116 26 }}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 116 26 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 20 26 }} raw_text = "@trade_advantage!" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 92 26 }} text = "TV_TRADE_LEAGUE_EMBARGO" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 126 26 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 126 26 }} raw_text = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_embargo_country_{good}').GetCountry.GetNameWithFlag]" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 48 26 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 48 26 }} raw_text = "{EMBARGO_COST_PCT}%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\taction_button = {{ size = {{ 28 24 }} using = button_regular_texture_alt_red using = action_button_common_template using = button_common_textobj_template text = "X" title = "tv_trade_cancel_embargo_{good}" description = "tv_trade_cancel_embargo_{good}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_cancel_embargo_{good}" }} }}
\t\t\t\t\t\t\t\t}}
"""


def io_variable(variable: str) -> str:
    return (
        "InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry"
        f".MakeScope.GetVariable('{variable}')"
    )


def market_metric_cell(good: str, prefix: str, rank: int, field: str) -> str:
    variable = io_variable(f"tv_trade_{prefix}_{field}_{rank}_{good}")
    return f"""\
\t\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 68 20 }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 68 20 }} raw_text = "[{variable}.GetValue|0]" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t}}
"""


def market_info_row(good: str, prefix: str, rank: int) -> str:
    market_var = io_variable(f"tv_trade_{prefix}_market_{rank}_{good}")
    control_var = io_variable(f"tv_trade_{prefix}_control_pct_{rank}_{good}")
    route_total_field = "total_import" if prefix == "consumer" else "total_export"
    route_io_field = "io_import" if prefix == "consumer" else "io_export"
    row_set_visible = f"[{market_var}.IsSet]"
    row_empty_visible = f"[Not({market_var}.IsSet)]"
    return f"""\
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "{row_set_visible}"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 22 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 126 20 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 126 20 }} raw_text = "@market! [{market_var}.GetLocation.GetMarket.GetNameWithNoTooltip]" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 44 20 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 44 20 }} raw_text = "[{control_var}.GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t}}
{market_metric_cell(good, prefix, rank, "local_demand")}{market_metric_cell(good, prefix, rank, "local_production")}{market_metric_cell(good, prefix, rank, route_total_field)}{market_metric_cell(good, prefix, rank, route_io_field)}\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "{row_empty_visible}"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 22 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 126 20 }} text_single = {{ size = {{ 126 20 }} raw_text = "-" align = nobaseline|left }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 44 20 }} text_single = {{ size = {{ 44 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 68 20 }} text_single = {{ size = {{ 68 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 68 20 }} text_single = {{ size = {{ 68 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 68 20 }} text_single = {{ size = {{ 68 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 68 20 }} text_single = {{ size = {{ 68 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t}}
"""


def market_info_section(good: str, prefix: str, title: str) -> str:
    rows = "".join(market_info_row(good, prefix, rank) for rank in range(1, 4))
    route_total_column = (
        "TV_TRADE_LEAGUE_TOTAL_IMPORT_COLUMN"
        if prefix == "consumer"
        else "TV_TRADE_LEAGUE_TOTAL_EXPORT_COLUMN"
    )
    route_io_column = (
        "TV_TRADE_LEAGUE_IO_IMPORT_COLUMN"
        if prefix == "consumer"
        else "TV_TRADE_LEAGUE_IO_EXPORT_COLUMN"
    )
    return f"""\
\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 112 }}
\t\t\t\t\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\t\t\t\t\tspacing = 2
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 22 }} text = "{title}" align = nobaseline|center }}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 462 20 }}
\t\t\t\t\t\t\t\t\t\tbackground = {{
\t\t\t\t\t\t\t\t\t\t\tusing = tooltip_table_field_texture
\t\t\t\t\t\t\t\t\t\t\talpha = 0.18
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 462 20 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 166 20 }} text_single = {{ size = {{ 166 20 }} text = "TV_TRADE_LEAGUE_MARKET_COLUMN" align = nobaseline|left }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 44 20 }} text_single = {{ size = {{ 44 20 }} text = "TV_TRADE_LEAGUE_CONTROL_COLUMN" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} text = "TV_TRADE_LEAGUE_LOCAL_DEMAND_COLUMN" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} text = "TV_TRADE_LEAGUE_LOCAL_PRODUCTION_COLUMN" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} text = "{route_total_column}" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} text = "{route_io_column}" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
{rows}\t\t\t\t\t\t\t\t}}
"""


def market_intelligence(good: str) -> str:
    return (
        market_info_section(good, "origin", "TV_TRADE_LEAGUE_PRODUCTION_MARKETS_TITLE")
        + market_info_section(good, "node", "TV_TRADE_LEAGUE_KEY_NODES_TITLE")
        + market_info_section(good, "consumer", "TV_TRADE_LEAGUE_CONSUMER_MARKETS_TITLE")
    )


def detail_card(good: str, index: int) -> str:
    visible = selected_visible(index)
    return f"""\
\t\t\t\t\tcard_common = {{
\t\t\t\t\t\tvisible = "{visible}"
\t\t\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/trade_goods/icon_goods_{good}.dds"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_MONOPOLY_DETAIL_TITLE"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\t\tmargin = {{ 4 6 }}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 60 }}
\t\t\t\t\t\t\t\t\tspacing = 8
\t\t\t\t\t\t\t\t\ticon = {{ size = {{ 48 48 }} texture = "gfx/interface/icons/trade_goods/icon_goods_{good}.dds" }}
\t\t\t\t\t\t\t\t\tpiechart = {{
\t\t\t\t\t\t\t\t\t\tsize = {{ 54 54 }}
\t\t\t\t\t\t\t\t\t\tusing = piechart_angles
\t\t\t\t\t\t\t\t\t\ticon = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" size = {{ 97% 97% }} parentanchor = center color = {{ 0.45 0.59 0.67 1 }} alpha = 0.3 }}
\t\t\t\t\t\t\t\t\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = "[FixedPointToFloat(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_monopoly_level_pct_{good}').GetValue)]" color = {{ 0.85 0.65 0.22 1 }} alpha = 0.8 }}
\t\t\t\t\t\t\t\t\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = "[Subtract_float('(float){MONOPOLY_DISPLAY_MAX_PCT}.0', FixedPointToFloat(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_monopoly_level_pct_{good}').GetValue))]" color = {{ 1 1 1 0 }} }}
\t\t\t\t\t\t\t\t\t\tusing = bg_circle_piechart
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\t\tsize = {{ 340 54 }}
\t\t\t\t\t\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 340 24 }} text = "{good}" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tvisible = "[GreaterThanOrEqualTo_CFixedPoint(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_monopoly_{good}').GetValue, '(CFixedPoint)1.0')]"
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 340 24 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 20 24 }} raw_text = "@trigger_yes!" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 58 24 }} raw_text = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_monopoly_level_pct_{good}').GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 250 24 }} text = "TV_TRADE_LEAGUE_MONOPOLY_COLUMN" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tvisible = "[Not(GreaterThanOrEqualTo_CFixedPoint(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_monopoly_{good}').GetValue, '(CFixedPoint)1.0'))]"
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 340 24 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 20 24 }} raw_text = "@trade!" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 58 24 }} raw_text = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_monopoly_level_pct_{good}').GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 250 24 }} text = "TV_TRADE_LEAGUE_NOT_MONOPOLIZED" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 24 }} text = "TV_TRADE_LEAGUE_USED_LEVEL_TITLE" align = nobaseline|center }}
\t\t\t\t\t\t\t\tprogressbar = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 18 }}
\t\t\t\t\t\t\t\t\tmax = {MONOPOLY_DISPLAY_MAX_PCT}
\t\t\t\t\t\t\t\t\tvalue = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_monopoly_level_pct_{good}').GetValue]"
\t\t\t\t\t\t\t\t\tusing = progress_bar_goldish
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\tprogressbar = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 18 }}
\t\t\t\t\t\t\t\t\tmax = {MONOPOLY_DISPLAY_MAX_PCT}
\t\t\t\t\t\t\t\t\tvalue = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_used_monopoly_level_pct_{good}').GetValue]"
\t\t\t\t\t\t\t\t\tusing = progress_bar_blue_alt
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 24 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 378 24 }} text = "TV_TRADE_LEAGUE_AVAILABLE_LEVEL" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 80 24 }} raw_text = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_available_monopoly_level_pct_{good}').GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 24 }} text = "TV_TRADE_LEAGUE_MARKET_INTELLIGENCE_TITLE" align = nobaseline|center }}
{market_intelligence(good)}
\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 24 }} text = "TV_TRADE_LEAGUE_ACTION_LIST_TITLE" align = nobaseline|center }}
{action_row(good, "virtual_demand", "TV_TRADE_LEAGUE_VIRTUAL_DEMAND", "@demand!")}
{action_row(good, "virtual_supply", "TV_TRADE_LEAGUE_VIRTUAL_PRODUCTION", "@supply!")}
{embargo_row(good)}
\t\t\t\t\t\t\t\ttext_multi = {{
\t\t\t\t\t\t\t\t\tvisible = "[And3(Not(GreaterThanOrEqualTo_CFixedPoint(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_virtual_demand_active_{good}').GetValue, '(CFixedPoint)1.0')), Not(GreaterThanOrEqualTo_CFixedPoint(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_virtual_supply_active_{good}').GetValue, '(CFixedPoint)1.0')), Not(GreaterThanOrEqualTo_CFixedPoint(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_embargo_active_{good}').GetValue, '(CFixedPoint)1.0')))]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\t\tautoresize = yes
\t\t\t\t\t\t\t\t\tmax_width = 462
\t\t\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_NO_ACTIONS"
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
"""


def action_card(good: str, index: int) -> str:
    visible = (
        "[And3("
        f"EqualTo_CFixedPoint(InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_trade_selected_good').GetValue, '(CFixedPoint){index}.0'), "
        f"GreaterThanOrEqualTo_CFixedPoint(InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_monopoly_{good}').GetValue, '(CFixedPoint)1.0'), "
        "InternationalOrganizationsView.GetInternationalOrganization.IsIOLeaderCountry(InternationalOrganizationsView.GetPlayer))]"
    )
    return f"""\
\t\t\t\t\tcard_common = {{
\t\t\t\t\t\tvisible = "{visible}"
\t\t\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_MONOPOLY_ACTIONS_TITLE"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\t\tmargin = {{ 4 6 }}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 24 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 378 24 }} text = "TV_TRADE_LEAGUE_AVAILABLE_LEVEL" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 80 24 }} raw_text = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('tv_trade_available_monopoly_level_pct_{good}').GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 30 }}
\t\t\t\t\t\t\t\t\tspacing = 8
\t\t\t\t\t\t\t\t\taction_button = {{ size = {{ 227 28 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "TV_TRADE_LEAGUE_VIRTUAL_DEMAND" title = "tv_trade_set_virtual_demand_{good}" description = "tv_trade_set_virtual_demand_{good}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_set_virtual_demand_{good}" }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ size = {{ 227 28 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "TV_TRADE_LEAGUE_VIRTUAL_PRODUCTION" title = "tv_trade_set_virtual_supply_{good}" description = "tv_trade_set_virtual_supply_{good}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_set_virtual_supply_{good}" }} }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\taction_button = {{ size = {{ 462 28 }} using = button_regular_texture_alt_red using = action_button_common_template using = button_common_textobj_template text = "TV_TRADE_LEAGUE_EMBARGO" title = "tv_trade_set_embargo_{good}" description = "tv_trade_set_embargo_{good}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_set_embargo_{good}" }} }}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
"""


def projected_var(variable: str) -> str:
    return f"InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('{variable}')"


def projected_selected_good_visible(index: int) -> str:
    return (
        "[EqualTo_CFixedPoint(InternationalOrganizationsView.GetPlayer.MakeScope.GetVariable('tv_trade_selected_good').GetValue, "
        f"'(CFixedPoint){index}.0')]"
    )


def projected_row_good_visible(row_index: str, index: int) -> str:
    return f"[EqualTo_CFixedPoint({row_index}.GetValue, '(CFixedPoint){index}.0')]"


def projected_leader_var(variable: str) -> str:
    return f"InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('{variable}')"


def projected_leader_visible() -> str:
    return "[InternationalOrganizationsView.GetInternationalOrganization.IsIOLeaderCountry(InternationalOrganizationsView.GetPlayer)]"


def projected_market_link(market: str, width: int, height: int = 20) -> str:
    return f"""\
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ {width} {height} }}
\t\t\t\t\t\t\t\t\t\tdatacontext = "[{market}.GetLocation.GetMarket]"
\t\t\t\t\t\t\t\t\t\ttext_single = {{
\t\t\t\t\t\t\t\t\t\t\tsize = {{ {width} {height} }}
\t\t\t\t\t\t\t\t\t\t\traw_text = "@market! [Market.GetNameWithNoTooltip]"
\t\t\t\t\t\t\t\t\t\t\talign = nobaseline|left
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\tbutton = {{
\t\t\t\t\t\t\t\t\t\t\tsize = {{ {width} {height} }}
\t\t\t\t\t\t\t\t\t\t\talpha = 0
\t\t\t\t\t\t\t\t\t\t\talwaystransparent = no
\t\t\t\t\t\t\t\t\t\t\taction_tooltip = {{
\t\t\t\t\t\t\t\t\t\t\t\tclick_type = left
\t\t\t\t\t\t\t\t\t\t\t\tclick_mode = single
\t\t\t\t\t\t\t\t\t\t\t\ttitle = "OPEN_MARKET"
\t\t\t\t\t\t\t\t\t\t\t\ton_action = "[ShowMarket(Market.Self)]"
\t\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\t\tonmousehierarchyenter = "[PdxGuiWidget.SetHighlightMarket(Market.Self)]"
\t\t\t\t\t\t\t\t\t\t\ttooltipwidget = {{ using = Market_tooltip }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
"""


def trade_chain_var(variable: str) -> str:
    return f"InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetVariable('{variable}')"


def trade_chain_count_equals(value: int) -> str:
    return f"[EqualTo_CFixedPoint({trade_chain_var('tv_trade_chain_count')}.GetValue, '(CFixedPoint){value}.0')]"


def trade_chain_count_at_least(value: int) -> str:
    return f"[GreaterThanOrEqualTo_CFixedPoint({trade_chain_var('tv_trade_chain_count')}.GetValue, '(CFixedPoint){value}.0')]"


def trade_chain_count_less_than(value: int) -> str:
    return f"[LessThan_CFixedPoint({trade_chain_var('tv_trade_chain_count')}.GetValue, '(CFixedPoint){value}.0')]"


def trade_chain_strength_card(chain_data: dict) -> str:
    medium = int(chain_data["medium_strength_threshold"])
    strong = int(chain_data["strong_strength_threshold"])
    length = trade_chain_var("tv_trade_chain_length")
    flow = trade_chain_var("tv_trade_chain_flow")
    strength = trade_chain_var("tv_trade_chain_strength")
    display = trade_chain_var("tv_trade_chain_strength_display")
    modifier_expr = (
        "ShowModifierEffect(Concatenate('tv_trade_chain_strength_display_', "
        f"ToString_int32(FixedPointToInt({display}.GetValue))))"
    )
    return f"""\
\t\t\tcard_common = {{
\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t}}
\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\ttext = "TV_TRADE_CHAIN_STRENGTH_CARD_TITLE"
\t\t\t\t}}
\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\tvbox = {{
\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\tsize = {{ 462 -1 }}
\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\tmargin = {{ 4 6 }}
\t\t\t\t\t\ttext_single = {{ size = {{ 462 24 }} text = "TV_TRADE_CHAIN_STRENGTH_TITLE" align = nobaseline|center }}
\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\tsize = {{ 462 20 }}
\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\ttext_single = {{ size = {{ 150 20 }} text = "TV_TRADE_CHAIN_LENGTH_LABEL" align = nobaseline|center fontsize = 12 }}
\t\t\t\t\t\t\ttext_single = {{ size = {{ 150 20 }} text = "TV_TRADE_CHAIN_FLOW_LABEL" align = nobaseline|center fontsize = 12 }}
\t\t\t\t\t\t\ttext_single = {{ size = {{ 150 20 }} text = "TV_TRADE_CHAIN_STRENGTH_LABEL" align = nobaseline|center fontsize = 12 }}
\t\t\t\t\t\t}}
\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\tsize = {{ 462 22 }}
\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\ttext_single = {{ size = {{ 150 22 }} raw_text = "[{length}.GetValue|0]" align = nobaseline|center fontsize = 13 }}
\t\t\t\t\t\t\ttext_single = {{ size = {{ 150 22 }} raw_text = "[{flow}.GetValue|2]" align = nobaseline|center fontsize = 13 }}
\t\t\t\t\t\t\ttext_single = {{ size = {{ 150 22 }} raw_text = "[{length}.GetValue|0] x [{flow}.GetValue|2] / 1000 = [{strength}.GetValue|0]" align = nobaseline|center fontsize = 13 }}
\t\t\t\t\t\t}}
\t\t\t\t\t\ttext_single = {{ visible = "[LessThan_CFixedPoint({strength}.GetValue, '(CFixedPoint){medium}.0')]" size = {{ 462 22 }} text = "TV_TRADE_CHAIN_TIER_WEAK" align = nobaseline|center fontsize = 14 }}
\t\t\t\t\t\ttext_single = {{ visible = "[And(GreaterThanOrEqualTo_CFixedPoint({strength}.GetValue, '(CFixedPoint){medium}.0'), LessThan_CFixedPoint({strength}.GetValue, '(CFixedPoint){strong}.0'))]" size = {{ 462 22 }} text = "TV_TRADE_CHAIN_TIER_MEDIUM" align = nobaseline|center fontsize = 14 }}
\t\t\t\t\t\ttext_single = {{ visible = "[GreaterThanOrEqualTo_CFixedPoint({strength}.GetValue, '(CFixedPoint){strong}.0')]" size = {{ 462 22 }} text = "TV_TRADE_CHAIN_TIER_STRONG" align = nobaseline|center fontsize = 14 }}
\t\t\t\t\t\tTooltipStringPairList = {{
\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\tmaximumsize = {{ 462 -1 }}
\t\t\t\t\t\t\tblockoverride "tooltip_minimumsize" {{ minimumsize = {{ 462 -1 }} }}
\t\t\t\t\t\t\tblockoverride "field_text_format" {{ fontsize = 13 }}
\t\t\t\t\t\t\tblockoverride "row_size" {{ maximumsize = {{ -1 22 }} minimumsize = {{ -1 22 }} }}
\t\t\t\t\t\t\ttextcontext = "[{modifier_expr}]"
\t\t\t\t\t\t}}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t}}
"""


def trade_chain_pie_widget(indent: str) -> str:
    return f"""{indent}widget = {{
{indent}\tlayoutpolicy_horizontal = fixed
{indent}\tlayoutpolicy_vertical = fixed
{indent}\tsize = {{ 72 72 }}
{indent}\tpiechart = {{
{indent}\t\tsize = {{ 72 72 }}
{indent}\t\tusing = piechart_angles
{indent}\t\ticon = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" size = {{ 97% 97% }} parentanchor = center color = {{ 0.20 0.27 0.31 1 }} alpha = 0.32 }}
{indent}\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = "[FixedPointToFloat(Market.GetTotalMerchantCapacity(Player.Self))]" color = {{ 0.82 0.62 0.22 1 }} alpha = 0.85 }}
{indent}\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = "[Subtract_float('(float)100.0', FixedPointToFloat(Market.GetTotalMerchantCapacity(Player.Self)))]" color = {{ 0.28 0.47 0.56 1 }} alpha = 0.75 }}
{indent}\t\ticon = {{ texture = "gfx/interface/icons/flat_icons/market_wealth.dds" size = {{ 34 34 }} parentanchor = center }}
{indent}\t\tusing = bg_circle_piechart
{indent}\t}}
{indent}}}"""


def trade_chain_market_card() -> str:
    pie = trade_chain_pie_widget("\t\t\t\t\t\t\t\t")
    return f"""\
\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\tsize = {{ 462 90 }}
\t\t\t\t\t\t\tbackground = {{ using = bg_paper_card }}
\t\t\t\t\t\t\tbackground = {{ using = bg_cabinet_card_frame }}
\t\t\t\t\t\t\tdatacontext = "[Scope.GetMarket]"
\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\tsize = {{ 462 90 }}
\t\t\t\t\t\t\t\tspacing = 0
\t\t\t\t\t\t\t\tmargin = {{ 0 9 }}
\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 10 72 }} }}
{pie}
\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 8 72 }} }}
\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 360 72 }}
\t\t\t\t\t\t\t\t\tspacing = 3
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 360 20 }} raw_text = "@market! [Market.GetNameWithNoTooltip]" align = nobaseline|left fontsize = 14 }}
\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 360 48 }}
\t\t\t\t\t\t\t\t\tspacing = 10
\t\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\t\tsize = {{ 175 48 }}
\t\t\t\t\t\t\t\t\t\tspacing = 2
\t\t\t\t\t\t\t\t\t\twidget = {{ size = {{ 175 22 }} datacontext = "[Market.GetCenterLocation.GetOwner]" text_single = {{ size = {{ 175 22 }} raw_text = "[Country.GetNameWithFlag]" align = nobaseline|left fontsize = 12 }} }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 175 22 }} raw_text = "[Market.GetTotalMerchantCapacity(Player.Self)|2]@trade_capacity!" align = nobaseline|left fontsize = 12 }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\t\tsize = {{ 175 48 }}
\t\t\t\t\t\t\t\t\t\tspacing = 2
\t\t\t\t\t\t\t\t\t\twidget = {{ visible = "[GreaterThan_CFixedPoint(Market.GetTotalMerchantCapacity(Player.Self),'(CFixedPoint)0')]" size = {{ 175 22 }} datacontext = "[Market.GetMerchant(Player.Self)]" text_single = {{ size = {{ 175 22 }} raw_text = "[Merchant.GetPowerWithLabel]@trade_advantage!" align = nobaseline|left fontsize = 12 }} }}
\t\t\t\t\t\t\t\t\t\twidget = {{ visible = "[GreaterThan_CFixedPoint(Market.GetTotalMerchantCapacity(Player.Self),'(CFixedPoint)0')]" size = {{ 175 22 }} datacontext = "[Market.GetMerchant(Player.Self)]" text_single = {{ size = {{ 175 22 }} raw_text = "[Merchant.GetTotalTradeProfit|2+=]@gold!" align = nobaseline|left fontsize = 12 }} }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = expanding layoutpolicy_vertical = fixed size = {{ -1 72 }} }}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
"""


def trade_chain_add_card(max_nodes: int) -> str:
    count_var = trade_chain_var("tv_trade_chain_count")
    visible = (
        "[And("
        "InternationalOrganizationsView.GetInternationalOrganization.IsIOLeaderCountry(InternationalOrganizationsView.GetPlayer), "
        f"Or(Not({count_var}.IsSet), {trade_chain_count_less_than(max_nodes)[1:-1]}))]"
    )
    return f"""\
\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\tvisible = "{visible}"
\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\tsize = {{ 462 90 }}
\t\t\t\t\t\t\tbackground = {{ using = bg_paper_card }}
\t\t\t\t\t\t\tbackground = {{ using = bg_cabinet_card_frame }}
\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\tsize = {{ 462 90 }}
\t\t\t\t\t\t\t\tspacing = 0
\t\t\t\t\t\t\t\tmargin = {{ 0 9 }}
\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 10 72 }} }}
\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 72 72 }}
\t\t\t\t\t\t\t\t\tpiechart = {{
\t\t\t\t\t\t\t\t\t\tsize = {{ 72 72 }}
\t\t\t\t\t\t\t\t\t\tusing = piechart_angles
\t\t\t\t\t\t\t\t\t\ticon = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" size = {{ 97% 97% }} parentanchor = center color = {{ 0.48 0.54 0.55 1 }} alpha = 0.5 }}
\t\t\t\t\t\t\t\t\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = 100 color = {{ 0.74 0.63 0.30 1 }} alpha = 0.75 }}
\t\t\t\t\t\t\t\t\t\tusing = bg_circle_piechart
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 72 72 }} raw_text = "+" align = nobaseline|center fontsize = 34 parentanchor = center }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 8 72 }} }}
\t\t\t\t\t\t\t\ttext_multi = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 360 72 }} autoresize = yes max_width = 360 text = "TV_TRADE_CHAIN_ADD_NODE_HINT" align = nobaseline|left }}
\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = expanding layoutpolicy_vertical = fixed size = {{ -1 72 }} }}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\taction_button = {{
\t\t\t\t\t\t\t\tsize = {{ 462 90 }}
\t\t\t\t\t\t\t\talpha = 0
\t\t\t\t\t\t\t\talwaystransparent = no
\t\t\t\t\t\t\t\tusing = action_button_common_template
\t\t\t\t\t\t\t\ttitle = "tv_trade_add_chain_node"
\t\t\t\t\t\t\t\tdescription = "tv_trade_add_chain_node_desc"
\t\t\t\t\t\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\t\t\t\t\t\tleft_action = {{ action_name = "tv_trade_add_chain_node" }}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
"""


def trade_chain_progress_background_variant(count: int, max_nodes: int) -> str:
    visible = trade_chain_count_equals(count)
    height = 90 * min(max_nodes, count + 1) + 8 * max(0, min(max_nodes, count + 1) - 1)
    filled = max(0, (count - 1) * 98)
    return f"""\
\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\tvisible = "{visible}"
\t\t\t\t\t\t\t\tposition = {{ 42 48 }}
\t\t\t\t\t\t\t\tsize = {{ 8 {height} }}
\t\t\t\t\t\t\t\tbackground = {{ using = tooltip_table_field_texture alpha = 0.22 }}
\t\t\t\t\t\t\t\twidget = {{ size = {{ 8 {filled} }} background = {{ using = color_gold alpha = 0.55 }} }}
\t\t\t\t\t\t\t}}
"""


def trade_chain_overview(chain_data: dict) -> str:
    max_nodes = int(chain_data["max_nodes"])
    progress = "".join(trade_chain_progress_background_variant(count, max_nodes) for count in range(1, max_nodes + 1))
    market_card = trade_chain_market_card()
    add_card = trade_chain_add_card(max_nodes)
    return (
        trade_chain_strength_card(chain_data)
        + f"""\
\t\t\tcard_common = {{
\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t}}
\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\ttext = "TV_TRADE_LEAGUE_TRADE_CHAIN_CARD_TITLE"
\t\t\t\t}}
\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\twidget = {{
\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\tlayoutpolicy_vertical = shrinking
\t\t\t\t\t\tset_parent_size_to_minimum = yes
\t\t\t\t\t\tminimumsize = {{ 462 -1 }}
\t\t\t\t\t\tmaximumsize = {{ 462 -1 }}
{progress}\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\tset_parent_size_to_minimum = yes
\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\tlayoutpolicy_vertical = shrinking
\t\t\t\t\t\t\tsize = {{ 462 -1 }}
\t\t\t\t\t\t\tspacing = 8
\t\t\t\t\t\t\tmargin = {{ 0 0 }}
\t\t\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\tset_parent_size_to_minimum = yes
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\tlayoutpolicy_vertical = shrinking
\t\t\t\t\t\t\t\tsize = {{ 462 -1 }}
\t\t\t\t\t\t\t\tspacing = 8
\t\t\t\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\t\t\t\tdatamodel = "[InternationalOrganizationsView.GetInternationalOrganization.GetLeaderCountry.MakeScope.GetList('tv_trade_chain_markets')]"
\t\t\t\t\t\t\t\titem = {{
{market_card}\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t}}
{add_card}\t\t\t\t\t\t}}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t}}

"""
        + OVERVIEW_ACTIONS_SUFFIX
    )


def projected_metric_cell(variable: str, width: int = 72, suffix: str = "") -> str:
    value = projected_var(variable)
    return f"""\
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ {width} 24 }}
\t\t\t\t\t\t\t\t\t\ttext_single = {{
\t\t\t\t\t\t\t\t\t\t\tsize = {{ {width} 24 }}
\t\t\t\t\t\t\t\t\t\t\traw_text = "[{value}.GetValue|0]{suffix}"
\t\t\t\t\t\t\t\t\t\t\talign = nobaseline|right
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
"""


def intelligence_page_controls() -> str:
    page = projected_var("tv_trade_intelligence_page")
    page_max = projected_var("tv_trade_intelligence_page_max")
    return f"""\
\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\tsize = {{ 462 30 }}
\t\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\t\texpand = {{}}
\t\t\t\t\t\t\t\taction_button = {{
\t\t\t\t\t\t\t\t\tsize = {{ 78 28 }}
\t\t\t\t\t\t\t\t\tusing = button_regular_texture_alt_yellow
\t\t\t\t\t\t\t\t\tusing = action_button_common_template
\t\t\t\t\t\t\t\t\tusing = button_common_textobj_template
\t\t\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_PREVIOUS_PAGE_SHORT"
\t\t\t\t\t\t\t\t\ttitle = "tv_trade_previous_intelligence_page"
\t\t\t\t\t\t\t\t\tdescription = "tv_trade_previous_intelligence_page_desc"
\t\t\t\t\t\t\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\t\t\t\t\t\t\tleft_action = {{ action_name = "tv_trade_previous_intelligence_page" }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\ttext_single = {{
\t\t\t\t\t\t\t\t\tsize = {{ 88 28 }}
\t\t\t\t\t\t\t\t\traw_text = "[{page}.GetValue|0]/[{page_max}.GetValue|0]"
\t\t\t\t\t\t\t\t\talign = nobaseline|center
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\taction_button = {{
\t\t\t\t\t\t\t\t\tsize = {{ 78 28 }}
\t\t\t\t\t\t\t\t\tusing = button_regular_texture_alt_yellow
\t\t\t\t\t\t\t\t\tusing = action_button_common_template
\t\t\t\t\t\t\t\t\tusing = button_common_textobj_template
\t\t\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_NEXT_PAGE_SHORT"
\t\t\t\t\t\t\t\t\ttitle = "tv_trade_next_intelligence_page"
\t\t\t\t\t\t\t\t\tdescription = "tv_trade_next_intelligence_page_desc"
\t\t\t\t\t\t\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\t\t\t\t\t\t\tleft_action = {{ action_name = "tv_trade_next_intelligence_page" }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\texpand = {{}}
\t\t\t\t\t\t\t}}
"""


def intelligence_table_header() -> str:
    return """\
\t\t\t\t\t\t\twidget = {
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\tsize = { 462 24 }
\t\t\t\t\t\t\t\tbackground = { using = tooltip_table_field_texture alpha = 0.28 }
\t\t\t\t\t\t\t\thbox = {
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = { 462 24 }
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 214 22 } text_single = { size = { 214 22 } text = "TV_TRADE_LEAGUE_MARKET_COLUMN" align = nobaseline|left } }
\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 112 22 } text_single = { size = { 112 22 } text = "TV_TRADE_LEAGUE_IO_TRADE_POWER_COLUMN" align = nobaseline|right } }
\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 96 22 } text_single = { size = { 96 22 } text = "TV_TRADE_LEAGUE_NETWORK_COLUMN" align = nobaseline|right } }
\t\t\t\t\t\t\t\t\twidget = { layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = { 24 22 } text_single = { size = { 24 22 } raw_text = "" align = nobaseline|center } }
\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t}
"""


def intelligence_row(row: int) -> str:
    visible = projected_var(f"tv_trade_intelligence_row_{row}_visible")
    market = projected_var(f"tv_trade_intelligence_row_{row}_market")
    slot = projected_var(f"tv_trade_intelligence_row_{row}_slot")
    selected = projected_var("tv_trade_selected_intelligence_slot")
    io_power = projected_var(f"tv_trade_intelligence_row_{row}_io_power")
    strength = projected_var(f"tv_trade_intelligence_row_{row}_strength_pct")
    active = projected_var(f"tv_trade_intelligence_row_{row}_active")
    selected_bg = f"[EqualTo_CFixedPoint({slot}.GetValue, {selected}.GetValue)]"
    return f"""\
\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\tvisible = "[GreaterThanOrEqualTo_CFixedPoint({visible}.GetValue, '(CFixedPoint)1.0')]"
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\tsize = {{ 462 26 }}
\t\t\t\t\t\t\t\tbackground = {{ using = tooltip_table_field_texture alpha = 0.16 }}
\t\t\t\t\t\t\t\tbackground = {{ visible = "{selected_bg}" using = click_modifier_bg_texture alpha = 0.34 }}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 26 }}
\t\t\t\t\t\t\t\t\tspacing = 4
{projected_market_link(market, 214, 24)}\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 112 24 }} text_single = {{ size = {{ 112 24 }} raw_text = "[{io_power}.GetValue|0]" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 96 24 }} text_single = {{ size = {{ 96 24 }} raw_text = "[{strength}.GetValue|1]%" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 24 24 }} text_single = {{ visible = "[GreaterThanOrEqualTo_CFixedPoint({active}.GetValue, '(CFixedPoint)1.0')]" size = {{ 24 24 }} raw_text = "@trigger_yes!" align = nobaseline|center }} }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\taction_button = {{
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 26 }}
\t\t\t\t\t\t\t\t\talpha = 0
\t\t\t\t\t\t\t\t\talwaystransparent = no
\t\t\t\t\t\t\t\t\tusing = action_button_common_template
\t\t\t\t\t\t\t\t\ttitle = "tv_trade_select_intelligence_row_{row}"
\t\t\t\t\t\t\t\t\tdescription = "tv_trade_select_intelligence_row_desc"
\t\t\t\t\t\t\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\t\t\t\t\t\t\tleft_action = {{ action_name = "tv_trade_select_intelligence_row_{row}" }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t}}
"""


def intelligence_top_country_row(rank: int) -> str:
    country = projected_var(f"tv_trade_selected_intelligence_top_country_{rank}")
    power = projected_var(f"tv_trade_selected_intelligence_top_power_{rank}")
    return f"""\
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "[{country}.IsSet]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 24 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 32 22 }} text_single = {{ size = {{ 32 22 }} raw_text = "#{rank}" align = nobaseline|left }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 312 22 }} text_single = {{ size = {{ 312 22 }} raw_text = "[{country}.GetCountry.GetNameWithFlag]" align = nobaseline|left }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 110 22 }} text_single = {{ size = {{ 110 22 }} raw_text = "[{power}.GetValue|0]" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "[Not({country}.IsSet)]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 24 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 32 22 }} text_single = {{ size = {{ 32 22 }} raw_text = "#{rank}" align = nobaseline|left }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 312 22 }} text_single = {{ size = {{ 312 22 }} raw_text = "-" align = nobaseline|left }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 110 22 }} text_single = {{ size = {{ 110 22 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t}}
"""


def intelligence_content() -> str:
    leader_merchant = projected_leader_var("tv_grand_merchant_char")
    selected_market = projected_var("tv_trade_selected_intelligence_market")
    strength = projected_var("tv_trade_selected_intelligence_strength_pct")
    active = projected_var("tv_trade_selected_intelligence_active")
    leader_visible = projected_leader_visible()
    rows = "".join(intelligence_row(row) for row in range(1, INTELLIGENCE_ROW_COUNT + 1))
    top_rows = "".join(intelligence_top_country_row(rank) for rank in range(1, 4))
    return f"""\
\tblockoverride "organization_resolutions_content" {{
\t\tmargin = {{ 0 0 }}
\t\tscrollarea = {{
\t\t\tusing = layoutpolicy_expanding
\t\t\tscrollbarpolicy_horizontal = always_off

\t\t\tscrollbar_vertical = {{
\t\t\t\tusing = Scrollbar_Vertical
\t\t\t}}

\t\t\tscrollwidget = {{
\t\t\t\tvbox = {{
\t\t\t\t\tmargin = {{ 10 0 }}
\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\tspacing = 10

\t\t\t\t\tcard_common = {{
\t\t\t\t\t\tvisible = "[Not({leader_merchant}.IsSet)]"
\t\t\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_INTELLIGENCE_CARD_TITLE"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\t\t\ttext_multi = {{
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tautoresize = yes
\t\t\t\t\t\t\t\tmax_width = 462
\t\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_SYSTEM_LOCKED_TEXT"
\t\t\t\t\t\t\t\tmargin = {{ 4 6 }}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}

\t\t\t\t\tcard_common = {{
\t\t\t\t\t\tvisible = "[{leader_merchant}.IsSet]"
\t\t\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_INTELLIGENCE_CARD_TITLE"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\tsize = {{ 462 -1 }}
\t\t\t\t\t\t\t\tspacing = 2
\t\t\t\t\t\t\t\tmargin = {{ 4 6 }}
{intelligence_page_controls()}{intelligence_table_header()}{rows}\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}

\t\t\t\t\tcard_common = {{
\t\t\t\t\t\tvisible = "[And({leader_merchant}.IsSet, {selected_market}.IsSet)]"
\t\t\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_INTELLIGENCE_DETAIL_TITLE"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\tsize = {{ 462 -1 }}
\t\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\t\tmargin = {{ 4 6 }}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 28 }}
\t\t\t\t\t\t\t\t\tspacing = 4
{projected_market_link(selected_market, 300, 26)}\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 158 26 }} raw_text = "[{strength}.GetValue|1]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\tprogressbar = {{ size = {{ 462 18 }} max = 100 value = "[{strength}.GetValue]" using = progress_bar_goldish }}
\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 24 }} text = "TV_TRADE_LEAGUE_TOP_TRADE_POWER_TITLE" align = nobaseline|center }}
{top_rows}\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "{leader_visible}"
\t\t\t\t\t\t\t\t\tsize = {{ 462 30 }}
\t\t\t\t\t\t\t\t\tspacing = 8
\t\t\t\t\t\t\t\t\taction_button = {{ visible = "[Not(GreaterThanOrEqualTo_CFixedPoint({active}.GetValue, '(CFixedPoint)1.0'))]" size = {{ 227 28 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "TV_TRADE_LEAGUE_START_NETWORK" title = "tv_trade_start_intelligence_network" description = "tv_trade_start_intelligence_network_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_start_intelligence_network" }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ visible = "[GreaterThanOrEqualTo_CFixedPoint({active}.GetValue, '(CFixedPoint)1.0')]" size = {{ 227 28 }} using = button_regular_texture_alt_red using = action_button_common_template using = button_common_textobj_template text = "TV_TRADE_LEAGUE_CANCEL_NETWORK" title = "tv_trade_cancel_intelligence_network" description = "tv_trade_cancel_intelligence_network_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_cancel_intelligence_network" }} }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t}}
\t\t}}
\t}}

"""


def projected_row_good_entries(goods: list[str], row_index: str) -> str:
    entries: list[str] = []
    for index, good in enumerate(goods, start=1):
        visible = projected_row_good_visible(row_index, index)
        entries.append(
            f"""\
\t\t\t\t\t\t\t\t\t\t\t\ticon = {{
\t\t\t\t\t\t\t\t\t\t\t\t\tvisible = "{visible}"
\t\t\t\t\t\t\t\t\t\t\t\t\tsize = {{ 20 20 }}
\t\t\t\t\t\t\t\t\t\t\t\t\ttexture = "gfx/interface/icons/trade_goods/icon_goods_{good}.dds"
\t\t\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{
\t\t\t\t\t\t\t\t\t\t\t\t\tvisible = "{visible}"
\t\t\t\t\t\t\t\t\t\t\t\t\ttext = "{good}"
\t\t\t\t\t\t\t\t\t\t\t\t\talign = nobaseline|left
\t\t\t\t\t\t\t\t\t\t\t\t}}"""
        )
    return "\n".join(entries)


def projected_good_icon_entries(goods: list[str], index_var: str, size: int) -> str:
    entries: list[str] = []
    for index, good in enumerate(goods, start=1):
        entries.append(
            f"""\t\t\t\t\t\t\t\t\t\t\t\ticon = {{ visible = "{projected_row_good_visible(index_var, index)}" size = {{ {size} {size} }} texture = "gfx/interface/icons/trade_goods/icon_goods_{good}.dds" parentanchor = center }}"""
        )
    return "\n".join(entries)


def projected_good_name_entries(goods: list[str], index_var: str, width: int, height: int) -> str:
    entries: list[str] = []
    for index, good in enumerate(goods, start=1):
        entries.append(
            f"""\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "{projected_row_good_visible(index_var, index)}" size = {{ {width} {height} }} text = "{good}" align = nobaseline|left }}"""
        )
    return "\n".join(entries)


def projected_type_label_entries(type_var: str, width: int, height: int) -> str:
    return f"""\
\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "[EqualTo_CFixedPoint({type_var}.GetValue, '(CFixedPoint)1.0')]" size = {{ {width} {height} }} text = "TV_TRADE_LEAGUE_ORIGIN_MONOPOLY" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "[EqualTo_CFixedPoint({type_var}.GetValue, '(CFixedPoint)2.0')]" size = {{ {width} {height} }} text = "TV_TRADE_LEAGUE_TRANSIT_MONOPOLY" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "[EqualTo_CFixedPoint({type_var}.GetValue, '(CFixedPoint)3.0')]" size = {{ {width} {height} }} text = "TV_TRADE_LEAGUE_CONSUMER_MONOPOLY" align = nobaseline|right }}"""


def projected_stage_label_entries(stage_var: str, width: int, height: int) -> str:
    return f"""\
\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "[EqualTo_CFixedPoint({stage_var}.GetValue, '(CFixedPoint)1.0')]" size = {{ {width} {height} }} text = "TV_TRADE_LEAGUE_MONOPOLY_POTENTIAL" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "[EqualTo_CFixedPoint({stage_var}.GetValue, '(CFixedPoint)2.0')]" size = {{ {width} {height} }} text = "TV_TRADE_LEAGUE_LOW_MONOPOLY" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "[EqualTo_CFixedPoint({stage_var}.GetValue, '(CFixedPoint)3.0')]" size = {{ {width} {height} }} text = "TV_TRADE_LEAGUE_HIGH_MONOPOLY" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "[EqualTo_CFixedPoint({stage_var}.GetValue, '(CFixedPoint)4.0')]" size = {{ {width} {height} }} text = "TV_TRADE_LEAGUE_COMPLETE_MONOPOLY" align = nobaseline|right }}"""


def projected_slot_metric_row(label: str, variable: str) -> str:
    value = projected_var(variable)
    return f"""\t\t\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\t\t\tsize = {{ 344 19 }}
\t\t\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 238 19 }} text = "{label}" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 102 19 }} raw_text = "[{value}.GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\t\t}}"""


def projected_monopoly_slot_card(slot: int, goods: list[str]) -> str:
    unlocked = projected_var(f"tv_trade_monopoly_slot_{slot}_unlocked")
    good_index = projected_var(f"tv_trade_monopoly_slot_{slot}_good_index")
    selected = projected_var("tv_trade_selected_good")
    pct = projected_var(f"tv_trade_monopoly_slot_{slot}_monopoly_level_pct")
    type_var = projected_var(f"tv_trade_monopoly_slot_{slot}_monopoly_type")
    stage_var = projected_var(f"tv_trade_monopoly_slot_{slot}_monopoly_stage")
    selected_bg = f"[And(GreaterThan_CFixedPoint({good_index}.GetValue, '(CFixedPoint)0.0'), EqualTo_CFixedPoint({good_index}.GetValue, {selected}.GetValue))]"
    filled = f"[GreaterThan_CFixedPoint({good_index}.GetValue, '(CFixedPoint)0.0')]"
    empty = f"[Not(GreaterThan_CFixedPoint({good_index}.GetValue, '(CFixedPoint)0.0'))]"
    good_names = projected_good_name_entries(goods, good_index, 196, 17)
    stage_labels = projected_stage_label_entries(stage_var, 196, 17)
    type_labels = projected_type_label_entries(type_var, 140, 17)
    return f"""\
\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\tvisible = "[GreaterThanOrEqualTo_CFixedPoint({unlocked}.GetValue, '(CFixedPoint)1.0')]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 104 }}
\t\t\t\t\t\t\t\t\tbackground = {{ using = tooltip_table_field_texture alpha = 0.18 }}
\t\t\t\t\t\t\t\t\tbackground = {{ visible = "{selected_bg}" using = click_modifier_bg_texture alpha = 0.34 }}
\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\tvisible = "{filled}"
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 462 104 }}
\t\t\t\t\t\t\t\t\t\tspacing = 10
\t\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 94 104 }}
\t\t\t\t\t\t\t\t\t\t\tpiechart = {{
\t\t\t\t\t\t\t\t\t\t\t\tsize = {{ 76 76 }}
\t\t\t\t\t\t\t\t\t\t\t\tparentanchor = center
\t\t\t\t\t\t\t\t\t\t\t\twidgetanchor = center
\t\t\t\t\t\t\t\t\t\t\t\tusing = piechart_angles
\t\t\t\t\t\t\t\t\t\t\t\ticon = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" size = {{ 97% 97% }} parentanchor = center color = {{ 0.45 0.59 0.67 1 }} alpha = 0.3 }}
\t\t\t\t\t\t\t\t\t\t\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = "[FixedPointToFloat({pct}.GetValue)]" color = {{ 0.85 0.65 0.22 1 }} alpha = 0.8 }}
\t\t\t\t\t\t\t\t\t\t\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = "[Subtract_float('(float)100.0', FixedPointToFloat({pct}.GetValue))]" color = {{ 1 1 1 0 }} }}
{projected_good_icon_entries(goods, good_index, 38)}
\t\t\t\t\t\t\t\t\t\t\t\tusing = bg_circle_piechart
\t\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 348 96 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\t\tsize = {{ 344 34 }}
\t\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\t\t\tsize = {{ 200 34 }}
\t\t\t\t\t\t\t\t\t\t\t\t\tignoreinvisible = yes
{good_names}
{stage_labels}
\t\t\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\t\t\tsize = {{ 140 34 }}
\t\t\t\t\t\t\t\t\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 140 17 }} raw_text = "[{pct}.GetValue|0]%" align = nobaseline|right }}
{type_labels}
\t\t\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\t\t}}
{projected_slot_metric_row("TV_TRADE_LEAGUE_ORIGIN_CONTROL_COLUMN", f"tv_trade_monopoly_slot_{slot}_origin_pct")}
{projected_slot_metric_row("TV_TRADE_LEAGUE_NODE_CONTROL_COLUMN", f"tv_trade_monopoly_slot_{slot}_node_pct")}
{projected_slot_metric_row("TV_TRADE_LEAGUE_CONSUMER_CONTROL_COLUMN", f"tv_trade_monopoly_slot_{slot}_consumer_pct")}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\ttext_multi = {{
\t\t\t\t\t\t\t\t\t\tvisible = "{empty}"
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\t\t\tautoresize = yes
\t\t\t\t\t\t\t\t\t\tmax_width = 430
\t\t\t\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_EMPTY_MONOPOLY_SLOT"
\t\t\t\t\t\t\t\t\t\tmargin = {{ 12 38 }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\taction_button = {{
\t\t\t\t\t\t\t\t\t\tvisible = "{filled}"
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 462 104 }}
\t\t\t\t\t\t\t\t\t\talpha = 0
\t\t\t\t\t\t\t\t\t\talwaystransparent = no
\t\t\t\t\t\t\t\t\t\tusing = action_button_common_template
\t\t\t\t\t\t\t\t\t\ttitle = "tv_trade_select_monopoly_slot_{slot}"
\t\t\t\t\t\t\t\t\t\tdescription = "tv_trade_select_monopoly_slot_desc"
\t\t\t\t\t\t\t\t\t\tactor = "[InternationalOrganizationsView.GetPlayer]"
\t\t\t\t\t\t\t\t\t\tleft_action = {{ action_name = "tv_trade_select_monopoly_slot_{slot}" }}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t}}
"""


def projected_action_row(action: str, title: str, icon: str) -> str:
    active = projected_var(f"tv_trade_selected_{action}_active")
    amount = projected_var(f"tv_trade_selected_{action}_amount")
    used = projected_var(f"tv_trade_selected_{action}_used_pct")
    location = projected_var(f"tv_trade_selected_{action}_location")
    leader_visible = projected_leader_visible()
    return f"""\
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "[GreaterThanOrEqualTo_CFixedPoint({active}.GetValue, '(CFixedPoint)1.0')]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 28 }}
\t\t\t\t\t\t\t\t\tspacing = 4
{projected_market_link(location, 140, 26)}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 116 26 }}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 116 26 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 20 26 }} raw_text = "{icon}" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 92 26 }} text = "{title}" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 74 26 }} text_single = {{ size = {{ 74 26 }} raw_text = "[{amount}.GetValue|0]" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 48 26 }} text_single = {{ size = {{ 48 26 }} raw_text = "[{used}.GetValue|0]%" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ visible = "{leader_visible}" size = {{ 24 24 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "+" title = "tv_trade_increase_selected_{action}" description = "tv_trade_increase_selected_{action}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_increase_selected_{action}" }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ visible = "{leader_visible}" size = {{ 24 24 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "-" title = "tv_trade_decrease_selected_{action}" description = "tv_trade_decrease_selected_{action}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_decrease_selected_{action}" }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ visible = "{leader_visible}" size = {{ 28 24 }} using = button_regular_texture_alt_red using = action_button_common_template using = button_common_textobj_template text = "X" title = "tv_trade_cancel_selected_{action}" description = "tv_trade_cancel_selected_{action}_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_cancel_selected_{action}" }} }}
\t\t\t\t\t\t\t\t}}
"""


def projected_embargo_row() -> str:
    active = projected_var("tv_trade_selected_embargo_active")
    location = projected_var("tv_trade_selected_embargo_location")
    country = projected_var("tv_trade_selected_embargo_country")
    used = projected_var("tv_trade_selected_embargo_used_pct")
    leader_visible = projected_leader_visible()
    return f"""\
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "[GreaterThanOrEqualTo_CFixedPoint({active}.GetValue, '(CFixedPoint)1.0')]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 28 }}
\t\t\t\t\t\t\t\t\tspacing = 4
{projected_market_link(location, 140, 26)}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 116 26 }}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 116 26 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 20 26 }} raw_text = "@trade_advantage!" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 92 26 }} text = "TV_TRADE_LEAGUE_EMBARGO" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 126 26 }} text_single = {{ size = {{ 126 26 }} raw_text = "[{country}.GetCountry.GetNameWithFlag]" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 48 26 }} text_single = {{ size = {{ 48 26 }} raw_text = "[{used}.GetValue|0]%" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ visible = "{leader_visible}" size = {{ 28 24 }} using = button_regular_texture_alt_red using = action_button_common_template using = button_common_textobj_template text = "X" title = "tv_trade_cancel_selected_embargo" description = "tv_trade_cancel_selected_embargo_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_cancel_selected_embargo" }} }}
\t\t\t\t\t\t\t\t}}
"""


def projected_market_metric_cell(prefix: str, rank: int, field: str, width: int = 58) -> str:
    variable = projected_var(f"tv_trade_selected_{prefix}_{field}_{rank}")
    return f"""\
\t\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ {width} 20 }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ {width} 20 }} raw_text = "[{variable}.GetValue|0]" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t}}
"""


def projected_market_info_row(prefix: str, rank: int) -> str:
    market = projected_var(f"tv_trade_selected_{prefix}_market_{rank}")
    control = projected_var(f"tv_trade_selected_{prefix}_control_pct_{rank}")
    route_total_field = "total_import" if prefix == "consumer" else "total_export"
    route_io_field = "io_import" if prefix == "consumer" else "io_export"
    return f"""\
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "[{market}.IsSet]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 22 }}
\t\t\t\t\t\t\t\t\tspacing = 4
{projected_market_link(market, 166)}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 44 20 }} text_single = {{ size = {{ 44 20 }} raw_text = "[{control}.GetValue|0]%" align = nobaseline|right }} }}
{projected_market_metric_cell(prefix, rank, "local_demand")}{projected_market_metric_cell(prefix, rank, "local_production")}{projected_market_metric_cell(prefix, rank, route_total_field)}{projected_market_metric_cell(prefix, rank, route_io_field)}\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tvisible = "[Not({market}.IsSet)]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 22 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 166 20 }} text_single = {{ size = {{ 166 20 }} raw_text = "-" align = nobaseline|left }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 44 20 }} text_single = {{ size = {{ 44 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} raw_text = "-" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t}}
"""


def projected_market_info_section(prefix: str, title: str) -> str:
    rows = "".join(projected_market_info_row(prefix, rank) for rank in range(1, 4))
    route_total_column = "TV_TRADE_LEAGUE_TOTAL_IMPORT_COLUMN" if prefix == "consumer" else "TV_TRADE_LEAGUE_TOTAL_EXPORT_COLUMN"
    route_io_column = "TV_TRADE_LEAGUE_IO_IMPORT_COLUMN" if prefix == "consumer" else "TV_TRADE_LEAGUE_IO_EXPORT_COLUMN"
    return f"""\
\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\tsize = {{ 462 112 }}
\t\t\t\t\t\t\t\t\tignoreinvisible = yes
\t\t\t\t\t\t\t\t\tspacing = 2
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 22 }} text = "{title}" align = nobaseline|center }}
\t\t\t\t\t\t\t\t\twidget = {{
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\tsize = {{ 462 20 }}
\t\t\t\t\t\t\t\t\t\tbackground = {{ using = tooltip_table_field_texture alpha = 0.18 }}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = fixed
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_vertical = fixed
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 462 20 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 166 20 }} text_single = {{ size = {{ 166 20 }} text = "TV_TRADE_LEAGUE_MARKET_COLUMN" align = nobaseline|left }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 44 20 }} text_single = {{ size = {{ 44 20 }} text = "TV_TRADE_LEAGUE_CONTROL_COLUMN" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} text = "TV_TRADE_LEAGUE_LOCAL_DEMAND_COLUMN" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} text = "TV_TRADE_LEAGUE_LOCAL_PRODUCTION_COLUMN" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} text = "{route_total_column}" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t\twidget = {{ layoutpolicy_horizontal = fixed layoutpolicy_vertical = fixed size = {{ 58 20 }} text_single = {{ size = {{ 58 20 }} text = "{route_io_column}" align = nobaseline|right }} }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
{rows}\t\t\t\t\t\t\t\t}}
"""


def projected_market_intelligence() -> str:
    return (
        projected_market_info_section("origin", "TV_TRADE_LEAGUE_PRODUCTION_MARKETS_TITLE")
        + projected_market_info_section("node", "TV_TRADE_LEAGUE_KEY_NODES_TITLE")
        + projected_market_info_section("consumer", "TV_TRADE_LEAGUE_CONSUMER_MARKETS_TITLE")
    )


def projected_detail_icon_entries(goods: list[str]) -> str:
    entries: list[str] = []
    for index, good in enumerate(goods, start=1):
        entries.append(
            f"""\t\t\t\t\t\t\t\t\ticon = {{ visible = "{projected_selected_good_visible(index)}" size = {{ 48 48 }} texture = "gfx/interface/icons/trade_goods/icon_goods_{good}.dds" }}"""
        )
    return "\n".join(entries)


def projected_detail_name_entries(goods: list[str]) -> str:
    entries: list[str] = []
    for index, good in enumerate(goods, start=1):
        entries.append(
            f"""\t\t\t\t\t\t\t\t\t\ttext_single = {{ visible = "{projected_selected_good_visible(index)}" size = {{ 340 24 }} text = "{good}" align = nobaseline|left }}"""
        )
    return "\n".join(entries)


def projected_detail_card(goods: list[str]) -> str:
    selected = projected_var("tv_trade_selected_good")
    selected_visible = f"[And({selected}.IsSet, GreaterThan_CFixedPoint({selected}.GetValue, '(CFixedPoint)0.0'))]"
    monopoly = projected_var("tv_trade_selected_monopoly")
    monopoly_pct = projected_var("tv_trade_selected_monopoly_level_pct")
    used_pct = projected_var("tv_trade_selected_used_monopoly_level_pct")
    available_pct = projected_var("tv_trade_selected_available_monopoly_level_pct")
    demand_active = projected_var("tv_trade_selected_virtual_demand_active")
    supply_active = projected_var("tv_trade_selected_virtual_supply_active")
    embargo_active = projected_var("tv_trade_selected_embargo_active")
    return f"""\
\t\t\t\t\tcard_common = {{
\t\t\t\t\t\tvisible = "{selected_visible}"
\t\t\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_MONOPOLY_DETAIL_TITLE"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\t\tmargin = {{ 4 6 }}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 60 }}
\t\t\t\t\t\t\t\t\tspacing = 8
{projected_detail_icon_entries(goods)}
\t\t\t\t\t\t\t\t\tpiechart = {{
\t\t\t\t\t\t\t\t\t\tsize = {{ 54 54 }}
\t\t\t\t\t\t\t\t\t\tusing = piechart_angles
\t\t\t\t\t\t\t\t\t\ticon = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" size = {{ 97% 97% }} parentanchor = center color = {{ 0.45 0.59 0.67 1 }} alpha = 0.3 }}
\t\t\t\t\t\t\t\t\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = "[FixedPointToFloat({monopoly_pct}.GetValue)]" color = {{ 0.85 0.65 0.22 1 }} alpha = 0.8 }}
\t\t\t\t\t\t\t\t\t\tpieslice = {{ texture = "gfx/interface/pie_charts/pie_chart_alpha_80.dds" value = "[Subtract_float('(float){MONOPOLY_DISPLAY_MAX_PCT}.0', FixedPointToFloat({monopoly_pct}.GetValue))]" color = {{ 1 1 1 0 }} }}
\t\t\t\t\t\t\t\t\t\tusing = bg_circle_piechart
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\t\t\tsize = {{ 340 54 }}
\t\t\t\t\t\t\t\t\t\tignoreinvisible = yes
{projected_detail_name_entries(goods)}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tvisible = "[GreaterThanOrEqualTo_CFixedPoint({monopoly}.GetValue, '(CFixedPoint)1.0')]"
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 340 24 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 20 24 }} raw_text = "@trigger_yes!" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 58 24 }} raw_text = "[{monopoly_pct}.GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 250 24 }} text = "TV_TRADE_LEAGUE_MONOPOLY_COLUMN" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\t\t\tvisible = "[Not(GreaterThanOrEqualTo_CFixedPoint({monopoly}.GetValue, '(CFixedPoint)1.0'))]"
\t\t\t\t\t\t\t\t\t\t\tsize = {{ 340 24 }}
\t\t\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 20 24 }} raw_text = "@trade!" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 58 24 }} raw_text = "[{monopoly_pct}.GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 250 24 }} text = "TV_TRADE_LEAGUE_NOT_MONOPOLIZED" align = nobaseline|left }}
\t\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 24 }} text = "TV_TRADE_LEAGUE_USED_LEVEL_TITLE" align = nobaseline|center }}
\t\t\t\t\t\t\t\tprogressbar = {{ size = {{ 462 18 }} max = {MONOPOLY_DISPLAY_MAX_PCT} value = "[{monopoly_pct}.GetValue]" using = progress_bar_goldish }}
\t\t\t\t\t\t\t\tprogressbar = {{ size = {{ 462 18 }} max = {MONOPOLY_DISPLAY_MAX_PCT} value = "[{used_pct}.GetValue]" using = progress_bar_blue_alt }}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 24 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 378 24 }} text = "TV_TRADE_LEAGUE_AVAILABLE_LEVEL" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 80 24 }} raw_text = "[{available_pct}.GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 24 }} text = "TV_TRADE_LEAGUE_MARKET_INTELLIGENCE_TITLE" align = nobaseline|center }}
{projected_market_intelligence()}
\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 462 24 }} text = "TV_TRADE_LEAGUE_ACTION_LIST_TITLE" align = nobaseline|center }}
{projected_action_row("virtual_demand", "TV_TRADE_LEAGUE_VIRTUAL_DEMAND", "@demand!")}
{projected_action_row("virtual_supply", "TV_TRADE_LEAGUE_VIRTUAL_PRODUCTION", "@supply!")}
{projected_embargo_row()}
\t\t\t\t\t\t\t\ttext_multi = {{
\t\t\t\t\t\t\t\t\tvisible = "[And3(Not(GreaterThanOrEqualTo_CFixedPoint({demand_active}.GetValue, '(CFixedPoint)1.0')), Not(GreaterThanOrEqualTo_CFixedPoint({supply_active}.GetValue, '(CFixedPoint)1.0')), Not(GreaterThanOrEqualTo_CFixedPoint({embargo_active}.GetValue, '(CFixedPoint)1.0')))]"
\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\t\tautoresize = yes
\t\t\t\t\t\t\t\t\tmax_width = 462
\t\t\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_NO_ACTIONS"
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
"""


def projected_action_card() -> str:
    monopoly = projected_var("tv_trade_selected_monopoly")
    available = projected_var("tv_trade_selected_available_monopoly_level_pct")
    visible = (
        "[And("
        f"GreaterThanOrEqualTo_CFixedPoint({monopoly}.GetValue, '(CFixedPoint)1.0'), "
        "InternationalOrganizationsView.GetInternationalOrganization.IsIOLeaderCountry(InternationalOrganizationsView.GetPlayer))]"
    )
    return f"""\
\t\t\t\t\tcard_common = {{
\t\t\t\t\t\tvisible = "{visible}"
\t\t\t\t\t\tmaximumsize = {{ 500 -1 }}
\t\t\t\t\t\tblockoverride "common_header_icon_texture" {{
\t\t\t\t\t\t\ttexture = "gfx/interface/icons/flat_icons/trade.dds"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_header_text" {{
\t\t\t\t\t\t\ttext = "TV_TRADE_LEAGUE_MONOPOLY_ACTIONS_TITLE"
\t\t\t\t\t\t}}
\t\t\t\t\t\tblockoverride "common_bottom_content" {{
\t\t\t\t\t\t\tvbox = {{
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\t\tmargin = {{ 4 6 }}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 24 }}
\t\t\t\t\t\t\t\t\tspacing = 4
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 378 24 }} text = "TV_TRADE_LEAGUE_AVAILABLE_LEVEL" align = nobaseline|right }}
\t\t\t\t\t\t\t\t\ttext_single = {{ size = {{ 80 24 }} raw_text = "[{available}.GetValue|0]%" align = nobaseline|right }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\thbox = {{
\t\t\t\t\t\t\t\t\tsize = {{ 462 30 }}
\t\t\t\t\t\t\t\t\tspacing = 8
\t\t\t\t\t\t\t\t\taction_button = {{ size = {{ 227 28 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "TV_TRADE_LEAGUE_VIRTUAL_DEMAND" title = "tv_trade_set_selected_virtual_demand" description = "tv_trade_set_selected_virtual_demand_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_set_selected_virtual_demand" }} }}
\t\t\t\t\t\t\t\t\taction_button = {{ size = {{ 227 28 }} using = button_regular_texture_alt_yellow using = action_button_common_template using = button_common_textobj_template text = "TV_TRADE_LEAGUE_VIRTUAL_PRODUCTION" title = "tv_trade_set_selected_virtual_supply" description = "tv_trade_set_selected_virtual_supply_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_set_selected_virtual_supply" }} }}
\t\t\t\t\t\t\t\t}}
\t\t\t\t\t\t\t\taction_button = {{ size = {{ 462 28 }} using = button_regular_texture_alt_red using = action_button_common_template using = button_common_textobj_template text = "TV_TRADE_LEAGUE_EMBARGO" title = "tv_trade_set_selected_embargo" description = "tv_trade_set_selected_embargo_desc" actor = "[InternationalOrganizationsView.GetPlayer]" left_action = {{ action_name = "tv_trade_set_selected_embargo" }} }}
\t\t\t\t\t\t\t}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
"""


def projected_generate(data: dict, chain_data: dict) -> str:
    slots = "".join(
        projected_monopoly_slot_card(slot, data["goods"])
        for slot in range(1, MONOPOLY_SLOT_COUNT + 1)
    )
    return (
        HEADER
        + PREFIX
        + trade_chain_overview(chain_data)
        + intelligence_content()
        + MONOPOLY_PREFIX
        + slots
        + LIST_CARD_SUFFIX
        + projected_detail_card(data["goods"])
        + projected_action_card()
        + SUFFIX
    )


generate = projected_generate


def main() -> None:
    with DATA_FILE.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)
    with TRADE_CHAIN_FILE.open(encoding="utf-8") as file:
        chain_data = yaml.safe_load(file)
    OUT_FILE.write_text(generate(data, chain_data), encoding="utf-8-sig")
    print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
