l_korean:
 cmf_settings_title: "커뮤니티 모드 프레임워크"
 cmf_settings_page_action_bar: "액션 바"
 cmf_settings_action_bar_group_layout: "레이아웃"
 cmf_settings_action_bar_position_activate: "이 위치 활성화"
 cmf_settings_action_bar_position: "액션 바 위치"
 cmf_settings_action_bar_position_top: "최상단"
 cmf_settings_action_bar_position_bottom_left: "좌측 하단"
 cmf_settings_action_bar_position_bottom_right: "우측 하단"
 cmf_settings_action_bar_group_active_buttons: "활성화된 버튼"
 cmf_settings_action_bar_group_active_button_activate: "활성화 버튼"
 cmf_settings_action_bar_group_active_button_deactivate: "비활성화 버튼"
