"""
Generate src/in_game/events/tv_research_d_events.txt from data/research_d_events.yaml.
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml


REPO_ROOT = Path(__file__).resolve().parents[3]
DATA_FILE = REPO_ROOT / "data" / "research_d_events.yaml"
OUT_FILE = REPO_ROOT / "src" / "in_game" / "events" / "tv_research_d_events.txt"
T = "\t"

GROUP_TRIGGERS = {
    "all": [],
    "tier1": ["tv_chief_scientist_effective_adm_less_than_20_trigger = yes"],
    "tier1_2": ["tv_chief_scientist_effective_adm_less_than_50_trigger = yes"],
    "tier2": [
        "tv_chief_scientist_effective_adm_at_least_20_trigger = yes",
        "tv_chief_scientist_effective_adm_less_than_50_trigger = yes",
    ],
    "tier2_3": [
        "tv_chief_scientist_effective_adm_at_least_20_trigger = yes",
        "tv_chief_scientist_effective_adm_less_than_80_trigger = yes",
    ],
    "tier3": [
        "tv_chief_scientist_effective_adm_at_least_50_trigger = yes",
        "tv_chief_scientist_effective_adm_less_than_80_trigger = yes",
    ],
    "tier3_4": ["tv_chief_scientist_effective_adm_at_least_50_trigger = yes"],
    "tier4": ["tv_chief_scientist_effective_adm_at_least_80_trigger = yes"],
}


def indent_lines(text: str, level: int) -> str:
    lines = text.rstrip().splitlines()
    return "\n".join((T * level + line if line.strip() else "") for line in lines)


def render_trigger(event: dict) -> str:
    group = event["group"]
    lines = [
        "trigger = {",
        T + "has_variable = tv_academy_io_member",
        T + "var:tv_research_phase ?= 2",
        T + "has_variable = tv_academy_leader_char",
        T + "var:tv_academy_leader_char ?= { is_alive = yes }",
    ]
    lines.extend(T + line for line in GROUP_TRIGGERS[group])
    if event.get("requires_cabinet"):
        lines.append(T + "any_cabinet_character = { count > 0 }")
    lines.append("}")
    return "\n".join(lines)


def render_desc(event_id: int, desc_type: str | None) -> str:
    if desc_type != "tiered":
        return f"desc = tv_research.{event_id}.d"

    variants = [
        ("tier1", "tv_chief_scientist_effective_adm_less_than_20_trigger = yes"),
        (
            "tier2",
            "tv_chief_scientist_effective_adm_at_least_20_trigger = yes tv_chief_scientist_effective_adm_less_than_50_trigger = yes",
        ),
        (
            "tier3",
            "tv_chief_scientist_effective_adm_at_least_50_trigger = yes tv_chief_scientist_effective_adm_less_than_80_trigger = yes",
        ),
        ("tier4", "tv_chief_scientist_effective_adm_at_least_80_trigger = yes"),
    ]
    lines = ["desc = {", T + "first_valid = {"]
    for suffix, trigger in variants:
        lines.extend(
            [
                T * 2 + "triggered_desc = {",
                T * 3 + f"trigger = {{ {trigger} }}",
                T * 3 + f"desc = tv_research.{event_id}.d_{suffix}",
                T * 2 + "}",
            ]
        )
    lines.extend([T + "}", "}"])
    return "\n".join(lines)


def render_immediate(event: dict) -> str:
    lines = [
        "immediate = {",
        T + "var:tv_academy_leader_char ?= { save_scope_as = tv_research_scientist }",
    ]
    if event.get("save_cabinet"):
        lines.extend(
            [
                T + "random_cabinet_character = {",
                T * 2 + "save_scope_as = tv_research_cabinet",
                T + "}",
            ]
        )
    lines.append("}")
    return "\n".join(lines)


def render_option(event_id: int, option: dict) -> str:
    lines = [
        "option = {",
        T + f"name = tv_research.{event_id}.{option['suffix']}",
    ]
    effect = option.get("effect")
    if effect:
        lines.append(indent_lines(effect, 1))
    lines.append("}")
    return "\n".join(lines)


def render_event(event: dict) -> str:
    event_id = event["id"]
    parts = [
        f"# -- tv_research.{event_id} -----------------------------------------------------",
        f"tv_research.{event_id} = {{",
        T + "type = country_event",
        T + f"title = tv_research.{event_id}.t",
        indent_lines(render_desc(event_id, event.get("desc")), 1),
        T + f"outcome = {event['outcome']}",
        "",
        indent_lines(render_trigger(event), 1),
        "",
        indent_lines(render_immediate(event), 1),
        "",
    ]
    rendered_options = [indent_lines(render_option(event_id, option), 1) for option in event["options"]]
    parts.append("\n".join(rendered_options))
    parts.append("}")
    return "\n".join(parts)


def generate(data: dict) -> str:
    header = """# @Generated by scripts/in_game/events/gen_tv_research_d_events.py
#   Data:    data/research_d_events.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/events/gen_tv_research_d_events.py
# Do not edit directly - modify the data file and re-run the generator.
# Towards Victory - Concentrated Research random events.

namespace = tv_research
"""
    events = "\n\n".join(render_event(event) for event in data["events"])
    return f"{header}\n{events}\n"


def main() -> None:
    with open(DATA_FILE, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    OUT_FILE.write_text(generate(data), encoding="utf-8-sig")
    print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
