l_spanish:
 cmf_settings_title: "Marco de trabajo de mods de la comunidad"
 cmf_settings_page_action_bar: "Barra de acciones"
 cmf_settings_action_bar_group_layout: "Diseño"
 cmf_settings_action_bar_position_activate: "Activar esta posición"
 cmf_settings_action_bar_position: "Posición de la barra de acciones"
 cmf_settings_action_bar_position_top: "Arriba"
 cmf_settings_action_bar_position_bottom_left: "Inferior izquierda"
 cmf_settings_action_bar_position_bottom_right: "Abajo a la derecha"
 cmf_settings_action_bar_group_active_buttons: "Botones activos"
 cmf_settings_action_bar_group_active_button_activate: "Activar botón"
 cmf_settings_action_bar_group_active_button_deactivate: "Botón de desactivación"
