"""
Generate generated English localization for Trade League monopoly controls.
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "trade_league_goods.yaml"
OUT_FILE = (
    REPO_ROOT
    / "src"
    / "main_menu"
    / "localization"
    / "english"
    / "tv_trade_league_monopoly_l_english.yml"
)


def good_name(good: str) -> str:
    return f"${good}$"


def action_entries(good: str) -> list[tuple[str, str]]:
    name = good_name(good)
    action_loc_entries = [
        (f"tv_trade_select_monopoly_good_{good}", f"Select {name}"),
        (f"tv_trade_select_monopoly_good_{good}_desc", f"Show monopoly details for {name}."),
        (f"tv_trade_set_virtual_demand_{good}", f"Virtual Demand: {name}"),
        (
            f"tv_trade_set_virtual_demand_{good}_desc",
            f"Allocate monopoly level to create temporary {name} demand in a selected market.",
        ),
        (f"tv_trade_increase_virtual_demand_{good}", f"Increase Virtual Demand: {name}"),
        (f"tv_trade_increase_virtual_demand_{good}_desc", f"Use 1 more monopoly level on virtual {name} demand."),
        (f"tv_trade_decrease_virtual_demand_{good}", f"Decrease Virtual Demand: {name}"),
        (f"tv_trade_decrease_virtual_demand_{good}_desc", f"Release 1 monopoly level from virtual {name} demand."),
        (f"tv_trade_cancel_virtual_demand_{good}", f"Cancel Virtual Demand: {name}"),
        (f"tv_trade_cancel_virtual_demand_{good}_desc", f"Remove the virtual {name} demand action."),
        (f"tv_trade_set_virtual_supply_{good}", f"Virtual Production: {name}"),
        (
            f"tv_trade_set_virtual_supply_{good}_desc",
            f"Allocate monopoly level to create temporary {name} production in a selected market.",
        ),
        (f"tv_trade_increase_virtual_supply_{good}", f"Increase Virtual Production: {name}"),
        (f"tv_trade_increase_virtual_supply_{good}_desc", f"Use 1 more monopoly level on virtual {name} production."),
        (f"tv_trade_decrease_virtual_supply_{good}", f"Decrease Virtual Production: {name}"),
        (f"tv_trade_decrease_virtual_supply_{good}_desc", f"Release 1 monopoly level from virtual {name} production."),
        (f"tv_trade_cancel_virtual_supply_{good}", f"Cancel Virtual Production: {name}"),
        (f"tv_trade_cancel_virtual_supply_{good}_desc", f"Remove the virtual {name} production action."),
        (f"tv_trade_set_embargo_{good}", f"Embargo: {name}"),
        (
            f"tv_trade_set_embargo_{good}_desc",
            f"Spend 10 monopoly level to give a country -50 trade advantage in a selected market.",
        ),
        (f"tv_trade_cancel_embargo_{good}", f"Cancel Embargo: {name}"),
        (f"tv_trade_cancel_embargo_{good}_desc", f"Remove the {name} embargo action."),
    ]
    entries = [
        (f"tv_trade_virtual_demand_{good}", f"Trade League Virtual Demand: {name}"),
        *action_loc_entries,
    ]
    actions = [key for key, _ in action_loc_entries if not key.endswith("_desc")]
    for action in actions:
        entries.extend(
            [
                (f"PERFORM_{action}_ACTION_SETUP", "When we use a Trade League monopoly control."),
                (f"PERFORM_{action}_ACTION_LOG", "We used a Trade League monopoly control."),
                (f"PERFORM_{action}_ACTION_MAP", ""),
            ]
        )
    return entries


def generate(data: dict) -> bytes:
    lines = [
        "l_english:",
        "# @Generated by scripts/main_menu/localization/english/gen_tv_trade_league_monopoly_l_english.py",
        "#   Data:    data/trade_league_goods.yaml",
        "#   Regen:   conda run --no-capture-output -n eu5 python scripts/main_menu/localization/english/gen_tv_trade_league_monopoly_l_english.py",
        "# Do not edit directly - modify the data file and re-run the generator.",
        "",
    ]
    for good in data["goods"]:
        for key, value in action_entries(good):
            escaped = value.replace('"', '\\"')
            lines.append(f' {key}: "{escaped}"')
    text = "\n".join(lines) + "\n"
    return b"\xef\xbb\xbf" + text.encode("utf-8")


def main() -> None:
    with DATA_FILE.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)
    OUT_FILE.write_bytes(generate(data))
    print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
