"""
Generate generated Simplified Chinese localization for Trade League monopoly controls.
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "trade_league_goods.yaml"
OUT_FILE = (
    REPO_ROOT
    / "src"
    / "main_menu"
    / "localization"
    / "simp_chinese"
    / "tv_trade_league_monopoly_l_simp_chinese.yml"
)

VIRTUAL_ACTION_COST_PCT = 5
EMBARGO_COST_PCT = 30


def good_name(good: str) -> str:
    return f"${good}$"


CATEGORY_LABELS = {
    "basic": ("基础商品", "在垄断列表中显示基础商品。"),
    "food": ("食品", "在垄断列表中显示食品。"),
    "manufactured": ("制成品", "在垄断列表中显示制成品。"),
    "luxury": ("奢侈品", "在垄断列表中显示奢侈品。"),
}


def category_entries(categories: list[dict]) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for category in categories:
        label, desc = CATEGORY_LABELS[category["id"]]
        action = category["action"]
        entries.extend(
            [
                (action, label),
                (f"{action}_desc", desc),
                (f"PERFORM_{action}_ACTION_SETUP", "当我们使用贸易联盟垄断控制时。"),
                (f"PERFORM_{action}_ACTION_LOG", "我们使用了一项贸易联盟垄断控制。"),
                (f"PERFORM_{action}_ACTION_MAP", ""),
            ]
        )
    return entries


def action_entries(good: str) -> list[tuple[str, str]]:
    name = good_name(good)
    action_loc_entries = [
        (f"tv_trade_select_monopoly_good_{good}", f"选择{name}"),
        (f"tv_trade_select_monopoly_good_{good}_desc", f"显示{name}的垄断详情。"),
        (f"tv_trade_set_virtual_demand_{good}", f"虚构需求：{name}"),
        (f"tv_trade_set_virtual_demand_{good}_desc", f"分配垄断水平，在选定市场创造临时{name}需求。"),
        (f"tv_trade_increase_virtual_demand_{good}", f"增加虚构需求：{name}"),
        (f"tv_trade_increase_virtual_demand_{good}_desc", f"为{name}虚构需求额外使用{VIRTUAL_ACTION_COST_PCT}%垄断水平。"),
        (f"tv_trade_decrease_virtual_demand_{good}", f"减少虚构需求：{name}"),
        (f"tv_trade_decrease_virtual_demand_{good}_desc", f"从{name}虚构需求释放{VIRTUAL_ACTION_COST_PCT}%垄断水平。"),
        (f"tv_trade_cancel_virtual_demand_{good}", f"取消虚构需求：{name}"),
        (f"tv_trade_cancel_virtual_demand_{good}_desc", f"移除{name}虚构需求行动。"),
        (f"tv_trade_set_virtual_supply_{good}", f"虚构生产：{name}"),
        (f"tv_trade_set_virtual_supply_{good}_desc", f"分配垄断水平，在选定市场创造临时{name}生产。"),
        (f"tv_trade_increase_virtual_supply_{good}", f"增加虚构生产：{name}"),
        (f"tv_trade_increase_virtual_supply_{good}_desc", f"为{name}虚构生产额外使用{VIRTUAL_ACTION_COST_PCT}%垄断水平。"),
        (f"tv_trade_decrease_virtual_supply_{good}", f"减少虚构生产：{name}"),
        (f"tv_trade_decrease_virtual_supply_{good}_desc", f"从{name}虚构生产释放{VIRTUAL_ACTION_COST_PCT}%垄断水平。"),
        (f"tv_trade_cancel_virtual_supply_{good}", f"取消虚构生产：{name}"),
        (f"tv_trade_cancel_virtual_supply_{good}_desc", f"移除{name}虚构生产行动。"),
        (f"tv_trade_set_embargo_{good}", f"禁运：{name}"),
        (f"tv_trade_set_embargo_{good}_desc", f"消耗{EMBARGO_COST_PCT}%垄断水平，使一个国家在选定市场获得-50贸易优势。"),
        (f"tv_trade_cancel_embargo_{good}", f"取消禁运：{name}"),
        (f"tv_trade_cancel_embargo_{good}_desc", f"移除{name}禁运行动。"),
    ]
    entries = [
        (f"tv_trade_virtual_demand_{good}", f"贸易联盟虚构需求：{name}"),
        *action_loc_entries,
    ]
    actions = [key for key, _ in action_loc_entries if not key.endswith("_desc")]
    for action in actions:
        entries.extend(
            [
                (f"PERFORM_{action}_ACTION_SETUP", "当我们使用贸易联盟垄断控制时。"),
                (f"PERFORM_{action}_ACTION_LOG", "我们使用了一项贸易联盟垄断控制。"),
                (f"PERFORM_{action}_ACTION_MAP", ""),
            ]
        )
    return entries


def generate(data: dict) -> bytes:
    lines = [
        "l_simp_chinese:",
        "# @Generated by scripts/main_menu/localization/simp_chinese/gen_tv_trade_league_monopoly_l_simp_chinese.py",
        "#   Data:    data/trade_league_goods.yaml",
        "#   Regen:   conda run --no-capture-output -n eu5 python scripts/main_menu/localization/simp_chinese/gen_tv_trade_league_monopoly_l_simp_chinese.py",
        "# Do not edit directly - modify the data file and re-run the generator.",
        "",
    ]
    for key, value in category_entries(data["categories"]):
        escaped = value.replace('"', '\\"')
        lines.append(f' {key}: "{escaped}"')
    for good in data["goods"]:
        for key, value in action_entries(good):
            escaped = value.replace('"', '\\"')
            lines.append(f' {key}: "{escaped}"')
    text = "\n".join(lines) + "\n"
    return b"\xef\xbb\xbf" + text.encode("utf-8")


def main() -> None:
    with DATA_FILE.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)
    OUT_FILE.write_bytes(generate(data))
    print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
