l_turkish:
 cmf_settings_title: "Topluluk Mod Çerçevesi"
 cmf_settings_page_action_bar: "Eylem Çubuğu"
 cmf_settings_action_bar_group_layout: "Düzen"
 cmf_settings_action_bar_position_activate: "Bu pozisyonu etkinleştir"
 cmf_settings_action_bar_position: "Eylem Çubuğu Konumu"
 cmf_settings_action_bar_position_top: "Üst"
 cmf_settings_action_bar_position_bottom_left: "Sol Alt"
 cmf_settings_action_bar_position_bottom_right: "Sağ Alt"
 cmf_settings_action_bar_group_active_buttons: "Aktif Butonlar"
 cmf_settings_action_bar_group_active_button_activate: "Butonu Aktifleştir"
 cmf_settings_action_bar_group_active_button_deactivate: "Düğmeyi Devre Dışı Bırak"
