l_simp_chinese:
 cheat_ski_tab_diplomats: "Diplomats"
 cheat_ski_tab_gold: "Gold"
 cheat_ski_tab_legitimacy: "Legitimacy"
 cheat_ski_tab_manpower: "Manpower"
 cheat_ski_tab_prestige: "Prestige"
 cheat_ski_tab_sailors: "Sailors"
 cheat_ski_tab_stability: "Stability"
 cheat_ski_tab_war_exhaustion: "War Exhaustion"
 cheat_ski_button_diplomats: "Diplomats"
 cheat_ski_button_gold: "Gold"
 cheat_ski_button_legitimacy: "Legitimacy"
 cheat_ski_button_manpower: "Manpower"
 cheat_ski_button_prestige: "Prestige"
 cheat_ski_button_sailors: "Sailors"
 cheat_ski_button_stability: "Stability"
 cheat_ski_button_war_exhaustion: "War Exhaustion"
 STATIC_MODIFIER_NAME_ski_country_stats_config_diplomats_diplomats_minus_1: "Diplomats -1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_diplomats_diplomats_minus_5: "Diplomats -5"
 STATIC_MODIFIER_NAME_ski_country_stats_config_diplomats_diplomats_plus_1: "Diplomats +1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_diplomats_diplomats_plus_5: "Diplomats +5"
 STATIC_MODIFIER_NAME_ski_country_stats_config_gold_gold_minus_10: "Gold -10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_gold_gold_minus_100: "Gold -100"
 STATIC_MODIFIER_NAME_ski_country_stats_config_gold_gold_minus_1000: "Gold -1000"
 STATIC_MODIFIER_NAME_ski_country_stats_config_gold_gold_minus_10000: "Gold -10000"
 STATIC_MODIFIER_NAME_ski_country_stats_config_gold_gold_plus_10: "Gold +10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_gold_gold_plus_100: "Gold +100"
 STATIC_MODIFIER_NAME_ski_country_stats_config_gold_gold_plus_1000: "Gold +1000"
 STATIC_MODIFIER_NAME_ski_country_stats_config_gold_gold_plus_10000: "Gold +10000"
 STATIC_MODIFIER_NAME_ski_country_stats_config_legitimacy_legitimacy_minus_1: "Legitimacy -1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_legitimacy_legitimacy_minus_10: "Legitimacy -10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_legitimacy_legitimacy_plus_1: "Legitimacy +1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_legitimacy_legitimacy_plus_10: "Legitimacy +10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_manpower_manpower_minus_0.1: "Manpower -0.1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_manpower_manpower_minus_1: "Manpower -1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_manpower_manpower_minus_10: "Manpower -10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_manpower_manpower_minus_100: "Manpower -100"
 STATIC_MODIFIER_NAME_ski_country_stats_config_manpower_manpower_plus_0.1: "Manpower +0.1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_manpower_manpower_plus_1: "Manpower +1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_manpower_manpower_plus_10: "Manpower +10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_manpower_manpower_plus_100: "Manpower +100"
 STATIC_MODIFIER_NAME_ski_country_stats_config_prestige_prestige_minus_1: "Prestige -1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_prestige_prestige_minus_10: "Prestige -10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_prestige_prestige_plus_1: "Prestige +1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_prestige_prestige_plus_10: "Prestige +10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_sailors_sailors_minus_0.1: "Sailors -0.1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_sailors_sailors_minus_1: "Sailors -1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_sailors_sailors_minus_10: "Sailors -10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_sailors_sailors_minus_100: "Sailors -100"
 STATIC_MODIFIER_NAME_ski_country_stats_config_sailors_sailors_plus_0.1: "Sailors +0.1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_sailors_sailors_plus_1: "Sailors +1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_sailors_sailors_plus_10: "Sailors +10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_sailors_sailors_plus_100: "Sailors +100"
 STATIC_MODIFIER_NAME_ski_country_stats_config_stability_stability_minus_1: "Stability -1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_stability_stability_minus_10: "Stability -10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_stability_stability_plus_1: "Stability +1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_stability_stability_plus_10: "Stability +10"
 STATIC_MODIFIER_NAME_ski_country_stats_config_war_exhaustion_war_exhaustion_minus_1: "War Exhaustion -1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_war_exhaustion_war_exhaustion_minus_5: "War Exhaustion -5"
 STATIC_MODIFIER_NAME_ski_country_stats_config_war_exhaustion_war_exhaustion_plus_1: "War Exhaustion +1"
 STATIC_MODIFIER_NAME_ski_country_stats_config_war_exhaustion_war_exhaustion_plus_5: "War Exhaustion +5"