l_simp_chinese:
 cheat_ski_tab_attributes: "Attributes"
 cheat_ski_tab_skills: "Skills"
 cheat_ski_button_administrative_skill: "Administrative Skill"
 cheat_ski_button_age: "Age"
 cheat_ski_button_diplomatic_skill: "Diplomatic Skill"
 cheat_ski_button_life_expectancy: "Life Expectancy"
 cheat_ski_button_military_skill: "Military Skill"
 STATIC_MODIFIER_NAME_ski_character_edit_config_attributes_character_life_expectancy_minus_1: "Life Expectancy -1"
 STATIC_MODIFIER_NAME_ski_character_edit_config_attributes_character_life_expectancy_minus_5: "Life Expectancy -5"
 STATIC_MODIFIER_NAME_ski_character_edit_config_attributes_character_life_expectancy_plus_1: "Life Expectancy +1"
 STATIC_MODIFIER_NAME_ski_character_edit_config_attributes_character_life_expectancy_plus_5: "Life Expectancy +5"