"""Generate Academy philosophy debate drift and endpoint scripted effects."""

import sys
import argparse
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "philosophy_debates.yaml"
OUT_FILE = (
    REPO_ROOT
    / "src"
    / "in_game"
    / "common"
    / "scripted_effects"
    / "tv_academy_philosophy_debate_effects.txt"
)

HEADER = """\
# @Generated by scripts/in_game/common/scripted_effects/gen_tv_academy_philosophy_debate_effects.py
#   Data:    data/philosophy_debates.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/scripted_effects/gen_tv_academy_philosophy_debate_effects.py
# Do not edit directly - modify the data file and re-run the generator.
"""

TEMP_VALUE_VAR = "tv_academy_philosophy_direction_value"
TEMP_CONTRIB_VAR = "tv_academy_philosophy_direction_contribution"
MONTHLY_DELTA_VAR = "tv_academy_philosophy_monthly_delta"
PENDING_RESULT_VAR = "tv_academy_philosophy_result_pending"
PENDING_ISSUE_VAR = "tv_academy_philosophy_result_issue"
PENDING_KIND_VAR = "tv_academy_philosophy_result_kind"

WEIGHT_EFFECTS = {
    "high": "tv_academy_philosophy_add_high_direction_effect",
    "medium": "tv_academy_philosophy_add_medium_direction_effect",
    "low": "tv_academy_philosophy_add_low_direction_effect",
}


def fmt(value: float) -> str:
    return f"{value:.5f}"


def emit(lines: list[str], level: int = 0, text: str = "") -> None:
    lines.append("\t" * level + text if text else "")


def validate_data(data: dict) -> None:
    settings = data.get("settings") or {}
    directions = data.get("directions") or {}
    issues = data.get("issues") or []
    weights = (settings.get("weights") or {}).keys()
    missing = []
    for field in ("base_monthly_delta", "literacy_multiplier", "weights"):
        if field not in settings:
            missing.append(f"settings.{field}")
    for weight in ("high", "medium", "low"):
        if weight not in weights:
            missing.append(f"settings.weights.{weight}")
            continue
        for polarity in ("positive", "negative"):
            if polarity not in settings["weights"][weight]:
                missing.append(f"settings.weights.{weight}.{polarity}")
    for issue in issues:
        key = issue.get("key", "<unknown>")
        for field in ("id", "key", "institution", "advance", "formula"):
            if field not in issue:
                missing.append(f"issues.{key}.{field}")
        formula = issue.get("formula") or {}
        for slot in ("high", "low"):
            direction = formula.get(slot)
            if direction not in directions:
                missing.append(f"issues.{key}.formula.{slot}")
        medium = formula.get("medium") or []
        if len(medium) != 2:
            missing.append(f"issues.{key}.formula.medium")
        for direction in medium:
            if direction not in directions:
                missing.append(f"issues.{key}.formula.medium.{direction}")
    if missing:
        raise ValueError("Missing/invalid philosophy debate fields:\n  " + "\n  ".join(missing))


def gen_direction_loader(lines: list[str], effect_name: str, direction: dict) -> None:
    source = direction["source"]
    sign = int(direction.get("sign", 1))
    emit(lines, 0, f"{effect_name} = {{")
    if sign == 1:
        emit(lines, 1, f"set_variable = {{ name = {TEMP_VALUE_VAR} value = {{ value = societal_value:{source} }} }}")
    else:
        emit(lines, 1, f"set_variable = {{ name = {TEMP_VALUE_VAR} value = {{ value = societal_value:{source} multiply = -1 }} }}")
    emit(lines, 0, "}")
    emit(lines)


def gen_weight_helper(lines: list[str], name: str, positive: float, negative: float) -> None:
    emit(lines, 0, f"{name} = {{")
    emit(lines, 1, f"set_variable = {{ name = {TEMP_CONTRIB_VAR} value = var:{TEMP_VALUE_VAR} }}")
    emit(lines, 1, "if = {")
    emit(lines, 2, f"limit = {{ var:{TEMP_VALUE_VAR} >= 0 }}")
    emit(lines, 2, f"change_variable = {{ name = {TEMP_CONTRIB_VAR} multiply = {fmt(positive)} }}")
    emit(lines, 1, "}")
    emit(lines, 1, "else = {")
    emit(lines, 2, f"change_variable = {{ name = {TEMP_CONTRIB_VAR} multiply = {fmt(negative)} }}")
    emit(lines, 1, "}")
    emit(lines, 1, f"change_variable = {{ name = {MONTHLY_DELTA_VAR} add = var:{TEMP_CONTRIB_VAR} }}")
    emit(lines, 0, "}")
    emit(lines)


def gen_direction_apply(lines: list[str], directions: dict, weight: str, direction_name: str) -> None:
    direction_effect = f"tv_academy_philosophy_load_direction_{direction_name}_effect"
    emit(lines, 1, f"{direction_effect} = yes")
    emit(lines, 1, f"{WEIGHT_EFFECTS[weight]} = yes")


def gen_issue_calculation(lines: list[str], issue: dict) -> None:
    key = issue["key"]
    formula = issue["formula"]
    emit(lines, 0, f"tv_academy_philosophy_calculate_monthly_delta_{key}_effect = {{")
    gen_direction_apply(lines, {}, "high", formula["high"])
    for direction in formula["medium"]:
        gen_direction_apply(lines, {}, "medium", direction)
    gen_direction_apply(lines, {}, "low", formula["low"])
    emit(lines, 0, "}")
    emit(lines)


def gen_issue_dispatch(lines: list[str], issues: list[dict]) -> None:
    emit(lines, 0, "tv_academy_philosophy_calculate_current_issue_monthly_delta_effect = {")
    for idx, issue in enumerate(issues):
        keyword = "if" if idx == 0 else "else_if"
        emit(lines, 1, f"{keyword} = {{")
        emit(lines, 2, f"limit = {{ var:tv_academy_philosophy_current ?= {issue['id']} }}")
        emit(lines, 2, f"tv_academy_philosophy_calculate_monthly_delta_{issue['key']}_effect = yes")
        emit(lines, 1, "}")
    emit(lines, 0, "}")
    emit(lines)


def gen_monthly_effect(lines: list[str], settings: dict) -> None:
    emit(lines, 0, "tv_academy_philosophy_apply_monthly_debate_drift_effect = {")
    emit(lines, 1, "if = {")
    emit(lines, 2, "limit = {")
    emit(lines, 3, "var:tv_academy_philosophy_phase ?= 1")
    emit(lines, 3, "var:tv_academy_debate_current_node_type ?= 1")
    emit(lines, 3, "tv_academy_philosophy_has_current_issue_trigger = yes")
    emit(lines, 3, "NOT = { tv_academy_philosophy_current_issue_embraced_trigger = yes }")
    emit(lines, 3, f"NOT = {{ has_variable = {PENDING_RESULT_VAR} }}")
    emit(lines, 3, "NOT = { has_variable = tv_academy_philosophy_recess_notice_pending }")
    emit(lines, 2, "}")
    emit(lines, 2, f"set_variable = {{ name = {MONTHLY_DELTA_VAR} value = {fmt(settings['base_monthly_delta'])} }}")
    emit(lines, 2, f"set_variable = {{ name = {TEMP_CONTRIB_VAR} value = {{ value = average_country_literacy multiply = {fmt(settings['literacy_multiplier'])} }} }}")
    emit(lines, 2, f"change_variable = {{ name = {MONTHLY_DELTA_VAR} add = var:{TEMP_CONTRIB_VAR} }}")
    emit(lines, 2, "tv_academy_philosophy_calculate_current_issue_monthly_delta_effect = yes")
    emit(lines, 2, f"change_variable = {{ name = tv_academy_philosophy_debate_position add = var:{MONTHLY_DELTA_VAR} }}")
    emit(lines, 2, "tv_academy_philosophy_check_debate_endpoint_effect = yes")
    emit(lines, 1, "}")
    emit(lines, 0, "}")
    emit(lines)


def gen_endpoint_checker(lines: list[str]) -> None:
    emit(lines, 0, "tv_academy_philosophy_check_debate_endpoint_effect = {")
    emit(lines, 1, "if = {")
    emit(lines, 2, "limit = {")
    emit(lines, 3, "var:tv_academy_philosophy_phase ?= 1")
    emit(lines, 3, f"NOT = {{ has_variable = {PENDING_RESULT_VAR} }}")
    emit(lines, 3, "var:tv_academy_philosophy_debate_position >= 100")
    emit(lines, 2, "}")
    emit(lines, 2, f"set_variable = {{ name = {PENDING_RESULT_VAR} value = 1 }}")
    emit(lines, 2, f"set_variable = {{ name = {PENDING_ISSUE_VAR} value = var:tv_academy_philosophy_current }}")
    emit(lines, 2, f"set_variable = {{ name = {PENDING_KIND_VAR} value = 1 }}")
    emit(lines, 2, "set_variable = { name = tv_academy_philosophy_phase value = 0 }")
    emit(lines, 2, "trigger_event_non_silently = { id = tv_research.43 days = 1 }")
    emit(lines, 1, "}")
    emit(lines, 1, "else_if = {")
    emit(lines, 2, "limit = {")
    emit(lines, 3, "var:tv_academy_philosophy_phase ?= 1")
    emit(lines, 3, f"NOT = {{ has_variable = {PENDING_RESULT_VAR} }}")
    emit(lines, 3, "var:tv_academy_philosophy_debate_position <= 0")
    emit(lines, 2, "}")
    emit(lines, 2, f"set_variable = {{ name = {PENDING_RESULT_VAR} value = 1 }}")
    emit(lines, 2, f"set_variable = {{ name = {PENDING_ISSUE_VAR} value = var:tv_academy_philosophy_current }}")
    emit(lines, 2, f"set_variable = {{ name = {PENDING_KIND_VAR} value = 2 }}")
    emit(lines, 2, "set_variable = { name = tv_academy_philosophy_phase value = 0 }")
    emit(lines, 2, "trigger_event_non_silently = { id = tv_research.44 days = 1 }")
    emit(lines, 1, "}")
    emit(lines, 0, "}")
    emit(lines)


def gen_result_cleanup(lines: list[str]) -> None:
    emit(lines, 0, "tv_academy_philosophy_clear_debate_result_effect = {")
    for var_name in (PENDING_RESULT_VAR, PENDING_ISSUE_VAR, PENDING_KIND_VAR, MONTHLY_DELTA_VAR, TEMP_VALUE_VAR, TEMP_CONTRIB_VAR):
        emit(lines, 1, f"remove_variable = {var_name}")
    emit(lines, 0, "}")
    emit(lines)


def gen_accepted_effect(lines: list[str], issue: dict) -> None:
    key = issue["key"]
    emit(lines, 0, f"tv_academy_philosophy_accept_{key}_effect = {{")
    emit(lines, 1, f"every_owned_location = {{ change_institution_progress = {{ type = institution:{issue['institution']} value = 100 }} }}")
    emit(lines, 1, f"research_advance = advance_type:{issue['advance']}")
    emit(lines, 0, "}")
    emit(lines)


def gen_accept_dispatch(lines: list[str], issues: list[dict]) -> None:
    emit(lines, 0, "tv_academy_philosophy_apply_pending_acceptance_effect = {")
    for idx, issue in enumerate(issues):
        keyword = "if" if idx == 0 else "else_if"
        emit(lines, 1, f"{keyword} = {{")
        emit(lines, 2, f"limit = {{ var:{PENDING_ISSUE_VAR} ?= {issue['id']} }}")
        emit(lines, 2, f"tv_academy_philosophy_accept_{issue['key']}_effect = yes")
        emit(lines, 1, "}")
    emit(lines, 0, "}")
    emit(lines)


def gen_resolve_effect(lines: list[str], accepted: bool) -> None:
    kind = "acceptance" if accepted else "rejection"
    result_kind = 1 if accepted else 2
    effect_name = f"tv_academy_philosophy_resolve_pending_{kind}_effect"
    emit(lines, 0, f"{effect_name} = {{")
    emit(lines, 1, "if = {")
    emit(lines, 2, "limit = {")
    emit(lines, 3, f"var:{PENDING_RESULT_VAR} ?= 1")
    emit(lines, 3, f"var:{PENDING_KIND_VAR} ?= {result_kind}")
    emit(lines, 3, "tv_academy_philosophy_has_current_issue_trigger = yes")
    emit(lines, 3, f"var:tv_academy_philosophy_current ?= var:{PENDING_ISSUE_VAR}")
    emit(lines, 2, "}")
    if accepted:
        emit(lines, 2, "tv_academy_philosophy_apply_pending_acceptance_effect = yes")
    emit(lines, 2, "tv_academy_philosophy_advance_current_issue_effect = yes")
    emit(lines, 2, "tv_academy_philosophy_enter_recess_effect = yes")
    emit(lines, 2, "tv_academy_philosophy_clear_debate_result_effect = yes")
    emit(lines, 1, "}")
    emit(lines, 0, "}")
    emit(lines)


def generate(data: dict) -> str:
    validate_data(data)
    settings = data["settings"]
    directions = data["directions"]
    issues = data["issues"]

    lines: list[str] = [HEADER.rstrip(), ""]
    emit(lines, 0, "# Country-scoped helpers. Monthly debate drift is signed and intentionally unclamped.")
    emit(lines)

    for direction_name, direction in directions.items():
        gen_direction_loader(lines, f"tv_academy_philosophy_load_direction_{direction_name}_effect", direction)

    for weight, effect_name in WEIGHT_EFFECTS.items():
        weight_settings = settings["weights"][weight]
        gen_weight_helper(lines, effect_name, weight_settings["positive"], weight_settings["negative"])

    for issue in issues:
        gen_issue_calculation(lines, issue)

    gen_issue_dispatch(lines, issues)
    gen_monthly_effect(lines, settings)
    gen_endpoint_checker(lines)
    gen_result_cleanup(lines)
    for issue in issues:
        gen_accepted_effect(lines, issue)
    gen_accept_dispatch(lines, issues)
    gen_resolve_effect(lines, accepted=True)
    gen_resolve_effect(lines, accepted=False)

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with DATA_FILE.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)

    content = generate(data)
    if args.dry:
        print(content)
    else:
        OUT_FILE.write_text(content, encoding="utf-8-sig")
        print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
