import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from wonder_mechanics_lib import (
    ceremony_modifier_for_building,
    load_all_wonder_mechanics,
    load_wonders_source_data,
    mechanic_key,
)

OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "scripted_effects" / "tv_wonder_module_effects.txt"
SCRIPT_REL = "scripts/in_game/common/scripted_effects/gen_tv_wonder_module_effects.py"
DATA_REL = "data/wonders.yaml + data/wonder_mechanics.yaml + data/unique_wonders.yaml"

HEADER = [
    f"# @Generated by {SCRIPT_REL}",
    f"#   Data:    {DATA_REL}",
    f"#   Regen:   conda run --no-capture-output -n eu5 python {SCRIPT_REL}",
    "# Do not edit directly - modify the data file and re-run the generator.",
    "",
]

T = "\t"
HELPER_BUILDING_TYPE_MAP = "tv_wonder_id_to_helper_building_type"
HELPER_BUILDING_TYPE_VAR = "tv_wonder_helper_building_type"
MODULE_BUILDING_TYPE_VAR = "tv_wonder_module_building_type"
REQUIRED_PROGRESS_MAP = "tv_wonder_id_to_required_progress"
REQUIRED_PROGRESS_VAR = "tv_wonder_required_progress"


def module_building_type_map_name(part_key: str) -> str:
    # Event option tooltips can render local_var building types, but the pre-renderer
    # failed when the map key was computed earlier in the same visible option chain.
    return f"tv_wonder_id_to_{part_key}_module_building_type"


def module_building_type_var_name(part_key: str) -> str:
    return f"tv_wonder_{part_key}_module_building_type"


def final_building_type_map_name(style: int) -> str:
    return f"tv_wonder_id_to_style_{style}_final_building_type"


def final_building_type_var_name(style: int) -> str:
    return f"tv_wonder_style_{style}_final_building_type"


def building_type_ref(building: str) -> str:
    if (
        building.startswith('"')
        or building.startswith("building_type:")
        or building.startswith("local_var:")
        or building.startswith("var:")
    ):
        return building
    return f"building_type:{building}"


def global_map_expr(map_name: str, key: str) -> str:
    return f'"global_variable_map({map_name}|{key})"'


def capture_global_map_value(var_name: str, map_name: str, key: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}set_local_variable = {{",
        f"{prefix}{T}name = {var_name}",
        f"{prefix}{T}value = {global_map_expr(map_name, key)}",
        f"{prefix}}}",
    ]


def loc_level(building: str, op: str, level: int) -> str:
    return f"location_building_level = {{ building_type = {building_type_ref(building)} value {op} {level} }}"


def change_level(building: str, value: int) -> list[str]:
    return [
        f"{T}change_building_level_in_location = {{",
        f"{T}{T}building = {building_type_ref(building)}",
        f"{T}{T}value = {value}",
        f"{T}{T}owner = prev",
        f"{T}}}",
    ]


def change_level_by_value(building: str, value_lines: list[str]) -> list[str]:
    return [
        f"{T}change_building_level_in_location = {{",
        f"{T}{T}building = {building_type_ref(building)}",
        f"{T}{T}value = {{",
        *[f"{T}{T}{T}{line}" for line in value_lines],
        f"{T}{T}}}",
        f"{T}{T}owner = prev",
        f"{T}}}",
    ]


def add_units_from_module_level(part: str, building: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    for level in range(1, 7):
        lines.extend(
            [
                f"{prefix}if = {{",
                f"{prefix}{T}limit = {{ {loc_level(building, '>=', level)} }}",
                f"{prefix}{T}prev = {{ change_variable = {{ name = tv_wonder_{part}_units add = 1 }} }}",
                f"{prefix}}}",
            ]
        )
    return lines


def set_units_to_at_least_level(building: str, parts: list[dict], indent: int = 1) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    for level in range(1, 7):
        lines.append(f"{prefix}if = {{")
        lines.append(f"{prefix}{T}limit = {{ {loc_level(building, '>=', level)} }}")
        lines.append(f"{prefix}{T}prev = {{")
        for part in parts:
            key = part["key"]
            lines.append(f"{prefix}{T}{T}if = {{")
            lines.append(f"{prefix}{T}{T}{T}limit = {{ var:tv_wonder_{key}_units < {level} }}")
            lines.append(f"{prefix}{T}{T}{T}set_variable = {{ name = tv_wonder_{key}_units value = {level} }}")
            lines.append(f"{prefix}{T}{T}}}")
        lines.append(f"{prefix}{T}}}")
        lines.append(f"{prefix}}}")
    return lines


def add_building_level(branch_limit: str, building: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}if = {{",
        f"{prefix}{T}limit = {{ {branch_limit} }}",
        f"{prefix}{T}if = {{",
        f"{prefix}{T}{T}limit = {{ NOT = {{ has_building = {building_type_ref(building)} }} }}",
        f"{prefix}{T}{T}construct_building = {{ building_type = {building_type_ref(building)} cost_multiplier = 0 cost_multiplier_reason = \"game_concept_event\" instant = yes }}",
        f"{prefix}{T}}}",
        f"{prefix}{T}else = {{",
        *[f"{prefix}{T}{line}" for line in change_level(building, 1)],
        f"{prefix}{T}}}",
        f"{prefix}}}",
    ]


def add_building_level_if_missing(branch_limit: str, building: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}if = {{",
        f"{prefix}{T}limit = {{ {branch_limit} NOT = {{ has_building = {building_type_ref(building)} }} }}",
        f"{prefix}{T}construct_building = {{ building_type = {building_type_ref(building)} cost_multiplier = 0 cost_multiplier_reason = \"game_concept_event\" instant = yes }}",
        f"{prefix}}}",
    ]


def reduce_building_level(building: str) -> list[str]:
    return change_level(building, -1)


def any_building_block(buildings: list[str], indent: int) -> list[str]:
    prefix = T * indent
    lines = [f"{prefix}OR = {{"]
    for building in buildings:
        lines.append(f"{prefix}{T}has_building = {building_type_ref(building)}")
    lines.append(f"{prefix}}}")
    return lines


def final_building_level_exact(building: str, level: int, indent: int) -> list[str]:
    prefix = T * indent
    lines = [f"{prefix}{loc_level(building, '>=', level)}"]
    if level < 6:
        lines.append(f"{prefix}NOT = {{ {loc_level(building, '>=', level + 1)} }}")
    return lines


def country_level_matches(level_var: str, level: int, indent: int) -> list[str]:
    prefix = T * indent
    return [f"{prefix}prev = {{ var:{level_var} ?= {level} }}"]


def unit_gap_matches(unit_var: str, gap: int, indent: int) -> list[str]:
    prefix = T * indent
    pairs: list[tuple[int, int]] = []
    for wonder_level in range(0, 7):
        for unit_level in range(0, 7):
            if max(unit_level - wonder_level, 0) == gap:
                pairs.append((unit_level, wonder_level))
    lines = [f"{prefix}OR = {{"]
    for unit_level, wonder_level in pairs:
        lines.append(f"{prefix}{T}AND = {{")
        lines.append(f"{prefix}{T}{T}prev = {{ var:{unit_var} ?= {unit_level} }}")
        lines.append(f"{prefix}{T}{T}prev = {{ var:tv_wonder_level ?= {wonder_level} }}")
        lines.append(f"{prefix}{T}}}")
    lines.append(f"{prefix}}}")
    return lines


def sync_building_to_literal_level(building: str, target_level: int, indent: int) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    branch_head = "if"
    if target_level > 0:
        lines.append(f"{prefix}if = {{")
        lines.append(f"{prefix}{T}limit = {{ NOT = {{ has_building = {building_type_ref(building)} }} }}")
        lines.append(
            f'{prefix}{T}construct_building = {{ building_type = {building_type_ref(building)} cost_multiplier = 0 cost_multiplier_reason = "game_concept_event" instant = yes }}'
        )
        if target_level > 1:
            lines.extend([f"{prefix}{T}{line}" for line in change_level(building, target_level - 1)])
        lines.append(f"{prefix}}}")
        branch_head = "else_if"
    for current_level in range(6, 0, -1):
        delta = target_level - current_level
        if delta == 0:
            continue
        lines.append(f"{prefix}{branch_head} = {{")
        lines.append(f"{prefix}{T}limit = {{")
        lines.extend(final_building_level_exact(building, current_level, indent + 2))
        lines.append(f"{prefix}{T}}}")
        lines.extend([f"{prefix}{T}{line}" for line in change_level(building, delta)])
        lines.append(f"{prefix}}}")
        branch_head = "else_if"
    return lines


def sync_building_from_target_levels(
    building: str,
    target_condition_builder,
    indent: int,
) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    head = "if"
    for target_level in range(6, -1, -1):
        lines.append(f"{prefix}{head} = {{")
        lines.append(f"{prefix}{T}limit = {{")
        lines.extend(target_condition_builder(target_level, indent + 2))
        lines.append(f"{prefix}{T}}}")
        lines.extend(sync_building_to_literal_level(building, target_level, indent + 1))
        lines.append(f"{prefix}}}")
        head = "else_if"
    return lines


def stored_tier_can_expand(wonder: dict, final_building: str, level: int, indent: int) -> list[str]:
    prefix = T * indent
    tier_var = f"tv_wonder_{wonder['key']}_scale_tier"
    lines = final_building_level_exact(final_building, level, indent)
    lines.append(f"{prefix}OR = {{")
    lines.append(f"{prefix}{T}var:{tier_var} ?= {{ this >= {level + 1} }}")
    lines.append(f"{prefix}{T}NOT = {{ has_variable = {tier_var} }}")
    lines.append(f"{prefix}}}")
    return lines


def final_building_below_cap_conditions(wonder: dict, indent: int) -> list[str]:
    prefix = T * indent
    lines = [f"{prefix}OR = {{"]
    for final_building in wonder["final_buildings"].values():
        for level in range(1, 6):
            lines.append(f"{prefix}{T}AND = {{")
            lines.extend(stored_tier_can_expand(wonder, final_building, level, indent + 2))
            lines.append(f"{prefix}{T}}}")
    lines.append(f"{prefix}}}")
    return lines


def proposal_setter(wonder: dict, mode: int, indent: int) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}prev = {{",
        f"{prefix}{T}set_variable = {{ name = tv_wonder_proposal value = {wonder['id']} }}",
        f"{prefix}{T}set_variable = {{ name = tv_wonder_proposal_mode value = {mode} }}",
        f"{prefix}{T}set_variable = {{ name = tv_wonder_priority_found value = 1 }}",
        f"{prefix}{T}set_variable = {{ name = tv_wonder_proposal_site value = scope:tv_wonder_priority_site }}",
        f"{prefix}{T}tv_wonder_set_proposal_on_great_engineer_effect = yes",
        f"{prefix}}}",
    ]


def set_building_level_from_level_var(
    building: str,
    level_var: str,
    current_level_var: str,
    indent: int,
) -> list[str]:
    del current_level_var
    return sync_building_from_target_levels(
        building,
        lambda target_level, target_indent: country_level_matches(level_var, target_level, target_indent),
        indent,
    )


def sync_helper_building_to_wonder_level(wonder: dict, indent: int) -> list[str]:
    helper = f"tv_wonder_{wonder['key']}"
    return set_building_level_from_level_var(
        helper,
        "tv_wonder_level",
        f"tv_wonder_{wonder['key']}_helper_current_level",
        indent,
    )


def sync_module_building_to_unit_gap(
    wonder: dict,
    part_key: str,
    building: str,
    indent: int,
) -> list[str]:
    del wonder
    unit_var = f"tv_wonder_{part_key}_units"
    return sync_building_from_target_levels(
        building,
        lambda target_level, target_indent: unit_gap_matches(unit_var, target_level, target_indent),
        indent,
    )


def combine_buildings_to_helper_once(
    helper: str,
    module_names: list[str],
    indent: int,
) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    for idx, level in enumerate(range(6, 0, -1)):
        head = "if" if idx == 0 else "else_if"
        lines.append(f"{prefix}{head} = {{")
        lines.append(f"{prefix}{T}limit = {{")
        for module in module_names:
            lines.append(f"{prefix}{T}{T}{loc_level(module, '>=', level)}")
        lines.append(f"{prefix}{T}}}")
        lines.append(f"{prefix}{T}if = {{")
        lines.append(f"{prefix}{T}{T}limit = {{ has_building = {building_type_ref(helper)} }}")
        lines.extend(
            [
                f"{prefix}{T}{line}"
                for line in change_level(helper, level)
            ]
        )
        lines.append(f"{prefix}{T}}}")
        lines.append(f"{prefix}{T}else = {{")
        lines.append(
            f'{prefix}{T}{T}construct_building = {{ building_type = {building_type_ref(helper)} cost_multiplier = 0 cost_multiplier_reason = "game_concept_event" instant = yes }}'
        )
        if level > 1:
            lines.extend(
                [
                    f"{prefix}{T}{line}"
                    for line in change_level(helper, level - 1)
                ]
            )
        lines.append(f"{prefix}{T}}}")
        for module in module_names:
            lines.extend(
                [
                    f"{prefix}{T}{line}"
                    for line in change_level(module, -level)
                ]
            )
        lines.append(f"{prefix}}}")
    return lines


def combine_modules_to_helper_once(
    wonder: dict,
    parts: list[dict],
    indent: int,
) -> list[str]:
    helper = f"tv_wonder_{wonder['key']}"
    module_names = [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts]
    return combine_buildings_to_helper_once(helper, module_names, indent)


def restore_final_building_state_for_style(
    style: int,
    final_building: str,
    parts: list[dict],
    indent: int,
) -> list[str]:
    prefix = T * indent
    lines = [
        f"{prefix}if = {{",
        f"{prefix}{T}limit = {{ has_building = {building_type_ref(final_building)} }}",
        f"{prefix}{T}prev = {{",
        f"{prefix}{T}{T}set_variable = {{ name = tv_wonder_ceremony_style value = {style} }}",
        f"{prefix}{T}{T}set_variable = {{ name = tv_wonder_ceremony_locked value = 1 }}",
        f"{prefix}{T}}}",
    ]
    lines.extend(set_units_to_at_least_level(final_building, parts, indent + 1))
    lines.append(f"{prefix}}}")
    return lines


def has_base_country_modifier(wonder: dict, mechanics: dict) -> bool:
    return bool(mechanics["base_modifiers"][mechanic_key(wonder)])


def append_clear_current_base_modifiers_effect(lines: list[str], name: str, wonders: list[dict], mechanics: dict) -> None:
    lines.append(f"{name} = {{")
    applicable_wonders = [wonder for wonder in wonders if has_base_country_modifier(wonder, mechanics)]
    for idx, wonder in enumerate(applicable_wonders):
        head = "if" if idx == 0 else "else_if"
        lines.append(f"{T}{head} = {{")
        lines.append(f"{T}{T}limit = {{ var:tv_wonder_locked ?= {wonder['id']} }}")
        for level in range(1, 7):
            lines.append(f"{T}{T}remove_country_modifier = tv_wonder_{wonder['key']}_level_{level}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def append_clear_current_ceremony_modifiers_effect(lines: list[str], name: str, wonders: list[dict], mechanics: dict) -> None:
    lines.append(f"{name} = {{")
    for idx, wonder in enumerate(wonders):
        head = "if" if idx == 0 else "else_if"
        lines.append(f"{T}{head} = {{")
        lines.append(f"{T}{T}limit = {{ var:tv_wonder_locked ?= {wonder['id']} }}")
        for building in wonder["final_buildings"].values():
            ceremony_modifier = ceremony_modifier_for_building(wonder, mechanics, building)
            if ceremony_modifier is None:
                continue
            modifier_name, _ = ceremony_modifier
            lines.append(f"{T}{T}remove_country_modifier = {modifier_name}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def append_destroy_intermediate_buildings_at_location_effect(
    lines: list[str],
    name: str,
    wonders: list[dict],
    parts: list[dict],
) -> None:
    lines.append(f"{name} = {{")
    lines.append(f"{T}prev = {{ save_scope_as = tv_wonder_module_owner }}")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        module_names = [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts]
        final_names = list(wonder["final_buildings"].values())
        lines.append(f"{T}if = {{")
        lines.append(f"{T}{T}limit = {{")
        lines.extend(any_building_block(final_names, 3))
        lines.append(f"{T}{T}}}")
        for building in [helper, *module_names]:
            lines.append(f"{T}{T}if = {{")
            lines.append(f"{T}{T}{T}limit = {{ has_building = building_type:{building} }}")
            lines.append(f"{T}{T}{T}destroy_building_forcefully = \"building(building_type:{building}|scope:tv_wonder_module_owner)\"")
            lines.append(f"{T}{T}}}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def append_destroy_locked_intermediate_buildings_effect(lines: list[str], name: str, parts: list[dict]) -> None:
    lines.append(f"{name} = {{")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}has_global_variable_map = {HELPER_BUILDING_TYPE_MAP}")
    lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {HELPER_BUILDING_TYPE_MAP} target = var:tv_wonder_locked }}")
    for part in parts:
        module_map = module_building_type_map_name(part["key"])
        lines.append(f"{T}{T}{T}has_global_variable_map = {module_map}")
        lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {module_map} target = var:tv_wonder_locked }}")
    lines.append(f"{T}{T}}}")
    lines.extend(capture_global_map_value(HELPER_BUILDING_TYPE_VAR, HELPER_BUILDING_TYPE_MAP, "var:tv_wonder_locked", 2))
    for part in parts:
        part_key = part["key"]
        lines.extend(
            capture_global_map_value(
                module_building_type_var_name(part_key),
                module_building_type_map_name(part_key),
                "var:tv_wonder_locked",
                2,
            )
        )
    lines.append(f"{T}{T}save_scope_as = tv_wonder_module_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for building_var in [HELPER_BUILDING_TYPE_VAR, *[module_building_type_var_name(part["key"]) for part in parts]]:
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{ has_building = local_var:{building_var} }}")
        lines.append(f"{T}{T}{T}{T}change_building_level_in_location = {{")
        lines.append(f"{T}{T}{T}{T}{T}building = local_var:{building_var}")
        lines.append(f"{T}{T}{T}{T}{T}value = -6")
        lines.append(f"{T}{T}{T}{T}{T}owner = prev")
        lines.append(f"{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    for part in parts:
        lines.append(f"{T}{T}remove_local_variable = {module_building_type_var_name(part['key'])}")
    lines.append(f"{T}{T}remove_local_variable = {HELPER_BUILDING_TYPE_VAR}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def append_destroy_intermediate_buildings_alias_effect(lines: list[str], name: str, target: str) -> None:
    lines.append(f"{name} = {{")
    lines.append(f"{T}{target} = yes")
    lines.append("}")
    lines.append("")


def append_destroy_intermediate_buildings_at_location_alias_effect(lines: list[str], name: str, target: str) -> None:
    lines.append(f"{name} = {{")
    lines.append(f"{T}prev = {{ {target} = yes }}")
    lines.append("}")
    lines.append("")


def append_destroy_intermediate_buildings_effect(lines: list[str], name: str, at_location_effect_name: str) -> None:
    lines.append(f"{name} = {{")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.append(f"{T}{T}{T}{at_location_effect_name} = yes")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def main() -> None:
    data = load_wonders_source_data()
    wonders, mechanics = load_all_wonder_mechanics()
    generic_wonders = [wonder for wonder in wonders if not wonder.get("is_unique")]
    unique_wonders = [wonder for wonder in wonders if wonder.get("is_unique")]
    parts = data["parts"]
    final_styles = sorted({int(style) for wonder in wonders for style in wonder["final_buildings"]})
    lines = HEADER[:]

    append_clear_current_base_modifiers_effect(lines, "tv_wonder_clear_current_generic_base_modifiers_effect", generic_wonders, mechanics)
    append_clear_current_base_modifiers_effect(lines, "tv_wonder_clear_current_unique_base_modifiers_effect", unique_wonders, mechanics)
    lines.append("tv_wonder_clear_current_base_modifiers_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_unique_locked_trigger = yes }}")
    lines.append(f"{T}{T}tv_wonder_clear_current_unique_base_modifiers_effect = yes")
    lines.append(f"{T}}}")
    lines.append(f"{T}else = {{")
    lines.append(f"{T}{T}tv_wonder_clear_current_generic_base_modifiers_effect = yes")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    append_clear_current_ceremony_modifiers_effect(lines, "tv_wonder_clear_current_unique_ceremony_modifiers_effect", unique_wonders, mechanics)
    lines.append("tv_wonder_clear_current_ceremony_modifiers_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_unique_locked_trigger = yes }}")
    lines.append(f"{T}{T}tv_wonder_clear_current_unique_ceremony_modifiers_effect = yes")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_set_required_progress_effect = {")
    lines.append(f"{T}set_variable = {{ name = tv_wonder_unit_required_progress value = 300000 }}")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}has_global_variable_map = {REQUIRED_PROGRESS_MAP}")
    lines.append(
        f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {REQUIRED_PROGRESS_MAP} target = var:tv_wonder_locked }}"
    )
    lines.append(f"{T}{T}}}")
    lines.extend(capture_global_map_value(REQUIRED_PROGRESS_VAR, REQUIRED_PROGRESS_MAP, "var:tv_wonder_locked", 2))
    lines.append(f"{T}{T}set_variable = {{ name = tv_wonder_unit_required_progress value = local_var:{REQUIRED_PROGRESS_VAR} }}")
    lines.append(f"{T}{T}remove_local_variable = {REQUIRED_PROGRESS_VAR}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_construct_module_for_last_completed_part_effect = {")
    lines.append(f"{T}tv_wonder_index_rebuild_global_maps_if_needed_effect = yes")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}var:tv_wonder_last_completed_part ?= {{ this >= 1 }}")
    lines.append(f"{T}{T}{T}var:tv_wonder_last_completed_part ?= {{ this <= {len(parts)} }}")
    lines.append(f"{T}{T}}}")
    for part_index, part in enumerate(parts, start=1):
        part_key = part["key"]
        module_map = module_building_type_map_name(part_key)
        head = "if" if part_index == 1 else "else_if"
        lines.append(f"{T}{T}{head} = {{")
        lines.append(f"{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}var:tv_wonder_last_completed_part ?= {part_index}")
        lines.append(f"{T}{T}{T}{T}has_global_variable_map = {module_map}")
        lines.append(f"{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {module_map} target = var:tv_wonder_locked }}")
        lines.append(f"{T}{T}{T}}}")
        lines.extend(capture_global_map_value(MODULE_BUILDING_TYPE_VAR, module_map, "var:tv_wonder_locked", 3))
        lines.append(f"{T}{T}{T}save_scope_as = tv_wonder_module_owner")
        lines.append(f"{T}{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(add_building_level("always = yes", f"local_var:{MODULE_BUILDING_TYPE_VAR}", 4))
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}remove_local_variable = {MODULE_BUILDING_TYPE_VAR}")
        lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_combine_completed_modules_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}has_global_variable_map = {HELPER_BUILDING_TYPE_MAP}")
    lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {HELPER_BUILDING_TYPE_MAP} target = var:tv_wonder_locked }}")
    for part in parts:
        module_map = module_building_type_map_name(part["key"])
        lines.append(f"{T}{T}{T}has_global_variable_map = {module_map}")
        lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {module_map} target = var:tv_wonder_locked }}")
    lines.append(f"{T}{T}}}")
    lines.extend(capture_global_map_value(HELPER_BUILDING_TYPE_VAR, HELPER_BUILDING_TYPE_MAP, "var:tv_wonder_locked", 2))
    for part in parts:
        part_key = part["key"]
        lines.extend(
            capture_global_map_value(
                module_building_type_var_name(part_key),
                module_building_type_map_name(part_key),
                "var:tv_wonder_locked",
                2,
            )
        )
    lines.append(f"{T}{T}save_scope_as = tv_wonder_module_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.extend(
        combine_buildings_to_helper_once(
            f"local_var:{HELPER_BUILDING_TYPE_VAR}",
            [f"local_var:{module_building_type_var_name(part['key'])}" for part in parts],
            3,
        )
    )
    lines.append(f"{T}{T}}}")
    for part in parts:
        lines.append(f"{T}{T}remove_local_variable = {module_building_type_var_name(part['key'])}")
    lines.append(f"{T}{T}remove_local_variable = {HELPER_BUILDING_TYPE_VAR}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_sync_units_from_buildings_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}has_global_variable_map = {HELPER_BUILDING_TYPE_MAP}")
    lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {HELPER_BUILDING_TYPE_MAP} target = var:tv_wonder_locked }}")
    for part in parts:
        module_map = module_building_type_map_name(part["key"])
        lines.append(f"{T}{T}{T}has_global_variable_map = {module_map}")
        lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {module_map} target = var:tv_wonder_locked }}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for part in parts:
        lines.append(f"{T}{T}{T}prev = {{ set_variable = {{ name = tv_wonder_{part['key']}_units value = 0 }} }}")
    lines.append(f"{T}{T}}}")
    lines.extend(capture_global_map_value(HELPER_BUILDING_TYPE_VAR, HELPER_BUILDING_TYPE_MAP, "var:tv_wonder_locked", 2))
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.extend(set_units_to_at_least_level(f"local_var:{HELPER_BUILDING_TYPE_VAR}", parts, 3))
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}remove_local_variable = {HELPER_BUILDING_TYPE_VAR}")
    for style in final_styles:
        final_map = final_building_type_map_name(style)
        final_var = final_building_type_var_name(style)
        lines.append(f"{T}{T}if = {{")
        lines.append(f"{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}has_global_variable_map = {final_map}")
        lines.append(f"{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {final_map} target = var:tv_wonder_locked }}")
        lines.append(f"{T}{T}{T}}}")
        lines.extend(capture_global_map_value(final_var, final_map, "var:tv_wonder_locked", 3))
        lines.append(f"{T}{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(set_units_to_at_least_level(f"local_var:{final_var}", parts, 4))
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}remove_local_variable = {final_var}")
        lines.append(f"{T}{T}}}")
    for part in parts:
        part_key = part["key"]
        module_var = module_building_type_var_name(part_key)
        lines.extend(capture_global_map_value(module_var, module_building_type_map_name(part_key), "var:tv_wonder_locked", 2))
        lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(add_units_from_module_level(part_key, f"local_var:{module_var}", 3))
        lines.append(f"{T}{T}}}")
        lines.append(f"{T}{T}remove_local_variable = {module_var}")
        lines.append(f"{T}{T}clamp_variable = {{ name = tv_wonder_{part_key}_units min = 0 max = 6 }}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_update_wonder_level_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_detect_existing_wonder_at_saved_site_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for wonder in wonders:
        all_buildings = [f"tv_wonder_{wonder['key']}"] + [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts] + list(wonder["final_buildings"].values())
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}{T}OR = {{")
        for building in all_buildings:
            lines.append(f"{T}{T}{T}{T}{T}{T}has_building = building_type:{building}")
        lines.append(f"{T}{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}prev = {{ set_variable = {{ name = tv_wonder_locked value = {wonder['id']} }} }}")
        for style, building in wonder["final_buildings"].items():
            lines.append(f"{T}{T}{T}{T}if = {{")
            lines.append(f"{T}{T}{T}{T}{T}limit = {{ has_building = building_type:{building} }}")
            lines.append(f"{T}{T}{T}{T}{T}prev = {{")
            lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_style value = {style} }}")
            lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_locked value = 1 }}")
            lines.append(f"{T}{T}{T}{T}{T}}}")
            lines.append(f"{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_index_refresh_country_cache_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_sync_existing_final_building_level_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for wonder in wonders:
        for style, building in wonder["final_buildings"].items():
            lines.append(f"{T}{T}{T}if = {{")
            lines.append(f"{T}{T}{T}{T}limit = {{ has_building = building_type:{building} }}")
            for level in range(6, 0, -1):
                lines.append(f"{T}{T}{T}{T}if = {{")
                lines.append(f"{T}{T}{T}{T}{T}limit = {{ {loc_level(building, '>=', level)} }}")
                lines.append(f"{T}{T}{T}{T}{T}prev = {{")
                lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_locked value = {wonder['id']} }}")
                lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_style value = {style} }}")
                lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_locked value = 1 }}")
                for part in parts:
                    lines.append(f"{T}{T}{T}{T}{T}{T}if = {{")
                    lines.append(f"{T}{T}{T}{T}{T}{T}{T}limit = {{ var:tv_wonder_{part['key']}_units < {level} }}")
                    lines.append(f"{T}{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_{part['key']}_units value = {level} }}")
                    lines.append(f"{T}{T}{T}{T}{T}{T}}}")
                lines.append(f"{T}{T}{T}{T}{T}}}")
                lines.append(f"{T}{T}{T}{T}}}")
            lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_update_wonder_level_effect = yes")
    lines.append(f"{T}tv_wonder_index_refresh_country_cache_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_restore_locked_wonder_final_building_state_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}}}")
    for style in final_styles:
        final_map = final_building_type_map_name(style)
        final_var = final_building_type_var_name(style)
        lines.append(f"{T}{T}if = {{")
        lines.append(f"{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}has_global_variable_map = {final_map}")
        lines.append(f"{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {final_map} target = var:tv_wonder_locked }}")
        lines.append(f"{T}{T}{T}}}")
        lines.extend(capture_global_map_value(final_var, final_map, "var:tv_wonder_locked", 3))
        lines.append(f"{T}{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(restore_final_building_state_for_style(style, f"local_var:{final_var}", parts, 4))
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}remove_local_variable = {final_var}")
        lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_update_wonder_level_effect = yes")
    lines.append(f"{T}tv_wonder_index_refresh_country_cache_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_apply_helper_building_to_final_site_effect = {")
    lines.append(f"{T}tv_wonder_index_rebuild_global_maps_if_needed_effect = yes")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}has_global_variable_map = {HELPER_BUILDING_TYPE_MAP}")
    lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {HELPER_BUILDING_TYPE_MAP} target = var:tv_wonder_locked }}")
    lines.append(f"{T}{T}}}")
    lines.extend(capture_global_map_value(HELPER_BUILDING_TYPE_VAR, HELPER_BUILDING_TYPE_MAP, "var:tv_wonder_locked", 2))
    lines.append(f"{T}{T}save_scope_as = tv_wonder_module_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.extend(
        set_building_level_from_level_var(
            f"local_var:{HELPER_BUILDING_TYPE_VAR}",
            "tv_wonder_level",
            "tv_wonder_helper_current_level",
            3,
        )
    )
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}remove_local_variable = {HELPER_BUILDING_TYPE_VAR}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_materialize_module_buildings_from_unit_vars_effect = {")
    lines.append(f"{T}tv_wonder_index_rebuild_global_maps_if_needed_effect = yes")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}}}")
    for part in parts:
        part_key = part["key"]
        module_map = module_building_type_map_name(part_key)
        lines.append(f"{T}{T}if = {{")
        lines.append(
            f"{T}{T}{T}limit = {{ "
            f"has_global_variable_map = {module_map} "
            f"is_key_in_global_variable_map = {{ name = {module_map} target = var:tv_wonder_locked }} }}"
        )
        lines.extend(capture_global_map_value(MODULE_BUILDING_TYPE_VAR, module_map, "var:tv_wonder_locked", 3))
        lines.append(f"{T}{T}{T}save_scope_as = tv_wonder_module_owner")
        lines.append(f"{T}{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(
            sync_module_building_to_unit_gap(
                {},
                part_key,
                f"local_var:{MODULE_BUILDING_TYPE_VAR}",
                4,
            )
        )
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}remove_local_variable = {MODULE_BUILDING_TYPE_VAR}")
        lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_combine_completed_modules_at_location_effect = {")
    for wonder in wonders:
        lines.extend(combine_modules_to_helper_once(wonder, parts, 1))
    lines.append("}")
    lines.append("")

    append_destroy_locked_intermediate_buildings_effect(
        lines,
        "tv_wonder_destroy_locked_intermediate_buildings_effect",
        parts,
    )
    append_destroy_intermediate_buildings_alias_effect(
        lines,
        "tv_wonder_destroy_generic_intermediate_buildings_effect",
        "tv_wonder_destroy_locked_intermediate_buildings_effect",
    )
    append_destroy_intermediate_buildings_alias_effect(
        lines,
        "tv_wonder_destroy_unique_intermediate_buildings_effect",
        "tv_wonder_destroy_locked_intermediate_buildings_effect",
    )
    append_destroy_intermediate_buildings_at_location_alias_effect(
        lines,
        "tv_wonder_destroy_generic_intermediate_buildings_at_location_effect",
        "tv_wonder_destroy_generic_intermediate_buildings_effect",
    )
    append_destroy_intermediate_buildings_at_location_alias_effect(
        lines,
        "tv_wonder_destroy_unique_intermediate_buildings_at_location_effect",
        "tv_wonder_destroy_unique_intermediate_buildings_effect",
    )
    append_destroy_intermediate_buildings_at_location_effect(
        lines,
        "tv_wonder_destroy_discovered_generic_intermediate_buildings_at_location_effect",
        generic_wonders,
        parts,
    )
    append_destroy_intermediate_buildings_at_location_effect(
        lines,
        "tv_wonder_destroy_discovered_unique_intermediate_buildings_at_location_effect",
        unique_wonders,
        parts,
    )
    lines.append("tv_wonder_destroy_intermediate_buildings_at_location_effect = {")
    lines.append(f"{T}tv_wonder_destroy_discovered_generic_intermediate_buildings_at_location_effect = yes")
    lines.append(f"{T}tv_wonder_destroy_discovered_unique_intermediate_buildings_at_location_effect = yes")
    lines.append("}")
    lines.append("")
    append_destroy_intermediate_buildings_effect(
        lines,
        "tv_wonder_destroy_intermediate_buildings_effect",
        "tv_wonder_destroy_intermediate_buildings_at_location_effect",
    )

    lines.append("tv_wonder_scan_priority_proposal_effect = {")
    lines.append(f"{T}remove_variable = tv_wonder_priority_found")
    lines.append(f"{T}remove_variable = tv_wonder_proposal_site")
    lines.append(f"{T}remove_variable = tv_wonder_proposal_mode")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ NOT = {{ has_variable = tv_wonder_priority_declined }} }}")
    lines.append(f"{T}{T}every_owned_location = {{")
    lines.append(f"{T}{T}{T}limit = {{ NOT = {{ prev = {{ has_variable = tv_wonder_priority_found }} }} }}")
    lines.append(f"{T}{T}{T}save_scope_as = tv_wonder_priority_site")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        module_names = [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts]
        final_names = list(wonder["final_buildings"].values())
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}{T}NOT = {{ prev = {{ has_variable = tv_wonder_priority_found }} }}")
        lines.append(f"{T}{T}{T}{T}{T}NOT = {{ tv_wonder_location_has_any_wonder_final_building_trigger = yes }}")
        lines.append(f"{T}{T}{T}{T}{T}OR = {{")
        for module in module_names:
            lines.append(f"{T}{T}{T}{T}{T}{T}has_building = building_type:{module}")
        lines.append(f"{T}{T}{T}{T}{T}{T}has_building = building_type:{helper}")
        lines.append(f"{T}{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}}}")
        lines.extend(proposal_setter(wonder, 1, 4))
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}{T}NOT = {{ prev = {{ has_variable = tv_wonder_priority_found }} }}")
        lines.extend(final_building_below_cap_conditions(wonder, 5))
        lines.append(f"{T}{T}{T}{T}}}")
        lines.extend(proposal_setter(wonder, 2, 4))
        lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    OUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
