import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from wonder_mechanics.io import (
    load_all_wonder_mechanics,
    load_wonders_source_data,
)

OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "scripted_effects" / "tv_wonder_module_effects.txt"
SCRIPT_REL = "scripts/in_game/common/scripted_effects/gen_tv_wonder_module_effects.py"
DATA_REL = "data/wonders.yaml + data/wonder_final_buildings.yaml + data/wonder_generic_rituals.yaml + data/wonder_base_modifiers.yaml + data/wonder_site_rules.yaml + data/unique_wonders.yaml"

HEADER = [
    f"# @Generated by {SCRIPT_REL}",
    f"#   Data:    {DATA_REL}",
    f"#   Regen:   conda run --no-capture-output -n eu5 python {SCRIPT_REL}",
    "# Do not edit directly - modify the data file and re-run the generator.",
    "",
]

T = "\t"
HELPER_BUILDING_TYPE_MAP = "tv_wonder_id_to_helper_building_type"
HELPER_BUILDING_TYPE_VAR = "tv_wonder_helper_building_type"
MODULE_BUILDING_TYPE_VAR = "tv_wonder_module_building_type"
COMBINE_WONDER_ID_LOCAL = "tv_wonder_module_combine_wonder_id"
COMBINE_FOUND_VAR = "tv_wonder_modules_combined"
COMBINE_LOCATION_SCOPE = "tv_wonder_module_combine_location"
REQUIRED_PROGRESS_MAP = "tv_wonder_id_to_required_progress"
REQUIRED_PROGRESS_VAR = "tv_wonder_required_progress"
INTERMEDIATE_BUILDING_WONDER_ID_MAP = "tv_wonder_intermediate_building_type_to_wonder_id"
FINAL_BUILDING_WONDER_ID_MAP = "tv_wonder_final_building_type_to_wonder_id"
FINAL_BUILDING_RITUAL_STYLE_MAP = "tv_wonder_final_building_type_to_ritual_style"
REVERSE_BUILDING_MAP_SCAN_MAX = 2000
PRIORITY_CANDIDATE_SITE_BY_ID_MAP = "tv_wonder_priority_candidate_site_by_id"
PRIORITY_CANDIDATE_WONDER_BY_ID_MAP = "tv_wonder_priority_candidate_wonder_by_id"
PRIORITY_CANDIDATE_MODE_BY_ID_MAP = "tv_wonder_priority_candidate_mode_by_id"
PRIORITY_NEXT_CANDIDATE_ID_VAR = "tv_wonder_priority_next_candidate_id"
PRIORITY_CANDIDATE_ID_LOCAL = "tv_wonder_priority_candidate_id"
PRIORITY_CANDIDATE_WONDER_ID_LOCAL = "tv_wonder_priority_saved_candidate_wonder_id"
PRIORITY_TARGET_WONDER_ID_LOCAL = "tv_wonder_priority_target_candidate_wonder_id"
PRIORITY_CANDIDATE_MODE_LOCAL = "tv_wonder_priority_candidate_mode"
PRIORITY_CANDIDATE_SITE_MATCH_VAR = "tv_wonder_priority_candidate_site_matches"
PRIORITY_CANDIDATE_VALID_VAR = "tv_wonder_priority_candidate_valid"
PRIORITY_CANDIDATE_CURRENT_MODE_VAR = "tv_wonder_priority_candidate_current_mode"
PRIORITY_CANDIDATE_WONDER_ID_VAR = "tv_wonder_priority_candidate_wonder_id"
EXISTING_WONDER_ID_LOCAL = "tv_wonder_existing_wonder_id"
EXISTING_RITUAL_STYLE_LOCAL = "tv_wonder_existing_ritual_style"
EXISTING_FOUND_VAR = "tv_wonder_existing_found"


def module_building_type_map_name(part_key: str) -> str:
    # Event option tooltips can render local_var building types, but the pre-renderer
    # failed when the map key was computed earlier in the same visible option chain.
    return f"tv_wonder_id_to_{part_key}_module_building_type"


def module_building_type_var_name(part_key: str) -> str:
    return f"tv_wonder_{part_key}_module_building_type"


def final_building_type_map_name(style: int) -> str:
    return f"tv_wonder_id_to_style_{style}_final_building_type"


def final_building_type_var_name(style: int) -> str:
    return f"tv_wonder_style_{style}_final_building_type"


def building_type_ref(building: str) -> str:
    if (
        building.startswith('"')
        or ":" in building
        or building in {"prev", "this", "root"}
    ):
        return building
    return f"building_type:{building}"


def global_map_expr(map_name: str, key: str) -> str:
    return f'"global_variable_map({map_name}|{key})"'


def variable_map_expr(map_name: str, key: str) -> str:
    return f'"variable_map({map_name}|{key})"'


def capture_global_map_value(var_name: str, map_name: str, key: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}set_local_variable = {{",
        f"{prefix}{T}name = {var_name}",
        f"{prefix}{T}value = {global_map_expr(map_name, key)}",
        f"{prefix}}}",
    ]


def loc_level(building: str, op: str, level: int) -> str:
    return f"location_building_level = {{ building_type = {building_type_ref(building)} value {op} {level} }}"


def change_level(building: str, value: int, owner: str = "prev") -> list[str]:
    return [
        f"{T}change_building_level_in_location = {{",
        f"{T}{T}building = {building_type_ref(building)}",
        f"{T}{T}value = {value}",
        f"{T}{T}owner = {owner}",
        f"{T}}}",
    ]


def change_level_by_value(building: str, value_lines: list[str], owner: str = "prev") -> list[str]:
    return [
        f"{T}change_building_level_in_location = {{",
        f"{T}{T}building = {building_type_ref(building)}",
        f"{T}{T}value = {{",
        *[f"{T}{T}{T}{line}" for line in value_lines],
        f"{T}{T}}}",
        f"{T}{T}owner = {owner}",
        f"{T}}}",
    ]


def construct_building_line(building: str, owner: str | None = None) -> str:
    owner_clause = f" owner = {owner}" if owner else ""
    return (
        f"construct_building = {{ building_type = {building_type_ref(building)}{owner_clause} "
        f"cost_multiplier = 0 cost_multiplier_reason = \"game_concept_event\" instant = yes }}"
    )


def add_units_from_module_level(part: str, building: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    for level in range(1, 7):
        lines.extend(
            [
                f"{prefix}if = {{",
                f"{prefix}{T}limit = {{ {loc_level(building, '>=', level)} }}",
                f"{prefix}{T}prev = {{ change_variable = {{ name = tv_wonder_{part}_units add = 1 }} }}",
                f"{prefix}}}",
            ]
        )
    return lines


def set_units_to_at_least_level(building: str, parts: list[dict], indent: int = 1) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    for level in range(1, 7):
        lines.append(f"{prefix}if = {{")
        lines.append(f"{prefix}{T}limit = {{ {loc_level(building, '>=', level)} }}")
        lines.append(f"{prefix}{T}prev = {{")
        for part in parts:
            key = part["key"]
            lines.append(f"{prefix}{T}{T}if = {{")
            lines.append(f"{prefix}{T}{T}{T}limit = {{ var:tv_wonder_{key}_units < {level} }}")
            lines.append(f"{prefix}{T}{T}{T}set_variable = {{ name = tv_wonder_{key}_units value = {level} }}")
            lines.append(f"{prefix}{T}{T}}}")
        lines.append(f"{prefix}{T}}}")
        lines.append(f"{prefix}}}")
    return lines


def add_building_level(branch_limit: str, building: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}if = {{",
        f"{prefix}{T}limit = {{ {branch_limit} }}",
        f"{prefix}{T}if = {{",
        f"{prefix}{T}{T}limit = {{ NOT = {{ has_building = {building_type_ref(building)} }} }}",
        f"{prefix}{T}{T}{construct_building_line(building)}",
        f"{prefix}{T}}}",
        f"{prefix}{T}else = {{",
        *[f"{prefix}{T}{line}" for line in change_level(building, 1)],
        f"{prefix}{T}}}",
        f"{prefix}}}",
    ]


def add_building_level_if_missing(branch_limit: str, building: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}if = {{",
        f"{prefix}{T}limit = {{ {branch_limit} NOT = {{ has_building = {building_type_ref(building)} }} }}",
        f"{prefix}{T}{construct_building_line(building)}",
        f"{prefix}}}",
    ]


def reduce_building_level(building: str) -> list[str]:
    return change_level(building, -1)


def any_building_block(buildings: list[str], indent: int) -> list[str]:
    prefix = T * indent
    lines = [f"{prefix}OR = {{"]
    for building in buildings:
        lines.append(f"{prefix}{T}has_building = {building_type_ref(building)}")
    lines.append(f"{prefix}}}")
    return lines


def final_building_level_exact(building: str, level: int, indent: int) -> list[str]:
    prefix = T * indent
    lines = [f"{prefix}{loc_level(building, '>=', level)}"]
    if level < 6:
        lines.append(f"{prefix}NOT = {{ {loc_level(building, '>=', level + 1)} }}")
    return lines


def country_level_matches(level_var: str, level: int, indent: int) -> list[str]:
    prefix = T * indent
    return [f"{prefix}prev = {{ var:{level_var} ?= {level} }}"]


def unit_gap_matches(unit_var: str, gap: int, indent: int) -> list[str]:
    prefix = T * indent
    pairs: list[tuple[int, int]] = []
    for wonder_level in range(0, 7):
        for unit_level in range(0, 7):
            if max(unit_level - wonder_level, 0) == gap:
                pairs.append((unit_level, wonder_level))
    lines = [f"{prefix}OR = {{"]
    for unit_level, wonder_level in pairs:
        lines.append(f"{prefix}{T}AND = {{")
        lines.append(f"{prefix}{T}{T}prev = {{ var:{unit_var} ?= {unit_level} }}")
        lines.append(f"{prefix}{T}{T}prev = {{ var:tv_wonder_level ?= {wonder_level} }}")
        lines.append(f"{prefix}{T}}}")
    lines.append(f"{prefix}}}")
    return lines


def sync_building_to_literal_level(building: str, target_level: int, indent: int) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    branch_head = "if"
    if target_level > 0:
        lines.append(f"{prefix}if = {{")
        lines.append(f"{prefix}{T}limit = {{ NOT = {{ has_building = {building_type_ref(building)} }} }}")
        lines.append(
            f'{prefix}{T}construct_building = {{ building_type = {building_type_ref(building)} cost_multiplier = 0 cost_multiplier_reason = "game_concept_event" instant = yes }}'
        )
        if target_level > 1:
            lines.extend([f"{prefix}{T}{line}" for line in change_level(building, target_level - 1)])
        lines.append(f"{prefix}}}")
        branch_head = "else_if"
    for current_level in range(6, 0, -1):
        delta = target_level - current_level
        if delta == 0:
            continue
        lines.append(f"{prefix}{branch_head} = {{")
        lines.append(f"{prefix}{T}limit = {{")
        lines.extend(final_building_level_exact(building, current_level, indent + 2))
        lines.append(f"{prefix}{T}}}")
        lines.extend([f"{prefix}{T}{line}" for line in change_level(building, delta)])
        lines.append(f"{prefix}}}")
        branch_head = "else_if"
    return lines


def sync_building_from_target_levels(
    building: str,
    target_condition_builder,
    indent: int,
) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    head = "if"
    for target_level in range(6, -1, -1):
        lines.append(f"{prefix}{head} = {{")
        lines.append(f"{prefix}{T}limit = {{")
        lines.extend(target_condition_builder(target_level, indent + 2))
        lines.append(f"{prefix}{T}}}")
        lines.extend(sync_building_to_literal_level(building, target_level, indent + 1))
        lines.append(f"{prefix}}}")
        head = "else_if"
    return lines


def capture_variable_map_value(var_name: str, map_name: str, key: str, indent: int = 1) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}set_local_variable = {{",
        f"{prefix}{T}name = {var_name}",
        f"{prefix}{T}value = {variable_map_expr(map_name, key)}",
        f"{prefix}}}",
    ]


def append_remove_priority_candidate_by_key(lines: list[str], key: str, indent: int) -> None:
    prefix = T * indent
    for map_name in [
        PRIORITY_CANDIDATE_SITE_BY_ID_MAP,
        PRIORITY_CANDIDATE_WONDER_BY_ID_MAP,
        PRIORITY_CANDIDATE_MODE_BY_ID_MAP,
    ]:
        lines.append(f"{prefix}remove_from_variable_map = {{ name = {map_name} key = {key} }}")


def append_priority_candidate_common_key_guards(lines: list[str], key: str, indent: int) -> None:
    prefix = T * indent
    lines.append(f"{prefix}scope:tv_wonder_priority_owner = {{")
    for map_name in [
        PRIORITY_CANDIDATE_WONDER_BY_ID_MAP,
        PRIORITY_CANDIDATE_MODE_BY_ID_MAP,
    ]:
        lines.append(f"{prefix}{T}is_key_in_variable_map = {{ name = {map_name} target = {key} }}")
    lines.append(f"{prefix}}}")


def append_priority_candidate_validation_effect(lines: list[str], wonders: list[dict]) -> None:
    lines.append("tv_wonder_validate_priority_candidate_for_saved_wonder_effect = {")
    lines.append(f"{T}scope:tv_wonder_priority_owner = {{")
    lines.append(f"{T}{T}remove_variable = {PRIORITY_CANDIDATE_VALID_VAR}")
    lines.append(f"{T}{T}remove_variable = {PRIORITY_CANDIDATE_CURRENT_MODE_VAR}")
    lines.append(f"{T}}}")
    for wonder in wonders:
        key = wonder["key"]
        lines.append(f"{T}if = {{")
        lines.append(f"{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}has_owner = yes")
        lines.append(f"{T}{T}{T}owner ?= scope:tv_wonder_priority_owner")
        lines.append(f"{T}{T}{T}scope:tv_wonder_priority_owner = {{ var:{PRIORITY_CANDIDATE_WONDER_ID_VAR} ?= {wonder['id']} }}")
        lines.append(f"{T}{T}}}")
        lines.append(f"{T}{T}if = {{")
        lines.append(f"{T}{T}{T}limit = {{ tv_wonder_location_is_valid_priority_module_project_for_{key}_trigger = yes }}")
        lines.append(f"{T}{T}{T}scope:tv_wonder_priority_owner = {{")
        lines.append(f"{T}{T}{T}{T}set_variable = {{ name = {PRIORITY_CANDIDATE_VALID_VAR} value = 1 }}")
        lines.append(f"{T}{T}{T}{T}set_variable = {{ name = {PRIORITY_CANDIDATE_CURRENT_MODE_VAR} value = 1 }}")
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}}}")
        lines.append(f"{T}{T}else_if = {{")
        lines.append(f"{T}{T}{T}limit = {{ tv_wonder_location_is_valid_priority_final_project_for_{key}_trigger = yes }}")
        lines.append(f"{T}{T}{T}scope:tv_wonder_priority_owner = {{")
        lines.append(f"{T}{T}{T}{T}set_variable = {{ name = {PRIORITY_CANDIDATE_VALID_VAR} value = 1 }}")
        lines.append(f"{T}{T}{T}{T}set_variable = {{ name = {PRIORITY_CANDIDATE_CURRENT_MODE_VAR} value = 2 }}")
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}}}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def append_priority_candidate_storage_effects(lines: list[str]) -> None:
    lines.append("tv_wonder_remove_current_priority_candidate_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ exists = scope:tv_wonder_priority_owner }}")
    lines.append(f"{T}{T}scope:tv_wonder_priority_owner = {{")
    append_remove_priority_candidate_by_key(lines, f"local_var:{PRIORITY_CANDIDATE_ID_LOCAL}", 3)
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_register_current_priority_candidate_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}exists = scope:tv_wonder_priority_site")
    lines.append(f"{T}{T}{T}has_variable = {PRIORITY_CANDIDATE_WONDER_ID_VAR}")
    lines.append(f"{T}{T}{T}has_variable = {PRIORITY_CANDIDATE_CURRENT_MODE_VAR}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}if = {{")
    lines.append(f"{T}{T}{T}limit = {{ NOT = {{ var:{PRIORITY_NEXT_CANDIDATE_ID_VAR} ?= {{ this >= 1 }} }} }}")
    lines.append(f"{T}{T}{T}set_variable = {{ name = {PRIORITY_NEXT_CANDIDATE_ID_VAR} value = 1 }}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}set_local_variable = {{ name = {PRIORITY_CANDIDATE_ID_LOCAL} value = var:{PRIORITY_NEXT_CANDIDATE_ID_VAR} }}")
    lines.append(f"{T}{T}change_variable = {{ name = {PRIORITY_NEXT_CANDIDATE_ID_VAR} add = 1 }}")
    append_remove_priority_candidate_by_key(lines, f"local_var:{PRIORITY_CANDIDATE_ID_LOCAL}", 2)
    lines.append(f"{T}{T}add_to_variable_map = {{ name = {PRIORITY_CANDIDATE_SITE_BY_ID_MAP} key = local_var:{PRIORITY_CANDIDATE_ID_LOCAL} value = scope:tv_wonder_priority_site }}")
    lines.append(f"{T}{T}add_to_variable_map = {{ name = {PRIORITY_CANDIDATE_WONDER_BY_ID_MAP} key = local_var:{PRIORITY_CANDIDATE_ID_LOCAL} value = var:{PRIORITY_CANDIDATE_WONDER_ID_VAR} }}")
    lines.append(f"{T}{T}add_to_variable_map = {{ name = {PRIORITY_CANDIDATE_MODE_BY_ID_MAP} key = local_var:{PRIORITY_CANDIDATE_ID_LOCAL} value = var:{PRIORITY_CANDIDATE_CURRENT_MODE_VAR} }}")
    lines.append(f"{T}{T}remove_local_variable = {PRIORITY_CANDIDATE_ID_LOCAL}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_unregister_current_site_priority_candidate_effect = {")
    lines.append(f"{T}save_scope_as = tv_wonder_priority_owner")
    lines.append(f"{T}remove_variable = {PRIORITY_CANDIDATE_SITE_MATCH_VAR}")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}exists = scope:tv_wonder_priority_site")
    lines.append(f"{T}{T}{T}has_variable = {PRIORITY_CANDIDATE_WONDER_ID_VAR}")
    lines.append(f"{T}{T}{T}has_variable_map = {PRIORITY_CANDIDATE_SITE_BY_ID_MAP}")
    lines.append(f"{T}{T}{T}has_variable_map = {PRIORITY_CANDIDATE_WONDER_BY_ID_MAP}")
    lines.append(f"{T}{T}{T}has_variable_map = {PRIORITY_CANDIDATE_MODE_BY_ID_MAP}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}set_local_variable = {{ name = {PRIORITY_TARGET_WONDER_ID_LOCAL} value = var:{PRIORITY_CANDIDATE_WONDER_ID_VAR} }}")
    lines.append(f"{T}{T}every_key_in_variable_map = {{")
    lines.append(f"{T}{T}{T}variable = {PRIORITY_CANDIDATE_SITE_BY_ID_MAP}")
    lines.append(f"{T}{T}{T}set_local_variable = {{ name = {PRIORITY_CANDIDATE_ID_LOCAL} value = this }}")
    lines.append(f"{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}limit = {{")
    append_priority_candidate_common_key_guards(lines, f"local_var:{PRIORITY_CANDIDATE_ID_LOCAL}", 5)
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{")
    lines.extend(capture_variable_map_value(
        PRIORITY_CANDIDATE_WONDER_ID_LOCAL,
        PRIORITY_CANDIDATE_WONDER_BY_ID_MAP,
        f"local_var:{PRIORITY_CANDIDATE_ID_LOCAL}",
        5,
    ))
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}NOT = {{ local_var:{PRIORITY_CANDIDATE_WONDER_ID_LOCAL} < local_var:{PRIORITY_TARGET_WONDER_ID_LOCAL} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}NOT = {{ local_var:{PRIORITY_CANDIDATE_WONDER_ID_LOCAL} > local_var:{PRIORITY_TARGET_WONDER_ID_LOCAL} }}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{ remove_variable = {PRIORITY_CANDIDATE_SITE_MATCH_VAR} }}")
    lines.append(f"{T}{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}{variable_map_expr(PRIORITY_CANDIDATE_SITE_BY_ID_MAP, f'local_var:{PRIORITY_CANDIDATE_ID_LOCAL}')} = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}limit = {{ this = scope:tv_wonder_priority_site }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{ set_variable = {{ name = {PRIORITY_CANDIDATE_SITE_MATCH_VAR} value = 1 }} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}limit = {{ scope:tv_wonder_priority_owner = {{ has_variable = {PRIORITY_CANDIDATE_SITE_MATCH_VAR} }} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}tv_wonder_remove_current_priority_candidate_effect = yes")
    lines.append(f"{T}{T}{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{ remove_variable = {PRIORITY_CANDIDATE_SITE_MATCH_VAR} }}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}remove_local_variable = {PRIORITY_CANDIDATE_WONDER_ID_LOCAL}")
    lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}remove_local_variable = {PRIORITY_CANDIDATE_ID_LOCAL}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}remove_local_variable = {PRIORITY_TARGET_WONDER_ID_LOCAL}")
    lines.append(f"{T}}}")
    lines.append(f"{T}remove_variable = {PRIORITY_CANDIDATE_SITE_MATCH_VAR}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_select_saved_priority_proposal_effect = {")
    lines.append(f"{T}remove_variable = tv_wonder_priority_found")
    lines.append(f"{T}remove_variable = tv_wonder_proposal_site")
    lines.append(f"{T}remove_variable = tv_wonder_proposal_mode")
    lines.append(f"{T}save_scope_as = tv_wonder_priority_owner")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}NOT = {{ has_variable = tv_wonder_priority_declined }}")
    lines.append(f"{T}{T}{T}has_variable_map = {PRIORITY_CANDIDATE_SITE_BY_ID_MAP}")
    lines.append(f"{T}{T}{T}has_variable_map = {PRIORITY_CANDIDATE_WONDER_BY_ID_MAP}")
    lines.append(f"{T}{T}{T}has_variable_map = {PRIORITY_CANDIDATE_MODE_BY_ID_MAP}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}every_key_in_variable_map = {{")
    lines.append(f"{T}{T}{T}variable = {PRIORITY_CANDIDATE_SITE_BY_ID_MAP}")
    lines.append(f"{T}{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}{T}NOT = {{ scope:tv_wonder_priority_owner = {{ has_variable = tv_wonder_priority_found }} }}")
    lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}set_local_variable = {{ name = {PRIORITY_CANDIDATE_ID_LOCAL} value = this }}")
    lines.append(f"{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}limit = {{")
    append_priority_candidate_common_key_guards(lines, f"local_var:{PRIORITY_CANDIDATE_ID_LOCAL}", 5)
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{")
    lines.extend(capture_variable_map_value(
        PRIORITY_CANDIDATE_WONDER_ID_LOCAL,
        PRIORITY_CANDIDATE_WONDER_BY_ID_MAP,
        f"local_var:{PRIORITY_CANDIDATE_ID_LOCAL}",
        5,
    ))
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{")
    lines.append(f"{T}{T}{T}{T}{T}set_variable = {{ name = {PRIORITY_CANDIDATE_WONDER_ID_VAR} value = local_var:{PRIORITY_CANDIDATE_WONDER_ID_LOCAL} }}")
    lines.append(f"{T}{T}{T}{T}{T}remove_variable = {PRIORITY_CANDIDATE_VALID_VAR}")
    lines.append(f"{T}{T}{T}{T}{T}remove_variable = {PRIORITY_CANDIDATE_CURRENT_MODE_VAR}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{")
    lines.append(f"{T}{T}{T}{T}{T}{variable_map_expr(PRIORITY_CANDIDATE_SITE_BY_ID_MAP, f'local_var:{PRIORITY_CANDIDATE_ID_LOCAL}')} = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}save_scope_as = tv_wonder_priority_site")
    lines.append(f"{T}{T}{T}{T}{T}{T}tv_wonder_validate_priority_candidate_for_saved_wonder_effect = yes")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}{T}limit = {{ scope:tv_wonder_priority_owner = {{ has_variable = {PRIORITY_CANDIDATE_VALID_VAR} }} }}")
    lines.append(f"{T}{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}remove_from_variable_map = {{ name = {PRIORITY_CANDIDATE_MODE_BY_ID_MAP} key = local_var:{PRIORITY_CANDIDATE_ID_LOCAL} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}add_to_variable_map = {{ name = {PRIORITY_CANDIDATE_MODE_BY_ID_MAP} key = local_var:{PRIORITY_CANDIDATE_ID_LOCAL} value = var:{PRIORITY_CANDIDATE_CURRENT_MODE_VAR} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_proposal value = local_var:{PRIORITY_CANDIDATE_WONDER_ID_LOCAL} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_proposal_mode value = var:{PRIORITY_CANDIDATE_CURRENT_MODE_VAR} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_priority_found value = 1 }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_proposal_site value = scope:tv_wonder_priority_site }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}tv_wonder_set_proposal_on_great_engineer_effect = yes")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}else = {{")
    lines.append(f"{T}{T}{T}{T}{T}tv_wonder_remove_current_priority_candidate_effect = yes")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}scope:tv_wonder_priority_owner = {{")
    lines.append(f"{T}{T}{T}{T}{T}remove_variable = {PRIORITY_CANDIDATE_VALID_VAR}")
    lines.append(f"{T}{T}{T}{T}{T}remove_variable = {PRIORITY_CANDIDATE_CURRENT_MODE_VAR}")
    lines.append(f"{T}{T}{T}{T}{T}remove_variable = {PRIORITY_CANDIDATE_WONDER_ID_VAR}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}remove_local_variable = {PRIORITY_CANDIDATE_WONDER_ID_LOCAL}")
    lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}remove_local_variable = {PRIORITY_CANDIDATE_ID_LOCAL}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def set_building_level_from_level_var(
    building: str,
    level_var: str,
    current_level_var: str,
    indent: int,
) -> list[str]:
    del current_level_var
    return sync_building_from_target_levels(
        building,
        lambda target_level, target_indent: country_level_matches(level_var, target_level, target_indent),
        indent,
    )


def sync_helper_building_to_wonder_level(wonder: dict, indent: int) -> list[str]:
    helper = f"tv_wonder_{wonder['key']}"
    return set_building_level_from_level_var(
        helper,
        "tv_wonder_level",
        f"tv_wonder_{wonder['key']}_helper_current_level",
        indent,
    )


def sync_module_building_to_unit_gap(
    wonder: dict,
    part_key: str,
    building: str,
    indent: int,
) -> list[str]:
    del wonder
    unit_var = f"tv_wonder_{part_key}_units"
    return sync_building_from_target_levels(
        building,
        lambda target_level, target_indent: unit_gap_matches(unit_var, target_level, target_indent),
        indent,
    )


def combine_buildings_to_helper_once(
    helper: str,
    module_names: list[str],
    indent: int,
    owner: str = "prev",
    construct_owner: str | None = None,
) -> list[str]:
    prefix = T * indent
    lines: list[str] = []
    for idx, level in enumerate(range(6, 0, -1)):
        head = "if" if idx == 0 else "else_if"
        lines.append(f"{prefix}{head} = {{")
        lines.append(f"{prefix}{T}limit = {{")
        for module in module_names:
            lines.append(f"{prefix}{T}{T}{loc_level(module, '>=', level)}")
        lines.append(f"{prefix}{T}}}")
        lines.append(f"{prefix}{T}if = {{")
        lines.append(f"{prefix}{T}{T}limit = {{ has_building = {building_type_ref(helper)} }}")
        lines.extend(
            [
                f"{prefix}{T}{line}"
                for line in change_level(helper, level, owner)
            ]
        )
        lines.append(f"{prefix}{T}}}")
        lines.append(f"{prefix}{T}else = {{")
        lines.append(f"{prefix}{T}{T}{construct_building_line(helper, construct_owner)}")
        if level > 1:
            lines.extend(
                [
                    f"{prefix}{T}{line}"
                    for line in change_level(helper, level - 1, owner)
                ]
            )
        lines.append(f"{prefix}{T}}}")
        for module in module_names:
            lines.extend(
                [
                    f"{prefix}{T}{line}"
                    for line in change_level(module, -level, owner)
                ]
            )
        lines.append(f"{prefix}}}")
    return lines


def combine_mapped_modules_to_helper_once(parts: list[dict], indent: int) -> list[str]:
    module_vars = [
        f"local_var:{module_building_type_var_name(part['key'])}"
        for part in parts
    ]
    return combine_buildings_to_helper_once(
        f"local_var:{HELPER_BUILDING_TYPE_VAR}",
        module_vars,
        indent,
        owner="scope:tv_wonder_module_owner",
        construct_owner="scope:tv_wonder_module_owner",
    )


def restore_final_building_state_for_style(
    style: int,
    final_building: str,
    parts: list[dict],
    indent: int,
) -> list[str]:
    prefix = T * indent
    lines = [
        f"{prefix}if = {{",
        f"{prefix}{T}limit = {{ has_building = {building_type_ref(final_building)} }}",
        f"{prefix}{T}prev = {{",
        f"{prefix}{T}{T}set_variable = {{ name = tv_wonder_ceremony_style value = {style} }}",
        f"{prefix}{T}{T}set_variable = {{ name = tv_wonder_ceremony_locked value = 1 }}",
        f"{prefix}{T}}}",
    ]
    lines.extend(set_units_to_at_least_level(final_building, parts, indent + 1))
    lines.append(f"{prefix}}}")
    return lines


def append_destroy_intermediate_buildings_at_location_effect(
    lines: list[str],
    name: str,
    wonders: list[dict],
    parts: list[dict],
) -> None:
    lines.append(f"{name} = {{")
    lines.append(f"{T}prev = {{ save_scope_as = tv_wonder_module_owner }}")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        module_names = [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts]
        final_names = list(wonder["final_buildings"].values())
        lines.append(f"{T}if = {{")
        lines.append(f"{T}{T}limit = {{")
        lines.extend(any_building_block(final_names, 3))
        lines.append(f"{T}{T}}}")
        for building in [helper, *module_names]:
            lines.append(f"{T}{T}if = {{")
            lines.append(f"{T}{T}{T}limit = {{ has_building = building_type:{building} }}")
            lines.append(f"{T}{T}{T}destroy_building_forcefully = \"building(building_type:{building}|scope:tv_wonder_module_owner)\"")
            lines.append(f"{T}{T}}}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")


def main() -> None:
    data = load_wonders_source_data()
    wonders, mechanics = load_all_wonder_mechanics()
    generic_wonders = [wonder for wonder in wonders if not wonder.get("is_unique")]
    unique_wonders = [wonder for wonder in wonders if wonder.get("is_unique")]
    parts = data["parts"]
    final_styles = sorted({int(style) for wonder in wonders for style in wonder["final_buildings"]})
    lines = HEADER[:]

    lines.append("tv_wonder_set_required_progress_effect = {")
    lines.append(f"{T}set_variable = {{ name = tv_wonder_unit_required_progress value = 300000 }}")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}has_global_variable_map = {REQUIRED_PROGRESS_MAP}")
    lines.append(
        f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {REQUIRED_PROGRESS_MAP} target = var:tv_wonder_locked }}"
    )
    lines.append(f"{T}{T}}}")
    lines.extend(capture_global_map_value(REQUIRED_PROGRESS_VAR, REQUIRED_PROGRESS_MAP, "var:tv_wonder_locked", 2))
    lines.append(f"{T}{T}set_variable = {{ name = tv_wonder_unit_required_progress value = local_var:{REQUIRED_PROGRESS_VAR} }}")
    lines.append(f"{T}{T}remove_local_variable = {REQUIRED_PROGRESS_VAR}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    append_priority_candidate_validation_effect(lines, wonders)
    append_priority_candidate_storage_effects(lines)

    lines.append("tv_wonder_construct_module_for_last_completed_part_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}var:tv_wonder_last_completed_part ?= {{ this >= 1 }}")
    lines.append(f"{T}{T}{T}var:tv_wonder_last_completed_part ?= {{ this <= {len(parts)} }}")
    lines.append(f"{T}{T}}}")
    for part_index, part in enumerate(parts, start=1):
        part_key = part["key"]
        module_map = module_building_type_map_name(part_key)
        head = "if" if part_index == 1 else "else_if"
        lines.append(f"{T}{T}{head} = {{")
        lines.append(f"{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}var:tv_wonder_last_completed_part ?= {part_index}")
        lines.append(f"{T}{T}{T}{T}has_global_variable_map = {module_map}")
        lines.append(f"{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {module_map} target = var:tv_wonder_locked }}")
        lines.append(f"{T}{T}{T}}}")
        lines.extend(capture_global_map_value(MODULE_BUILDING_TYPE_VAR, module_map, "var:tv_wonder_locked", 3))
        lines.append(f"{T}{T}{T}save_scope_as = tv_wonder_module_owner")
        lines.append(f"{T}{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(add_building_level("always = yes", f"local_var:{MODULE_BUILDING_TYPE_VAR}", 4))
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}remove_local_variable = {MODULE_BUILDING_TYPE_VAR}")
        lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_sync_units_from_buildings_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}has_global_variable_map = {HELPER_BUILDING_TYPE_MAP}")
    lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {HELPER_BUILDING_TYPE_MAP} target = var:tv_wonder_locked }}")
    for part in parts:
        module_map = module_building_type_map_name(part["key"])
        lines.append(f"{T}{T}{T}has_global_variable_map = {module_map}")
        lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {module_map} target = var:tv_wonder_locked }}")
    lines.append(f"{T}{T}}}")
    lines.extend(capture_global_map_value(HELPER_BUILDING_TYPE_VAR, HELPER_BUILDING_TYPE_MAP, "var:tv_wonder_locked", 2))
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.extend(set_units_to_at_least_level(f"local_var:{HELPER_BUILDING_TYPE_VAR}", parts, 3))
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}remove_local_variable = {HELPER_BUILDING_TYPE_VAR}")
    for style in final_styles:
        final_map = final_building_type_map_name(style)
        final_var = final_building_type_var_name(style)
        lines.append(f"{T}{T}if = {{")
        lines.append(f"{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}has_global_variable_map = {final_map}")
        lines.append(f"{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {final_map} target = var:tv_wonder_locked }}")
        lines.append(f"{T}{T}{T}}}")
        lines.extend(capture_global_map_value(final_var, final_map, "var:tv_wonder_locked", 3))
        lines.append(f"{T}{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(set_units_to_at_least_level(f"local_var:{final_var}", parts, 4))
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}remove_local_variable = {final_var}")
        lines.append(f"{T}{T}}}")
    for part in parts:
        part_key = part["key"]
        module_var = module_building_type_var_name(part_key)
        lines.extend(capture_global_map_value(module_var, module_building_type_map_name(part_key), "var:tv_wonder_locked", 2))
        lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(add_units_from_module_level(part_key, f"local_var:{module_var}", 3))
        lines.append(f"{T}{T}}}")
        lines.append(f"{T}{T}remove_local_variable = {module_var}")
        lines.append(f"{T}{T}clamp_variable = {{ name = tv_wonder_{part_key}_units min = 0 max = 6 }}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_update_wonder_level_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_detect_existing_wonder_at_saved_site_effect = {")
    lines.append(f"{T}remove_variable = {EXISTING_FOUND_VAR}")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}save_scope_as = tv_wonder_existing_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.append(f"{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}{T}{T}has_global_variable_map = {FINAL_BUILDING_WONDER_ID_MAP}")
    lines.append(f"{T}{T}{T}{T}{T}has_global_variable_map = {FINAL_BUILDING_RITUAL_STYLE_MAP}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}ordered_key_in_global_variable_map = {{")
    lines.append(f"{T}{T}{T}{T}{T}variable = {FINAL_BUILDING_WONDER_ID_MAP}")
    lines.append(f"{T}{T}{T}{T}{T}max = {REVERSE_BUILDING_MAP_SCAN_MAX}")
    lines.append(f"{T}{T}{T}{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}NOT = {{ scope:tv_wonder_existing_owner = {{ has_variable = {EXISTING_FOUND_VAR} }} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {FINAL_BUILDING_RITUAL_STYLE_MAP} target = this }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}prev = {{ has_building = prev }}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.extend(capture_global_map_value(EXISTING_WONDER_ID_LOCAL, FINAL_BUILDING_WONDER_ID_MAP, "this", 5))
    lines.extend(capture_global_map_value(EXISTING_RITUAL_STYLE_LOCAL, FINAL_BUILDING_RITUAL_STYLE_MAP, "this", 5))
    lines.append(f"{T}{T}{T}{T}{T}scope:tv_wonder_existing_owner = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_locked value = local_var:{EXISTING_WONDER_ID_LOCAL} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_style value = local_var:{EXISTING_RITUAL_STYLE_LOCAL} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_locked value = 1 }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = {EXISTING_FOUND_VAR} value = 1 }}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}{T}remove_local_variable = {EXISTING_RITUAL_STYLE_LOCAL}")
    lines.append(f"{T}{T}{T}{T}{T}remove_local_variable = {EXISTING_WONDER_ID_LOCAL}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}limit = {{ has_global_variable_map = {INTERMEDIATE_BUILDING_WONDER_ID_MAP} }}")
    lines.append(f"{T}{T}{T}{T}ordered_key_in_global_variable_map = {{")
    lines.append(f"{T}{T}{T}{T}{T}variable = {INTERMEDIATE_BUILDING_WONDER_ID_MAP}")
    lines.append(f"{T}{T}{T}{T}{T}max = {REVERSE_BUILDING_MAP_SCAN_MAX}")
    lines.append(f"{T}{T}{T}{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}NOT = {{ scope:tv_wonder_existing_owner = {{ has_variable = {EXISTING_FOUND_VAR} }} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}prev = {{ has_building = prev }}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.extend(capture_global_map_value(EXISTING_WONDER_ID_LOCAL, INTERMEDIATE_BUILDING_WONDER_ID_MAP, "this", 5))
    lines.append(f"{T}{T}{T}{T}{T}scope:tv_wonder_existing_owner = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_locked value = local_var:{EXISTING_WONDER_ID_LOCAL} }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = {EXISTING_FOUND_VAR} value = 1 }}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}{T}remove_local_variable = {EXISTING_WONDER_ID_LOCAL}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}remove_variable = {EXISTING_FOUND_VAR}")
    lines.append(f"{T}tv_wonder_index_refresh_country_cache_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_sync_existing_final_building_level_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}save_scope_as = tv_wonder_existing_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.append(f"{T}{T}{T}if = {{")
    lines.append(f"{T}{T}{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}{T}{T}has_global_variable_map = {FINAL_BUILDING_WONDER_ID_MAP}")
    lines.append(f"{T}{T}{T}{T}{T}has_global_variable_map = {FINAL_BUILDING_RITUAL_STYLE_MAP}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}ordered_key_in_global_variable_map = {{")
    lines.append(f"{T}{T}{T}{T}{T}variable = {FINAL_BUILDING_WONDER_ID_MAP}")
    lines.append(f"{T}{T}{T}{T}{T}max = {REVERSE_BUILDING_MAP_SCAN_MAX}")
    lines.append(f"{T}{T}{T}{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {FINAL_BUILDING_RITUAL_STYLE_MAP} target = this }}")
    lines.append(f"{T}{T}{T}{T}{T}{T}prev = {{ has_building = prev }}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.extend(capture_global_map_value(EXISTING_WONDER_ID_LOCAL, FINAL_BUILDING_WONDER_ID_MAP, "this", 5))
    lines.extend(capture_global_map_value(EXISTING_RITUAL_STYLE_LOCAL, FINAL_BUILDING_RITUAL_STYLE_MAP, "this", 5))
    lines.append(f"{T}{T}{T}{T}{T}prev = {{")
    for level in range(6, 0, -1):
        lines.append(f"{T}{T}{T}{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}{T}{T}{T}limit = {{ {loc_level('prev', '>=', level)} }}")
        lines.append(f"{T}{T}{T}{T}{T}{T}{T}scope:tv_wonder_existing_owner = {{")
        lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_locked value = local_var:{EXISTING_WONDER_ID_LOCAL} }}")
        lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_style value = local_var:{EXISTING_RITUAL_STYLE_LOCAL} }}")
        lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_locked value = 1 }}")
        for part in parts:
            lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}if = {{")
            lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}{T}limit = {{ var:tv_wonder_{part['key']}_units < {level} }}")
            lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_{part['key']}_units value = {level} }}")
            lines.append(f"{T}{T}{T}{T}{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}{T}{T}remove_local_variable = {EXISTING_RITUAL_STYLE_LOCAL}")
    lines.append(f"{T}{T}{T}{T}{T}remove_local_variable = {EXISTING_WONDER_ID_LOCAL}")
    lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_update_wonder_level_effect = yes")
    lines.append(f"{T}tv_wonder_index_refresh_country_cache_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_restore_locked_wonder_final_building_state_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}}}")
    for style in final_styles:
        final_map = final_building_type_map_name(style)
        final_var = final_building_type_var_name(style)
        lines.append(f"{T}{T}if = {{")
        lines.append(f"{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}has_global_variable_map = {final_map}")
        lines.append(f"{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {final_map} target = var:tv_wonder_locked }}")
        lines.append(f"{T}{T}{T}}}")
        lines.extend(capture_global_map_value(final_var, final_map, "var:tv_wonder_locked", 3))
        lines.append(f"{T}{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(restore_final_building_state_for_style(style, f"local_var:{final_var}", parts, 4))
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}remove_local_variable = {final_var}")
        lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_update_wonder_level_effect = yes")
    lines.append(f"{T}tv_wonder_index_refresh_country_cache_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_apply_helper_building_to_final_site_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}{T}has_global_variable_map = {HELPER_BUILDING_TYPE_MAP}")
    lines.append(f"{T}{T}{T}is_key_in_global_variable_map = {{ name = {HELPER_BUILDING_TYPE_MAP} target = var:tv_wonder_locked }}")
    lines.append(f"{T}{T}}}")
    lines.extend(capture_global_map_value(HELPER_BUILDING_TYPE_VAR, HELPER_BUILDING_TYPE_MAP, "var:tv_wonder_locked", 2))
    lines.append(f"{T}{T}save_scope_as = tv_wonder_module_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.extend(
        set_building_level_from_level_var(
            f"local_var:{HELPER_BUILDING_TYPE_VAR}",
            "tv_wonder_level",
            "tv_wonder_helper_current_level",
            3,
        )
    )
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}remove_local_variable = {HELPER_BUILDING_TYPE_VAR}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_materialize_module_buildings_from_unit_vars_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}tv_wonder_construction_site_selected_trigger = yes")
    lines.append(f"{T}{T}{T}has_variable = tv_wonder_locked")
    lines.append(f"{T}{T}}}")
    for part in parts:
        part_key = part["key"]
        module_map = module_building_type_map_name(part_key)
        lines.append(f"{T}{T}if = {{")
        lines.append(
            f"{T}{T}{T}limit = {{ "
            f"has_global_variable_map = {module_map} "
            f"is_key_in_global_variable_map = {{ name = {module_map} target = var:tv_wonder_locked }} }}"
        )
        lines.extend(capture_global_map_value(MODULE_BUILDING_TYPE_VAR, module_map, "var:tv_wonder_locked", 3))
        lines.append(f"{T}{T}{T}save_scope_as = tv_wonder_module_owner")
        lines.append(f"{T}{T}{T}var:tv_wonder_site ?= {{")
        lines.extend(
            sync_module_building_to_unit_gap(
                {},
                part_key,
                f"local_var:{MODULE_BUILDING_TYPE_VAR}",
                4,
            )
        )
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}remove_local_variable = {MODULE_BUILDING_TYPE_VAR}")
        lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_combine_completed_modules_at_location_effect = {")
    lines.append(f"{T}prev = {{ save_scope_as = tv_wonder_module_owner }}")
    lines.append(f"{T}save_scope_as = {COMBINE_LOCATION_SCOPE}")
    lines.append(f"{T}remove_variable = {COMBINE_FOUND_VAR}")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}has_global_variable_map = {HELPER_BUILDING_TYPE_MAP}")
    for part in parts:
        lines.append(f"{T}{T}{T}has_global_variable_map = {module_building_type_map_name(part['key'])}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}{T}ordered_key_in_global_variable_map = {{")
    lines.append(f"{T}{T}{T}variable = {HELPER_BUILDING_TYPE_MAP}")
    lines.append(f"{T}{T}{T}max = {REVERSE_BUILDING_MAP_SCAN_MAX}")
    lines.append(f"{T}{T}{T}limit = {{")
    lines.append(f"{T}{T}{T}{T}NOT = {{ scope:{COMBINE_LOCATION_SCOPE} = {{ has_variable = {COMBINE_FOUND_VAR} }} }}")
    for part in parts:
        module_map = module_building_type_map_name(part["key"])
        lines.append(f"{T}{T}{T}{T}is_key_in_global_variable_map = {{ name = {module_map} target = this }}")
        lines.append(f"{T}{T}{T}{T}{global_map_expr(module_map, 'this')} = {{")
        lines.append(f"{T}{T}{T}{T}{T}scope:{COMBINE_LOCATION_SCOPE} = {{")
        lines.append(f"{T}{T}{T}{T}{T}{T}{loc_level('prev', '>=', 1)}")
        lines.append(f"{T}{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}{T}scope:{COMBINE_LOCATION_SCOPE} = {{")
    lines.append(f"{T}{T}{T}{T}set_local_variable = {{ name = {COMBINE_WONDER_ID_LOCAL} value = prev }}")
    lines.extend(capture_global_map_value(
        HELPER_BUILDING_TYPE_VAR,
        HELPER_BUILDING_TYPE_MAP,
        f"local_var:{COMBINE_WONDER_ID_LOCAL}",
        4,
    ))
    for part in parts:
        part_key = part["key"]
        lines.extend(capture_global_map_value(
            module_building_type_var_name(part_key),
            module_building_type_map_name(part_key),
            f"local_var:{COMBINE_WONDER_ID_LOCAL}",
            4,
        ))
    lines.extend(combine_mapped_modules_to_helper_once(parts, 4))
    lines.append(f"{T}{T}{T}{T}set_variable = {{ name = {COMBINE_FOUND_VAR} value = 1 }}")
    for part in parts:
        lines.append(f"{T}{T}{T}{T}remove_local_variable = {module_building_type_var_name(part['key'])}")
    lines.append(f"{T}{T}{T}{T}remove_local_variable = {HELPER_BUILDING_TYPE_VAR}")
    lines.append(f"{T}{T}{T}{T}remove_local_variable = {COMBINE_WONDER_ID_LOCAL}")
    lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}remove_variable = {COMBINE_FOUND_VAR}")
    lines.append("}")
    lines.append("")

    append_destroy_intermediate_buildings_at_location_effect(
        lines,
        "tv_wonder_destroy_discovered_generic_intermediate_buildings_at_location_effect",
        generic_wonders,
        parts,
    )
    append_destroy_intermediate_buildings_at_location_effect(
        lines,
        "tv_wonder_destroy_discovered_unique_intermediate_buildings_at_location_effect",
        unique_wonders,
        parts,
    )
    lines.append("tv_wonder_destroy_intermediate_buildings_at_location_effect = {")
    lines.append(f"{T}tv_wonder_destroy_discovered_generic_intermediate_buildings_at_location_effect = yes")
    lines.append(f"{T}tv_wonder_destroy_discovered_unique_intermediate_buildings_at_location_effect = yes")
    lines.append("}")
    lines.append("")

    OUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
