import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from wonder_mechanics_lib import WONDERS_FILE, ceremony_modifier_for_building, load_all_wonder_mechanics, load_yaml

OUT_FILE = REPO_ROOT / "src" / "in_game" / "common" / "scripted_effects" / "tv_wonder_module_effects.txt"
SCRIPT_REL = "scripts/in_game/common/scripted_effects/gen_tv_wonder_module_effects.py"
DATA_REL = "data/wonders.yaml + data/wonder_mechanics.yaml + data/unique_wonders.yaml"

HEADER = [
    f"# @Generated by {SCRIPT_REL}",
    f"#   Data:    {DATA_REL}",
    f"#   Regen:   conda run --no-capture-output -n eu5 python {SCRIPT_REL}",
    "# Do not edit directly - modify the data file and re-run the generator.",
    "",
]

T = "\t"


def loc_level(building: str, op: str, level: int) -> str:
    return f"location_building_level = {{ building_type = building_type:{building} value {op} {level} }}"


def change_level(building: str, value: int) -> list[str]:
    return [
        f"{T}change_building_level_in_location = {{",
        f"{T}{T}building = building_type:{building}",
        f"{T}{T}value = {value}",
        f"{T}{T}owner = prev",
        f"{T}}}",
    ]


def add_units_from_module_level(part: str, building: str) -> list[str]:
    lines: list[str] = []
    for level in range(1, 7):
        lines.extend(
            [
                f"{T}if = {{",
                f"{T}{T}limit = {{ {loc_level(building, '>=', level)} }}",
                f"{T}{T}prev = {{ change_variable = {{ name = tv_wonder_{part}_units add = 1 }} }}",
                f"{T}}}",
            ]
        )
    return lines


def set_units_to_at_least_level(building: str, parts: list[dict]) -> list[str]:
    lines: list[str] = []
    for level in range(1, 7):
        lines.append(f"{T}if = {{")
        lines.append(f"{T}{T}limit = {{ {loc_level(building, '>=', level)} }}")
        lines.append(f"{T}{T}prev = {{")
        for part in parts:
            key = part["key"]
            lines.append(f"{T}{T}{T}if = {{")
            lines.append(f"{T}{T}{T}{T}limit = {{ var:tv_wonder_{key}_units < {level} }}")
            lines.append(f"{T}{T}{T}{T}set_variable = {{ name = tv_wonder_{key}_units value = {level} }}")
            lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}}}")
        lines.append(f"{T}}}")
    return lines


def add_building_level(branch_limit: str, building: str) -> list[str]:
    return [
        f"{T}if = {{",
        f"{T}{T}limit = {{ {branch_limit} }}",
        f"{T}{T}if = {{",
        f"{T}{T}{T}limit = {{ NOT = {{ has_building = building_type:{building} }} }}",
        f"{T}{T}{T}construct_building = {{ building_type = building_type:{building} cost_multiplier = 0 cost_multiplier_reason = \"game_concept_event\" instant = yes }}",
        f"{T}{T}}}",
        f"{T}{T}else = {{",
        *[f"{T}{T}{line}" for line in change_level(building, 1)],
        f"{T}{T}}}",
        f"{T}}}",
    ]


def reduce_building_level(building: str) -> list[str]:
    return change_level(building, -1)


def any_building_block(buildings: list[str], indent: int) -> list[str]:
    prefix = T * indent
    lines = [f"{prefix}OR = {{"]
    for building in buildings:
        lines.append(f"{prefix}{T}has_building = building_type:{building}")
    lines.append(f"{prefix}}}")
    return lines


def final_building_level_exact(building: str, level: int, indent: int) -> list[str]:
    prefix = T * indent
    lines = [f"{prefix}{loc_level(building, '>=', level)}"]
    if level < 6:
        lines.append(f"{prefix}NOT = {{ {loc_level(building, '>=', level + 1)} }}")
    return lines


def stored_tier_can_expand(wonder: dict, final_building: str, level: int, indent: int) -> list[str]:
    prefix = T * indent
    tier_var = f"tv_wonder_{wonder['key']}_scale_tier"
    lines = final_building_level_exact(final_building, level, indent)
    lines.append(f"{prefix}OR = {{")
    lines.append(f"{prefix}{T}var:{tier_var} ?= {{ this >= {level + 1} }}")
    lines.append(f"{prefix}{T}NOT = {{ has_variable = {tier_var} }}")
    lines.append(f"{prefix}}}")
    return lines


def final_building_below_cap_conditions(wonder: dict, indent: int) -> list[str]:
    prefix = T * indent
    lines = [f"{prefix}OR = {{"]
    for final_building in wonder["final_buildings"].values():
        for level in range(1, 6):
            lines.append(f"{prefix}{T}AND = {{")
            lines.extend(stored_tier_can_expand(wonder, final_building, level, indent + 2))
            lines.append(f"{prefix}{T}}}")
    lines.append(f"{prefix}}}")
    return lines


def proposal_setter(wonder: dict, mode: int, indent: int) -> list[str]:
    prefix = T * indent
    return [
        f"{prefix}prev = {{",
        f"{prefix}{T}set_variable = {{ name = tv_wonder_proposal value = {wonder['id']} }}",
        f"{prefix}{T}set_variable = {{ name = tv_wonder_proposal_mode value = {mode} }}",
        f"{prefix}{T}set_variable = {{ name = tv_wonder_priority_found value = 1 }}",
        f"{prefix}{T}set_variable = {{ name = tv_wonder_proposal_site value = scope:tv_wonder_priority_site }}",
        f"{prefix}{T}tv_wonder_set_proposal_on_great_engineer_effect = yes",
        f"{prefix}}}",
    ]


def main() -> None:
    data = load_yaml(WONDERS_FILE)
    wonders, mechanics = load_all_wonder_mechanics()
    parts = data["parts"]
    lines = HEADER[:]

    lines.append("tv_wonder_clear_current_base_modifiers_effect = {")
    for idx, wonder in enumerate(wonders):
        head = "if" if idx == 0 else "else_if"
        lines.append(f"{T}{head} = {{")
        lines.append(f"{T}{T}limit = {{ var:tv_wonder_locked ?= {wonder['id']} }}")
        for level in range(1, 7):
            lines.append(f"{T}{T}remove_country_modifier = tv_wonder_{wonder['key']}_level_{level}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_clear_current_ceremony_modifiers_effect = {")
    for idx, wonder in enumerate(wonders):
        head = "if" if idx == 0 else "else_if"
        lines.append(f"{T}{head} = {{")
        lines.append(f"{T}{T}limit = {{ var:tv_wonder_locked ?= {wonder['id']} }}")
        for building in wonder["final_buildings"].values():
            ceremony_modifier = ceremony_modifier_for_building(wonder, mechanics, building)
            if ceremony_modifier is None:
                continue
            modifier_name, _ = ceremony_modifier
            lines.append(f"{T}{T}remove_country_modifier = {modifier_name}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_set_required_progress_effect = {")
    lines.append(f"{T}set_variable = {{ name = tv_wonder_unit_required_progress value = 300000 }}")
    for wonder in wonders:
        progress = data["sizes"][wonder["size"]]["progress"]
        prefix = "if" if wonder is wonders[0] else "else_if"
        lines.append(f"{T}{prefix} = {{")
        lines.append(f"{T}{T}limit = {{ var:tv_wonder_locked ?= {wonder['id']} }}")
        lines.append(f"{T}{T}set_variable = {{ name = tv_wonder_unit_required_progress value = {progress} }}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_construct_module_for_last_completed_part_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}save_scope_as = tv_wonder_module_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for wonder in wonders:
        for idx, part in enumerate(parts, start=1):
            building = f"tv_wonder_{wonder['key']}_{part['key']}"
            limit = f"prev = {{ var:tv_wonder_locked ?= {wonder['id']} var:tv_wonder_last_completed_part ?= {idx} }}"
            lines.extend([f"{T}{T}{line}" for line in add_building_level(limit, building)])
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_combine_completed_modules_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}save_scope_as = tv_wonder_module_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        module_names = [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts]
        for level in range(1, 7):
            lines.append(f"{T}{T}{T}while = {{")
            lines.append(f"{T}{T}{T}{T}limit = {{")
            lines.append(f"{T}{T}{T}{T}{T}prev = {{ var:tv_wonder_locked ?= {wonder['id']} }}")
            for module in module_names:
                lines.append(f"{T}{T}{T}{T}{T}{loc_level(module, '>=', level)}")
            lines.append(f"{T}{T}{T}{T}}}")
            for module in module_names:
                lines.extend([f"{T}{T}{T}{line}" for line in reduce_building_level(module)])
            lines.extend([f"{T}{T}{T}{line}" for line in add_building_level("always = yes", helper)])
            lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_sync_units_from_buildings_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for part in parts:
        lines.append(f"{T}{T}{T}prev = {{ set_variable = {{ name = tv_wonder_{part['key']}_units value = 0 }} }}")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{ prev = {{ var:tv_wonder_locked ?= {wonder['id']} }} }}")
        lines.extend([f"{T}{T}{line}" for line in set_units_to_at_least_level(helper, parts)])
        for final_building in wonder["final_buildings"].values():
            lines.extend([f"{T}{T}{line}" for line in set_units_to_at_least_level(final_building, parts)])
        lines.append(f"{T}{T}{T}}}")
        for part in parts:
            building = f"tv_wonder_{wonder['key']}_{part['key']}"
            lines.append(f"{T}{T}{T}if = {{")
            lines.append(f"{T}{T}{T}{T}limit = {{ prev = {{ var:tv_wonder_locked ?= {wonder['id']} }} }}")
            lines.extend([f"{T}{T}{line}" for line in add_units_from_module_level(part["key"], building)])
            lines.append(f"{T}{T}{T}{T}prev = {{ clamp_variable = {{ name = tv_wonder_{part['key']}_units min = 0 max = 6 }} }}")
            lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_update_wonder_level_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_detect_existing_wonder_at_saved_site_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for wonder in wonders:
        all_buildings = [f"tv_wonder_{wonder['key']}"] + [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts] + list(wonder["final_buildings"].values())
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}{T}OR = {{")
        for building in all_buildings:
            lines.append(f"{T}{T}{T}{T}{T}{T}has_building = building_type:{building}")
        lines.append(f"{T}{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}prev = {{ set_variable = {{ name = tv_wonder_locked value = {wonder['id']} }} }}")
        for style, building in wonder["final_buildings"].items():
            lines.append(f"{T}{T}{T}{T}if = {{")
            lines.append(f"{T}{T}{T}{T}{T}limit = {{ has_building = building_type:{building} }}")
            lines.append(f"{T}{T}{T}{T}{T}prev = {{")
            lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_style value = {style} }}")
            lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_locked value = 1 }}")
            lines.append(f"{T}{T}{T}{T}{T}}}")
            lines.append(f"{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_sync_existing_final_building_level_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for wonder in wonders:
        for style, building in wonder["final_buildings"].items():
            lines.append(f"{T}{T}{T}if = {{")
            lines.append(f"{T}{T}{T}{T}limit = {{ has_building = building_type:{building} }}")
            for level in range(6, 0, -1):
                lines.append(f"{T}{T}{T}{T}if = {{")
                lines.append(f"{T}{T}{T}{T}{T}limit = {{ {loc_level(building, '>=', level)} }}")
                lines.append(f"{T}{T}{T}{T}{T}prev = {{")
                lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_locked value = {wonder['id']} }}")
                lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_style value = {style} }}")
                lines.append(f"{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_ceremony_locked value = 1 }}")
                for part in parts:
                    lines.append(f"{T}{T}{T}{T}{T}{T}if = {{")
                    lines.append(f"{T}{T}{T}{T}{T}{T}{T}limit = {{ var:tv_wonder_{part['key']}_units < {level} }}")
                    lines.append(f"{T}{T}{T}{T}{T}{T}{T}set_variable = {{ name = tv_wonder_{part['key']}_units value = {level} }}")
                    lines.append(f"{T}{T}{T}{T}{T}{T}}}")
                lines.append(f"{T}{T}{T}{T}{T}}}")
                lines.append(f"{T}{T}{T}{T}}}")
            lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append(f"{T}tv_wonder_update_wonder_level_effect = yes")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_apply_helper_building_to_final_site_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}save_scope_as = tv_wonder_module_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{ prev = {{ var:tv_wonder_locked ?= {wonder['id']} }} }}")
        for level in range(1, 7):
            lines.append(f"{T}{T}{T}{T}while = {{")
            lines.append(f"{T}{T}{T}{T}{T}limit = {{ prev = {{ var:tv_wonder_level ?= {level} }} NOT = {{ {loc_level(helper, '>=', level)} }} }}")
            lines.extend([f"{T}{T}{T}{T}{line}" for line in add_building_level("always = yes", helper)])
            lines.append(f"{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_materialize_module_buildings_from_unit_vars_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}save_scope_as = tv_wonder_module_owner")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    for wonder in wonders:
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{ prev = {{ var:tv_wonder_locked ?= {wonder['id']} }} }}")
        for part in parts:
            building = f"tv_wonder_{wonder['key']}_{part['key']}"
            part_key = part["key"]
            for level in range(1, 7):
                for completed_level in range(0, level):
                    module_level = level - completed_level
                    lines.append(f"{T}{T}{T}{T}if = {{")
                    lines.append(f"{T}{T}{T}{T}{T}limit = {{")
                    lines.append(f"{T}{T}{T}{T}{T}{T}prev = {{")
                    lines.append(f"{T}{T}{T}{T}{T}{T}{T}var:tv_wonder_{part_key}_units ?= {{ this >= {level} }}")
                    lines.append(f"{T}{T}{T}{T}{T}{T}{T}var:tv_wonder_level ?= {completed_level}")
                    lines.append(f"{T}{T}{T}{T}{T}{T}}}")
                    lines.append(f"{T}{T}{T}{T}{T}{T}NOT = {{ {loc_level(building, '>=', module_level)} }}")
                    lines.append(f"{T}{T}{T}{T}{T}}}")
                    lines.extend([f"{T}{T}{T}{T}{line}" for line in add_building_level("always = yes", building)])
                    lines.append(f"{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_combine_completed_modules_at_location_effect = {")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        module_names = [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts]
        for level in range(1, 7):
            lines.append(f"{T}while = {{")
            lines.append(f"{T}{T}limit = {{")
            for module in module_names:
                lines.append(f"{T}{T}{T}{loc_level(module, '>=', level)}")
            lines.append(f"{T}{T}}}")
            for module in module_names:
                lines.extend([f"{T}{T}{line}" for line in reduce_building_level(module)])
            lines.extend([f"{T}{T}{line}" for line in add_building_level("always = yes", helper)])
            lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_destroy_intermediate_buildings_at_location_effect = {")
    lines.append(f"{T}prev = {{ save_scope_as = tv_wonder_module_owner }}")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        module_names = [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts]
        final_names = list(wonder["final_buildings"].values())
        lines.append(f"{T}if = {{")
        lines.append(f"{T}{T}limit = {{")
        lines.extend(any_building_block(final_names, 3))
        lines.append(f"{T}{T}}}")
        for building in [helper, *module_names]:
            lines.append(f"{T}{T}if = {{")
            lines.append(f"{T}{T}{T}limit = {{ has_building = building_type:{building} }}")
            lines.append(f"{T}{T}{T}destroy_building_forcefully = \"building(building_type:{building}|scope:tv_wonder_module_owner)\"")
            lines.append(f"{T}{T}}}")
        lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_destroy_intermediate_buildings_effect = {")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ tv_wonder_construction_site_selected_trigger = yes }}")
    lines.append(f"{T}{T}var:tv_wonder_site ?= {{")
    lines.append(f"{T}{T}{T}tv_wonder_destroy_intermediate_buildings_at_location_effect = yes")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_ensure_helper_building_from_final_buildings_effect = {")
    lines.append(f"{T}# Final buildings are authoritative after inauguration; helper buildings stay construction-only.")
    lines.append("}")
    lines.append("")

    lines.append("tv_wonder_scan_priority_proposal_effect = {")
    lines.append(f"{T}remove_variable = tv_wonder_priority_found")
    lines.append(f"{T}remove_variable = tv_wonder_proposal_site")
    lines.append(f"{T}remove_variable = tv_wonder_proposal_mode")
    lines.append(f"{T}if = {{")
    lines.append(f"{T}{T}limit = {{ NOT = {{ has_variable = tv_wonder_priority_declined }} }}")
    lines.append(f"{T}{T}every_owned_location = {{")
    lines.append(f"{T}{T}{T}limit = {{ NOT = {{ prev = {{ has_variable = tv_wonder_priority_found }} }} }}")
    lines.append(f"{T}{T}{T}save_scope_as = tv_wonder_priority_site")
    for wonder in wonders:
        helper = f"tv_wonder_{wonder['key']}"
        module_names = [f"tv_wonder_{wonder['key']}_{part['key']}" for part in parts]
        final_names = list(wonder["final_buildings"].values())
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}{T}NOT = {{ prev = {{ has_variable = tv_wonder_priority_found }} }}")
        lines.append(f"{T}{T}{T}{T}{T}NOT = {{ tv_wonder_location_has_any_wonder_final_building_trigger = yes }}")
        lines.append(f"{T}{T}{T}{T}{T}OR = {{")
        for module in module_names:
            lines.append(f"{T}{T}{T}{T}{T}{T}has_building = building_type:{module}")
        lines.append(f"{T}{T}{T}{T}{T}{T}has_building = building_type:{helper}")
        lines.append(f"{T}{T}{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}{T}}}")
        lines.extend(proposal_setter(wonder, 1, 4))
        lines.append(f"{T}{T}{T}}}")
        lines.append(f"{T}{T}{T}if = {{")
        lines.append(f"{T}{T}{T}{T}limit = {{")
        lines.append(f"{T}{T}{T}{T}{T}NOT = {{ prev = {{ has_variable = tv_wonder_priority_found }} }}")
        lines.extend(final_building_below_cap_conditions(wonder, 5))
        lines.append(f"{T}{T}{T}{T}}}")
        lines.extend(proposal_setter(wonder, 2, 4))
        lines.append(f"{T}{T}{T}}}")
    lines.append(f"{T}{T}}}")
    lines.append(f"{T}}}")
    lines.append("}")
    lines.append("")

    OUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
