"""
Generate src/in_game/common/scripted_effects/tv_trade_league_effects.txt.

The monthly monopoly update repeats the same production, trade, and monopoly
calculation for every tracked good, so the effect is generated from data.
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "trade_league_goods.yaml"
OUT_FILE = (
    REPO_ROOT
    / "src"
    / "in_game"
    / "common"
    / "scripted_effects"
    / "tv_trade_league_effects.txt"
)

HEADER = """\
# @Generated by scripts/in_game/common/scripted_effects/gen_tv_trade_league_effects.py
#   Data:    data/trade_league_goods.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/scripted_effects/gen_tv_trade_league_effects.py
# Do not edit directly - modify the data file and re-run the generator.

"""

CREATE_EFFECT = """\
tv_trade_league_create_effect = {
\tsave_scope_as = tv_trade_league_founder
\tif = {
\t\tlimit = {
\t\t\tcustom_tooltip = {
\t\t\t\ttext = TV_HAS_VARIABLE_NOT_SET_TT
\t\t\t\tNOT = { has_variable = tv_trade_league_member }
\t\t\t}
\t\t}
\t\tset_variable = { name = tv_trade_league_member value = 1 }
\t}
\tif = {
\t\tlimit = {
\t\t\tNOT = {
\t\t\t\tany_international_organizations_member_of = {
\t\t\t\t\tinternational_organization_type = international_organization_type:tv_trade_league
\t\t\t\t\tleader_country ?= scope:tv_trade_league_founder
\t\t\t\t}
\t\t\t}
\t\t}
\t\tcreate_international_organization = {
\t\t\ttype = international_organization_type:tv_trade_league
\t\t\tadd_country_to_international_organization = prev
\t\t\tset_leader_country = prev
\t\t}
\t}
}

"""

UPDATE_PREFIX = """\
tv_trade_league_update_monopolies_effect = {
"""

UPDATE_SUFFIX = """\
}
"""


def good_update_block(good: str) -> str:
    return f"""\
\t# {good}
\tset_local_variable = {{ name = tv_trade_global_total value = 0 }}
\tevery_country = {{
\t\tchange_local_variable = {{ name = tv_trade_global_total add = "total_effective_goods_production_buildings(goods:{good})" }}
\t}}
\tset_variable = {{ name = tv_trade_global_{good} value = local_var:tv_trade_global_total }}
\tset_global_variable = {{ name = tv_trade_global_{good} value = local_var:tv_trade_global_total }}

\tset_local_variable = {{ name = tv_trade_io_total value = 0 }}
\tevery_international_organization_member = {{
\t\tevery_market_present_in_country = {{
\t\t\tchange_local_variable = {{ name = tv_trade_io_total add = traded_in_market:{good} }}
\t\t}}
\t}}
\tset_variable = {{ name = tv_trade_io_{good} value = local_var:tv_trade_io_total }}

\tset_variable = {{ name = tv_trade_monopoly_{good} value = 0 }}
\tset_variable = {{ name = tv_trade_monopoly_level_{good} value = 0 }}
\tif = {{
\t\tlimit = {{ var:tv_trade_global_{good} > 0 }}
\t\tset_variable = {{ name = tv_trade_monopoly_level_{good} value = var:tv_trade_io_{good} }}
\t\tchange_variable = {{ name = tv_trade_monopoly_level_{good} divide = var:tv_trade_global_{good} }}
\t\tif = {{
\t\t\tlimit = {{ var:tv_trade_monopoly_level_{good} >= 0.5 }}
\t\t\tset_variable = {{ name = tv_trade_monopoly_{good} value = 1 }}
\t\t\tchange_variable = {{ name = tv_trade_monopoly_level_{good} add = 0.1 }}
\t\t}}
\t}}
"""


def generate(data: dict) -> str:
    goods = data["goods"]
    updates = "\n".join(good_update_block(good) for good in goods)
    return HEADER + CREATE_EFFECT + UPDATE_PREFIX + updates + UPDATE_SUFFIX


def main() -> None:
    with DATA_FILE.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)
    OUT_FILE.write_text(generate(data), encoding="utf-8-sig")
    print(f"Written: {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
