l_french:
 cmf_settings_title: "Framework de Modding Communautaire"
 cmf_settings_page_action_bar: "Barre d'action"
 cmf_settings_action_bar_group_layout: "Disposition"
 cmf_settings_action_bar_position_activate: "Activer cette position"
 cmf_settings_action_bar_position: "Position de la barre d'action"
 cmf_settings_action_bar_position_top: "Haut"
 cmf_settings_action_bar_position_bottom_left: "En bas à gauche"
 cmf_settings_action_bar_position_bottom_right: "En bas à droite"
 cmf_settings_action_bar_group_active_buttons: "Boutons actifs"
 cmf_settings_action_bar_group_active_button_activate: "Bouton d'activation"
 cmf_settings_action_bar_group_active_button_deactivate: "Bouton de désactivation"
