l_simp_chinese:
 ACE_SETTINGS_HEADER: "自动教育"
 ACE_SKIP_HEIRS: "继承人"
 ACE_SKIP_HEIRS_TT: "跳过继承人，允许玩家手动管理"
 ACE_SKIP_CROWN: "王室领地"
 ACE_SKIP_CROWN_TT: "跳过直属领地子嗣"
 ACE_SKIP_PRODIGY: "奇才/天赋异禀"
 ACE_SKIP_PRODIGY_TT: "跳过奇才和天赋异禀，因为其属性上限都已固定。"
 ACE_EXCLUDE: "排除："
 ACE_RUN_NOW: "立即运行"
 ACE_RUN_NOW_TT: "立即处理所有符合条件的子女。请在控制台查看结果。"
 ACE_RUN_NOW_HINT: "（请查看控制台以获取结果）"