l_german:
 cmf_settings_title: "Community Mod Framework"
 cmf_settings_page_action_bar: "Aktionsleiste"
 cmf_settings_action_bar_group_layout: "Layout"
 cmf_settings_action_bar_position_activate: "Diese Position aktivieren"
 cmf_settings_action_bar_position: "Aktionsleistenposition"
 cmf_settings_action_bar_position_top: "Oben"
 cmf_settings_action_bar_position_bottom_left: "Unten links"
 cmf_settings_action_bar_position_bottom_right: "Unten rechts"
 cmf_settings_action_bar_group_active_buttons: "Aktive Schaltflächen"
 cmf_settings_action_bar_group_active_button_activate: "Schaltfläche aktivieren"
 cmf_settings_action_bar_group_active_button_deactivate: "Deaktivieren-Schaltfläche"
