"""Generate dedicated source for the fully-implemented Unique Wonder Rituals:
Pharos Lighthouse and Hagia Sophia.

Alhambra, Dome of the Rock, Bank of Saint George, and St. Peter's Basilica were
previously implemented through this same pipeline but had their bespoke rituals
removed and reverted to the generic immediate-mode ritual in
data/unique_wonders.yaml; only Pharos and Hagia remain here.

Content for each wonder lives in scripts/unique_wonder_ritual_content/<key>.py.
Pharos and Hagia carry full per-entity fidelity in their existing hand-written
mechanics.

GUI cards remain merged into the single shared
src/in_game/gui/panels/organization/tv_engineering_department.gui panel via the
existing scripts/in_game/gui/panels/organization/gen_tv_engineering_department_wonder_mechanics_gui.py
+ merge_tv_engineering_department_wonder_mechanics_gui.py mechanism (one organization
panel, not a per-wonder file) — this script does not touch GUI.

Pharos and Hagia's localization text lives in its existing,
already-correct home (data/wonder_localization.yaml ->
src/main_menu/localization/*/tv_engineering_department_wonder_mechanics_l_*.yml);
neither wonder needs a dedicated per-wonder localization file.

Usage:
    C:\\Users\\Hades\\anaconda3\\envs\\eu5\\python.exe scripts\\gen_unique_wonder_rituals.py          # dry-run
    C:\\Users\\Hades\\anaconda3\\envs\\eu5\\python.exe scripts\\gen_unique_wonder_rituals.py --write  # writes files
"""
import argparse
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from unique_wonder_ritual_content import RITUAL_MODULES  # noqa: E402

SCRIPT_REL = "scripts/gen_unique_wonder_rituals.py"
T = "\t"


def header_lines(data_rel: str, target: str) -> list[str]:
    return [
        f"# @Generated by {SCRIPT_REL}",
        f"#   Data:    {data_rel}",
        f"#   Regen:   conda run --no-capture-output -n eu5 python {SCRIPT_REL}",
        "# Do not edit directly - modify the data file and re-run the generator.",
        f"# Target: {target}",
        "",
    ]


def build_events_file(module) -> str:
    target = f"src/in_game/events/tv_wonder_unique_{module.NAME_SLUG}_ritual_events.txt"
    lines = header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target)
    lines.append("namespace = tv_engineering_department")
    lines.append("")
    lines.extend(module.build_events_body())
    return "\n".join(lines).rstrip() + "\n"


def build_effects_file(module) -> str:
    target = f"src/in_game/common/scripted_effects/tv_wonder_unique_{module.NAME_SLUG}_ritual_effects.txt"
    lines = header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target)
    module.append_effects(lines)
    return "\n".join(lines).rstrip() + "\n"


def build_triggers_file(module) -> str:
    target = f"src/in_game/common/scripted_triggers/tv_wonder_unique_{module.NAME_SLUG}_ritual_triggers.txt"
    lines = header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target)
    module.append_triggers(lines)
    return "\n".join(lines).rstrip() + "\n"


def build_modifiers_file() -> str:
    target = "src/main_menu/common/static_modifiers/towards_victory_unique_wonder_ritual_modifiers.txt"
    lines = header_lines("scripts/unique_wonder_ritual_content/*.py (WONDER['modifier_bundles'])", target)
    for module in RITUAL_MODULES:
        wonder = getattr(module, "WONDER", None)
        if not wonder or "modifier_bundles" not in wonder:
            continue
        for modifier_name, effects in wonder["modifier_bundles"].items():
            lines.append(f"{modifier_name} = {{")
            for key, value in effects.items():
                lines.append(f"{T}{key} = {value}")
            lines.append("}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_on_action_file(module) -> str:
    target = f"src/in_game/common/on_action/tv_wonder_unique_{module.NAME_SLUG}_ritual_on_actions.txt"
    lines = header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target)
    lines.extend(module.build_on_action_body())
    return "\n".join(lines).rstrip() + "\n"


def output_paths(module) -> dict[str, Path]:
    paths = {
        "events": REPO_ROOT / "src" / "in_game" / "events" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_events.txt",
        "effects": REPO_ROOT / "src" / "in_game" / "common" / "scripted_effects" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_effects.txt",
        "triggers": REPO_ROOT / "src" / "in_game" / "common" / "scripted_triggers" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_triggers.txt",
    }
    if hasattr(module, "build_on_action_body"):
        paths["on_action"] = REPO_ROOT / "src" / "in_game" / "common" / "on_action" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_on_actions.txt"
    return paths


def build_all(module) -> dict[str, str]:
    outputs = {
        "events": build_events_file(module),
        "effects": build_effects_file(module),
        "triggers": build_triggers_file(module),
    }
    if hasattr(module, "build_on_action_body"):
        outputs["on_action"] = build_on_action_file(module)
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write the generated files (default: dry-run preview).")
    args = parser.parse_args()

    total_files = 0

    modifiers_path = REPO_ROOT / "src" / "main_menu" / "common" / "static_modifiers" / "towards_victory_unique_wonder_ritual_modifiers.txt"
    modifiers_content = build_modifiers_file()
    total_files += 1
    if args.write:
        modifiers_path.parent.mkdir(parents=True, exist_ok=True)
        modifiers_path.write_text(modifiers_content, encoding="utf-8-sig")
        print(f"Wrote {modifiers_path.relative_to(REPO_ROOT)}")
    else:
        print(f"Dry-run: would write {modifiers_path.relative_to(REPO_ROOT)} ({len(modifiers_content.splitlines())} lines)")

    for module in RITUAL_MODULES:
        outputs = build_all(module)
        paths = output_paths(module)
        print(f"{module.WONDER_KEY} (wonder_id={module.WONDER_ID}): {len(outputs)} files")
        for key, path in paths.items():
            content = outputs[key]
            total_files += 1
            if args.write:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8-sig")
                print(f"  Wrote {path.relative_to(REPO_ROOT)}")
            else:
                print(f"  Dry-run: would write {path.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")

    mode = "Wrote" if args.write else "Dry-run"
    print(f"{mode}: {len(RITUAL_MODULES)} wonders, {total_files} files.")


if __name__ == "__main__":
    main()
