#!/usr/bin/env python3
r"""
Generate docs/knowledge/BRIEF.md from docs/knowledge/*.yaml, risk cards,
and PROJECT_OVERVIEW.md. Run after editing AI knowledge files.

Usage:
  C:\Users\Hades\anaconda3\envs\eu5\python.exe scripts\gen_brief.py
"""

from datetime import date
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

try:
    import yaml
except ImportError:
    print("[ERROR] PyYAML not installed. Run: pip install pyyaml")
    raise SystemExit(1)

REPO_ROOT = Path(__file__).parent.parent
KNOWLEDGE_DIR = REPO_ROOT / "docs" / "knowledge"
OUTPUT = KNOWLEDGE_DIR / "BRIEF.md"
OVERVIEW = KNOWLEDGE_DIR / "PROJECT_OVERVIEW.md"
INDEX_DIR = REPO_ROOT / "data" / "index"
RISK_CARDS_DIR = KNOWLEDGE_DIR / "risk_cards"
MANAGED_SANDBOX_PYTHON = r"C:\Users\Hades\anaconda3\envs\eu5\python.exe"

CODEGEN_SCRIPTS = [
    ("gen_brief.py",   "anti_patterns.yaml + valid_enums.yaml + PROJECT_OVERVIEW.md + risk_cards/", "docs/knowledge/BRIEF.md",    "After editing any AI knowledge file"),
    ("gen_index.py",   "reference_game_files + src/",                                  "data/index/*.txt symbol indexes",           "Run by gen_brief.py automatically"),
    ("gen_scaffold.py","--type argument",                                               "Scaffold .txt/.yml file in dir",            "When creating a new EU5 file"),
    ("ai_context.py",  "--changed / --files",                                           "Compact AI task context + risk cards",      "At AI session start or before editing a task domain"),
    ("test_lint_rules.py", "anti_patterns.yaml + tests/fixtures/anti_patterns/",        "Fixture test report for lint regexes",      "After adding/changing detectability: lint rules"),
    ("gen_victory.py", "data/victory_paths.yaml",                                      "13 victory-path game files (see below)",    "After editing data/victory_paths.yaml"),
    ("in_game/common/customizable_localization/gen_character_title.py", "data/io_leaders.yaml", "both mod roots' full-copy character_title.txt", "After editing IO leader title data"),
    ("gen_messagetypes.py", "vanilla messagetypes + generic actions and action data", "both mod roots' full-copy messagetypes.txt", "After adding or moving a generic action"),
    ("validate.py",    "src/ mod files + knowledge YAML",                              "Console report (exit 0/1)",                 "Before launching game; --changed for quick check"),
]

AUTOGENERATED_FILES = [
    ("docs/knowledge/BRIEF.md",                                                        "gen_brief.py"),
    ("data/index/icons.txt",                                                            "gen_index.py"),
    ("data/index/scripted_triggers.txt",                                                "gen_index.py"),
    ("data/index/scripted_effects.txt",                                                 "gen_index.py"),
    ("data/index/static_modifiers.txt",                                                 "gen_index.py"),
    ("data/index/loc_keys_en.txt",                                                      "gen_index.py"),
    ("src/in_game/common/scripted_triggers/towards_victory_triggers.txt",               "gen_victory.py"),
    ("src/in_game/common/scripted_effects/towards_victory_effects.txt",                 "gen_victory.py"),
    ("src/in_game/common/static_modifiers/towards_victory_modifiers.txt",               "gen_victory.py"),
    ("src/in_game/common/situations/towards_victory_situations.txt",                    "gen_victory.py"),
    ("src/in_game/common/on_action/towards_victory_yearly.txt",                         "gen_victory.py"),
    ("src/in_game/events/towards_victory_conquest_events.txt",                          "gen_victory.py"),
    ("src/in_game/events/towards_victory_prosperity_events.txt",                        "gen_victory.py"),
    ("src/in_game/events/towards_victory_trade_events.txt",                             "gen_victory.py"),
    ("src/in_game/events/towards_victory_diplomatic_events.txt",                        "gen_victory.py"),
    ("src/in_game/events/towards_victory_cultural_events.txt",                          "gen_victory.py"),
    ("src/in_game/events/towards_victory_science_events.txt",                           "gen_victory.py"),
    ("src/main_menu/localization/english/towards_victory_l_english.yml",                "gen_victory.py"),
    ("src/main_menu/localization/simp_chinese/towards_victory_l_simp_chinese.yml",      "gen_victory.py"),
    ("src/in_game/common/customizable_localization/character_title.txt",                 "in_game/common/customizable_localization/gen_character_title.py"),
    ("src_engineering_department/in_game/common/customizable_localization/character_title.txt", "in_game/common/customizable_localization/gen_character_title.py"),
    ("src/main_menu/gui/messagetypes.txt",                                               "gen_messagetypes.py"),
    ("src_engineering_department/main_menu/gui/messagetypes.txt",                        "gen_messagetypes.py"),
]


def load(filename: str):
    path = KNOWLEDGE_DIR / filename
    if not path.exists():
        return None
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def md_row(*cols: str) -> str:
    return "| " + " | ".join(str(c) for c in cols) + " |"


def _run_gen_index() -> None:
    """Run gen_index.py as a subprocess so indexes are fresh before reading counts."""
    import subprocess
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "gen_index.py")],
        capture_output=True,
        encoding="utf-8",
        errors="ignore",
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        print(f"[WARN] gen_index.py failed: {stderr}")
    elif (result.stdout or "").strip():
        print(result.stdout.strip())


def main():
    _run_gen_index()
    anti_patterns = load("anti_patterns.yaml") or []
    enums = load("valid_enums.yaml") or {}

    lines: list[str] = []
    lines.append("# EU5 Knowledge Brief")
    lines.append("")
    lines.append(
        "> **Auto-generated** — do not edit this file directly.  "
    )
    lines.append(
        "> Edit `docs/knowledge/anti_patterns.yaml`, `valid_enums.yaml`, or `PROJECT_OVERVIEW.md`, "
        f"then run `{MANAGED_SANDBOX_PYTHON} scripts\\gen_brief.py` in managed sandboxes.  "
    )
    lines.append(f"> Last updated: {date.today()}")
    lines.append("")

    # ── Project overview ──────────────────────────────────────────────────────
    if OVERVIEW.exists():
        overview_text = OVERVIEW.read_text(encoding="utf-8")
        body_lines = overview_text.splitlines()
        start = next((i for i, ln in enumerate(body_lines) if ln.startswith("## ")), 0)
        lines.append("\n".join(body_lines[start:]).strip())
        lines.append("")

    # ── Risk cards ───────────────────────────────────────────────────────────
    risk_cards = sorted(RISK_CARDS_DIR.glob("*.md")) if RISK_CARDS_DIR.exists() else []
    if risk_cards:
        lines.append("## AI Risk Cards")
        lines.append("")
        lines.append("> Load the relevant card before editing files in that task domain.")
        lines.append("")
        lines.append(md_row("Domain", "Card"))
        lines.append(md_row("---", "---"))
        for card in risk_cards:
            lines.append(md_row(card.stem, f"`docs/knowledge/risk_cards/{card.name}`"))
        lines.append("")

    # ── Anti-patterns ────────────────────────────────────────────────────────
    lines.append("## Known Anti-Patterns")
    lines.append("")
    lines.append(md_row("Detectability", "Category", "Scope", "Bad Form", "Correct Form", "Notes"))
    lines.append(md_row("---", "---", "---", "---", "---", "---"))
    for p in anti_patterns:
        detectability = p.get("detectability") or ("lint" if p.get("pattern") else "advisory")
        lines.append(
            md_row(
                detectability,
                p.get("category", ""),
                p.get("scope", ""),
                p.get("bad", ""),
                p.get("correction", ""),
                p.get("notes", ""),
            )
        )
    lines.append("")

    # ── Valid enums ───────────────────────────────────────────────────────────
    lines.append("## Valid Enum Values")
    lines.append("")
    lines.append(md_row("Enum", "Valid Values", "Notes"))
    lines.append(md_row("---", "---", "---"))
    for enum_name, enum_data in enums.items():
        values = ", ".join(enum_data.get("values", []))
        notes = enum_data.get("notes", "")
        lines.append(md_row(enum_name, values, notes))
    lines.append("")

    # ── Quick-ref rules ───────────────────────────────────────────────────────
    lines.append("## Quick Reference Rules")
    lines.append("")
    lines.append("- **3-Step Rule**: Direct edit only if 100% certain → `reference_official_defines/` → `reference_game_files/` + `reference_mods/`")
    lines.append("- **Mandatory Step 2/3** for: `blockoverride` names, `custom_tooltip` keys, `situation_card_common` structure, `location_rank:*`, modifier names, scripted triggers/effects, localization YAML encoding, GUI expressions")
    lines.append("- **Verification format**: output `**Verification** — Step [2/3], Reference: file:line, Quote: \"exact text\"` before any code")
    lines.append("- **Bug fix rule**: Replace syntax with verified form; do NOT remove the feature")
    lines.append(f"- **Python runner**: In Codex, Claude subagents, or managed sandboxes, run scripts with `{MANAGED_SANDBOX_PYTHON}`; do not run `conda run -n eu5` there")
    lines.append(f"- **Pre-test**: Run `{MANAGED_SANDBOX_PYTHON} scripts\\validate.py --changed` before launching game in managed sandboxes")
    lines.append("- **Float precision**: EU5 truncates all floats at 5 decimal places; never emit 6+ dp in mod files")
    lines.append("")

    # ── Symbol quick-reference ─────────────────────────────────────────────
    lines.append("## Symbol Quick-Reference")
    lines.append("")
    lines.append("> Read `data/index/<name>.txt` for the full list (one entry per line).  ")
    lines.append("> For icon availability, check `data/index/icons.txt` before using `@icon_name!` inline syntax.")
    lines.append("")
    lines.append(md_row("Category", "Count", "Index file", "Notes"))
    lines.append(md_row("---", "---", "---", "---"))
    index_meta = [
        ("GUI Icons (`@xxx!`)", "icons.txt",            "Use `@name!` in raw_text/text fields and YAML values"),
        ("Scripted Triggers",   "scripted_triggers.txt", "Verify name before using in `trigger = { ... }`"),
        ("Scripted Effects",    "scripted_effects.txt",  "Verify name before using in `effect = { ... }`"),
        ("Static Modifiers",    "static_modifiers.txt",  "Modifier name whitelist; validate.py checks these"),
        ("English Loc Keys",    "loc_keys_en.txt",       "All defined EN keys; cross-check before adding duplicates"),
    ]
    for label, fname, notes in index_meta:
        index_path = INDEX_DIR / fname
        count = "—"
        if index_path.exists():
            count = str(sum(1 for ln in index_path.read_text(encoding="utf-8").splitlines() if ln.strip()))
        lines.append(md_row(label, count, f"`data/index/{fname}`", notes))
    lines.append("")

    # ── Codegen script map ─────────────────────────────────────────────────
    lines.append("## Codegen Script Map")
    lines.append("")
    lines.append(md_row("Script", "Input(s)", "Output(s)", "When to run"))
    lines.append(md_row("---", "---", "---", "---"))
    for script, inputs, outputs, when in CODEGEN_SCRIPTS:
        lines.append(md_row(f"`scripts/{script}`", inputs, outputs, when))
    lines.append("")

    # ── Auto-generated files ───────────────────────────────────────────────
    lines.append("## Auto-Generated Files (do not edit directly)")
    lines.append("")
    lines.append("> These files have `# @AUTOGENERATED` on line 1.  ")
    lines.append("> `validate.py` warns if any of them appear in `git diff --cached`.")
    lines.append("")
    lines.append(md_row("File", "Generator"))
    lines.append(md_row("---", "---"))
    for rel_path, generator in AUTOGENERATED_FILES:
        lines.append(md_row(f"`{rel_path}`", f"`scripts/{generator}`"))
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    overview_status = "with overview" if OVERVIEW.exists() else "no overview"
    index_counts = {fname: (INDEX_DIR / fname).exists() for _, fname, _ in index_meta}
    index_status = f", index {'ready' if all(index_counts.values()) else 'missing (run gen_index.py)'}"
    print(f"[OK] Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(anti_patterns)} patterns, {len(enums)} enums, {overview_status}{index_status})")


if __name__ == "__main__":
    main()
