#!/usr/bin/env python3
"""Generate the Research Mechanism unlock-effects file from data/locked_advances.yaml.

As of v0.1.x: frontier advances are NOT locked at game start. This script only emits
the unlock-effect file, which is invoked by `tv_research_concentrated_complete_effect`
as a shortcut to immediately grant a target advance upon cycle completion.

Usage:
    conda run --no-capture-output -n eu5 python scripts/gen_locked_advances.py        # write files
    conda run --no-capture-output -n eu5 python scripts/gen_locked_advances.py --dry  # preview only

1对1原则: Each YAML field maps to one piece of output. This generator is a template
filler, not a code reasoner.

Generated file (DO NOT HAND-EDIT):
  src/in_game/common/scripted_effects/tv_advance_unlock_effects.txt
"""
import sys
import argparse
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: conda install -n eu5 pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).parent.parent
SRC = ROOT / "src"
DATA_YAML = ROOT / "data" / "locked_advances.yaml"

HEADER = "# AUTO-GENERATED by gen_locked_advances.py — DO NOT HAND-EDIT\n"

REQUIRED_FIELDS = ["id", "vanilla_advance_id", "age", "research_unlock_var"]


def write_file(path: Path, content: str, dry: bool) -> None:
    """Write UTF-8 BOM file, or print to stdout in dry mode."""
    if dry:
        print(f"\n{'='*72}")
        print(f"=== {path.relative_to(ROOT)}")
        print(f"{'='*72}")
        print(content[:2000])
        if len(content) > 2000:
            print(f"... [{len(content)-2000} more chars]")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8-sig")
        print(f"  wrote {path.relative_to(ROOT)}")


def validate_yaml(entries: list) -> None:
    """Validate all required fields are present. Exits with error on failure."""
    errors = []
    for i, entry in enumerate(entries):
        entry_id = entry.get("id", f"<entry #{i}>")
        for field in REQUIRED_FIELDS:
            if field not in entry or entry[field] is None:
                errors.append(f"  Entry '{entry_id}': missing required field '{field}'")
    if errors:
        print("ERROR: locked_advances.yaml validation failed:", file=sys.stderr)
        for e in errors:
            print(e, file=sys.stderr)
        sys.exit(1)


def gen_effects(entries: list) -> str:
    lines = [HEADER, ""]
    lines.append(f"# {'─'*70}")
    lines.append("# ADVANCE UNLOCK EFFECTS — Research Mechanism shortcut")
    lines.append("# Called from tv_research_concentrated_complete_effect on cycle D completion.")
    lines.append(f"# {'─'*70}")
    lines.append("")
    for e in entries:
        aid = e["id"]
        var = e["research_unlock_var"]
        vanilla_id = e["vanilla_advance_id"]
        lines.append(f"tv_unlock_advance_{aid}_effect = {{")
        lines.append(f"\tset_variable = {{ name = {var} value = 1 }}")
        lines.append(f"\tresearch_advance = advance_type:{vanilla_id}")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Research Mechanism unlock-effect file.")
    parser.add_argument("--dry", action="store_true", help="Print output to stdout; do not write files.")
    args = parser.parse_args()

    if not DATA_YAML.exists():
        print(f"ERROR: {DATA_YAML} not found", file=sys.stderr)
        sys.exit(1)

    with DATA_YAML.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    entries = data.get("locked_advances", [])
    if not entries:
        print("ERROR: locked_advances list is empty", file=sys.stderr)
        sys.exit(1)

    validate_yaml(entries)

    effects_content = gen_effects(entries)

    write_file(
        SRC / "in_game/common/scripted_effects/tv_advance_unlock_effects.txt",
        effects_content,
        args.dry,
    )

    if not args.dry:
        print("Done.")


if __name__ == "__main__":
    main()
