#!/usr/bin/env python3
r"""
Generate a compact docs/knowledge/BRIEF.md.

The brief is the mandatory broad read, so it must stay short. Domain details
belong in routed risk cards and are surfaced by scripts/ai_context.py.

Usage:
  C:\Users\Hades\anaconda3\envs\eu5\python.exe scripts\gen_brief.py
"""

from __future__ import annotations

from datetime import date
import subprocess
import sys
from pathlib import Path
from typing import Any

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

try:
    import yaml
except ImportError:
    print("[ERROR] PyYAML not installed. Run: pip install pyyaml")
    raise SystemExit(1)

REPO_ROOT = Path(__file__).parent.parent
KNOWLEDGE_DIR = REPO_ROOT / "docs" / "knowledge"
OUTPUT = KNOWLEDGE_DIR / "BRIEF.md"
OVERVIEW = KNOWLEDGE_DIR / "PROJECT_OVERVIEW.md"
ROUTES_FILE = KNOWLEDGE_DIR / "context_routes.yaml"
RISK_CARDS_DIR = KNOWLEDGE_DIR / "risk_cards"
INDEX_DIR = REPO_ROOT / "data" / "index"
MANAGED_SANDBOX_PYTHON = r"C:\Users\Hades\anaconda3\envs\eu5\python.exe"

CODEGEN_SCRIPTS = [
    ("ai_context.py", "--changed / --files [--full] [--json]", "task-scoped route summary + optional full card text", "Before non-trivial edits"),
    ("gen_brief.py", "anti_patterns.yaml + valid_enums.yaml + PROJECT_OVERVIEW.md + context_routes.yaml", "docs/knowledge/BRIEF.md", "After editing AI knowledge files"),
    ("gen_index.py", "reference_game_files + deployable mod roots", "data/index/*.txt symbol indexes", "Run by gen_brief.py"),
    ("validate.py", "src/ roots + data + knowledge policy checks", "console or JSON validation report", "Before launching game"),
    ("test_lint_rules.py", "anti_patterns.yaml + fixtures", "fixture report for lint rules", "After adding/changing lint rules"),
    ("test_ai_context.py", "context_routes.yaml + sample files", "routing regression report", "After changing AI context routing"),
    ("gen_victory.py", "data/victory_paths.yaml", "victory-path source and localization outputs", "After editing victory path data"),
    ("gen_messagetypes.py", "vanilla messagetypes + generated action data", "root-specific full-copy messagetypes.txt", "After adding or moving actions"),
]

AUTOGENERATED_FILES = [
    ("docs/knowledge/BRIEF.md", "scripts/gen_brief.py"),
    ("data/index/icons.txt", "scripts/gen_index.py"),
    ("data/index/scripted_triggers.txt", "scripts/gen_index.py"),
    ("data/index/scripted_effects.txt", "scripts/gen_index.py"),
    ("data/index/static_modifiers.txt", "scripts/gen_index.py"),
    ("data/index/loc_keys_en.txt", "scripts/gen_index.py"),
]


def load_yaml(path: Path) -> Any:
    if not path.exists():
        return None
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def md_cell(value: Any, limit: int | None = None) -> str:
    text = " ".join(str(value or "").split())
    if limit and len(text) > limit:
        text = text[: limit - 3].rstrip() + "..."
    return text.replace("|", "\\|")


def md_row(*cols: Any) -> str:
    return "| " + " | ".join(md_cell(c) for c in cols) + " |"


def extract_overview_section(name: str) -> list[str]:
    if not OVERVIEW.exists():
        return []
    lines = OVERVIEW.read_text(encoding="utf-8").splitlines()
    start = next((idx for idx, line in enumerate(lines) if line == f"## {name}"), None)
    if start is None:
        return []
    end = next((idx for idx in range(start + 1, len(lines)) if lines[idx].startswith("## ")), len(lines))
    return lines[start:end]


def run_gen_index() -> None:
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "gen_index.py")],
        cwd=REPO_ROOT,
        capture_output=True,
        encoding="utf-8",
        errors="ignore",
    )
    if result.returncode != 0:
        print(f"[WARN] gen_index.py failed: {(result.stderr or '').strip()}")
    elif (result.stdout or "").strip():
        print(result.stdout.strip())


def append_route_table(lines: list[str], routes: dict[str, Any]) -> None:
    lines.append("## Context Routing")
    lines.append("")
    lines.append("Use `scripts/ai_context.py` for task-scoped details. Default output is concise; pass `--full` only when the full card text is needed.")
    lines.append("")
    lines.append(md_row("Route Type", "ID", "Card / Read", "Why It Routes"))
    lines.append(md_row("---", "---", "---", "---"))
    for route_type in ("domain_routes", "filename_routes"):
        for route in routes.get(route_type, []) or []:
            card = route.get("card") or ""
            target = f"`docs/knowledge/risk_cards/{card}`" if card else ""
            lines.append(md_row(route_type, route.get("id", ""), target, route.get("summary") or route.get("reason", ""),))
    for route in routes.get("content_routes", []) or []:
        reads = ", ".join(f"`{read.get('path')}`" for read in route.get("reads", []) or [])
        lines.append(md_row("content_routes", route.get("id", ""), reads, route.get("reason", "")))
    for route in routes.get("object_alerts", []) or []:
        card = route.get("card") or ""
        target = f"`docs/knowledge/risk_cards/{card}`" if card else ""
        lines.append(md_row("object_alerts", route.get("id", ""), target, route.get("message", ""),))
    lines.append("")


def main() -> None:
    run_gen_index()
    anti_patterns = load_yaml(KNOWLEDGE_DIR / "anti_patterns.yaml") or []
    enums = load_yaml(KNOWLEDGE_DIR / "valid_enums.yaml") or {}
    routes = load_yaml(ROUTES_FILE) or {}

    lines: list[str] = []
    lines.append("# EU5 Knowledge Brief")
    lines.append("")
    lines.append("> Auto-generated. Do not edit this file directly.")
    lines.append(f"> Edit knowledge sources, then run `{MANAGED_SANDBOX_PYTHON} scripts\\gen_brief.py`.")
    lines.append(f"> Last updated: {date.today()}")
    lines.append("")

    for section in ("Mod Identity", "Development Policy"):
        section_lines = extract_overview_section(section)
        if section_lines:
            lines.extend(section_lines)
            lines.append("")

    lines.append("## Quick Rules")
    lines.append("")
    lines.append("- Use `CLAUDE.md` as the single startup workflow entry.")
    lines.append("- Before non-trivial edits, run `scripts/ai_context.py --changed` or `--files <paths>` with the direct `eu5` interpreter in managed sandboxes.")
    lines.append("- Default `ai_context.py` output is concise; use `--full` only for full risk-card text.")
    lines.append("- This project is unreleased: do not add migrations, compatibility branches, old-state probes, or read-path repair fallbacks unless explicitly requested.")
    lines.append("- EU5 uses Jomini, not EU4 syntax. Mandatory-reference categories still require checking official defines or source examples before editing.")
    lines.append("- Check `data/generated_files.yaml` before editing generated outputs.")
    lines.append("")

    append_route_table(lines, routes)

    risk_cards = sorted(RISK_CARDS_DIR.glob("*.md")) if RISK_CARDS_DIR.exists() else []
    if risk_cards:
        lines.append("## Risk Card Index")
        lines.append("")
        lines.append(md_row("Card", "Purpose"))
        lines.append(md_row("---", "---"))
        for card in risk_cards:
            first_body = ""
            for line in card.read_text(encoding="utf-8").splitlines()[1:]:
                if line.strip() and not line.startswith("#"):
                    first_body = line.strip()
                    break
            lines.append(
                "| "
                + " | ".join(
                    [
                        md_cell(f"`docs/knowledge/risk_cards/{card.name}`"),
                        md_cell(first_body, 140),
                    ]
                )
                + " |"
            )
        lines.append("")

    lines.append("## Anti-Pattern Index")
    lines.append("")
    lines.append("This is an index only. Use `scripts/ai_context.py` for task-relevant summaries or read `docs/knowledge/anti_patterns.yaml` for full detail.")
    lines.append("")
    lines.append(md_row("ID", "Detectability", "Category", "Scope"))
    lines.append(md_row("---", "---", "---", "---"))
    for entry in anti_patterns:
        detectability = entry.get("detectability") or ("lint" if entry.get("pattern") else "advisory")
        lines.append(md_row(f"`{entry.get('id', '')}`", detectability, entry.get("category", ""), entry.get("scope", "")))
    lines.append("")

    lines.append("## Valid Enum Values")
    lines.append("")
    lines.append(md_row("Enum", "Valid Values", "Notes"))
    lines.append(md_row("---", "---", "---"))
    for enum_name, enum_data in enums.items():
        values = ", ".join(enum_data.get("values", []))
        notes = enum_data.get("notes", "")
        lines.append(md_row(enum_name, values, notes))
    lines.append("")

    lines.append("## Symbol Quick Reference")
    lines.append("")
    lines.append(md_row("Category", "Count", "Index File"))
    lines.append(md_row("---", "---", "---"))
    for label, fname in [
        ("GUI Icons", "icons.txt"),
        ("Scripted Triggers", "scripted_triggers.txt"),
        ("Scripted Effects", "scripted_effects.txt"),
        ("Static Modifiers", "static_modifiers.txt"),
        ("English Loc Keys", "loc_keys_en.txt"),
    ]:
        index_path = INDEX_DIR / fname
        count = "missing"
        if index_path.exists():
            count = str(sum(1 for ln in index_path.read_text(encoding="utf-8").splitlines() if ln.strip()))
        lines.append(md_row(label, count, f"`data/index/{fname}`"))
    lines.append("")

    lines.append("## Codegen Script Map")
    lines.append("")
    lines.append(md_row("Script", "Input(s)", "Output(s)", "When To Run"))
    lines.append(md_row("---", "---", "---", "---"))
    for script, inputs, outputs, when in CODEGEN_SCRIPTS:
        lines.append(md_row(f"`scripts/{script}`", inputs, outputs, when))
    lines.append("")

    lines.append("## Auto-Generated Files")
    lines.append("")
    lines.append(md_row("File", "Generator"))
    lines.append(md_row("---", "---"))
    for rel_path, generator in AUTOGENERATED_FILES:
        lines.append(md_row(f"`{rel_path}`", f"`{generator}`"))
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"[OK] Generated {OUTPUT.relative_to(REPO_ROOT)} "
        f"({len(anti_patterns)} patterns, {len(enums)} enums, {len(risk_cards)} risk cards)"
    )


if __name__ == "__main__":
    main()
