"""Generate the 3 pilot "Unique Wonder Ritual" wonders using a repeated-row
event/effect/trigger pattern structurally identical to the Alhambra Harness
output (src/in_game/events/tv_wonder_unique_alhambra_ritual_events.txt and its
sibling effects/triggers/localization files), but produced by a small,
project-owned generator instead of the frozen Harness pipeline.

This is deliberately analogous to how Pharos has its own standalone generator
(scripts/in_game/events/gen_tv_wonder_unique_pharos_lighthouse_ritual_events.py)
rather than routing through scripts/gen_unique_wonder_ritual_code.py. It does
NOT read or write anything under the frozen Harness surface: it never touches
scripts/wonder_unique_ritual_harness.py, scripts/gen_unique_wonder_ritual_code.py,
or the identity.status / generation.status / may_write_src fields of
data/unique_wonder_ritual_specs.yaml.

Usage:
    C:\\Users\\Hades\\anaconda3\\envs\\eu5\\python.exe scripts\\gen_repeated_row_pilot_wonders.py          # dry-run, prints a summary
    C:\\Users\\Hades\\anaconda3\\envs\\eu5\\python.exe scripts\\gen_repeated_row_pilot_wonders.py --write  # writes all 15 files

1对1原则: data/repeated_row_pilot_wonders.yaml stores the wonder identity, the
per-row-set stage list, and each stage's fully authored EN/ZH title, desc, and
option text verbatim; this generator is a template filler that arranges that
data into the Alhambra-shaped event/effect/trigger/localization skeleton. It
does not invent or rewrite narrative text.

Generated files (do NOT hand-edit; edit data/repeated_row_pilot_wonders.yaml
and re-run this script instead):
  src/in_game/events/tv_wonder_unique_{name_slug}_ritual_events.txt (x3)
  src/in_game/common/scripted_effects/tv_wonder_unique_{name_slug}_ritual_effects.txt (x3)
  src/in_game/common/scripted_triggers/tv_wonder_unique_{name_slug}_ritual_triggers.txt (x3)
  src/main_menu/localization/english/tv_wonder_unique_{name_slug}_ritual_l_english.yml (x3)
  src/main_menu/localization/simp_chinese/tv_wonder_unique_{name_slug}_ritual_l_simp_chinese.yml (x3)
"""
import argparse
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "data" / "repeated_row_pilot_wonders.yaml"
SCRIPT_REL = "scripts/gen_repeated_row_pilot_wonders.py"
DATA_REL = "data/repeated_row_pilot_wonders.yaml"
NAMESPACE = "tv_engineering_department"
T = "\t"
DASH_RULE = "-" * 46

STAGE_ORDER = ("opening", "update", "retry", "resolve")
OPTION_LETTERS = "abcdefghijklmnopqrstuvwxyz"

# GUI status-card chrome (waiting/active/branch/complete/failed chips, current-stage
# label, row-set labels, reward-branch label). This is UI chrome text, not narrative
# ritual content, so unlike the row/stage data above it is authored here rather than
# sourced from data/repeated_row_pilot_wonders.yaml. Mirrors the per-wonder panel-status
# key set already established by TV_ENGINEERING_ALHAMBRA_STATUS_* etc.
PANEL_STATUS_WORDS = {
    "waiting": ("Waiting", "等待中"),
    "active": ("Active", "进行中"),
    "branch_recorded": ("Branch recorded", "分支已记录"),
    "complete": ("Complete", "已完成"),
    "failed": ("Failed", "失败"),
}
PANEL_ROW_SET_LABELS = {
    "unique_dome_of_the_rock": {
        "sanctuary_access_groups": ("Sanctuary access covenant", "圣所门禁盟约"),
        "custody_duties": ("Custody duties", "职守托付"),
    },
    "unique_bank_of_saint_george": {
        "charter_options": ("Founding charter", "创立宪章"),
        "public_credit_pledges": ("Public credit pledges", "公共信用抵押"),
    },
    "unique_st_peters_basilica": {
        "sacred_official_candidates": ("Sacred official", "神圣官员"),
        "apostolic_service_duties": ("Apostolic duties", "使徒职责"),
    },
}
PANEL_REWARD_BRANCH_LABEL = ("Reward branch", "奖励分支")
PANEL_STAGE_REWARD_LABEL = ("Reward ready", "奖励就绪")
PANEL_CURRENT_STAGE_LABEL = ("Current stage", "当前阶段")


def header_lines(target: str) -> list[str]:
    return [
        f"# @Generated by {SCRIPT_REL}",
        f"#   Data:    {DATA_REL}",
        f"#   Regen:   conda run --no-capture-output -n eu5 python {SCRIPT_REL}",
        "# Do not edit directly — modify the data file and re-run the generator.",
        f"# Target: {target}",
    ]


def load_data() -> dict:
    with DATA_FILE.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def row_prefix(name_slug: str, row_set_key: str) -> str:
    return f"tv_wonder_unique_{name_slug}_ritual_{row_set_key}"


def loc_key(event_id: int, suffix: str) -> str:
    return f"{NAMESPACE}.{event_id}.{suffix}"


# ---------------------------------------------------------------------------
# events file
# ---------------------------------------------------------------------------

def build_events(wonder: dict) -> str:
    name_slug = wonder["name_slug"]
    lines = header_lines(f"src/in_game/events/tv_wonder_unique_{name_slug}_ritual_events.txt")
    lines.append(f"namespace = {NAMESPACE}")
    lines.append("")

    all_stages: list[tuple[str, dict]] = []
    for row_set in wonder["row_sets"]:
        for stage in row_set["stages"]:
            all_stages.append((row_set["row_set_key"], stage))
    all_stages.sort(key=lambda item: item[1]["event_id"])

    for row_set_key, stage in all_stages:
        prefix = row_prefix(name_slug, row_set_key)
        event_id = stage["event_id"]
        stage_name = stage["stage"]
        option_count = len(stage["en_options"])

        lines.append(f"# -- {NAMESPACE}.{event_id} {DASH_RULE}")
        lines.append(f"{NAMESPACE}.{event_id} = {{")
        lines.append(f"{T}type = country_event")
        lines.append(f"{T}title = {NAMESPACE}.{event_id}.t")
        lines.append(f"{T}desc = {NAMESPACE}.{event_id}.d")
        lines.append(f"{T}outcome = neutral")
        lines.append("")
        lines.append(f"{T}# row_set = {row_set_key}; stage = {stage_name}")
        lines.append("")

        for option_index in range(option_count):
            letter = OPTION_LETTERS[option_index]
            lines.append(f"{T}option = {{")
            lines.append(f"{T}{T}name = {NAMESPACE}.{event_id}.{letter}")
            lines.append(f"{T}{T}trigger = {{")
            lines.append(f"{T}{T}{T}{prefix}_scripted_trigger_eligibility_trigger = yes")
            lines.append(f"{T}{T}{T}{prefix}_scripted_trigger_tooltip_safe_condition_group_trigger = yes")
            lines.append(f"{T}{T}}}")
            if stage_name == "opening":
                lines.append(f"{T}{T}{prefix}_row_init_effect = yes")
                lines.append(f"{T}{T}{prefix}_aggregate_refresh_effect = yes")
            elif stage_name == "update":
                lines.append(f"{T}{T}{prefix}_row_state_write_effect = yes")
                lines.append(f"{T}{T}{prefix}_aggregate_refresh_effect = yes")
            elif stage_name == "retry":
                lines.append(f"{T}{T}{prefix}_branch_write_effect = yes")
                lines.append(f"{T}{T}{prefix}_aggregate_refresh_effect = yes")
            elif stage_name == "resolve":
                lines.append(f"{T}{T}{prefix}_completion_effect = yes")
                lines.append(f"{T}{T}{prefix}_cleanup_write_effect = yes")
            else:
                raise ValueError(f"Unknown stage {stage_name!r} for {name_slug}/{row_set_key}")
            lines.append(f"{T}}}")
            lines.append("")

        # drop the trailing blank line inserted after the last option, then close event
        if lines[-1] == "":
            lines.pop()
        lines.append("}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# effects file
# ---------------------------------------------------------------------------

def _row_init_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_row_init_effect {DASH_RULE}", f"{prefix}_row_init_effect = {{"]
    lines.append(f"{T}# family = effect; operation = row_init")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    for suffix, value in (
        ("started", 1),
        ("progress", 0),
        ("branch", 0),
        ("completed", 0),
        ("failed", 0),
        ("reset", 0),
        ("state", 0),
    ):
        lines.append(f"{T}set_variable = {{ name = {prefix}_{suffix} value = {value} }}")
    lines.append("}")
    return lines


def _row_state_write_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_row_state_write_effect {DASH_RULE}", f"{prefix}_row_state_write_effect = {{"]
    lines.append(f"{T}# family = effect; operation = row_state_write")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_started value = 1 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_progress value = 1 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_failed value = 0 }}")
    lines.append("}")
    return lines


def _aggregate_refresh_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_aggregate_refresh_effect {DASH_RULE}", f"{prefix}_aggregate_refresh_effect = {{"]
    lines.append(f"{T}# family = effect; operation = aggregate_refresh")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_state value = 1 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_progress value = 1 }}")
    lines.append("}")
    return lines


def _branch_write_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_branch_write_effect {DASH_RULE}", f"{prefix}_branch_write_effect = {{"]
    lines.append(f"{T}# family = effect; operation = branch_write")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_started value = 1 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_branch value = 1 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_failed value = 0 }}")
    lines.append("}")
    return lines


def _cleanup_write_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_cleanup_write_effect {DASH_RULE}", f"{prefix}_cleanup_write_effect = {{"]
    lines.append(f"{T}# family = effect; operation = cleanup_write")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    for suffix in ("started", "progress", "branch", "failed", "reset", "state"):
        lines.append(f"{T}remove_variable = {prefix}_{suffix}")
    lines.append("}")
    return lines


def _completion_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_completion_effect {DASH_RULE}", f"{prefix}_completion_effect = {{"]
    lines.append(f"{T}# family = cleanup; operation = completion")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_started value = 1 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_progress value = 2 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_completed value = 1 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_failed value = 0 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_state value = 2 }}")
    lines.append("}")
    return lines


def _failure_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_failure_effect {DASH_RULE}", f"{prefix}_failure_effect = {{"]
    lines.append(f"{T}# family = cleanup; operation = failure")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_failed value = 1 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_completed value = 0 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_progress value = 0 }}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_state value = 0 }}")
    lines.append("}")
    return lines


def _ownership_loss_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_ownership_loss_effect {DASH_RULE}", f"{prefix}_ownership_loss_effect = {{"]
    lines.append(f"{T}# family = cleanup; operation = ownership_loss")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    for suffix in ("started", "progress", "branch", "failed", "reset", "state", "completed"):
        lines.append(f"{T}remove_variable = {prefix}_{suffix}")
    lines.append("}")
    return lines


def _ritual_reset_block(prefix: str) -> list[str]:
    lines = [f"# -- {prefix}_ritual_reset_effect {DASH_RULE}", f"{prefix}_ritual_reset_effect = {{"]
    lines.append(f"{T}# family = cleanup; operation = reset")
    lines.append(f"{T}# row_set = {prefix.split('_ritual_', 1)[1]}")
    for suffix in ("started", "progress", "branch", "failed", "reset", "state", "completed"):
        lines.append(f"{T}remove_variable = {prefix}_{suffix}")
    lines.append(f"{T}set_variable = {{ name = {prefix}_reset value = 1 }}")
    lines.append("}")
    return lines


def build_effects(wonder: dict) -> str:
    name_slug = wonder["name_slug"]
    lines = header_lines(f"src/in_game/common/scripted_effects/tv_wonder_unique_{name_slug}_ritual_effects.txt")
    prefixes = [row_prefix(name_slug, rs["row_set_key"]) for rs in wonder["row_sets"]]

    for prefix in prefixes:
        lines.append("")
        lines.extend(_row_init_block(prefix))
        lines.append("")
        lines.extend(_row_state_write_block(prefix))
        lines.append("")
        lines.extend(_aggregate_refresh_block(prefix))
        lines.append("")
        lines.extend(_branch_write_block(prefix))
        lines.append("")
        lines.extend(_cleanup_write_block(prefix))

    for prefix in prefixes:
        lines.append("")
        lines.extend(_completion_block(prefix))
        lines.append("")
        lines.extend(_failure_block(prefix))
        lines.append("")
        lines.extend(_ownership_loss_block(prefix))
        lines.append("")
        lines.extend(_ritual_reset_block(prefix))

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# triggers file
# ---------------------------------------------------------------------------

def build_triggers(wonder: dict) -> str:
    name_slug = wonder["name_slug"]
    lines = header_lines(f"src/in_game/common/scripted_triggers/tv_wonder_unique_{name_slug}_ritual_triggers.txt")
    prefixes = [row_prefix(name_slug, rs["row_set_key"]) for rs in wonder["row_sets"]]

    for prefix in prefixes:
        row_set_key = prefix.split("_ritual_", 1)[1]

        lines.append("")
        lines.append(f"# -- {prefix}_scripted_trigger_row_completion_trigger {DASH_RULE}")
        lines.append(f"{prefix}_scripted_trigger_row_completion_trigger = {{")
        lines.append(f"{T}# row_set = {row_set_key}")
        lines.append(f"{T}# condition_group = row_completion")
        lines.append(f"{T}has_variable = {prefix}_completed")
        lines.append(f"{T}var:{prefix}_completed ?= 1")
        lines.append("}")

        lines.append("")
        lines.append(f"# -- {prefix}_scripted_trigger_eligibility_trigger {DASH_RULE}")
        lines.append(f"{prefix}_scripted_trigger_eligibility_trigger = {{")
        lines.append(f"{T}# row_set = {row_set_key}")
        lines.append(f"{T}# condition_group = eligibility")
        lines.append(f"{T}always = yes")
        lines.append("}")

        lines.append("")
        lines.append(f"# -- {prefix}_scripted_trigger_tooltip_safe_condition_group_trigger {DASH_RULE}")
        lines.append(f"{prefix}_scripted_trigger_tooltip_safe_condition_group_trigger = {{")
        lines.append(f"{T}# row_set = {row_set_key}")
        lines.append(f"{T}# condition_group = tooltip_safe_condition_group")
        lines.append(f"{T}always = yes")
        lines.append("}")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# localization files
# ---------------------------------------------------------------------------

def panel_status_key_prefix(name_slug: str) -> str:
    return f"TV_ENGINEERING_{name_slug.upper()}"


def opening_row_set(wonder: dict) -> dict:
    """The row set whose opening stage has the lowest event_id; used for the card title."""
    return min(wonder["row_sets"], key=lambda rs: min(st["event_id"] for st in rs["stages"]))


def build_panel_status_lines(wonder: dict, language: str) -> list[str]:
    name_slug = wonder["name_slug"]
    wonder_key = wonder["wonder_key"]
    key_prefix = panel_status_key_prefix(name_slug)
    lang_index = 0 if language == "english" else 1
    title_field = "en_title" if language == "english" else "zh_title"

    lines: list[str] = []

    opening_rs = opening_row_set(wonder)
    opening_stage = min(opening_rs["stages"], key=lambda st: st["event_id"])
    lines.append(f' {key_prefix}_OPENING_TITLE:0 "{opening_stage[title_field]}"')

    lines.append(f' {key_prefix}_CURRENT_STAGE:0 "{PANEL_CURRENT_STAGE_LABEL[lang_index]}"')
    for row_set in wonder["row_sets"]:
        row_set_key = row_set["row_set_key"]
        label = PANEL_ROW_SET_LABELS[wonder_key][row_set_key][lang_index]
        lines.append(f' {key_prefix}_STAGE_{row_set_key.upper()}:0 "{label}"')
    lines.append(f' {key_prefix}_STAGE_REWARD:0 "{PANEL_STAGE_REWARD_LABEL[lang_index]}"')

    for word_key, values in PANEL_STATUS_WORDS.items():
        lines.append(f' {key_prefix}_STATUS_{word_key.upper()}:0 "{values[lang_index]}"')

    for row_set in wonder["row_sets"]:
        row_set_key = row_set["row_set_key"]
        label = PANEL_ROW_SET_LABELS[wonder_key][row_set_key][lang_index]
        lines.append(f' {key_prefix}_{row_set_key.upper()}_STATUS:0 "{label}"')

    lines.append(f' {key_prefix}_REWARD_BRANCH_STATUS:0 "{PANEL_REWARD_BRANCH_LABEL[lang_index]}"')

    return lines


def build_localization(wonder: dict, language: str) -> str:
    name_slug = wonder["name_slug"]
    header_key = "l_english" if language == "english" else "l_simp_chinese"
    suffix = "l_english" if language == "english" else "l_simp_chinese"
    target = f"src/main_menu/localization/{language}/tv_wonder_unique_{name_slug}_ritual_{suffix}.yml"

    lines = [f"{header_key}:"]
    for hline in header_lines(target):
        lines.append(f" {hline}")
    lines.append(" ")

    all_stages: list[dict] = []
    for row_set in wonder["row_sets"]:
        for stage in row_set["stages"]:
            all_stages.append(stage)
    all_stages.sort(key=lambda st: st["event_id"])

    title_field = "en_title" if language == "english" else "zh_title"
    desc_field = "en_desc" if language == "english" else "zh_desc"
    options_field = "en_options" if language == "english" else "zh_options"

    for stage in all_stages:
        event_id = stage["event_id"]
        lines.append(f' {loc_key(event_id, "t")}:0 "{stage[title_field]}"')
        lines.append(f' {loc_key(event_id, "d")}:0 "{stage[desc_field]}"')
        for option_index, option_text in enumerate(stage[options_field]):
            letter = OPTION_LETTERS[option_index]
            lines.append(f' {loc_key(event_id, letter)}:0 "{option_text}"')

    lines.extend(build_panel_status_lines(wonder, language))

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------

def output_paths(wonder: dict) -> dict[str, Path]:
    name_slug = wonder["name_slug"]
    return {
        "events": REPO_ROOT / "src" / "in_game" / "events" / f"tv_wonder_unique_{name_slug}_ritual_events.txt",
        "effects": REPO_ROOT / "src" / "in_game" / "common" / "scripted_effects" / f"tv_wonder_unique_{name_slug}_ritual_effects.txt",
        "triggers": REPO_ROOT / "src" / "in_game" / "common" / "scripted_triggers" / f"tv_wonder_unique_{name_slug}_ritual_triggers.txt",
        "l_english": REPO_ROOT / "src" / "main_menu" / "localization" / "english" / f"tv_wonder_unique_{name_slug}_ritual_l_english.yml",
        "l_simp_chinese": REPO_ROOT / "src" / "main_menu" / "localization" / "simp_chinese" / f"tv_wonder_unique_{name_slug}_ritual_l_simp_chinese.yml",
    }


def build_all(wonder: dict) -> dict[str, str]:
    return {
        "events": build_events(wonder),
        "effects": build_effects(wonder),
        "triggers": build_triggers(wonder),
        "l_english": build_localization(wonder, "english"),
        "l_simp_chinese": build_localization(wonder, "simp_chinese"),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write the generated files (default: dry-run preview).")
    args = parser.parse_args()

    data = load_data()
    wonders = data["wonders"]

    total_events = 0
    for wonder_key, wonder in wonders.items():
        outputs = build_all(wonder)
        paths = output_paths(wonder)
        event_count = sum(len(rs["stages"]) for rs in wonder["row_sets"])
        total_events += event_count
        print(f"{wonder_key} (wonder_id={wonder['wonder_id']}): {event_count} events across {len(wonder['row_sets'])} row set(s)")
        for key, path in paths.items():
            content = outputs[key]
            if args.write:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8-sig")
                print(f"  Wrote {path.relative_to(REPO_ROOT)}")
            else:
                print(f"  Dry-run: would write {path.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")

    mode = "Wrote" if args.write else "Dry-run"
    print(f"{mode}: {len(wonders)} wonders, {total_events} events, {5 * len(wonders)} files.")


if __name__ == "__main__":
    main()
