"""Generate dedicated source for the 6 fully-implemented Unique Wonder Rituals:
Pharos Lighthouse, Hagia Sophia, Alhambra, Dome of the Rock, Bank of Saint
George, and St. Peter's Basilica.

This is the single generation pipeline for these 6 wonders, replacing three
previously separate pipelines:
  - scripts/wonder_unique_rituals/ (hardcoded Pharos/Hagia plugins merged into
    the shared tv_engineering_department_wonder_mechanics_{effects,triggers}.txt
    and the tv_engineering_department.gui fragment) plus two standalone
    hardcoded event generators
    (gen_tv_wonder_unique_{pharos_lighthouse,hagia_sophia}_ritual_events.py).
  - scripts/gen_repeated_row_pilot_wonders.py + data/repeated_row_pilot_wonders.yaml
    (Dome of the Rock / Bank of Saint George / St. Peter's Basilica generic
    row-set skeleton with no per-entity fidelity and no reward effects).
  - scripts/gen_unique_wonder_ritual_code.py --write-alhambra-source (the
    Harness-driven Alhambra vertical slice, which emitted an unrelated generic
    8-event skeleton with `always = yes` triggers).

Content for each wonder lives in scripts/unique_wonder_ritual_content/<key>.py.
Pharos and Hagia already carry full per-entity fidelity in their existing
hand-written mechanics (ported unchanged); Dome of the Rock, Bank of Saint
George, St. Peter's Basilica, and Alhambra are implemented through the shared
per-entity engine in scripts/unique_wonder_ritual_content/_entity_ritual.py.

GUI cards for all 6 wonders remain merged into the single shared
src/in_game/gui/panels/organization/tv_engineering_department.gui panel via the
existing scripts/in_game/gui/panels/organization/gen_tv_engineering_department_wonder_mechanics_gui.py
+ merge_tv_engineering_department_wonder_mechanics_gui.py mechanism (one organization
panel, not a per-wonder file) — this script does not touch GUI.

Pharos and Hagia's localization text is intentionally left in its existing,
already-correct home (data/wonder_localization.yaml ->
src/main_menu/localization/*/tv_engineering_department_wonder_mechanics_l_*.yml);
only the newly-fully-implemented Dome of the Rock, Bank of Saint George,
St. Peter's Basilica, and Alhambra get dedicated per-wonder localization files
here, matching their dedicated events/effects/triggers files.

Usage:
    C:\\Users\\Hades\\anaconda3\\envs\\eu5\\python.exe scripts\\gen_unique_wonder_rituals.py          # dry-run
    C:\\Users\\Hades\\anaconda3\\envs\\eu5\\python.exe scripts\\gen_unique_wonder_rituals.py --write  # writes files
"""
import argparse
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from unique_wonder_ritual_content import RITUAL_MODULES  # noqa: E402

SCRIPT_REL = "scripts/gen_unique_wonder_rituals.py"
T = "\t"

# Pharos and Hagia keep their existing, already-correct shared localization
# pipeline (data/wonder_localization.yaml); only the 4 newly-completed wonders
# get dedicated per-wonder localization files from this driver.
DEDICATED_LOCALIZATION_SLUGS = {
    "alhambra",
    "dome_of_the_rock",
    "bank_of_saint_george",
    "st_peters_basilica",
}


def header_lines(data_rel: str, target: str) -> list[str]:
    return [
        f"# @Generated by {SCRIPT_REL}",
        f"#   Data:    {data_rel}",
        f"#   Regen:   conda run --no-capture-output -n eu5 python {SCRIPT_REL}",
        "# Do not edit directly - modify the data file and re-run the generator.",
        f"# Target: {target}",
        "",
    ]


def build_events_file(module) -> str:
    target = f"src/in_game/events/tv_wonder_unique_{module.NAME_SLUG}_ritual_events.txt"
    lines = header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target)
    lines.append("namespace = tv_engineering_department")
    lines.append("")
    lines.extend(module.build_events_body())
    return "\n".join(lines).rstrip() + "\n"


def build_effects_file(module) -> str:
    target = f"src/in_game/common/scripted_effects/tv_wonder_unique_{module.NAME_SLUG}_ritual_effects.txt"
    lines = header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target)
    module.append_effects(lines)
    return "\n".join(lines).rstrip() + "\n"


def build_triggers_file(module) -> str:
    target = f"src/in_game/common/scripted_triggers/tv_wonder_unique_{module.NAME_SLUG}_ritual_triggers.txt"
    lines = header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target)
    module.append_triggers(lines)
    return "\n".join(lines).rstrip() + "\n"


def build_localization_file(module, language: str) -> str:
    suffix = "l_english" if language == "english" else "l_simp_chinese"
    target = f"src/main_menu/localization/{language}/tv_wonder_unique_{module.NAME_SLUG}_ritual_{suffix}.yml"
    header_key = suffix
    lines = [f"{header_key}:"]
    for hline in header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target):
        lines.append(f" {hline}" if hline else "")
    lines.append(" ")
    lines.extend(module.build_localization(language))
    return "\n".join(lines).rstrip() + "\n"


def build_modifiers_file() -> str:
    target = "src/main_menu/common/static_modifiers/towards_victory_unique_wonder_ritual_modifiers.txt"
    lines = header_lines("scripts/unique_wonder_ritual_content/*.py (WONDER['modifier_bundles'])", target)
    for module in RITUAL_MODULES:
        wonder = getattr(module, "WONDER", None)
        if not wonder or "modifier_bundles" not in wonder:
            continue
        for modifier_name, effects in wonder["modifier_bundles"].items():
            lines.append(f"{modifier_name} = {{")
            for key, value in effects.items():
                lines.append(f"{T}{key} = {value}")
            lines.append("}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_on_action_file(module) -> str:
    target = f"src/in_game/common/on_action/tv_wonder_unique_{module.NAME_SLUG}_ritual_on_actions.txt"
    lines = header_lines(f"scripts/unique_wonder_ritual_content/{module.__name__.rsplit('.', 1)[-1]}.py", target)
    lines.extend(module.build_on_action_body())
    return "\n".join(lines).rstrip() + "\n"


def output_paths(module) -> dict[str, Path]:
    paths = {
        "events": REPO_ROOT / "src" / "in_game" / "events" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_events.txt",
        "effects": REPO_ROOT / "src" / "in_game" / "common" / "scripted_effects" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_effects.txt",
        "triggers": REPO_ROOT / "src" / "in_game" / "common" / "scripted_triggers" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_triggers.txt",
    }
    if module.NAME_SLUG in DEDICATED_LOCALIZATION_SLUGS:
        paths["l_english"] = REPO_ROOT / "src" / "main_menu" / "localization" / "english" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_l_english.yml"
        paths["l_simp_chinese"] = REPO_ROOT / "src" / "main_menu" / "localization" / "simp_chinese" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_l_simp_chinese.yml"
    if hasattr(module, "build_on_action_body"):
        paths["on_action"] = REPO_ROOT / "src" / "in_game" / "common" / "on_action" / f"tv_wonder_unique_{module.NAME_SLUG}_ritual_on_actions.txt"
    return paths


def build_all(module) -> dict[str, str]:
    outputs = {
        "events": build_events_file(module),
        "effects": build_effects_file(module),
        "triggers": build_triggers_file(module),
    }
    if module.NAME_SLUG in DEDICATED_LOCALIZATION_SLUGS:
        outputs["l_english"] = build_localization_file(module, "english")
        outputs["l_simp_chinese"] = build_localization_file(module, "simp_chinese")
    if hasattr(module, "build_on_action_body"):
        outputs["on_action"] = build_on_action_file(module)
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write the generated files (default: dry-run preview).")
    args = parser.parse_args()

    total_files = 0

    modifiers_path = REPO_ROOT / "src" / "main_menu" / "common" / "static_modifiers" / "towards_victory_unique_wonder_ritual_modifiers.txt"
    modifiers_content = build_modifiers_file()
    total_files += 1
    if args.write:
        modifiers_path.parent.mkdir(parents=True, exist_ok=True)
        modifiers_path.write_text(modifiers_content, encoding="utf-8-sig")
        print(f"Wrote {modifiers_path.relative_to(REPO_ROOT)}")
    else:
        print(f"Dry-run: would write {modifiers_path.relative_to(REPO_ROOT)} ({len(modifiers_content.splitlines())} lines)")

    for module in RITUAL_MODULES:
        outputs = build_all(module)
        paths = output_paths(module)
        print(f"{module.WONDER_KEY} (wonder_id={module.WONDER_ID}): {len(outputs)} files")
        for key, path in paths.items():
            content = outputs[key]
            total_files += 1
            if args.write:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8-sig")
                print(f"  Wrote {path.relative_to(REPO_ROOT)}")
            else:
                print(f"  Dry-run: would write {path.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")

    mode = "Wrote" if args.write else "Dry-run"
    print(f"{mode}: {len(RITUAL_MODULES)} wonders, {total_files} files.")


if __name__ == "__main__":
    main()
