"""
Shared codegen helpers for the Victory Path Tree node system, driven by
data/victory_path_tree_variant.yaml. Imported by the 1:1 generator scripts
under scripts/in_game/common/{static_modifiers,scripted_effects,generic_actions,
generic_action_ai_lists}/ and scripts/main_menu/localization/{english,simp_chinese}/.

Pattern: one data entry per node (trunk t1..t5, and each branch's nodes) across
6 paths (~104 nodes total); each node generates one static modifier + one
unlock effect + one generic action + one loc key pair. Structurally repetitive
per-node boilerplate, hence scripted per the Script System rules in CLAUDE.md.

NOTE: tv_{path}_tree_points and each node's `cost` are placeholders — the real
point economy (accrual source, balanced per-node cost) is an open design item
(see docs/design/Victory_Path_Tree_Variant_Design.md, "实现前待决事项").
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "data" / "victory_path_tree_variant.yaml"

TREE_POINTS_TRICKLE = 1  # flat placeholder points/month per active path — NOT balanced

# Stable per-node numeric id scheme for the click -> pending -> confirm/cancel flow.
# Mirrors victory_paths.yaml's gui.order for the *other* (linear) system purely so the
# numbering scheme reads consistently across both GUI generators; this file stays
# independent of victory_paths.yaml otherwise (see module docstring).
PATH_ORDER = {
    "conquest": 0,
    "prosperity": 1,
    "trade": 2,
    "diplomatic": 3,
    "cultural": 4,
    "science": 5,
}

PENDING_VAR = "tv_tree_pending_id"
CONFIRM_ACTION = "tv_tree_confirm_pending"
CANCEL_ACTION = "tv_tree_cancel_pending"

PATH_LABELS_EN = {
    "conquest": "Conquest",
    "prosperity": "Prosperity",
    "trade": "Trade",
    "diplomatic": "Diplomatic",
    "cultural": "Cultural",
    "science": "Scientific",
}
PATH_LABELS_ZH = {
    "conquest": "征服",
    "prosperity": "繁荣",
    "trade": "贸易",
    "diplomatic": "外交",
    "cultural": "文化",
    "science": "科技",
}


def load_data() -> dict:
    with DATA_FILE.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def write_output(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8-sig")


def header(regen_script: str, output_desc: str) -> str:
    return (
        f"# @Generated by {regen_script}\n"
        f"#   Data:    data/victory_path_tree_variant.yaml\n"
        f"#   Regen:   conda run --no-capture-output -n eu5 python {regen_script}\n"
        f"# Do not edit directly — modify the data file and re-run the generator.\n"
        f"# {output_desc}\n"
    )


def flatten_nodes(path: dict) -> list[dict]:
    """Ordered node list with kind/parent_id, mirroring victory_tree_planner_web/service.py's _build_path_nodes."""
    nodes = []
    trunk = path["trunk"]
    for i, n in enumerate(trunk):
        parent = trunk[i - 1]["id"] if i > 0 else None
        nodes.append({**n, "kind": "trunk", "parent_id": parent})
    for branch in path["branches"]:
        prev = branch["attach_after"]
        for n in branch["nodes"]:
            nodes.append({**n, "kind": "branch", "branch_id": branch["id"], "parent_id": prev})
            prev = n["id"]
    return nodes


def modifier_name(pid: str, node_id: str) -> str:
    return f"tv_tree_{pid}_{node_id}_modifier"


def unlocked_var(pid: str, node_id: str) -> str:
    return f"tv_tree_{pid}_{node_id}_unlocked"


def unlock_effect_name(pid: str, node_id: str) -> str:
    return f"tv_tree_{pid}_{node_id}_unlock_effect"


def action_name(pid: str, node_id: str) -> str:
    """GUI-facing action: click a node to stage it as the pending selection."""
    return f"tv_tree_select_{pid}_{node_id}"


def points_var(pid: str) -> str:
    return f"tv_{pid}_tree_points"


def node_uid(data: dict, pid: str, node_id: str) -> int:
    """Stable numeric id for the pending-selection variable, unique across all paths."""
    for path in data["paths"]:
        if path["id"] != pid:
            continue
        for index, node in enumerate(flatten_nodes(path)):
            if node["id"] == node_id:
                return PATH_ORDER[pid] * 1000 + index
    raise KeyError(f"Unknown tree node {pid}/{node_id}")


def fmt_value(value: str) -> str:
    value = value.strip()
    return value[1:] if value.startswith("+") else value


# ─────────────────────────────────────────────────────────────────────────────
# 1. STATIC MODIFIERS
# ─────────────────────────────────────────────────────────────────────────────

def generate_modifiers(data: dict, regen_script: str) -> str:
    lines = [header(regen_script, "Node reward static modifiers, one per trunk/branch node."), ""]
    for path in data["paths"]:
        pid = path["id"]
        lines.append(f"# {'─' * 70}")
        lines.append(f"# {pid.upper()} TREE NODE MODIFIERS")
        lines.append(f"# {'─' * 70}")
        lines.append("")
        for node in flatten_nodes(path):
            name = modifier_name(pid, node["id"])
            lines.append(f"{name} = {{")
            if node.get("modifier_ids"):
                for mid in node["modifier_ids"]:
                    lines.append(f"\t{mid} = {fmt_value(node['value'])}")
            elif node.get("modifier_id"):
                value = node["value"].strip()
                if value == "":
                    lines.append(f"\t{node['modifier_id']} = yes")
                else:
                    lines.append(f"\t{node['modifier_id']} = {fmt_value(value)}")
            else:
                lines.append("\t# TODO: no verified modifier_id for this node yet")
            lines.append("}")
            lines.append("")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 2. SCRIPTED EFFECTS (unlock effects + points monthly trickle)
# ─────────────────────────────────────────────────────────────────────────────

def generate_effects(data: dict, regen_script: str) -> str:
    lines = [header(regen_script, "Node unlock effects and the points monthly-trickle pulse."), ""]
    lines.append("# " + "═" * 71)
    lines.append("# SECTION 1: NODE UNLOCK EFFECTS")
    lines.append("# Called from each node's generic action after allow-block checks pass.")
    lines.append("# " + "═" * 71)
    lines.append("")
    for path in data["paths"]:
        pid = path["id"]
        lines.append(f"# {pid.capitalize()} Victory Tree")
        for node in flatten_nodes(path):
            lines.append(f"{unlock_effect_name(pid, node['id'])} = {{")
            lines.append(f"\tset_variable = {{ name = {unlocked_var(pid, node['id'])} value = 1 }}")
            lines.append(f"\tchange_variable = {{ name = {points_var(pid)} add = -{node['cost']} }}")
            lines.append(f"\tadd_country_modifier = {{ modifier = {modifier_name(pid, node['id'])} days = -1 }}")
            lines.append("}")
            lines.append("")
        lines.append("")

    lines.append("# " + "═" * 71)
    lines.append("# SECTION 2: POINTS MONTHLY TRICKLE (PLACEHOLDER ECONOMY)")
    lines.append(f"# Flat +{TREE_POINTS_TRICKLE}/month per actively-pursued path. NOT a balanced")
    lines.append("# economy — a stand-in until the real point economy is designed.")
    lines.append("# " + "═" * 71)
    lines.append("")
    lines.append("tv_victory_tree_points_monthly_pulse = {")
    for path in data["paths"]:
        pid = path["id"]
        lines.append("\tif = {")
        lines.append(f"\t\tlimit = {{ has_variable = tv_{pid}_victory_enabled }}")
        lines.append(f"\t\tchange_variable = {{ name = {points_var(pid)} add = {TREE_POINTS_TRICKLE} }}")
        lines.append("\t}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 3. GENERIC ACTIONS
# ─────────────────────────────────────────────────────────────────────────────

def generate_actions(data: dict, regen_script: str) -> str:
    lines = [header(regen_script, "Click-to-select and confirm/cancel generic actions per node."), ""]
    lines.append("# " + "═" * 71)
    lines.append("# SECTION 1: PER-NODE SELECT ACTIONS")
    lines.append("# Clicking a node only stages it as the pending selection; the actual")
    lines.append(f"# unlock ({PENDING_VAR} dispatch) happens via {CONFIRM_ACTION} below.")
    lines.append("# " + "═" * 71)
    lines.append("")
    for path in data["paths"]:
        pid = path["id"]
        lines.append(f"# {pid.capitalize()} Victory Tree")
        for node in flatten_nodes(path):
            node_id = node["id"]
            name = action_name(pid, node_id)
            uid = node_uid(data, pid, node_id)
            lines.append(f"{name} = {{")
            lines.append("\ttype = owncountry")
            lines.append("\tsound = UI_action_religion_generic")
            lines.append("\tshow_message = no")
            lines.append("\tai_tick = never")
            lines.append("\tautomation_tick = never")
            lines.append("")
            lines.append("\tpotential = {")
            lines.append("\t\tscope:actor = {")
            lines.append(f"\t\t\thas_variable = tv_{pid}_victory_enabled")
            lines.append("\t\t}")
            lines.append("\t}")
            lines.append("")
            lines.append("\tallow = {")
            lines.append("\t\tscope:actor = {")
            if node["parent_id"]:
                lines.append(f"\t\t\thas_variable = {unlocked_var(pid, node['parent_id'])}")
            lines.append(f"\t\t\tNOT = {{ has_variable = {unlocked_var(pid, node_id)} }}")
            lines.append(f"\t\t\tvar:{points_var(pid)} ?= {{ this >= {node['cost']} }}")
            lines.append("\t\t}")
            lines.append("\t}")
            lines.append("")
            lines.append("\teffect = {")
            lines.append("\t\tscope:actor = {")
            lines.append(f"\t\t\tset_variable = {{ name = {PENDING_VAR} value = {uid} }}")
            lines.append("\t\t}")
            lines.append("\t}")
            lines.append("")
            lines.append("\tai_will_do = { add = -100 }")
            lines.append("}")
            lines.append("")

    lines.append("# " + "═" * 71)
    lines.append("# SECTION 2: SHARED CONFIRM / CANCEL DISPATCH ACTIONS")
    lines.append(f"# {CONFIRM_ACTION} maps the pending id back to the node's unlock effect;")
    lines.append(f"# {CANCEL_ACTION} discards the pending selection untouched.")
    lines.append("# " + "═" * 71)
    lines.append("")
    lines.append(f"{CONFIRM_ACTION} = {{")
    lines.append("\ttype = owncountry")
    lines.append("\tsound = UI_action_religion_generic")
    lines.append("\tshow_message = no")
    lines.append("\tai_tick = never")
    lines.append("\tautomation_tick = never")
    lines.append("")
    lines.append("\tpotential = { always = yes }")
    lines.append("")
    lines.append("\tallow = {")
    lines.append("\t\tscope:actor = { has_variable = " + PENDING_VAR + " }")
    lines.append("\t}")
    lines.append("")
    lines.append("\teffect = {")
    lines.append("\t\tscope:actor = {")
    first = True
    for path in data["paths"]:
        pid = path["id"]
        for node in flatten_nodes(path):
            node_id = node["id"]
            uid = node_uid(data, pid, node_id)
            branch = "if" if first else "else_if"
            first = False
            lines.append(f"\t\t\t{branch} = {{")
            lines.append(f"\t\t\t\tlimit = {{ var:{PENDING_VAR} = {uid} }}")
            lines.append(f"\t\t\t\t{unlock_effect_name(pid, node_id)} = yes")
            lines.append("\t\t\t}")
    lines.append(f"\t\t\tremove_variable = {PENDING_VAR}")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("")
    lines.append("\tai_will_do = { add = -100 }")
    lines.append("}")
    lines.append("")
    lines.append(f"{CANCEL_ACTION} = {{")
    lines.append("\ttype = owncountry")
    lines.append("\tsound = UI_action_religion_generic")
    lines.append("\tshow_message = no")
    lines.append("\tai_tick = never")
    lines.append("\tautomation_tick = never")
    lines.append("")
    lines.append("\tpotential = { always = yes }")
    lines.append("")
    lines.append("\tallow = {")
    lines.append("\t\tscope:actor = { has_variable = " + PENDING_VAR + " }")
    lines.append("\t}")
    lines.append("")
    lines.append("\teffect = {")
    lines.append("\t\tscope:actor = {")
    lines.append(f"\t\t\tremove_variable = {PENDING_VAR}")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("")
    lines.append("\tai_will_do = { add = -100 }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_ai_list(data: dict, regen_script: str) -> str:
    lines = [header(regen_script, "Registers all tree node actions as player-only (no AI eligibility)."), ""]
    lines.append("tv_victory_tree_node_actions_list = {")
    lines.append("\tpotential = { always = no }")
    lines.append("\tactions = {")
    for path in data["paths"]:
        pid = path["id"]
        for node in flatten_nodes(path):
            lines.append(f"\t\t{action_name(pid, node['id'])}")
    lines.append(f"\t\t{CONFIRM_ACTION}")
    lines.append(f"\t\t{CANCEL_ACTION}")
    lines.append("\t}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 4. LOCALIZATION
# ─────────────────────────────────────────────────────────────────────────────

def _prereq_effect_label(path: dict, node: dict) -> str | None:
    if not node["parent_id"]:
        return None
    for n in flatten_nodes(path):
        if n["id"] == node["parent_id"]:
            return n["effect"]
    return None


def generate_loc(data: dict, regen_script: str, *, lang: str) -> str:
    zh = lang == "zh"
    lines = [
        "# @Generated by " + regen_script,
        "#   Data:    data/victory_path_tree_variant.yaml",
        f"#   Regen:   conda run --no-capture-output -n eu5 python {regen_script}",
        "# Do not edit directly — modify the data file and re-run the generator.",
        "",
        f"l_{'simp_chinese' if zh else 'english'}:",
    ]
    for path in data["paths"]:
        pid = path["id"]
        for node in flatten_nodes(path):
            key = action_name(pid, node["id"])
            value = fmt_value(node["value"])
            sign = "" if (not value or node["value"].strip().startswith("-")) else "+"
            value_disp = f"{sign}{value}" if value else ""
            title = f'{node["effect"]}{(" " + value_disp) if value_disp else ""}'
            prereq = _prereq_effect_label(path, node)
            if zh:
                desc_parts = [f"花费：#Y {node['cost']} 点#!"]
                if prereq:
                    desc_parts.append(f"需求：{prereq}")
            else:
                desc_parts = [f"Cost: #Y {node['cost']} points#!"]
                if prereq:
                    desc_parts.append(f"Requires: {prereq}")
            desc_line = " \\n".join(desc_parts)
            lines.append(f' {key}:0 "#G {title}#!"')
            lines.append(f' {key}_desc:0 "{desc_line}"')
            lines.append(f' STATIC_MODIFIER_NAME_{modifier_name(pid, node["id"])}:0 "{title}"')
            if zh:
                lines.append(f' PERFORM_{key}_ACTION_SETUP:0 "当我们选择一个胜利之路树状节点时。"')
                lines.append(f' PERFORM_{key}_ACTION_LOG:0 "我们选择了一个胜利之路树状节点，等待确认。"')
            else:
                lines.append(f' PERFORM_{key}_ACTION_SETUP:0 "When we select a Victory Path Tree node."')
                lines.append(f' PERFORM_{key}_ACTION_LOG:0 "We selected a Victory Path Tree node, pending confirmation."')
            lines.append(f' PERFORM_{key}_ACTION_MAP:0 ""')

    if zh:
        lines.append(' TV_TREE_CONFIRM_TITLE:0 "确认解锁"')
        lines.append(' TV_TREE_CONFIRM_BUTTON:0 "确认"')
        lines.append(' TV_TREE_CANCEL_BUTTON:0 "取消"')
        lines.append(f' {CONFIRM_ACTION}:0 "确认"')
        lines.append(f' {CONFIRM_ACTION}_desc:0 "解锁当前选中的胜利之路树状节点。"')
        lines.append(f' {CANCEL_ACTION}:0 "取消"')
        lines.append(f' {CANCEL_ACTION}_desc:0 "放弃当前选择，不解锁任何节点。"')
        lines.append(f' PERFORM_{CONFIRM_ACTION}_ACTION_SETUP:0 "当我们确认一个胜利之路树状节点的解锁时。"')
        lines.append(f' PERFORM_{CONFIRM_ACTION}_ACTION_LOG:0 "我们确认解锁了一个胜利之路树状节点。"')
        lines.append(f' PERFORM_{CANCEL_ACTION}_ACTION_SETUP:0 "当我们取消一个待确认的胜利之路树状节点选择时。"')
        lines.append(f' PERFORM_{CANCEL_ACTION}_ACTION_LOG:0 "我们取消了一个待确认的胜利之路树状节点选择。"')
    else:
        lines.append(' TV_TREE_CONFIRM_TITLE:0 "Confirm Unlock"')
        lines.append(' TV_TREE_CONFIRM_BUTTON:0 "Confirm"')
        lines.append(' TV_TREE_CANCEL_BUTTON:0 "Cancel"')
        lines.append(f' {CONFIRM_ACTION}:0 "Confirm"')
        lines.append(f' {CONFIRM_ACTION}_desc:0 "Unlock the currently selected Victory Path Tree node."')
        lines.append(f' {CANCEL_ACTION}:0 "Cancel"')
        lines.append(f' {CANCEL_ACTION}_desc:0 "Discard the current selection without unlocking anything."')
        lines.append(f' PERFORM_{CONFIRM_ACTION}_ACTION_SETUP:0 "When we confirm unlocking a Victory Path Tree node."')
        lines.append(f' PERFORM_{CONFIRM_ACTION}_ACTION_LOG:0 "We confirmed unlocking a Victory Path Tree node."')
        lines.append(f' PERFORM_{CANCEL_ACTION}_ACTION_SETUP:0 "When we cancel a pending Victory Path Tree node selection."')
        lines.append(f' PERFORM_{CANCEL_ACTION}_ACTION_LOG:0 "We cancelled a pending Victory Path Tree node selection."')
    lines.append(f' PERFORM_{CONFIRM_ACTION}_ACTION_MAP:0 ""')
    lines.append(f' PERFORM_{CANCEL_ACTION}_ACTION_MAP:0 ""')
    return "\n".join(lines) + "\n"
