l_russian:
 cmf_settings_title: "Фреймворк сообщества модов"
 cmf_settings_page_action_bar: "Панель действий"
 cmf_settings_action_bar_group_layout: "Макет"
 cmf_settings_action_bar_position_activate: "Активировать эту позицию"
 cmf_settings_action_bar_position: "Положение панели действий"
 cmf_settings_action_bar_position_top: "В начало"
 cmf_settings_action_bar_position_bottom_left: "Снизу слева"
 cmf_settings_action_bar_position_bottom_right: "Снизу справа"
 cmf_settings_action_bar_group_active_buttons: "Активные кнопки"
 cmf_settings_action_bar_group_active_button_activate: "Активировать кнопку"
 cmf_settings_action_bar_group_active_button_deactivate: "Кнопка деактивации"
