"""
Generate identical full-copy character_title.txt outputs for both deployable mods.

The engine treats top-level customizable localization keys as unique database
entries. ``character_title_prefix`` must therefore be generated as a full
vanilla copy in each root. Dependency order cannot be relied on to choose the
main-mod copy, so both copies include the complete TV title mapping.
"""

import sys
import argparse
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
DATA_FILE = REPO_ROOT / "data" / "io_leaders.yaml"
VANILLA_FILE = (
    REPO_ROOT
    / "reference_game_files"
    / "game"
    / "in_game"
    / "common"
    / "customizable_localization"
    / "character_title.txt"
)
MAIN_OUT_FILE = (
    REPO_ROOT
    / "src"
    / "in_game"
    / "common"
    / "customizable_localization"
    / "character_title.txt"
)
ENGINEERING_OUT_FILE = (
    REPO_ROOT
    / "src_engineering_department"
    / "in_game"
    / "common"
    / "customizable_localization"
    / "character_title.txt"
)
COURT_OUT_FILE = (
    REPO_ROOT
    / "src_court_positions"
    / "in_game"
    / "common"
    / "customizable_localization"
    / "character_title.txt"
)

HEADER = """\
# @Generated by scripts/in_game/common/customizable_localization/gen_character_title.py
#   Data:    data/io_leaders.yaml
#   Regen:   conda run --no-capture-output -n eu5 python scripts/in_game/common/customizable_localization/gen_character_title.py
# Do not edit directly - modify the data file and re-run the generator.
"""


def _tv_title_entries(data: dict) -> str:
    entries: list[str] = []
    for io in data.get("ios", []):
        title_modifier = io.get("title_modifier")
        title_loc_key = io.get("title_loc_key")
        if not title_modifier:
            continue
        if not title_loc_key:
            raise ValueError(f"{io.get('id', '<unknown>')} has title_modifier but no title_loc_key")
        entries.append(
            "\ttext = {\n"
            f"\t\tlocalization_key = {title_loc_key}\n"
            f"\t\ttrigger = {{ has_character_modifier = {title_modifier} }}\n"
            "\t}"
        )
    if not entries:
        return ""
    return "\n\t# Towards Victory IO leader titles\n\n" + "\n\n".join(entries) + "\n"


def _find_block_end(text: str, block_name: str) -> int:
    needle = f"{block_name} = {{"
    start = text.find(needle)
    if start < 0:
        raise ValueError(f"Could not find block: {block_name}")

    brace_start = text.find("{", start)
    depth = 0
    for index in range(brace_start, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError(f"Could not find end of block: {block_name}")


def generate(data: dict) -> str:
    vanilla = VANILLA_FILE.read_text(encoding="utf-8-sig")
    insertion = _tv_title_entries(data)
    if insertion:
        end = _find_block_end(vanilla, "character_title_prefix")
        vanilla = vanilla[:end].rstrip() + "\n" + insertion + vanilla[end:]
    return HEADER + "\n" + vanilla.rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    with DATA_FILE.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)

    main_content = generate(data)
    engineering_content = generate(data)
    court_content = generate(data)

    if args.dry:
        print(main_content)
    else:
        for output, content in (
            (MAIN_OUT_FILE, main_content),
            (ENGINEERING_OUT_FILE, engineering_content),
            (COURT_OUT_FILE, court_content),
        ):
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(content, encoding="utf-8-sig")
            print(f"Written: {output.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
